using System;
using System.Collections.Generic;

namespace StormSwitchBox.Services
{
    public static class GameCubeCatalogData
    {
        public static List<NintendoCatalogItem> GetCatalog()
        {
            var list = new List<NintendoCatalogItem>(236);

            var games = new (string Title, string Genre, int Year, string Dev, string Pub, string Region, string Desc)[]
            {
                ("Super Smash Bros. Melee", "Файтинг-кроссовер", 2001, "HAL Laboratory", "Nintendo", "WW", "Культовый эталон соревновательного файтинга с невероятной скоростью, техникой wave-dashing и 26 персонажами."),
                ("The Legend of Zelda: The Wind Waker", "Action-Adventure", 2002, "Nintendo EAD", "Nintendo", "WW", "Морская одиссея Линка и Тетры на Великом Море с великолепной сел-шейдинг анимацией и парусником Король Красных Львов."),
                ("The Legend of Zelda: Twilight Princess", "Action-Adventure", 2006, "Nintendo EAD", "Nintendo", "WW", "Эпическое темное приключение Линка-волка и Мидны в Сумеречном Царстве с непревзойденными храмами."),
                ("Metroid Prime", "Шутер / Приключения от первого лица", 2002, "Retro Studios", "Nintendo", "WW", "Один из величайших шедевров всех времен: 3D-перерождение метроидвании на планете Таллон IV со сканирующим визором."),
                ("Metroid Prime 2: Echoes", "Шутер / Приключения", 2004, "Retro Studios", "Nintendo", "WW", "Самус Аран исследует раздвоенную планету Эфир (Светлый и Темный миры) и сражается с Темной Самус."),
                ("Super Mario Sunshine", "3D Платформер", 2002, "Nintendo EAD", "Nintendo", "WW", "Марио на тропическом острове Дельфино с водяным ранцем FLUDD, очисткой граффити и катанием на кальмарах."),
                ("Mario Kart: Double Dash!!", "Картинговые гонки", 2003, "Nintendo EAD", "Nintendo", "WW", "Уникальная механика двух гонщиков на одном карте со сменой мест и эксклюзивными спец-предметами."),
                ("Luigi's Mansion", "Приключенческий экшен", 2001, "Nintendo EAD", "Nintendo", "WW", "Стартовый хит консоли: Луиджи ловит привидений пылесосом Poltergust 3000 в особняке, спасая Марио."),
                ("Paper Mario: The Thousand-Year Door", "JRPG", 2004, "Intelligent Systems", "Nintendo", "WW", "Шедевр бумажного Марио в портовом городе Рогпорт с театральной сценой со зрителями и 7 кристальными звездами."),
                ("F-Zero GX", "Сверхзвуковые гонки", 2003, "Amusement Vision / Sega", "Nintendo", "WW", "Вершина футуристических гонок со скоростью свыше 2000 км/ч, сюжетным режимом Капитана Фэлкона и 30 болидами при 60 FPS."),
                ("Resident Evil 4", "Survival Horror / Экшен", 2005, "Capcom Production Studio 4", "Capcom", "WW", "Революция экшенов от третьего лица от Синдзи Миками: Леон Кеннеди спасает дочь президента Эшли в Испании."),
                ("Resident Evil (Remake)", "Survival Horror", 2002, "Capcom", "Capcom", "WW", "Непревзойденный эталон ремейков: особняк Спенсера с фотореалистичными задниками, новыми зонами и зомби Crimson Heads."),
                ("Resident Evil Zero", "Survival Horror", 2002, "Capcom", "Capcom", "WW", "Ребекка Чемберс и Билли Коэн в поезде Эклипс Экспресс с механикой переключения напарников Partner Zapping."),
                ("Pikmin", "Стратегия в реальном времени", 2001, "Nintendo EAD", "Nintendo", "WW", "Капитан Олимар терпит крушение и командует сотнями разноцветных растительных существ Пикминов за 30 дней."),
                ("Pikmin 2", "Стратегия в реальном времени", 2004, "Nintendo EAD", "Nintendo", "WW", "Олимар и Луи исследуют неизведанные подземелья без ограничения по времени с новыми фиолетовыми и белыми пикминами."),
                ("Animal Crossing", "Симулятор жизни", 2001, "Nintendo EAD", "Nintendo", "WW", "Жизнь в уютной деревне с часами реального времени, праздниками, ловлей рыбы и выплатой ипотеки Тому Нуку."),
                ("Star Wars Rogue Squadron II: Rogue Leader", "Космический 3D симулятор", 2001, "Factor 5", "LucasArts", "WW", "Графический шедевр стартовой линейки: атака на Звезду Смерти и битва за Хот от лица Люка и Веджа."),
                ("Star Wars Rogue Squadron III: Rebel Strike", "Космический симулятор", 2003, "Factor 5", "LucasArts", "WW", "Воздушные и наземные битвы с полным кооперативным прохождением кампании Rogue Leader."),
                ("Eternal Darkness: Sanity's Requiem", "Психологический хоррор", 2002, "Silicon Knights", "Nintendo", "WW", "Эпическая сага сквозь 2000 лет с революционной шкалой рассудка Sanity Meter, ломающей четвертую стену."),
                ("Fire Emblem: Path of Radiance", "Тактическая RPG", 2005, "Intelligent Systems", "Nintendo", "WW", "Наемник Айк и лагузы-трансформеры на континенте Теллиус в первой трехмерной части Fire Emblem."),
                ("Tales of Symphonia", "JRPG", 2003, "Namco Tales Studio", "Namco", "WW", "Ллойд Ирвинг и Колетт Брунель отправляются в путешествие Регенерации Мира Сильварант."),
                ("Baten Kaitos: Eternal Wings and the Lost Ocean", "JRPG", 2003, "Monolith Soft / tri-Crescendo", "Namco", "WW", "Парящие острова в небесах, Калас с механическим крылом и карточная боевая система Magnus."),
                ("Baten Kaitos Origins", "JRPG", 2006, "Monolith Soft / tri-Crescendo", "Nintendo", "WW", "Приквел о Саги, Милли и механическом спутнике Гильо с динамичной карточной боевкой."),
                ("Skies of Arcadia Legends", "JRPG", 2002, "Overworks / Sega", "Sega", "WW", "Воздушные пираты Вайз, Айка и Фина бороздят небеса на парусных кораблях в поисках Лунных камней."),
                ("Viewtiful Joe", "Стилизованный Beat 'em up", 2003, "Clover Studio / Capcom", "Capcom", "WW", "Супергеройский комикс-экшен от Хидеки Камии с кино-способностями замедления Slow, ускорения Mach Speed и Zoom."),
                ("Alien Hominid", "Run and Gun", 2004, "O-3", "O-3", "WW", "Alien Hominid — популярная игра для Nintendo GameCube."),
                ("Auto Modellista", "Сел-шейдинг автогонки от Capcom", 2003, "Capcom", "Capcom", "WW", "Auto Modellista — популярная игра для Nintendo GameCube."),
                ("Battalion Wars", "Тактический экшен в реальном времени от Kuju", 2005, "Nintendo", "Nintendo", "WW", "Battalion Wars — популярная игра для Nintendo GameCube."),
                ("Beyond Good & Evil", "Шедевр Мишеля Анселя: журналистка Джейд с фотоаппаратом на планете Хиллия", 2003, "Ubisoft", "Ubisoft", "WW", "Beyond Good & Evil — популярная игра для Nintendo GameCube."),
                ("Billy Hatcher and the Giant Egg", "Платформер мальчика Билли, катающего волшебные яйца от Sonic Team", 2003, "Sega", "Sega", "WW", "Billy Hatcher and the Giant Egg — популярная игра для Nintendo GameCube."),
                ("Bloody Roar: Primal Fury", "3D файтинг с превращением бойцов в зверей", 2002, "Hudson Soft", "Hudson Soft", "WW", "Bloody Roar: Primal Fury — популярная игра для Nintendo GameCube."),
                ("Burnout", "Аркадные гонки с авариями", 2002, "Acclaim", "Acclaim", "WW", "Burnout — популярная игра для Nintendo GameCube."),
                ("Burnout 2: Point of Impact", "Гонки с режимом Crash Mode", 2003, "Acclaim", "Acclaim", "WW", "Burnout 2: Point of Impact — популярная игра для Nintendo GameCube."),
                ("Call of Duty: Finest Hour", "Военный FPS", 2004, "Activision", "Activision", "WW", "Call of Duty: Finest Hour — популярная игра для Nintendo GameCube."),
                ("Call of Duty 2: Big Red One", "Военный FPS о Первой пехотной дивизии", 2005, "Activision", "Activision", "WW", "Call of Duty 2: Big Red One — популярная игра для Nintendo GameCube."),
                ("Capcom vs. SNK 2 EO", "Ультимативный кроссовер 2D файтингов с 6 стилями боевых систем", 2003, "Capcom", "Capcom", "WW", "Capcom vs. SNK 2 EO — популярная игра для Nintendo GameCube."),
                ("Chibi-Robo!", "Маленький робот-уборщик делает семью Сандерсонов счастливой от Skip Ltd.", 2005, "Nintendo", "Nintendo", "WW", "Chibi-Robo! — популярная игра для Nintendo GameCube."),
                ("Crazy Taxi", "Безумное такси от Sega под панк-рок The Offspring", 2001, "Sega", "Sega", "WW", "Crazy Taxi — популярная игра для Nintendo GameCube."),
                ("Custom Robo", "3D арена-битвы кастомизируемых роботов в голокубах", 2004, "Nintendo", "Nintendo", "WW", "Custom Robo — популярная игра для Nintendo GameCube."),
                ("Dance Dance Revolution: Mario Mix", "Танцевальная ритм-игра с ковриком и Марио", 2005, "Nintendo", "Nintendo", "WW", "Dance Dance Revolution: Mario Mix — популярная игра для Nintendo GameCube."),
                ("Def Jam: Fight for NY", "Легендарный хип-хоп файтинг на движке AKI: Snoop Dogg, DMX, Busta Rhymes", 2004, "EA Games", "EA Games", "WW", "Def Jam: Fight for NY — популярная игра для Nintendo GameCube."),
                ("Def Jam Vendetta", "Хип-хоп рестлинг от AKI", 2003, "EA Games", "EA Games", "WW", "Def Jam Vendetta — популярная игра для Nintendo GameCube."),
                ("Donkey Kong Jungle Beat", "Ураганный платформер от Nintendo EAD Tokyo с управлением бонго DK Bongos", 2004, "Nintendo", "Nintendo", "WW", "Donkey Kong Jungle Beat — популярная игра для Nintendo GameCube."),
                ("Donkey Konga", "Музыкальная ритм-игра на барабанах DK Bongos", 2003, "Nintendo", "Nintendo", "WW", "Donkey Konga — популярная игра для Nintendo GameCube."),
                ("Donkey Konga 2", "Вторая часть ритм-игры на бонго", 2004, "Nintendo", "Nintendo", "WW", "Donkey Konga 2 — популярная игра для Nintendo GameCube."),
                ("Enter the Matrix", "Кинематографичный экшен по Матрице с Нео, Морфеусом и Тринити", 2003, "Atari", "Atari", "WW", "Enter the Matrix — популярная игра для Nintendo GameCube."),
                ("FIFA 06", "Футбол EA Sports", 2005, "EA Sports", "EA Sports", "WW", "FIFA 06 — популярная игра для Nintendo GameCube."),
                ("Fight Night Round 2", "Реалистичный симулятор бокса с управлением ударами правым стиком", 2005, "EA Sports", "EA Sports", "WW", "Fight Night Round 2 — популярная игра для Nintendo GameCube."),
                ("Final Fantasy Crystal Chronicles", "Кооперативная Action-RPG на 4 игроков через кабели GBA-GameCube", 2003, "Square Enix", "Square Enix", "WW", "Final Fantasy Crystal Chronicles — популярная игра для Nintendo GameCube."),
                ("Geist", "Sci-Fi хоррор-шутер от первого лица: призрак Джона Раймона вселяется во врагов и предметы", 2005, "Nintendo", "Nintendo", "WW", "Geist — популярная игра для Nintendo GameCube."),
                ("Gladius", "Пошаговая тактическая RPG гладиаторской школы от LucasArts", 2003, "LucasArts", "LucasArts", "WW", "Gladius — популярная игра для Nintendo GameCube."),
                ("Godzilla: Destroy All Monsters Melee", "3D файтинг гигантских кайдзю-монстров", 2002, "Infogrames", "Infogrames", "WW", "Godzilla: Destroy All Monsters Melee — популярная игра для Nintendo GameCube."),
                ("Gotcha Force", "Культовые 3D сражения миниатюрных боевых роботов Боргов от Capcom", 2003, "Capcom", "Capcom", "WW", "Gotcha Force — популярная игра для Nintendo GameCube."),
                ("Gun", "Кинематографичный вестерн с открытым миром от Neversoft", 2005, "Activision", "Activision", "WW", "Gun — популярная игра для Nintendo GameCube."),
                ("Hitman 2: Silent Assassin", "Стелс-экшен Агента 47 с удавкой и переодеваниями", 2003, "Eidos", "Eidos", "WW", "Hitman 2: Silent Assassin — популярная игра для Nintendo GameCube."),
                ("Ikaruga", "Шедевр аркадных SHMUP от Treasure с полярностью корабля Черный/Белый", 2003, "Atari", "Atari", "WW", "Ikaruga — популярная игра для Nintendo GameCube."),
                ("Killer7", "Сюрреалистичный стильный нуар-триллер Гоити Суды (Suda51) о 7 личностях киллера", 2005, "Capcom", "Capcom", "WW", "Killer7 — популярная игра для Nintendo GameCube."),
                ("Lost Kingdoms", "Action-RPG карточных призывов принцессы Катии от FromSoftware", 2002, "Activision", "Activision", "WW", "Lost Kingdoms — популярная игра для Nintendo GameCube."),
                ("Lost Kingdoms II", "Вторая часть карточной RPG от FromSoftware с трансформациями", 2003, "Activision", "Activision", "WW", "Lost Kingdoms II — популярная игра для Nintendo GameCube."),
                ("Mario Golf: Toadstool Tour", "Спортивный гольф Марио от Camelot с разнообразными полями", 2003, "Nintendo", "Nintendo", "WW", "Mario Golf: Toadstool Tour — популярная игра для Nintendo GameCube."),
                ("Mario Power Tennis", "Спортивный теннис Марио с пауэр-ударами и безумными кортами", 2004, "Nintendo", "Nintendo", "WW", "Mario Power Tennis — популярная игра для Nintendo GameCube."),
                ("Mario Superstar Baseball", "Аркадный бейсбол Марио с командной химией персонажей", 2005, "Nintendo", "Nintendo", "WW", "Mario Superstar Baseball — популярная игра для Nintendo GameCube."),
                ("Mario Party 4", "Первая вечеринка на GameCube с мини- и мега-грибами", 2002, "Nintendo", "Nintendo", "WW", "Mario Party 4 — популярная игра для Nintendo GameCube."),
                ("Mario Party 5", "Вечеринка в Стране Снов с капсулами предметов и боями на машинках", 2003, "Nintendo", "Nintendo", "WW", "Mario Party 5 — популярная игра для Nintendo GameCube."),
                ("Mario Party 6", "Вечеринка со сменой Дня и Ночи и микрофоном GameCube Mic", 2004, "Nintendo", "Nintendo", "WW", "Mario Party 6 — популярная игра для Nintendo GameCube."),
                ("Mario Party 7", "Кругосветный круиз на 8 игроков с микрофоном", 2005, "Nintendo", "Nintendo", "WW", "Mario Party 7 — популярная игра для Nintendo GameCube."),
                ("Mario Strikers (Super Mario Strikers)", "Агрессивный аркадный футбол без правил со взрывами и суперударами", 2005, "Nintendo", "Nintendo", "WW", "Mario Strikers (Super Mario Strikers) — популярная игра для Nintendo GameCube."),
                ("Medal of Honor: Frontline", "Военный FPS с легендарной высадкой в Нормандии на Омаха-Бич", 2002, "EA Games", "EA Games", "WW", "Medal of Honor: Frontline — популярная игра для Nintendo GameCube."),
                ("Medal of Honor: European Assault", "FPS на европейском театре военных действий", 2005, "EA Games", "EA Games", "WW", "Medal of Honor: European Assault — популярная игра для Nintendo GameCube."),
                ("Medal of Honor: Rising Sun", "FPS на тихоокеанском фронте с Перл-Харбором", 2003, "EA Games", "EA Games", "WW", "Medal of Honor: Rising Sun — популярная игра для Nintendo GameCube."),
                ("Mega Man Anniversary Collection", "Сборник Mega Man 1-8 плюс аркадные Power Battles", 2004, "Capcom", "Capcom", "WW", "Mega Man Anniversary Collection — популярная игра для Nintendo GameCube."),
                ("Mega Man Network Transmission", "Платформер в мире Battle Network", 2003, "Capcom", "Capcom", "WW", "Mega Man Network Transmission — популярная игра для Nintendo GameCube."),
                ("Mega Man X Collection", "Сборник Mega Man X1-X6 плюс эксклюзивная Mega Man Battle & Chase", 2006, "Capcom", "Capcom", "WW", "Mega Man X Collection — популярная игра для Nintendo GameCube."),
                ("Mega Man X: Command Mission", "Пошаговая RPG во вселенной Mega Man X", 2004, "Capcom", "Capcom", "WW", "Mega Man X: Command Mission — популярная игра для Nintendo GameCube."),
                ("Metal Gear Solid: The Twin Snakes", "Кинематографичный ремейк MGS1 на движке MGS2 от Silicon Knights и Рюхэя Китамуры", 2004, "Konami", "Konami", "WW", "Metal Gear Solid: The Twin Snakes — популярная игра для Nintendo GameCube."),
                ("Need for Speed: Underground", "Культовые ночные нелегальные уличные гонки и тюнинг", 2003, "EA Games", "EA Games", "WW", "Need for Speed: Underground — популярная игра для Nintendo GameCube."),
                ("Need for Speed: Underground 2", "Ночные гонки по открытому городу Бэйвью под Riders on the Storm", 2004, "EA Games", "EA Games", "WW", "Need for Speed: Underground 2 — популярная игра для Nintendo GameCube."),
                ("Need for Speed: Most Wanted", "Дневные гонки от полиции в Рокпорте за первое место Черного Списка", 2005, "EA Games", "EA Games", "WW", "Need for Speed: Most Wanted — популярная игра для Nintendo GameCube."),
                ("Need for Speed: Carbon", "Гонки по каньонам и контроль районов бандами", 2006, "EA Games", "EA Games", "WW", "Need for Speed: Carbon — популярная игра для Nintendo GameCube."),
                ("Need for Speed: Hot Pursuit 2", "Полицейские погони на суперкарах Ferrari, Porsche, Lamborghini", 2002, "EA Games", "EA Games", "WW", "Need for Speed: Hot Pursuit 2 — популярная игра для Nintendo GameCube."),
                ("NHL Hitz 20-03", "Аркадный хоккей без правил от Midway", 2002, "Midway", "Midway", "WW", "NHL Hitz 20-03 — популярная игра для Nintendo GameCube."),
                ("Pac-Man Vs.", "Инновационный мультиплеер Сигэру Миямото: игрок на GBA видит весь лабиринт против 3 охотников на ТВ", 2003, "Namco / Nintendo", "Namco / Nintendo", "WW", "Pac-Man Vs. — популярная игра для Nintendo GameCube."),
                ("Pac-Man World 2", "3D платформер Пакмана на острове Призраков", 2002, "Namco", "Namco", "WW", "Pac-Man World 2 — популярная игра для Nintendo GameCube."),
                ("Phantasy Star Online Episode I & II", "Легендарная онлайн Action-RPG на планете Рагол от Sonic Team", 2002, "Sega", "Sega", "WW", "Phantasy Star Online Episode I & II — популярная игра для Nintendo GameCube."),
                ("Phantasy Star Online Episode III: C.A.R.D. Revolution", "Пошаговая карточная стратегическая RPG", 2003, "Sega", "Sega", "WW", "Phantasy Star Online Episode III: C.A.R.D. Revolution — популярная игра для Nintendo GameCube."),
                ("Prince of Persia: The Sands of Time", "Шедевр акробатики и управления временем с Кинжалом Времени", 2003, "Ubisoft", "Ubisoft", "WW", "Prince of Persia: The Sands of Time — популярная игра для Nintendo GameCube."),
                ("Prince of Persia: Warrior Within", "Мрачный акробатический экшен с Дахакой и метал-саундтреком", 2004, "Ubisoft", "Ubisoft", "WW", "Prince of Persia: Warrior Within — популярная игра для Nintendo GameCube."),
                ("Prince of Persia: The Two Thrones", "Финальная часть трилогии с Темным Принцем и колесницами", 2005, "Ubisoft", "Ubisoft", "WW", "Prince of Persia: The Two Thrones — популярная игра для Nintendo GameCube."),
                ("Rayman 3: Hoodlum Havoc", "3D платформер Рэймана с банками комбо-костюмов", 2003, "Ubisoft", "Ubisoft", "WW", "Rayman 3: Hoodlum Havoc — популярная игра для Nintendo GameCube."),
                ("Red Faction II", "Sci-Fi FPS с технологией разрушения окружения Geo-Mod", 2003, "THQ", "THQ", "WW", "Red Faction II — популярная игра для Nintendo GameCube."),
                ("Resident Evil 2", "Классический Survival Horror Леона и Клэр в Раккун-Сити", 2003, "Capcom", "Capcom", "WW", "Resident Evil 2 — популярная игра для Nintendo GameCube."),
                ("Resident Evil 3: Nemesis", "Джилл Валентайн спасается от Немезиса", 2003, "Capcom", "Capcom", "WW", "Resident Evil 3: Nemesis — популярная игра для Nintendo GameCube."),
                ("Resident Evil Code: Veronica X", "Клэр Редфилд на острове Рокфорт против Альфреда и Алексии Эшфорд", 2003, "Capcom", "Capcom", "WW", "Resident Evil Code: Veronica X — популярная игра для Nintendo GameCube."),
                ("Second Sight", "Психологический экшен о телекинезе и пси-способностях от Free Radical", 2004, "Codemasters", "Codemasters", "WW", "Second Sight — популярная игра для Nintendo GameCube."),
                ("Shadow the Hedgehog", "Спин-офф ежа Шэдоу с огнестрельным оружием и выбором добра/зла", 2005, "Sega", "Sega", "WW", "Shadow the Hedgehog — популярная игра для Nintendo GameCube."),
                ("Sonic Adventure DX: Director's Cut", "3D приключения Соника и 6 персонажей с садом Чао", 2003, "Sega", "Sega", "WW", "Sonic Adventure DX: Director's Cut — популярная игра для Nintendo GameCube."),
                ("Sonic Adventure 2: Battle", "Противостояние Героев и Злодеев, появление ежа Шэдоу и летучей мыши Руж", 2001, "Sega", "Sega", "WW", "Sonic Adventure 2: Battle — популярная игра для Nintendo GameCube."),
                ("Sonic Heroes", "Командный 3D скоростной экшен за тройки героев (Скорость, Полет, Сила)", 2003, "Sega", "Sega", "WW", "Sonic Heroes — популярная игра для Nintendo GameCube."),
                ("Sonic Riders", "Сверхзвуковые гонки на летающих ховербордах Extreme Gear", 2006, "Sega", "Sega", "WW", "Sonic Riders — популярная игра для Nintendo GameCube."),
                ("Soulcalibur II", "Легендарный файтинг на мечах с эксклюзивным гостевым бойцом Линком с Master Sword", 2003, "Namco", "Namco", "WW", "Soulcalibur II — популярная игра для Nintendo GameCube."),
                ("Spartan: Total Warrior", "Масштабный античный слэшер спартанского воина от Creative Assembly", 2005, "Sega", "Sega", "WW", "Spartan: Total Warrior — популярная игра для Nintendo GameCube."),
                ("SSX Tricky", "Культовый безумный сноубординг с супертрюками под Run-D.M.C.", 2001, "EA Sports BIG", "EA Sports BIG", "WW", "SSX Tricky — популярная игра для Nintendo GameCube."),
                ("SSX 3", "Сноубординг по открытой гигантской горе с пика до подножия от EA Sports BIG", 2003, "EA Sports BIG", "EA Sports BIG", "WW", "SSX 3 — популярная игра для Nintendo GameCube."),
                ("Star Fox Adventures", "Приключения Фокса Макклауда на планете динозавров Саурия с волшебным посохом от Rare", 2002, "Nintendo", "Nintendo", "WW", "Star Fox Adventures — популярная игра для Nintendo GameCube."),
                ("Star Fox: Assault", "Космические битвы Arwing и наземные перестрелки с апароидами от Namco", 2005, "Nintendo", "Nintendo", "WW", "Star Fox: Assault — популярная игра для Nintendo GameCube."),
                ("Super Monkey Ball", "Прокатывание обезьянки в прозрачном шаре по трехмерным лабиринтам от Amusement Vision", 2001, "Sega", "Sega", "WW", "Super Monkey Ball — популярная игра для Nintendo GameCube."),
                ("Super Monkey Ball 2", "Вторая часть обезьяньих лабиринтов с 12 мини-играми для вечеринок", 2002, "Sega", "Sega", "WW", "Super Monkey Ball 2 — популярная игра для Nintendo GameCube."),
                ("TimeSplitters 2", "Один из лучших консольных FPS всех времен с путешествиями во времени от Free Radical", 2002, "Eidos", "Eidos", "WW", "TimeSplitters 2 — популярная игра для Nintendo GameCube."),
                ("TimeSplitters: Future Perfect", "Кортез спасает человечество сквозь эпохи с грави-пушкой", 2005, "EA Games", "EA Games", "WW", "TimeSplitters: Future Perfect — популярная игра для Nintendo GameCube."),
                ("Tony Hawk's Pro Skater 3", "Скейтбординг Тони Хоука 3", 2001, "Activision", "Activision", "WW", "Tony Hawk's Pro Skater 3 — популярная игра для Nintendo GameCube."),
                ("Tony Hawk's Pro Skater 4", "Скейтбординг с открытыми локациями без таймера", 2002, "Activision", "Activision", "WW", "Tony Hawk's Pro Skater 4 — популярная игра для Nintendo GameCube."),
                ("Tony Hawk's Underground", "Сюжетный подъем скейтера из трущоб в профессионалы", 2003, "Activision", "Activision", "WW", "Tony Hawk's Underground — популярная игра для Nintendo GameCube."),
                ("Tony Hawk's Underground 2", "Безумный мировой тур разрушений с Бэмом Марджерой", 2004, "Activision", "Activision", "WW", "Tony Hawk's Underground 2 — популярная игра для Nintendo GameCube."),
                ("Tony Hawk's American Wasteland", "Бесшовный Лос-Анджелес для скейтбординга и BMX", 2005, "Activision", "Activision", "WW", "Tony Hawk's American Wasteland — популярная игра для Nintendo GameCube."),
                ("True Crime: Streets of LA", "Полицейский экшен в открытом Лос-Анджелесе в масштабе 1:1", 2003, "Activision", "Activision", "WW", "True Crime: Streets of LA — популярная игра для Nintendo GameCube."),
                ("True Crime: New York City", "Полицейский боевик на улицах Нью-Йорка", 2005, "Activision", "Activision", "WW", "True Crime: New York City — популярная игра для Nintendo GameCube."),
                ("Ultimate Spider-Man", "Сел-шейдинг экшен Человека-Паука и Венома по комиксам Брайана Бендиса", 2005, "Activision", "Activision", "WW", "Ultimate Spider-Man — популярная игра для Nintendo GameCube."),
                ("Viewtiful Joe 2", "Джо и его подруга Сильвия в кино-мирах", 2004, "Capcom", "Capcom", "WW", "Viewtiful Joe 2 — популярная игра для Nintendo GameCube."),
                ("Wario World", "3D экшен-платформер Варио с рестлинг-бросками от студии Treasure", 2003, "Nintendo", "Nintendo", "WW", "Wario World — популярная игра для Nintendo GameCube."),
                ("WarioWare, Inc.: Mega Party Game$!", "Безумные микро-игры для 4 игроков на одном экране", 2003, "Nintendo", "Nintendo", "WW", "WarioWare, Inc.: Mega Party Game$! — популярная игра для Nintendo GameCube."),
                ("Wave Race: Blue Storm", "Водные гонки на гидроциклах с динамической симуляцией волн и бурь от NST", 2001, "Nintendo", "Nintendo", "WW", "Wave Race: Blue Storm — популярная игра для Nintendo GameCube."),
                ("WWE Day of Reckoning", "Реалистичный рестлинг с физикой повреждений тела", 2004, "THQ", "THQ", "WW", "WWE Day of Reckoning — популярная игра для Nintendo GameCube."),
                ("WWE Day of Reckoning 2", "Вторая часть рестлинга с сюжетным режимом и механикой выносливости", 2005, "THQ", "THQ", "WW", "WWE Day of Reckoning 2 — популярная игра для Nintendo GameCube."),
                ("X-Men Legends", "Кооперативная Action-RPG Людей Икс на 4 игроков", 2004, "Activision", "Activision", "WW", "X-Men Legends — популярная игра для Nintendo GameCube."),
                ("X-Men Legends II: Rise of Apocalypse", "Объединение Людей Икс и Братства Мутантов Магнето против Апокалипсиса", 2005, "Activision", "Activision", "WW", "X-Men Legends II: Rise of Apocalypse — популярная игра для Nintendo GameCube."),
                ("BloodRayne", "Экшен-слэшер", 2002, "Terminal Reality", "Majesco", "WW", "Полувампирша Рейн кромсает нацистов лезвиями и пьет кровь в слоу-мо."),
                ("Bomberman Generation", "3D Приключения", 2002, "Hudson Soft", "Majesco", "WW", "Сел-шейдинг приключения Бомбермена с кормлением и выращиванием питомцев Чарабамов."),
                ("Bomberman Jetters", "3D Приключения", 2003, "Hudson Soft", "Majseco", "WW", "По мотивам аниме Jetters с элементами стихийных бомб."),
                ("Harvest Moon: A Wonderful Life", "Симулятор жизни / фермы", 2003, "Marvelous", "Natsume", "WW", "Жизнь фермера в долине Незабудок сквозь 6 глав от молодости до старости и воспитания сына."),
                ("Harvest Moon: Magical Melody", "Симулятор фермы", 2005, "Marvelous", "Natsume", "WW", "Сбор 100 музыкальных нот для пробуждения Богини Урожая с покупкой земли в деревне."),
                ("Kirby Air Ride", "Гонки", 2003, "HAL Laboratory", "Nintendo", "WW", "Гонки на летающих звездах от Масахиро Сакурая с легендарным режимом исследования City Trial."),
                ("Pokemon Colosseum", "3D JRPG", 2003, "Genius Sonority", "Nintendo", "WW", "Уэс с мотоциклом спасает темных покемонов Shadow Pokemon в регионе Орре с двойными битвами."),
                ("Pokemon XD: Gale of Darkness", "3D JRPG", 2005, "Genius Sonority", "Nintendo", "WW", "Майкл и Темная Лугия Shadow Lugia XD001 в пустынном Орре."),
                ("Resident Evil 0", "Survival Horror", 2002, "Capcom", "Capcom", "WW", "Ребекка Чемберс и Билли Коэн в поезде Эклипс с системой переключения Partner Zapping без сундуков."),
                ("The Legend of Zelda: Four Swords Adventures", "Кооперативный Action-Adventure", 2004, "Nintendo EAD", "Nintendo", "WW", "4 разноцветных Линка сражаются и решают головоломки на GameCube с экранами GBA."),
                ("WarioWare, Inc.: Mega Party Games!", "Вечеринка микро-игр", 2003, "Nintendo R&D1", "Nintendo", "WW", "Безумные 5-секундные микро-игры для 4 игроков на одном экране."),
            };

            foreach (var g in games)
            {
                list.Add(new NintendoCatalogItem
                {
                    Title = g.Title,
                    Genre = g.Genre,
                    Year = g.Year,
                    Developer = g.Dev,
                    Publisher = g.Pub,
                    Region = g.Region,
                    Desc = g.Desc
                });
            }

            return list;
        }
    }
}
