using System;
using System.Collections.Generic;

namespace StormSwitchBox.Services
{
    public static class GameBoyCatalogData
    {
        public static List<NintendoCatalogItem> GetCatalog()
        {
            var list = new List<NintendoCatalogItem>(305);

            var games = new (string Title, string Genre, int Year, string Dev, string Pub, string Region, string Desc)[]
            {
                ("Tetris", "Головоломка", 1989, "Nintendo R&D1", "Nintendo", "WW", "Легендарный стартовый хит карманной консоли Game Boy, разошедшийся тиражом более 35 млн копий."),
                ("Super Mario Land", "Платформер", 1989, "Nintendo R&D1", "Nintendo", "WW", "Первое портативное приключение Марио в королевстве Сарасаленд и спасение принцессы Дейзи от Татанги."),
                ("Super Mario Land 2: 6 Golden Coins", "Платформер", 1992, "Nintendo R&D1", "Nintendo", "WW", "Шедевр портативного гейминга, впервые представивший миру антигероя Варио и его замок."),
                ("Wario Land: Super Mario Land 3", "Платформер", 1994, "Nintendo R&D1", "Nintendo", "WW", "Дебют Варио в качестве главного героя с охотой за сокровищами и шляпами-трансформациями."),
                ("Wario Land II", "Платформер", 1998, "Nintendo R&D1", "Nintendo", "WW", "Бессмертный Варио решает физические головоломки, превращаясь в огонь, зомби и пружину."),
                ("The Legend of Zelda: Link's Awakening", "Action-Adventure", 1993, "Nintendo EAD", "Nintendo", "WW", "Линк терпит кораблекрушение на таинственном острове Кохолинт и будит Рыбу Ветров."),
                ("Pokemon Red Version", "JRPG", 1996, "Game Freak", "Nintendo", "WW", "Рождение глобального феномена ловли 151 покемона в регионе Канто от Сатоси Тадзири."),
                ("Pokemon Blue Version", "JRPG", 1996, "Game Freak", "Nintendo", "WW", "Оригинальная версия парной RPG с эксклюзивными покемонами и обменом через кабель Game Link."),
                ("Pokemon Yellow Version: Special Pikachu Edition", "JRPG", 1998, "Game Freak", "Nintendo", "WW", "Специальное издание по мотивам аниме: Пикачу следует за тренером по пятам."),
                ("Metroid II: Return of Samus", "Метроидвания", 1991, "Nintendo R&D1", "Nintendo", "WW", "Самус Аран спускается в недра планеты SR388 для полного уничтожения вида Метроидов."),
                ("Kirby's Dream Land", "Платформер", 1992, "HAL Laboratory", "Nintendo", "WW", "Дебют розового колобка Кирби от Масахиро Сакурая со втягиванием врагов и полетами."),
                ("Kirby's Dream Land 2", "Платформер", 1995, "HAL Laboratory", "Nintendo", "WW", "Кирби путешествует верхом на хомяке Рике, филине Ку и рыбе Кайн."),
                ("Kirby's Pinball Land", "Пинбол", 1993, "HAL Laboratory", "Nintendo", "WW", "Три многоярусных стола пинбола со звездами вселенной Кирби."),
                ("Kirby's Block Ball", "Арканоид", 1995, "HAL Laboratory / Nintendo", "Nintendo", "WW", "Разрушение блоков шариком-Кирби с уникальными способностями копирования."),
                ("Donkey Kong (Game Boy '94)", "Головоломка / Платформер", 1994, "Nintendo EAD / Pax Softnica", "Nintendo", "WW", "Грандиозное переосмысление с 101 уровнем, сальто Марио, стойками на руках и спасением Полин."),
                ("Donkey Kong Land", "Платформер", 1995, "Rare", "Nintendo", "WW", "Технологическое чудо с предрендеренной 3D-графикой от Rare на 8-битном экране."),
                ("Donkey Kong Land 2", "Платформер", 1996, "Rare", "Nintendo", "WW", "Дидди Конг и Дикси спасают Донки Конга с острова Крокодилов."),
                ("Donkey Kong Land III", "Платформер", 1997, "Rare", "Nintendo", "WW", "Поиск Затерянного мира в Северном Кремсфере с Дикси и Кидди Конгом."),
                ("Mega Man: Dr. Wily's Revenge", "Экшен / Платформер", 1991, "Minakuchi Engineering", "Capcom", "WW", "Портативный дебют Мегамена против 8 боссов и Энкер с зеркальным копьем."),
                ("Mega Man II", "Экшен / Платформер", 1992, "Japan Art Media", "Capcom", "WW", "Мегамен против Квинт и его землеройного бура Сакагар."),
                ("Mega Man III", "Экшен / Платформер", 1992, "Minakuchi Engineering", "Capcom", "WW", "Мегамен и собака Раш против Панка и Screw Crusher."),
                ("Mega Man IV", "Экшен / Платформер", 1993, "Minakuchi Engineering", "Capcom", "WW", "Появление магазина доктора Лайта и бластера Mega Arm."),
                ("Mega Man V", "Экшен / Платформер", 1994, "Minakuchi Engineering", "Capcom", "WW", "Уникальная игра с боссами-планетами Stardroids и космическим котом Танго."),
                ("Castlevania: The Adventure", "Экшен / Платформер", 1989, "Konami", "Konami", "WW", "Кристофер Бельмонт уничтожает летучих мышей и вампиров кнутом с огненными шарами."),
                ("Castlevania II: Belmont's Revenge", "Экшен / Платформер", 1991, "Konami", "Konami", "WW", "Один из лучших саундтреков Game Boy и спасение сына Солейла."),
                ("Castlevania Legends", "Экшен / Платформер", 1997, "KCE Nagoya", "Konami", "WW", "Соня Бельмонт с кнутом и силой душ предков в битве против Дракулы."),
                ("Gargoyle's Quest", "Action-RPG / Платформер", 1990, "Capcom", "Capcom", "WW", "Горгулья Файрбренд парит над лавой и спасает Мир Демонов."),
                ("Final Fantasy Adventure (Seiken Densetsu)", "Action-RPG", 1991, "Square", "Square", "WW", "Рождение легендарной саги Mana с мечами, топорами, магией и Древом Маны."),
                ("Final Fantasy Legend, The (SaGa)", "JRPG", 1989, "Square", "Square", "WW", "Первая портативная JRPG Акитоси Кавадзу с восхождением на Башню к Богу."),
                ("Final Fantasy Legend II (SaGa 2)", "JRPG", 1990, "Square", "Square", "WW", "Поиск 77 фрагментов реликвий богов Magi через разные миры."),
                ("Final Fantasy Legend III (SaGa 3)", "JRPG", 1991, "Square", "Square", "WW", "Путешествия сквозь прошлое, настоящее и будущее на летающем корабле Talon."),
                ("Bionic Commando (Game Boy)", "Экшен / Платформер", 1992, "Minakuchi Engineering", "Capcom", "WW", "Футуристический ремейк с механической рукой-крюком и лазерным бластером."),
                ("Kid Icarus: Of Myths and Monsters", "Платформер", 1991, "Nintendo R&D1 / TOSE", "Nintendo", "WW", "Пит тренируется ради спасения Ангельской земли от демона Орки."),
                ("DuckTales (Game Boy)", "Платформер", 1990, "Capcom", "Capcom", "WW", "Портативное путешествие Скруджа Макдака за сокровищами."),
                ("DuckTales 2 (Game Boy)", "Платформер", 1993, "Capcom", "Capcom", "WW", "Поиск фрагментов карты сокровищ."),
                ("Darkwing Duck (Game Boy)", "Платформер", 1993, "Capcom", "Capcom", "WW", "Черный Плащ на улицах Сен-Канара."),
                ("Ninja Gaiden Shadow", "Экшен / Платформер", 1991, "Natsume", "Tecmo", "WW", "Рю Хаябуса с ниндзя-мечом и крюком штурмует секретную цитадель."),
                ("Batman: The Video Game (Game Boy)", "Экшен / Платформер", 1990, "Sunsoft", "Sunsoft", "WW", "Бэтмен с бэтарангами и огнестрельным оружием в Готэме."),
                ("Batman: Return of the Joker (Game Boy)", "Платформер", 1992, "Sunsoft", "Sunsoft", "WW", "Бэтмен против Джокера с разнообразным оружием."),
                ("Batman: The Animated Series", "Экшен / Платформер", 1993, "Konami", "Konami", "WW", "Бэтмен и Робин по мотивам культового мультсериала."),
                ("R-Type (Game Boy)", "Горизонтальный SHMUP", 1991, "Bits Studios", "Irem", "WW", "Корабль R-9 с модулем Force против инопланетной империи Байд."),
                ("Gradius: The Interstellar Assault (Nemesis II)", "Горизонтальный SHMUP", 1991, "Konami", "Konami", "WW", "Vic Viper в космическом пространстве с апгрейдами щита и лазеров."),
                ("Parodius (Game Boy)", "Комедийный SHMUP", 1991, "Konami", "Konami", "WW", "Осьминог Тако, пингвин Пентаро и летающий корабль Vic Viper."),
                ("Avenging Spirit", "Аркадный экшен", 1992, "Jaleco", "Jaleco", "WW", "Призрак вселяется в тела врагов, чтобы спасти свою девушку."),
                ("Mole Mania", "Логическая головоломка", 1996, "Pax Softnica / Nintendo", "Nintendo", "WW", "Крот Мадди копает подземные ходы под руководством Сигэру Миямото."),
                ("Mario & Yoshi", "Головоломка", 1991, "Game Freak", "Nintendo", "WW", "Падающие скорлупки и монстры от создателей покемонов."),
                ("Yoshi's Cookie (Game Boy)", "Головоломка", 1992, "TOSE", "Nintendo", "WW", "Передвижение рядов печенья под веселую музыку."),
                ("Wario's Woods (Game Boy)", "Головоломка", 1994, "Nintendo R&D1", "Nintendo", "WW", "Тоад уничтожает монстров бомбами."),
                ("Dr. Mario (Game Boy)", "Головоломка", 1990, "Nintendo R&D1", "Nintendo", "WW", "Уничтожение вирусов цветными пилюлями."),
                ("Qix (Game Boy)", "Аркада", 1990, "Nintendo R&D1", "Nintendo", "WW", "Захват площади с танцующим Марио."),
                ("Alleyway", "Арканоид", 1989, "Nintendo R&D1", "Nintendo", "WW", "Стартовый арканоид с пилотом Марио в бите."),
                ("SolarStriker", "Вертикальный SHMUP", 1990, "Nintendo R&D1 / Minakuchi", "Nintendo", "WW", "Классический вертикальный космический шутер от Гумпэя Ёкои."),
                ("Balloon Kid", "Платформер", 1990, "Pax Softnica / Nintendo", "Nintendo", "WW", "Девочка Элис летит на воздушных шариках спасать брата Джима."),
                ("Adventure Island", "Платформер", 1992, "Hudson Soft", "Hudson Soft", "WW", "Adventure Island — популярная игра для Nintendo Game Boy."),
                ("Adventure Island II", "Платформер", 1993, "Hudson Soft", "Hudson Soft", "WW", "Adventure Island II — популярная игра для Nintendo Game Boy."),
                ("Adventures of Lolo", "Головоломка", 1994, "HAL Laboratory", "HAL Laboratory", "WW", "Adventures of Lolo — популярная игра для Nintendo Game Boy."),
                ("Alien 3", "Экшен / Выживание", 1993, "LJN", "LJN", "WW", "Alien 3 — популярная игра для Nintendo Game Boy."),
                ("Alien vs Predator", "Экшен", 1993, "Activision", "Activision", "WW", "Alien vs Predator — популярная игра для Nintendo Game Boy."),
                ("Animaniacs", "Платформер", 1995, "Konami", "Konami", "WW", "Animaniacs — популярная игра для Nintendo Game Boy."),
                ("Arcade Classic No. 1: Pong & Asteroids", "Ретро-аркада", 1995, "Nintendo", "Nintendo", "WW", "Arcade Classic No. 1: Pong & Asteroids — популярная игра для Nintendo Game Boy."),
                ("Arcade Classic No. 2: Centipede & Millipede", "Ретро-аркада", 1995, "Nintendo", "Nintendo", "WW", "Arcade Classic No. 2: Centipede & Millipede — популярная игра для Nintendo Game Boy."),
                ("Arcade Classic No. 3: Galaga & Galaxian", "Ретро-космошутер", 1995, "Nintendo", "Nintendo", "WW", "Arcade Classic No. 3: Galaga & Galaxian — популярная игра для Nintendo Game Boy."),
                ("Arcade Classic No. 4: Defender & Joust", "Ретро-аркада", 1995, "Nintendo", "Nintendo", "WW", "Arcade Classic No. 4: Defender & Joust — популярная игра для Nintendo Game Boy."),
                ("Asterix", "Платформер", 1993, "Infogrames", "Infogrames", "WW", "Asterix — популярная игра для Nintendo Game Boy."),
                ("Asteroids", "Космошутер", 1991, "Mindscape", "Mindscape", "WW", "Asteroids — популярная игра для Nintendo Game Boy."),
                ("Attack of the Killer Tomatoes", "Экшен-платформер", 1992, "THQ", "THQ", "WW", "Attack of the Killer Tomatoes — популярная игра для Nintendo Game Boy."),
                ("Balloon Fight GB", "Аркада", 2000, "Nintendo", "Nintendo", "WW", "Balloon Fight GB — популярная игра для Nintendo Game Boy."),
                ("Barbie: Game Girl", "Приключения", 1992, "Hi-Tech", "Hi-Tech", "WW", "Barbie: Game Girl — популярная игра для Nintendo Game Boy."),
                ("Bart Simpson's Escape from Camp Deadly", "Приключения", 1991, "Acclaim", "Acclaim", "WW", "Bart Simpson's Escape from Camp Deadly — популярная игра для Nintendo Game Boy."),
                ("Baseball", "Спорт / Бейсбол", 1989, "Nintendo", "Nintendo", "WW", "Baseball — популярная игра для Nintendo Game Boy."),
                ("Battle Arena Toshinden", "Файтинг", 1996, "Takara", "Takara", "WW", "Battle Arena Toshinden — популярная игра для Nintendo Game Boy."),
                ("Battle City", "Танчики", 1991, "Namco", "Namco", "WW", "Battle City — популярная игра для Nintendo Game Boy."),
                ("Battletoads in Ragnarok's World", "Beat 'em up", 1993, "Tradewest", "Tradewest", "WW", "Battletoads in Ragnarok's World — популярная игра для Nintendo Game Boy."),
                ("Battletoads & Double Dragon", "Beat 'em up", 1993, "Tradewest", "Tradewest", "WW", "Battletoads & Double Dragon — популярная игра для Nintendo Game Boy."),
                ("Blaster Master Boy", "Экшен", 1991, "Sunsoft", "Sunsoft", "WW", "Blaster Master Boy — популярная игра для Nintendo Game Boy."),
                ("Bomberman GB", "Аркада", 1994, "Hudson Soft", "Hudson Soft", "WW", "Bomberman GB — популярная игра для Nintendo Game Boy."),
                ("Bomberman GB 2", "Аркада", 1995, "Hudson Soft", "Hudson Soft", "WW", "Bomberman GB 2 — популярная игра для Nintendo Game Boy."),
                ("Bomberman GB 3", "Аркада", 1996, "Hudson Soft", "Hudson Soft", "WW", "Bomberman GB 3 — популярная игра для Nintendo Game Boy."),
                ("Bonk's Adventure", "Платформер", 1992, "Hudson Soft", "Hudson Soft", "WW", "Bonk's Adventure — популярная игра для Nintendo Game Boy."),
                ("Bonk's Revenge", "Платформер", 1994, "Hudson Soft", "Hudson Soft", "WW", "Bonk's Revenge — популярная игра для Nintendo Game Boy."),
                ("Boxxle", "Головоломка", 1989, "FCI", "FCI", "WW", "Boxxle — популярная игра для Nintendo Game Boy."),
                ("Boxxle II", "Головоломка", 1991, "FCI", "FCI", "WW", "Boxxle II — популярная игра для Nintendo Game Boy."),
                ("Bram Stoker's Dracula", "Экшен", 1993, "Sony Imagesoft", "Sony Imagesoft", "WW", "Bram Stoker's Dracula — популярная игра для Nintendo Game Boy."),
                ("Bubble Bobble", "Аркада", 1991, "Taito", "Taito", "WW", "Bubble Bobble — популярная игра для Nintendo Game Boy."),
                ("Bubble Bobble Part 2", "Аркада", 1993, "Taito", "Taito", "WW", "Bubble Bobble Part 2 — популярная игра для Nintendo Game Boy."),
                ("Bubble Ghost", "Головоломка", 1990, "Pony Canyon", "Pony Canyon", "WW", "Bubble Ghost — популярная игра для Nintendo Game Boy."),
                ("Bugs Bunny Crazy Castle", "Головоломка", 1989, "Kemco", "Kemco", "WW", "Bugs Bunny Crazy Castle — популярная игра для Nintendo Game Boy."),
                ("Bugs Bunny Crazy Castle II", "Головоломка", 1992, "Kemco", "Kemco", "WW", "Bugs Bunny Crazy Castle II — популярная игра для Nintendo Game Boy."),
                ("BurgerTime Deluxe", "Аркада", 1991, "Data East", "Data East", "WW", "BurgerTime Deluxe — популярная игра для Nintendo Game Boy."),
                ("Bust-A-Move 2: Arcade Edition", "Головоломка", 1997, "Taito", "Taito", "WW", "Bust-A-Move 2: Arcade Edition — популярная игра для Nintendo Game Boy."),
                ("Bust-A-Move 3 DX", "Головоломка", 1998, "Taito", "Taito", "WW", "Bust-A-Move 3 DX — популярная игра для Nintendo Game Boy."),
                ("Buster Bros. (Pang)", "Аркада", 1993, "Hudson Soft", "Hudson Soft", "WW", "Buster Bros. (Pang) — популярная игра для Nintendo Game Boy."),
                ("Capcom Baseball", "Спорт", 1989, "Capcom", "Capcom", "WW", "Capcom Baseball — популярная игра для Nintendo Game Boy."),
                ("Captain Tsubasa J", "Спортивная тактика", 1995, "Bandai", "Bandai", "WW", "Captain Tsubasa J — популярная игра для Nintendo Game Boy."),
                ("Casper", "Приключения", 1996, "Interplay", "Interplay", "WW", "Casper — популярная игра для Nintendo Game Boy."),
                ("Centipede", "Аркада", 1992, "Accolade", "Accolade", "WW", "Centipede — популярная игра для Nintendo Game Boy."),
                ("Choplifter II", "Экшен", 1991, "Victor", "Victor", "WW", "Choplifter II — популярная игра для Nintendo Game Boy."),
                ("Choplifter III", "Экшен", 1993, "Ocean", "Ocean", "WW", "Choplifter III — популярная игра для Nintendo Game Boy."),
                ("Chuck Rock", "Платформер", 1992, "Virgin", "Virgin", "WW", "Chuck Rock — популярная игра для Nintendo Game Boy."),
                ("Cliffhanger", "Экшен", 1993, "Sony Imagesoft", "Sony Imagesoft", "WW", "Cliffhanger — популярная игра для Nintendo Game Boy."),
                ("Contra: The Alien Wars (Operation C)", "Run and Gun", 1991, "Konami", "Konami", "WW", "Contra: The Alien Wars (Operation C) — популярная игра для Nintendo Game Boy."),
                ("Cool Spot", "Платформер", 1994, "Virgin", "Virgin", "WW", "Cool Spot — популярная игра для Nintendo Game Boy."),
                ("Cosmo Tank", "Танковый симулятор", 1990, "Asmik", "Asmik", "WW", "Cosmo Tank — популярная игра для Nintendo Game Boy."),
                ("Daffy Duck: The Marvin Missions", "Платформер", 1994, "Sunsoft", "Sunsoft", "WW", "Daffy Duck: The Marvin Missions — популярная игра для Nintendo Game Boy."),
                ("Days of Thunder", "Гонки", 1991, "Mindscape", "Mindscape", "WW", "Days of Thunder — популярная игра для Nintendo Game Boy."),
                ("Desert Strike: Return to the Gulf", "Экшен / Вертолет", 1994, "Electronic Arts", "Electronic Arts", "WW", "Desert Strike: Return to the Gulf — популярная игра для Nintendo Game Boy."),
                ("Dick Tracy", "Экшен", 1991, "Bandai", "Bandai", "WW", "Dick Tracy — популярная игра для Nintendo Game Boy."),
                ("Dig Dug", "Аркада", 1992, "Namco", "Namco", "WW", "Dig Dug — популярная игра для Nintendo Game Boy."),
                ("Double Dragon", "Beat 'em up", 1990, "Tradewest", "Tradewest", "WW", "Double Dragon — популярная игра для Nintendo Game Boy."),
                ("Double Dragon II", "Beat 'em up", 1991, "Acclaim", "Acclaim", "WW", "Double Dragon II — популярная игра для Nintendo Game Boy."),
                ("Double Dragon 3", "Beat 'em up", 1992, "Acclaim", "Acclaim", "WW", "Double Dragon 3 — популярная игра для Nintendo Game Boy."),
                ("Dr. Franken", "Платформер", 1992, "Kemco", "Kemco", "WW", "Dr. Franken — популярная игра для Nintendo Game Boy."),
                ("Earthworm Jim", "Платформер", 1995, "Playmates", "Playmates", "WW", "Earthworm Jim — популярная игра для Nintendo Game Boy."),
                ("Elevator Action", "Экшен", 1991, "Taito", "Taito", "WW", "Elevator Action — популярная игра для Nintendo Game Boy."),
                ("F-1 Race", "Гонки", 1990, "Nintendo", "Nintendo", "WW", "F-1 Race — популярная игра для Nintendo Game Boy."),
                ("F1 Pole Position", "Гонки", 1993, "Ubisoft", "Ubisoft", "WW", "F1 Pole Position — популярная игра для Nintendo Game Boy."),
                ("Faceball 2000", "FPS 3D", 1991, "Bullet-Proof", "Bullet-Proof", "WW", "Faceball 2000 — популярная игра для Nintendo Game Boy."),
                ("Felix the Cat", "Платформер", 1993, "Hudson Soft", "Hudson Soft", "WW", "Felix the Cat — популярная игра для Nintendo Game Boy."),
                ("FIFA International Soccer", "Спорт / Футбол", 1995, "Electronic Arts", "Electronic Arts", "WW", "FIFA International Soccer — популярная игра для Nintendo Game Boy."),
                ("FIFA 96", "Спорт / Футбол", 1995, "Electronic Arts", "Electronic Arts", "WW", "FIFA 96 — популярная игра для Nintendo Game Boy."),
                ("FIFA 97", "Спорт / Футбол", 1996, "Electronic Arts", "Electronic Arts", "WW", "FIFA 97 — популярная игра для Nintendo Game Boy."),
                ("FIFA 98: Road to World Cup", "Спорт / Футбол", 1997, "Electronic Arts", "Electronic Arts", "WW", "FIFA 98: Road to World Cup — популярная игра для Nintendo Game Boy."),
                ("Flintstones: King Rock Theater", "Платформер", 1993, "Taito", "Taito", "WW", "Flintstones: King Rock Theater — популярная игра для Nintendo Game Boy."),
                ("Frogger", "Аркада", 1998, "Majesco", "Majesco", "WW", "Frogger — популярная игра для Nintendo Game Boy."),
                ("Game & Watch Gallery", "Сборник аркад", 1997, "Nintendo", "Nintendo", "WW", "Game & Watch Gallery — популярная игра для Nintendo Game Boy."),
                ("Game & Watch Gallery 2", "Сборник аркад", 1998, "Nintendo", "Nintendo", "WW", "Game & Watch Gallery 2 — популярная игра для Nintendo Game Boy."),
                ("Game & Watch Gallery 3", "Сборник аркад", 1999, "Nintendo", "Nintendo", "WW", "Game & Watch Gallery 3 — популярная игра для Nintendo Game Boy."),
                ("Gauntlet II", "Экшен / Подземелья", 1990, "Mindscape", "Mindscape", "WW", "Gauntlet II — популярная игра для Nintendo Game Boy."),
                ("Ghostbusters II", "Экшен", 1990, "HAL Laboratory", "HAL Laboratory", "WW", "Ghostbusters II — популярная игра для Nintendo Game Boy."),
                ("Ghosts 'n Goblins", "Платформер", 1999, "Capcom", "Capcom", "WW", "Ghosts 'n Goblins — популярная игра для Nintendo Game Boy."),
                ("Godzilla", "Экшен", 1990, "Toho", "Toho", "WW", "Godzilla — популярная игра для Nintendo Game Boy."),
                ("Golf", "Спорт / Гольф", 1989, "Nintendo", "Nintendo", "WW", "Golf — популярная игра для Nintendo Game Boy."),
                ("Gradius", "SHMUP", 1990, "Konami", "Konami", "WW", "Gradius — популярная игра для Nintendo Game Boy."),
                ("Gremlins 2: The New Batch", "Экшен", 1991, "Sunsoft", "Sunsoft", "WW", "Gremlins 2: The New Batch — популярная игра для Nintendo Game Boy."),
                ("Hammerin' Harry", "Экшен / Платформер", 1992, "Irem", "Irem", "WW", "Hammerin' Harry — популярная игра для Nintendo Game Boy."),
                ("Harvest Moon GB", "Симулятор фермы", 1997, "Natsume", "Natsume", "WW", "Harvest Moon GB — популярная игра для Nintendo Game Boy."),
                ("Home Alone", "Приключения", 1991, "THQ", "THQ", "WW", "Home Alone — популярная игра для Nintendo Game Boy."),
                ("Home Alone 2: Lost in New York", "Приключения", 1992, "THQ", "THQ", "WW", "Home Alone 2: Lost in New York — популярная игра для Nintendo Game Boy."),
                ("Hook", "Платформер", 1992, "Sony Imagesoft", "Sony Imagesoft", "WW", "Hook — популярная игра для Nintendo Game Boy."),
                ("Hugo", "Платформер", 1995, "Laguna", "Laguna", "WW", "Hugo — популярная игра для Nintendo Game Boy."),
                ("Hyper Lode Runner", "Головоломка", 1989, "Bandai", "Bandai", "WW", "Hyper Lode Runner — популярная игра для Nintendo Game Boy."),
                ("Indiana Jones and the Last Crusade", "Приключения", 1993, "Ubisoft", "Ubisoft", "WW", "Indiana Jones and the Last Crusade — популярная игра для Nintendo Game Boy."),
                ("Ironman Ivan Stewart's Super Off Road", "Гонки", 1992, "Tradewest", "Tradewest", "WW", "Ironman Ivan Stewart's Super Off Road — популярная игра для Nintendo Game Boy."),
                ("James Bond 007", "Action-Adventure", 1998, "Nintendo", "Nintendo", "WW", "James Bond 007 — популярная игра для Nintendo Game Boy."),
                ("Judge Dredd", "Экшен", 1995, "Acclaim", "Acclaim", "WW", "Judge Dredd — популярная игра для Nintendo Game Boy."),
                ("Jungle Book, The", "Платформер", 1994, "Virgin", "Virgin", "WW", "Jungle Book, The — популярная игра для Nintendo Game Boy."),
                ("Jungle Strike", "Экшен / Вертолет", 1995, "Electronic Arts", "Electronic Arts", "WW", "Jungle Strike — популярная игра для Nintendo Game Boy."),
                ("Jurassic Park", "Экшен", 1993, "Ocean", "Ocean", "WW", "Jurassic Park — популярная игра для Nintendo Game Boy."),
                ("Jurassic Park 2: The Chaos Continues", "Экшен", 1994, "Ocean", "Ocean", "WW", "Jurassic Park 2: The Chaos Continues — популярная игра для Nintendo Game Boy."),
                ("Kid Dracula", "Платформер", 1993, "Konami", "Konami", "WW", "Kid Dracula — популярная игра для Nintendo Game Boy."),
                ("Killer Instinct", "Файтинг", 1995, "Nintendo", "Nintendo", "WW", "Killer Instinct — популярная игра для Nintendo Game Boy."),
                ("Klax", "Головоломка", 1991, "Mindscape", "Mindscape", "WW", "Klax — популярная игра для Nintendo Game Boy."),
                ("Lemmings", "Головоломка", 1993, "Ocean", "Ocean", "WW", "Lemmings — популярная игра для Nintendo Game Boy."),
                ("Lemmings 2: The Tribes", "Головоломка", 1994, "Ocean", "Ocean", "WW", "Lemmings 2: The Tribes — популярная игра для Nintendo Game Boy."),
                ("Lion King, The", "Платформер", 1994, "Virgin", "Virgin", "WW", "Lion King, The — популярная игра для Nintendo Game Boy."),
                ("Little Mermaid, The", "Платформер", 1992, "Capcom", "Capcom", "WW", "Little Mermaid, The — популярная игра для Nintendo Game Boy."),
                ("Lucky Luke", "Платформер", 1996, "Infogrames", "Infogrames", "WW", "Lucky Luke — популярная игра для Nintendo Game Boy."),
                ("Madden NFL 95", "Спорт", 1995, "Electronic Arts", "Electronic Arts", "WW", "Madden NFL 95 — популярная игра для Nintendo Game Boy."),
                ("Madden NFL 96", "Спорт", 1995, "Electronic Arts", "Electronic Arts", "WW", "Madden NFL 96 — популярная игра для Nintendo Game Boy."),
                ("Madden NFL 97", "Спорт", 1996, "Electronic Arts", "Electronic Arts", "WW", "Madden NFL 97 — популярная игра для Nintendo Game Boy."),
                ("Magical Drop", "Головоломка", 1999, "Data East", "Data East", "WW", "Magical Drop — популярная игра для Nintendo Game Boy."),
                ("Marble Madness", "Головоломка", 1991, "Mindscape", "Mindscape", "WW", "Marble Madness — популярная игра для Nintendo Game Boy."),
                ("Mario's Picross", "Нонограммы", 1995, "Nintendo", "Nintendo", "WW", "Mario's Picross — популярная игра для Nintendo Game Boy."),
                ("Mario's Picross 2", "Нонограммы", 1996, "Nintendo", "Nintendo", "WW", "Mario's Picross 2 — популярная игра для Nintendo Game Boy."),
                ("Micro Machines", "Гонки", 1995, "Ocean", "Ocean", "WW", "Micro Machines — популярная игра для Nintendo Game Boy."),
                ("Micro Machines 2: Turbo Tournament", "Гонки", 1996, "Ocean", "Ocean", "WW", "Micro Machines 2: Turbo Tournament — популярная игра для Nintendo Game Boy."),
                ("Mighty Morphin Power Rangers", "Beat 'em up", 1994, "Bandai", "Bandai", "WW", "Mighty Morphin Power Rangers — популярная игра для Nintendo Game Boy."),
                ("Monopoly", "Настольная игра", 1991, "Parker Brothers", "Parker Brothers", "WW", "Monopoly — популярная игра для Nintendo Game Boy."),
                ("Mortal Kombat", "Файтинг", 1993, "Acclaim", "Acclaim", "WW", "Mortal Kombat — популярная игра для Nintendo Game Boy."),
                ("Mortal Kombat II", "Файтинг", 1994, "Acclaim", "Acclaim", "WW", "Mortal Kombat II — популярная игра для Nintendo Game Boy."),
                ("Mortal Kombat 3", "Файтинг", 1995, "Acclaim", "Acclaim", "WW", "Mortal Kombat 3 — популярная игра для Nintendo Game Boy."),
                ("Motocross Maniacs", "Мотогонки", 1989, "Konami", "Konami", "WW", "Motocross Maniacs — популярная игра для Nintendo Game Boy."),
                ("Mr. Nutz", "Платформер", 1994, "Ocean", "Ocean", "WW", "Mr. Nutz — популярная игра для Nintendo Game Boy."),
                ("Mystical Ninja Starring Goemon", "Action-Adventure", 1998, "Konami", "Konami", "WW", "Mystical Ninja Starring Goemon — популярная игра для Nintendo Game Boy."),
                ("NBA Jam", "Спорт / Баскетбол", 1994, "Acclaim", "Acclaim", "WW", "NBA Jam — популярная игра для Nintendo Game Boy."),
                ("NBA Jam Tournament Edition", "Спорт / Баскетбол", 1995, "Acclaim", "Acclaim", "WW", "NBA Jam Tournament Edition — популярная игра для Nintendo Game Boy."),
                ("NBA Live 96", "Спорт / Баскетбол", 1995, "Electronic Arts", "Electronic Arts", "WW", "NBA Live 96 — популярная игра для Nintendo Game Boy."),
                ("NFL Football", "Спорт", 1990, "Nintendo", "Nintendo", "WW", "NFL Football — популярная игра для Nintendo Game Boy."),
                ("NHL Hockey 95", "Спорт / Хоккей", 1994, "Electronic Arts", "Electronic Arts", "WW", "NHL Hockey 95 — популярная игра для Nintendo Game Boy."),
                ("NHL 96", "Спорт / Хоккей", 1995, "Electronic Arts", "Electronic Arts", "WW", "NHL 96 — популярная игра для Nintendo Game Boy."),
                ("Pac-Attack", "Головоломка", 1994, "Namco", "Namco", "WW", "Pac-Attack — популярная игра для Nintendo Game Boy."),
                ("Pac-In-Time", "Платформер", 1995, "Namco", "Namco", "WW", "Pac-In-Time — популярная игра для Nintendo Game Boy."),
                ("Pac-Man", "Аркада", 1990, "Namco", "Namco", "WW", "Pac-Man — популярная игра для Nintendo Game Boy."),
                ("Paperboy", "Аркада", 1990, "Mindscape", "Mindscape", "WW", "Paperboy — популярная игра для Nintendo Game Boy."),
                ("Paperboy 2", "Аркада", 1992, "Mindscape", "Mindscape", "WW", "Paperboy 2 — популярная игра для Nintendo Game Boy."),
                ("Pinball Dreams", "Пинбол", 1993, "GameTek", "GameTek", "WW", "Pinball Dreams — популярная игра для Nintendo Game Boy."),
                ("Pinball Fantasies", "Пинбол", 1995, "GameTek", "GameTek", "WW", "Pinball Fantasies — популярная игра для Nintendo Game Boy."),
                ("Pinocchio", "Платформер", 1996, "Virgin", "Virgin", "WW", "Pinocchio — популярная игра для Nintendo Game Boy."),
                ("Pit-Fighter", "Файтинг", 1992, "THQ", "THQ", "WW", "Pit-Fighter — популярная игра для Nintendo Game Boy."),
                ("Pocahontas", "Платформер", 1996, "Disney", "Disney", "WW", "Pocahontas — популярная игра для Nintendo Game Boy."),
                ("Pocket Bomberman", "Платформер", 1997, "Hudson Soft", "Hudson Soft", "WW", "Pocket Bomberman — популярная игра для Nintendo Game Boy."),
                ("Populous", "Симулятор бога", 1993, "Imagineer", "Imagineer", "WW", "Populous — популярная игра для Nintendo Game Boy."),
                ("Primal Rage", "Файтинг", 1995, "Time Warner", "Time Warner", "WW", "Primal Rage — популярная игра для Nintendo Game Boy."),
                ("Prince of Persia", "Платформер", 1992, "Mindscape", "Mindscape", "WW", "Prince of Persia — популярная игра для Nintendo Game Boy."),
                ("Probotector", "Run and Gun", 1991, "Konami", "Konami", "WW", "Probotector — популярная игра для Nintendo Game Boy."),
                ("Punisher: The Ultimate Payback, The", "Шутер", 1991, "Acclaim", "Acclaim", "WW", "Punisher: The Ultimate Payback, The — популярная игра для Nintendo Game Boy."),
                ("Q*bert", "Аркада", 1992, "Jaleco", "Jaleco", "WW", "Q*bert — популярная игра для Nintendo Game Boy."),
                ("Quarth", "Головоломка-шутер", 1990, "Konami", "Konami", "WW", "Quarth — популярная игра для Nintendo Game Boy."),
                ("R-Type II", "SHMUP", 1992, "Irem", "Irem", "WW", "R-Type II — популярная игра для Nintendo Game Boy."),
                ("Rampart", "Стратегия / Аркада", 1992, "Electronic Arts", "Electronic Arts", "WW", "Rampart — популярная игра для Nintendo Game Boy."),
                ("Rayman", "Платформер", 1997, "Ubisoft", "Ubisoft", "WW", "Rayman — популярная игра для Nintendo Game Boy."),
                ("Road Rash", "Мотогонки", 1994, "Electronic Arts", "Electronic Arts", "WW", "Road Rash — популярная игра для Nintendo Game Boy."),
                ("RoboCop", "Экшен", 1990, "Ocean", "Ocean", "WW", "RoboCop — популярная игра для Nintendo Game Boy."),
                ("RoboCop 2", "Экшен", 1991, "Ocean", "Ocean", "WW", "RoboCop 2 — популярная игра для Nintendo Game Boy."),
                ("RoboCop versus The Terminator", "Экшен", 1993, "Virgin", "Virgin", "WW", "RoboCop versus The Terminator — популярная игра для Nintendo Game Boy."),
                ("Samurai Shodown", "Файтинг", 1994, "Takara", "Takara", "WW", "Samurai Shodown — популярная игра для Nintendo Game Boy."),
                ("Sensible Soccer", "Спорт / Футбол", 1995, "Sony Imagesoft", "Sony Imagesoft", "WW", "Sensible Soccer — популярная игра для Nintendo Game Boy."),
                ("Shadowgate", "Квест", 1993, "Mindscape", "Mindscape", "WW", "Shadowgate — популярная игра для Nintendo Game Boy."),
                ("Simpsons: Bart & the Beanstalk", "Платформер", 1994, "Acclaim", "Acclaim", "WW", "Simpsons: Bart & the Beanstalk — популярная игра для Nintendo Game Boy."),
                ("Smurfs, The", "Платформер", 1994, "Infogrames", "Infogrames", "WW", "Smurfs, The — популярная игра для Nintendo Game Boy."),
                ("Snow Bros. Jr.", "Платформер", 1991, "Capcom", "Capcom", "WW", "Snow Bros. Jr. — популярная игра для Nintendo Game Boy."),
                ("Soccer", "Спорт", 1991, "Nintendo", "Nintendo", "WW", "Soccer — популярная игра для Nintendo Game Boy."),
                ("Space Invaders", "Космошутер", 1990, "Taito", "Taito", "WW", "Space Invaders — популярная игра для Nintendo Game Boy."),
                ("Speedy Gonzales", "Платформер", 1993, "Sunsoft", "Sunsoft", "WW", "Speedy Gonzales — популярная игра для Nintendo Game Boy."),
                ("Spider-Man and the X-Men", "Экшен", 1994, "LJN", "LJN", "WW", "Spider-Man and the X-Men — популярная игра для Nintendo Game Boy."),
                ("Star Wars", "Экшен", 1992, "Capcom", "Capcom", "WW", "Star Wars — популярная игра для Nintendo Game Boy."),
                ("Star Wars: The Empire Strikes Back", "Экшен", 1993, "Capcom", "Capcom", "WW", "Star Wars: The Empire Strikes Back — популярная игра для Nintendo Game Boy."),
                ("Street Fighter II", "Файтинг", 1995, "Capcom", "Capcom", "WW", "Street Fighter II — популярная игра для Nintendo Game Boy."),
                ("Street Racer", "Гонки", 1996, "Ubisoft", "Ubisoft", "WW", "Street Racer — популярная игра для Nintendo Game Boy."),
                ("Super Off Road", "Гонки", 1992, "Tradewest", "Tradewest", "WW", "Super Off Road — популярная игра для Nintendo Game Boy."),
                ("Super R.C. Pro-Am", "Гонки", 1992, "Nintendo", "Nintendo", "WW", "Super R.C. Pro-Am — популярная игра для Nintendo Game Boy."),
                ("Superman", "Экшен", 1997, "Titus", "Titus", "WW", "Superman — популярная игра для Nintendo Game Boy."),
                ("TaleSpin", "Платформер", 1992, "Capcom", "Capcom", "WW", "TaleSpin — популярная игра для Nintendo Game Boy."),
                ("Tarzan: Lord of the Jungle", "Платформер", 1994, "GameTek", "GameTek", "WW", "Tarzan: Lord of the Jungle — популярная игра для Nintendo Game Boy."),
                ("Taz-Mania", "Платформер", 1993, "Sunsoft", "Sunsoft", "WW", "Taz-Mania — популярная игра для Nintendo Game Boy."),
                ("Teenage Mutant Ninja Turtles: Fall of the Foot Clan", "Beat 'em up", 1990, "Konami", "Konami", "WW", "Teenage Mutant Ninja Turtles: Fall of the Foot Clan — популярная игра для Nintendo Game Boy."),
                ("Teenage Mutant Ninja Turtles II: Back from the Sewers", "Beat 'em up", 1991, "Konami", "Konami", "WW", "Teenage Mutant Ninja Turtles II: Back from the Sewers — популярная игра для Nintendo Game Boy."),
                ("Teenage Mutant Ninja Turtles III: Radical Rescue", "Метроидвания", 1993, "Konami", "Konami", "WW", "Teenage Mutant Ninja Turtles III: Radical Rescue — популярная игра для Nintendo Game Boy."),
                ("Tennis", "Спорт / Теннис", 1989, "Nintendo", "Nintendo", "WW", "Tennis — популярная игра для Nintendo Game Boy."),
                ("Terminator 2: Judgment Day", "Экшен", 1992, "LJN", "LJN", "WW", "Terminator 2: Judgment Day — популярная игра для Nintendo Game Boy."),
                ("Tintin in Tibet", "Приключения", 1995, "Infogrames", "Infogrames", "WW", "Tintin in Tibet — популярная игра для Nintendo Game Boy."),
                ("Tiny Toon Adventures: Babs' Big Break", "Платформер", 1992, "Konami", "Konami", "WW", "Tiny Toon Adventures: Babs' Big Break — популярная игра для Nintendo Game Boy."),
                ("Tiny Toon Adventures 2: Montana's Movie Madness", "Платформер", 1993, "Konami", "Konami", "WW", "Tiny Toon Adventures 2: Montana's Movie Madness — популярная игра для Nintendo Game Boy."),
                ("Tiny Toon Adventures: Wacky Sports", "Спорт", 1994, "Konami", "Konami", "WW", "Tiny Toon Adventures: Wacky Sports — популярная игра для Nintendo Game Boy."),
                ("Tom and Jerry", "Платформер", 1993, "Hi-Tech", "Hi-Tech", "WW", "Tom and Jerry — популярная игра для Nintendo Game Boy."),
                ("Top Gun: Guts & Glory", "Авиасимулятор", 1993, "Mindscape", "Mindscape", "WW", "Top Gun: Guts & Glory — популярная игра для Nintendo Game Boy."),
                ("Total Carnage", "Run and Gun", 1993, "THQ", "THQ", "WW", "Total Carnage — популярная игра для Nintendo Game Boy."),
                ("Track & Field", "Спорт", 1992, "Konami", "Konami", "WW", "Track & Field — популярная игра для Nintendo Game Boy."),
                ("True Lies", "Экшен", 1995, "LJN", "LJN", "WW", "True Lies — популярная игра для Nintendo Game Boy."),
                ("Tumblepop", "Платформер", 1992, "Data East", "Data East", "WW", "Tumblepop — популярная игра для Nintendo Game Boy."),
                ("Turok: Battle of the Bionosaurs", "Экшен", 1997, "Acclaim", "Acclaim", "WW", "Turok: Battle of the Bionosaurs — популярная игра для Nintendo Game Boy."),
                ("Urban Strike", "Экшен / Вертолет", 1996, "THQ", "THQ", "WW", "Urban Strike — популярная игра для Nintendo Game Boy."),
                ("Wario Blast: Featuring Bomberman!", "Аркада", 1994, "Nintendo", "Nintendo", "WW", "Wario Blast: Featuring Bomberman! — популярная игра для Nintendo Game Boy."),
                ("Wave Race", "Водные гонки", 1992, "Nintendo", "Nintendo", "WW", "Wave Race — популярная игра для Nintendo Game Boy."),
                ("Who Framed Roger Rabbit", "Приключения", 1991, "Capcom", "Capcom", "WW", "Who Framed Roger Rabbit — популярная игра для Nintendo Game Boy."),
                ("Wizards & Warriors X: Fortress of Fear", "Платформер", 1990, "Acclaim", "Acclaim", "WW", "Wizards & Warriors X: Fortress of Fear — популярная игра для Nintendo Game Boy."),
                ("World Heroes 2 Jet", "Файтинг", 1995, "Takara", "Takara", "WW", "World Heroes 2 Jet — популярная игра для Nintendo Game Boy."),
                ("Worms", "Пошаговая стратегия", 1996, "Ocean", "Ocean", "WW", "Worms — популярная игра для Nintendo Game Boy."),
                ("WWF Raw", "Рестлинг", 1994, "LJN", "LJN", "WW", "WWF Raw — популярная игра для Nintendo Game Boy."),
                ("WWF Superstars", "Рестлинг", 1991, "LJN", "LJN", "WW", "WWF Superstars — популярная игра для Nintendo Game Boy."),
                ("WWF War Zone", "Рестлинг", 1998, "Acclaim", "Acclaim", "WW", "WWF War Zone — популярная игра для Nintendo Game Boy."),
                ("Xenon 2: Megablast", "SHMUP", 1992, "Mindscape", "Mindscape", "WW", "Xenon 2: Megablast — популярная игра для Nintendo Game Boy."),
                ("Yoshi", "Головоломка", 1991, "Nintendo", "Nintendo", "WW", "Yoshi — популярная игра для Nintendo Game Boy."),
                ("Zen: Intergalactic Ninja", "Экшен", 1993, "Konami", "Konami", "WW", "Zen: Intergalactic Ninja — популярная игра для Nintendo Game Boy."),
                ("Zool: Ninja of the Nth Dimension", "Платформер", 1993, "Gremlin", "Gremlin", "WW", "Zool: Ninja of the Nth Dimension — популярная игра для Nintendo Game Boy."),
            };

            foreach (var g in games)
            {
                list.Add(new NintendoCatalogItem
                {
                    Title = g.Title,
                    Genre = g.Genre,
                    Year = g.Year,
                    Developer = g.Dev,
                    Publisher = g.Pub,
                    Region = g.Region,
                    Desc = g.Desc
                });
            }

            return list;
        }
    }
}
