using System;
using System.Collections.Generic;

namespace StormSwitchBox.Services
{
    public static class GbaCatalogData
    {
        public static List<NintendoCatalogItem> GetCatalog()
        {
            var list = new List<NintendoCatalogItem>(202);

            var games = new (string Title, string Genre, int Year, string Dev, string Pub, string Region, string Desc)[]
            {
                ("Pokemon Emerald Version", "JRPG", 2004, "Game Freak", "Nintendo", "WW", "Ультимативная версия с Рэйквазой, укрощением двух легенд и непревзойденной боевой зоной Battle Frontier."),
                ("Pokemon FireRed Version", "JRPG", 2004, "Game Freak", "Nintendo", "WW", "Ремейк оригинального Канто с островами Sevii Islands, беспроводным адаптером Wireless Adapter и современной графикой."),
                ("Pokemon LeafGreen Version", "JRPG", 2004, "Game Freak", "Nintendo", "WW", "Ремейк классики с Венузавром и исследованием островов архипелага Севии."),
                ("Pokemon Ruby Version", "JRPG", 2002, "Game Freak", "Nintendo", "WW", "Третье поколение в регионе Хоэнн: Граудон, командные битвы 2х2 и базы Secret Bases."),
                ("Pokemon Sapphire Version", "JRPG", 2002, "Game Freak", "Nintendo", "WW", "Владыка океана Кайогр, команда Аква и погружения под воду с механикой Dive."),
                ("The Legend of Zelda: The Minish Cap", "Action-Adventure", 2004, "Capcom (Flagship)", "Nintendo", "WW", "Линк и говорящая птичья шапка Эзло уменьшаются до размера песчинки в мире крошечных пиклов."),
                ("The Legend of Zelda: A Link to the Past & Four Swords", "Action-Adventure", 2002, "Nintendo / Capcom", "Nintendo", "WW", "Классический шедевр плюс первое кооперативное приключение на 4 Линков."),
                ("Metroid Fusion (Metroid 4)", "Метроидвания", 2002, "Nintendo R&D1", "Nintendo", "WW", "Самус Аран в органическом костюме Fusion Suit спасается от смертоносного клона SA-X."),
                ("Metroid: Zero Mission", "Метроидвания", 2004, "Nintendo R&D1", "Nintendo", "WW", "Эталонный ремейк первой Metroid с новой стелс-главой за Самус в костюме Zero Suit."),
                ("Castlevania: Aria of Sorrow", "Метроидвания", 2003, "Konami (KCET)", "Konami", "WW", "Сома Крус в замке Дракулы внутри солнечного затмения 2035 года с поглощением душ врагов Tactical Soul."),
                ("Castlevania: Circle of the Moon", "Метроидвания", 2001, "Konami (KCEK)", "Konami", "WW", "Натан Грейвз с кнутом Hunter Whip и карточной комбинационной системой магии DSS."),
                ("Castlevania: Harmony of Dissonance", "Метроидвания", 2002, "Konami (KCET)", "Konami", "WW", "Жюст Бельмонт с магическими книгами заклинаний исследует раздвоенный замок Дракулы."),
                ("Golden Sun", "JRPG", 2001, "Camelot", "Nintendo", "WW", "Исаак и адепты стихий спасают мир Вейярд от алхимии с магией Псинергии и духами Джиннами."),
                ("Golden Sun: The Lost Age", "JRPG", 2002, "Camelot", "Nintendo", "WW", "Продолжение саги от лица Феликса с кораблем, новыми классами магии и переносом всех данных."),
                ("Advance Wars", "Пошаговая тактика", 2001, "Intelligent Systems", "Nintendo", "WW", "Командующие Энди, Сэми и Макс ведут танки, вертолеты и артиллерию на поле боя с силами CO Powers."),
                ("Advance Wars 2: Black Hole Rising", "Пошаговая тактика", 2003, "Intelligent Systems", "Nintendo", "WW", "Оборона 4 континентов от армии Черной Дыры Штурма с суперсилами Super CO Powers."),
                ("Fire Emblem: The Blazing Blade", "Тактическая RPG", 2003, "Intelligent Systems", "Nintendo", "WW", "Первый западный релиз серии: Лин, Эливуд и Гектор на континенте Элиб."),
                ("Fire Emblem: The Sacred Stones", "Тактическая RPG", 2004, "Intelligent Systems", "Nintendo", "WW", "Принц Эфраим и принцесса Эрика против армий нежити с разветвленной прокачкой классов."),
                ("Mario & Luigi: Superstar Saga", "JRPG / Комедия", 2003, "AlphaDream", "Nintendo", "WW", "Марио и Луиджи отправляются в Бобовое королевство возвращать украденный голос принцессы Пич."),
                ("Super Mario Advance 4: Super Mario Bros. 3", "Платформер", 2003, "Nintendo EAD", "Nintendo", "WW", "Идеальная версия SMB3 с голосом Марио и 38 бонусными уровнями e-Reader."),
                ("Mother 3", "JRPG", 2006, "Brownie Brown / HAL", "Nintendo", "JPN", "Шедевр Сигэсато Итои о Лукасе, Клаусе и собаке Бонго с ритмичной боевой системой."),
                ("Final Fantasy Tactics Advance", "Тактическая RPG", 2003, "Square Enix", "Square Enix", "WW", "Марш попадает в сказочную страну Ивалис с правилами судьи Судейской системы."),
                ("Kingdom Hearts: Chain of Memories", "Action-RPG", 2004, "Square Enix", "Square Enix", "WW", "Сора и Дональд в Замке Забвения с карточной колодой атак Организации XIII."),
                ("WarioWare, Inc.: Mega Microgame$!", "Сборник микро-игр", 2003, "Nintendo R&D1", "Nintendo", "WW", "Сотни безумных 5-секундных мини-игр от компании Варио."),
                ("WarioWare: Twisted!", "Микро-игры с гироскопом", 2004, "Nintendo SPD", "Nintendo", "WW", "Картридж со встроенным физическим гироскопом и тактильной отдачей."),
                ("Alien Hominid", "Run and Gun", 2006, "Zoo", "Zoo", "WW", "Alien Hominid — популярная игра для Nintendo Game Boy Advance."),
                ("Astro Boy: Omega Factor", "Beat 'em up / SHMUP от Treasure", 2003, "Sega", "Sega", "WW", "Astro Boy: Omega Factor — популярная игра для Nintendo Game Boy Advance."),
                ("Banjo-Kazooie: Grunty's Revenge", "Изометрический 3D платформер медведя Банджо", 2003, "THQ", "THQ", "WW", "Banjo-Kazooie: Grunty's Revenge — популярная игра для Nintendo Game Boy Advance."),
                ("Banjo-Pilot", "Гонки на самолетах Rare", 2005, "THQ", "THQ", "WW", "Banjo-Pilot — популярная игра для Nintendo Game Boy Advance."),
                ("Boktai: The Sun Is in Your Hand", "Стелс-экшен с датчиком солнечного света Хидео Кодзимы", 2003, "Konami", "Konami", "WW", "Boktai: The Sun Is in Your Hand — популярная игра для Nintendo Game Boy Advance."),
                ("Boktai 2: Solar Boy Django", "Action-RPG с солнечным датчиком и вампирами", 2004, "Konami", "Konami", "WW", "Boktai 2: Solar Boy Django — популярная игра для Nintendo Game Boy Advance."),
                ("Boktai 3: Sabata's Counterattack", "Третья часть саги Джанго и Сабаты", 2005, "Konami", "Konami", "WW", "Boktai 3: Sabata's Counterattack — популярная игра для Nintendo Game Boy Advance."),
                ("Breath of Fire", "JRPG", 2001, "Capcom", "Capcom", "WW", "Breath of Fire — популярная игра для Nintendo Game Boy Advance."),
                ("Breath of Fire II", "JRPG", 2001, "Capcom", "Capcom", "WW", "Breath of Fire II — популярная игра для Nintendo Game Boy Advance."),
                ("Crash Bandicoot: The Huge Adventure", "Платформер Крэша Бандикута", 2002, "Universal", "Universal", "WW", "Crash Bandicoot: The Huge Adventure — популярная игра для Nintendo Game Boy Advance."),
                ("Crash Bandicoot 2: N-Tranced", "Вторая часть Крэша Бандикута", 2003, "Universal", "Universal", "WW", "Crash Bandicoot 2: N-Tranced — популярная игра для Nintendo Game Boy Advance."),
                ("Crash Nitro Kart", "Картинговые гонки Крэша", 2003, "Vivendi", "Vivendi", "WW", "Crash Nitro Kart — популярная игра для Nintendo Game Boy Advance."),
                ("Donkey Kong Country", "Платформер", 2003, "Nintendo", "Nintendo", "WW", "Donkey Kong Country — популярная игра для Nintendo Game Boy Advance."),
                ("Donkey Kong Country 2", "Платформер", 2004, "Nintendo", "Nintendo", "WW", "Donkey Kong Country 2 — популярная игра для Nintendo Game Boy Advance."),
                ("Donkey Kong Country 3", "Платформер", 2005, "Nintendo", "Nintendo", "WW", "Donkey Kong Country 3 — популярная игра для Nintendo Game Boy Advance."),
                ("Donkey Kong: King of Swing", "Платформер-лазание на плечах с триггерами L/R", 2005, "Nintendo", "Nintendo", "WW", "Donkey Kong: King of Swing — популярная игра для Nintendo Game Boy Advance."),
                ("Doom", "3D FPS Думгая", 2001, "Activision", "Activision", "WW", "Doom — популярная игра для Nintendo Game Boy Advance."),
                ("Doom II", "3D FPS Думгая 2", 2002, "Activision", "Activision", "WW", "Doom II — популярная игра для Nintendo Game Boy Advance."),
                ("Dragon Ball: Advanced Adventure", "Beat 'em up юного Гоку с шестом Нёибо", 2004, "Banpresto", "Banpresto", "WW", "Dragon Ball: Advanced Adventure — популярная игра для Nintendo Game Boy Advance."),
                ("Dragon Ball Z: The Legacy of Goku", "Action-RPG Гоку", 2002, "Infogrames", "Infogrames", "WW", "Dragon Ball Z: The Legacy of Goku — популярная игра для Nintendo Game Boy Advance."),
                ("Dragon Ball Z: The Legacy of Goku II", "Action-RPG Гоку, Гохана, Веджеты, Пикколо и Транкса", 2003, "Atari", "Atari", "WW", "Dragon Ball Z: The Legacy of Goku II — популярная игра для Nintendo Game Boy Advance."),
                ("Dragon Ball Z: Buu's Fury", "Финальная Action-RPG саги Маджина Буу", 2004, "Atari", "Atari", "WW", "Dragon Ball Z: Buu's Fury — популярная игра для Nintendo Game Boy Advance."),
                ("Drill Dozer", "Платформер девочки Джилл на роботе-буре с картриджем-вибро от Game Freak", 2005, "Nintendo", "Nintendo", "WW", "Drill Dozer — популярная игра для Nintendo Game Boy Advance."),
                ("Duke Nukem Advance", "3D FPS Дюка Нюкема", 2002, "Take-Two", "Take-Two", "WW", "Duke Nukem Advance — популярная игра для Nintendo Game Boy Advance."),
                ("Dynasty Warriors Advance", "Слэшер трех королевств", 2005, "Koei", "Koei", "WW", "Dynasty Warriors Advance — популярная игра для Nintendo Game Boy Advance."),
                ("Earthworm Jim", "Платформер", 2001, "Interplay", "Interplay", "WW", "Earthworm Jim — популярная игра для Nintendo Game Boy Advance."),
                ("F-Zero: Maximum Velocity", "Сверхзвуковые гонки F-Zero", 2001, "Nintendo", "Nintendo", "WW", "F-Zero: Maximum Velocity — популярная игра для Nintendo Game Boy Advance."),
                ("F-Zero: GP Legend", "Сюжетные гонки Рика Уиллера", 2003, "Nintendo", "Nintendo", "WW", "F-Zero: GP Legend — популярная игра для Nintendo Game Boy Advance."),
                ("F-Zero: Climax", "Финальная часть саги с редактором трасс", 2004, "Nintendo", "Nintendo", "WW", "F-Zero: Climax — популярная игра для Nintendo Game Boy Advance."),
                ("Final Fantasy I & II: Dawn of Souls", "Сборник ремейков FF1 и FF2 с новыми подземельями", 2004, "Square Enix", "Square Enix", "WW", "Final Fantasy I & II: Dawn of Souls — популярная игра для Nintendo Game Boy Advance."),
                ("Final Fantasy IV Advance", "Портативный ремейк FF4 с бонусным подземельем Lunar Ruins", 2005, "Square Enix", "Square Enix", "WW", "Final Fantasy IV Advance — популярная игра для Nintendo Game Boy Advance."),
                ("Final Fantasy V Advance", "Портативный ремейк FF5 с 4 новыми профессиями (Некромант, Гладиатор, Канонир, Оракул)", 2006, "Square Enix", "Square Enix", "WW", "Final Fantasy V Advance — популярная игра для Nintendo Game Boy Advance."),
                ("Final Fantasy VI Advance", "Ультимативный ремейк FF6 с новыми эсперами и логовом драконов", 2006, "Square Enix", "Square Enix", "WW", "Final Fantasy VI Advance — популярная игра для Nintendo Game Boy Advance."),
                ("Fire Pro Wrestling", "Рестлинг", 2001, "BAM!", "BAM!", "WW", "Fire Pro Wrestling — популярная игра для Nintendo Game Boy Advance."),
                ("Frogger's Adventures: Temple of the Frog", "Приключения лягушонка Фроггера", 2001, "Konami", "Konami", "WW", "Frogger's Adventures: Temple of the Frog — популярная игра для Nintendo Game Boy Advance."),
                ("Grand Theft Auto Advance", "GTA в Либерти-Сити с видом сверху", 2004, "Rockstar Games", "Rockstar Games", "WW", "Grand Theft Auto Advance — популярная игра для Nintendo Game Boy Advance."),
                ("Gunstar Super Heroes", "Шедевр Run and Gun от Treasure", 2005, "Sega", "Sega", "WW", "Gunstar Super Heroes — популярная игра для Nintendo Game Boy Advance."),
                ("Harvest Moon: Friends of Mineral Town", "Величайший портативный симулятор фермы", 2003, "Natsume", "Natsume", "WW", "Harvest Moon: Friends of Mineral Town — популярная игра для Nintendo Game Boy Advance."),
                ("Harvest Moon: More Friends of Mineral Town", "Версия фермы с девушкой-протагонистом Клэр", 2003, "Natsume", "Natsume", "WW", "Harvest Moon: More Friends of Mineral Town — популярная игра для Nintendo Game Boy Advance."),
                ("Iridion 3D", "Космический 3D-шутер", 2001, "Majesco", "Majesco", "WW", "Iridion 3D — популярная игра для Nintendo Game Boy Advance."),
                ("Iridion II", "Вертикальный космический SHMUP", 2003, "Majesco", "Majesco", "WW", "Iridion II — популярная игра для Nintendo Game Boy Advance."),
                ("Klonoa: Empire of Dreams", "Головоломка-платформер Клоноа с кольцом ветра", 2001, "Namco", "Namco", "WW", "Klonoa: Empire of Dreams — популярная игра для Nintendo Game Boy Advance."),
                ("Klonoa 2: Dream Champ Tournament", "Вторая часть турнира Клоноа", 2002, "Namco", "Namco", "WW", "Klonoa 2: Dream Champ Tournament — популярная игра для Nintendo Game Boy Advance."),
                ("Konami Krazy Racers", "Картинговые гонки персонажей Konami (Грей Фокс, Дракула, Гоэмон, Пародиус)", 2001, "Konami", "Konami", "WW", "Konami Krazy Racers — популярная игра для Nintendo Game Boy Advance."),
                ("Kurukuru Kururin", "Вращающаяся вертушка-стик через узкие лабиринты", 2001, "Nintendo", "Nintendo", "WW", "Kurukuru Kururin — популярная игра для Nintendo Game Boy Advance."),
                ("Kururin Paradise", "Вторая часть головоломки Курурина", 2002, "Nintendo", "Nintendo", "WW", "Kururin Paradise — популярная игра для Nintendo Game Boy Advance."),
                ("Lego Star Wars: The Video Game", "Лего Звездные Войны: Эпизоды I-III", 2005, "Eidos", "Eidos", "WW", "Lego Star Wars: The Video Game — популярная игра для Nintendo Game Boy Advance."),
                ("Lego Star Wars II: The Original Trilogy", "Лего Звездные Войны: Эпизоды IV-VI", 2006, "LucasArts", "LucasArts", "WW", "Lego Star Wars II: The Original Trilogy — популярная игра для Nintendo Game Boy Advance."),
                ("Lufia: The Ruins of Lore", "JRPG с лодочником Элдоном и древними руинами", 2002, "Atlus", "Atlus", "WW", "Lufia: The Ruins of Lore — популярная игра для Nintendo Game Boy Advance."),
                ("Mario Golf: Advance Tour", "Спортивная RPG в гольф-клубе от Camelot", 2004, "Nintendo", "Nintendo", "WW", "Mario Golf: Advance Tour — популярная игра для Nintendo Game Boy Advance."),
                ("Mario Kart: Super Circuit", "Картинг с 40 трассами Super Mario Kart и новыми чемпионатами", 2001, "Nintendo", "Nintendo", "WW", "Mario Kart: Super Circuit — популярная игра для Nintendo Game Boy Advance."),
                ("Mario Party Advance", "Настольная игра на карте города Грибного городка", 2005, "Nintendo", "Nintendo", "WW", "Mario Party Advance — популярная игра для Nintendo Game Boy Advance."),
                ("Mario Pinball Land", "Пинбол превратившегося в шар Марио от Fuse Games", 2004, "Nintendo", "Nintendo", "WW", "Mario Pinball Land — популярная игра для Nintendo Game Boy Advance."),
                ("Mario Tennis: Power Tour", "Спортивная теннисная RPG с суперударами от Camelot", 2005, "Nintendo", "Nintendo", "WW", "Mario Tennis: Power Tour — популярная игра для Nintendo Game Boy Advance."),
                ("Mario vs. Donkey Kong", "Головоломка Марио и механических мини-Марио с ключами", 2004, "Nintendo", "Nintendo", "WW", "Mario vs. Donkey Kong — популярная игра для Nintendo Game Boy Advance."),
                ("Max Payne", "Изометрический нуарный шутер Макса Пейна с Bullet Time от Rockstar", 2003, "Rockstar Games", "Rockstar Games", "WW", "Max Payne — популярная игра для Nintendo Game Boy Advance."),
                ("Medabots: Metabee Version", "RPG битв роботов медаботов", 2002, "Natsume", "Natsume", "WW", "Medabots: Metabee Version — популярная игра для Nintendo Game Boy Advance."),
                ("Medabots: Rokusho Version", "RPG медаботов Рокусё", 2002, "Natsume", "Natsume", "WW", "Medabots: Rokusho Version — популярная игра для Nintendo Game Boy Advance."),
                ("Mega Man Battle Network", "Action-RPG на сетке 3х3", 2001, "Capcom", "Capcom", "WW", "Mega Man Battle Network — популярная игра для Nintendo Game Boy Advance."),
                ("Mega Man Battle Network 2", "Вторая часть кибер-приключений", 2001, "Capcom", "Capcom", "WW", "Mega Man Battle Network 2 — популярная игра для Nintendo Game Boy Advance."),
                ("Mega Man Battle Network 3: Blue / White", "Третья часть с битвами за Нави-чипы", 2002, "Capcom", "Capcom", "WW", "Mega Man Battle Network 3: Blue / White — популярная игра для Nintendo Game Boy Advance."),
                ("Mega Man Battle Network 4: Red Sun / Blue Moon", "Турниры душ Soul Unison", 2003, "Capcom", "Capcom", "WW", "Mega Man Battle Network 4: Red Sun / Blue Moon — популярная игра для Nintendo Game Boy Advance."),
                ("Mega Man Battle Network 5: Team ProtoMan / Team Colonel", "Освободительные миссии", 2004, "Capcom", "Capcom", "WW", "Mega Man Battle Network 5: Team ProtoMan / Team Colonel — популярная игра для Nintendo Game Boy Advance."),
                ("Mega Man Battle Network 6: Cybeast Gregar / Cybeast Falzar", "Финальная битва с кибер-зверями", 2005, "Capcom", "Capcom", "WW", "Mega Man Battle Network 6: Cybeast Gregar / Cybeast Falzar — популярная игра для Nintendo Game Boy Advance."),
                ("Mega Man Zero", "Экшен мечника Зеро", 2002, "Capcom", "Capcom", "WW", "Mega Man Zero — популярная игра для Nintendo Game Boy Advance."),
                ("Mega Man Zero 2", "Экшен Зеро с цепным гарпуном Chain Rod", 2003, "Capcom", "Capcom", "WW", "Mega Man Zero 2 — популярная игра для Nintendo Game Boy Advance."),
                ("Mega Man Zero 3", "Зеро против Омеги и доктора Вейла", 2004, "Capcom", "Capcom", "WW", "Mega Man Zero 3 — популярная игра для Nintendo Game Boy Advance."),
                ("Mega Man Zero 4", "Финальная битва Зеро за Рагнарек", 2005, "Capcom", "Capcom", "WW", "Mega Man Zero 4 — популярная игра для Nintendo Game Boy Advance."),
                ("Mega Man & Bass", "Платформер Мегамена и Басса", 2002, "Capcom", "Capcom", "WW", "Mega Man & Bass — популярная игра для Nintendo Game Boy Advance."),
                ("Metal Slug Advance", "Военный Run and Gun Уолтера и Тайры с картами улучшений", 2004, "SNK", "SNK", "WW", "Metal Slug Advance — популярная игра для Nintendo Game Boy Advance."),
                ("Ninja Five-O (Shadow Police)", "Хардкорный ниндзя-полицейский Джо Осуги с тросом-кунаем", 2003, "Konami", "Konami", "WW", "Ninja Five-O (Shadow Police) — популярная игра для Nintendo Game Boy Advance."),
                ("Pac-Man Collection", "Сборник Пакмана", 2001, "Namco", "Namco", "WW", "Pac-Man Collection — популярная игра для Nintendo Game Boy Advance."),
                ("Phantasy Star Collection", "Сборник Phantasy Star I, II, III", 2002, "Sega", "Sega", "WW", "Phantasy Star Collection — популярная игра для Nintendo Game Boy Advance."),
                ("Pokemon Mystery Dungeon: Red Rescue Team", "Рогалик команды спасателей покемонов в подземельях", 2005, "Nintendo", "Nintendo", "WW", "Pokemon Mystery Dungeon: Red Rescue Team — популярная игра для Nintendo Game Boy Advance."),
                ("Pokemon Pinball: Ruby & Sapphire", "Пинбол третьего поколения покемонов", 2003, "Nintendo", "Nintendo", "WW", "Pokemon Pinball: Ruby & Sapphire — популярная игра для Nintendo Game Boy Advance."),
                ("Polarium Advance", "Логическая головоломка с переворотом плиток черное/белое", 2005, "Nintendo", "Nintendo", "WW", "Polarium Advance — популярная игра для Nintendo Game Boy Advance."),
                ("Rayman 3: Hoodlum Havoc", "Платформер Рэймана", 2003, "Ubisoft", "Ubisoft", "WW", "Rayman 3: Hoodlum Havoc — популярная игра для Nintendo Game Boy Advance."),
                ("Rayman Advance", "Платформер Рэймана", 2001, "Ubisoft", "Ubisoft", "WW", "Rayman Advance — популярная игра для Nintendo Game Boy Advance."),
                ("Rhythm Tengoku", "Культовая ритм-игра", 2006, "Nintendo", "Nintendo", "WW", "Rhythm Tengoku — популярная игра для Nintendo Game Boy Advance."),
                ("Riviera: The Promised Land", "Тактическая JRPG ангела Эйнхарта от Sting", 2004, "Atlus", "Atlus", "WW", "Riviera: The Promised Land — популярная игра для Nintendo Game Boy Advance."),
                ("Shining Force: Resurrection of the Dark Dragon", "Тактическая RPG ремейк классики Genesis", 2004, "Sega", "Sega", "WW", "Shining Force: Resurrection of the Dark Dragon — популярная игра для Nintendo Game Boy Advance."),
                ("Shining Soul", "Hack 'n' Slash Action-RPG", 2002, "Sega", "Sega", "WW", "Shining Soul — популярная игра для Nintendo Game Boy Advance."),
                ("Shining Soul II", "Кооперативный ролевой боевик на 4 игроков", 2003, "Sega", "Sega", "WW", "Shining Soul II — популярная игра для Nintendo Game Boy Advance."),
                ("SimCity 2000", "Градостроительный симулятор", 2003, "Zoo", "Zoo", "WW", "SimCity 2000 — популярная игра для Nintendo Game Boy Advance."),
                ("Sims: Bustin' Out, The", "Ролевая жизнь симов в городе с байками и карьерой", 2003, "Electronic Arts", "Electronic Arts", "WW", "Sims: Bustin' Out, The — популярная игра для Nintendo Game Boy Advance."),
                ("Sims 2, The", "Симулятор жизни симов в Стренджтауне", 2005, "Electronic Arts", "Electronic Arts", "WW", "Sims 2, The — популярная игра для Nintendo Game Boy Advance."),
                ("Sonic Advance", "Скоростной платформер Соника, Тейлза, Наклза и Эми", 2001, "Sega", "Sega", "WW", "Sonic Advance — популярная игра для Nintendo Game Boy Advance."),
                ("Sonic Advance 2", "Сверхзвуковые трюки и появление крольчихи Крим с чао Чизом", 2002, "Sega", "Sega", "WW", "Sonic Advance 2 — популярная игра для Nintendo Game Boy Advance."),
                ("Sonic Advance 3", "Парные связки персонажей с уникальными совместными суперприемами", 2004, "Sega", "Sega", "WW", "Sonic Advance 3 — популярная игра для Nintendo Game Boy Advance."),
                ("Sonic Battle", "3D файтинг на изометрических аренах с роботом Эмерлом", 2003, "Sega", "Sega", "WW", "Sonic Battle — популярная игра для Nintendo Game Boy Advance."),
                ("Sonic Pinball Party", "Пинбол Соника, Nights и Samba de Amigo", 2003, "Sega", "Sega", "WW", "Sonic Pinball Party — популярная игра для Nintendo Game Boy Advance."),
                ("Spider-Man: Mysterio's Menace", "Экшен Человека-Паука от Vicarious Visions", 2001, "Activision", "Activision", "WW", "Spider-Man: Mysterio's Menace — популярная игра для Nintendo Game Boy Advance."),
                ("Spyro: Season of Ice", "Изометрический платформер дракончика Спайро", 2001, "Universal", "Universal", "WW", "Spyro: Season of Ice — популярная игра для Nintendo Game Boy Advance."),
                ("Spyro 2: Season of Flame", "Вторая часть Спайро с огненным дыханием", 2002, "Universal", "Universal", "WW", "Spyro 2: Season of Flame — популярная игра для Nintendo Game Boy Advance."),
                ("Spyro: Attack of the Rhynocs", "RPG-приключение Спайро", 2003, "Vivendi", "Vivendi", "WW", "Spyro: Attack of the Rhynocs — популярная игра для Nintendo Game Boy Advance."),
                ("Street Fighter Alpha 3", "Ультимативный файтинг с 31 бойцом и режимом World Tour", 2002, "Capcom", "Capcom", "WW", "Street Fighter Alpha 3 — популярная игра для Nintendo Game Boy Advance."),
                ("Summon Night: Swordcraft Story", "Action-RPG кузнеца с ковкой собственного оружия", 2003, "Atlus", "Atlus", "WW", "Summon Night: Swordcraft Story — популярная игра для Nintendo Game Boy Advance."),
                ("Summon Night: Swordcraft Story 2", "Вторая часть кузнеца с созданием мечей, копий, буров и кастетов", 2004, "Atlus", "Atlus", "WW", "Summon Night: Swordcraft Story 2 — популярная игра для Nintendo Game Boy Advance."),
                ("Super Mario Advance (Super Mario Bros. 2)", "Ремейк SMB2 с улучшенным звуком и голосом", 2001, "Nintendo", "Nintendo", "WW", "Super Mario Advance (Super Mario Bros. 2) — популярная игра для Nintendo Game Boy Advance."),
                ("Super Mario Advance 2: Super Mario World", "Ремейк SMW со сбором перьев и Луиджи с парением", 2001, "Nintendo", "Nintendo", "WW", "Super Mario Advance 2: Super Mario World — популярная игра для Nintendo Game Boy Advance."),
                ("Super Mario Advance 3: Yoshi's Island", "Ремейк Острова Йоши с 6 эксклюзивными уровнями", 2002, "Nintendo", "Nintendo", "WW", "Super Mario Advance 3: Yoshi's Island — популярная игра для Nintendo Game Boy Advance."),
                ("Super Robot Taisen: Original Generation", "Тактическая RPG гигантских боевых мехов", 2002, "Banpresto / Atlus", "Banpresto / Atlus", "WW", "Super Robot Taisen: Original Generation — популярная игра для Nintendo Game Boy Advance."),
                ("Super Robot Taisen: Original Generation 2", "Вторая часть тактики роботов", 2005, "Banpresto / Atlus", "Banpresto / Atlus", "WW", "Super Robot Taisen: Original Generation 2 — популярная игра для Nintendo Game Boy Advance."),
                ("Sword of Mana (Shinyaku Seiken Densetsu)", "Грандиозный ремейк Final Fantasy Adventure от Square", 2003, "Square Enix", "Square Enix", "WW", "Sword of Mana (Shinyaku Seiken Densetsu) — популярная игра для Nintendo Game Boy Advance."),
                ("Tactics Ogre: The Knight of Lodis", "Тактическая RPG Альфонса Беовеля с эмблемами от Quest", 2001, "Atlus", "Atlus", "WW", "Tactics Ogre: The Knight of Lodis — популярная игра для Nintendo Game Boy Advance."),
                ("Tales of Phantasia", "Портативная JRPG Клесса и Минт с линейной боевой системой LMBS", 2003, "Namco", "Namco", "WW", "Tales of Phantasia — популярная игра для Nintendo Game Boy Advance."),
                ("TMNT (Teenage Mutant Ninja Turtles)", "Ураганный Beat 'em up Черепашек-ниндзя от Ubisoft", 2007, "Ubisoft", "Ubisoft", "WW", "TMNT (Teenage Mutant Ninja Turtles) — популярная игра для Nintendo Game Boy Advance."),
                ("Tony Hawk's Pro Skater 2", "Изометрический скейтбординг от Vicarious Visions", 2001, "Activision", "Activision", "WW", "Tony Hawk's Pro Skater 2 — популярная игра для Nintendo Game Boy Advance."),
                ("Tony Hawk's Pro Skater 3", "Скейтбординг Тони Хоука 3", 2002, "Activision", "Activision", "WW", "Tony Hawk's Pro Skater 3 — популярная игра для Nintendo Game Boy Advance."),
                ("Tony Hawk's Pro Skater 4", "Скейтбординг Тони Хоука 4", 2002, "Activision", "Activision", "WW", "Tony Hawk's Pro Skater 4 — популярная игра для Nintendo Game Boy Advance."),
                ("Tony Hawk's Underground", "Сюжетный скейтбординг THUG", 2003, "Activision", "Activision", "WW", "Tony Hawk's Underground — популярная игра для Nintendo Game Boy Advance."),
                ("Tony Hawk's Underground 2", "Скейтбординг THUG 2", 2004, "Activision", "Activision", "WW", "Tony Hawk's Underground 2 — популярная игра для Nintendo Game Boy Advance."),
                ("Top Gear Rally", "Ралли с реалистичной физикой", 2003, "Kemco", "Kemco", "WW", "Top Gear Rally — популярная игра для Nintendo Game Boy Advance."),
                ("Torneko no Daibouken 2 Advance", "Рогалик торговца Торнеко из Dragon Quest", 2001, "Enix", "Enix", "WW", "Torneko no Daibouken 2 Advance — популярная игра для Nintendo Game Boy Advance."),
                ("Torneko no Daibouken 3 Advance", "Третья часть рогалика Торнеко", 2004, "Square Enix", "Square Enix", "WW", "Torneko no Daibouken 3 Advance — популярная игра для Nintendo Game Boy Advance."),
                ("Turok: Evolution", "Экшен Турока", 2002, "Acclaim", "Acclaim", "WW", "Turok: Evolution — популярная игра для Nintendo Game Boy Advance."),
                ("V-Rally 3", "Выдающийся трехмерный раллийный симулятор с полигональной графикой", 2002, "Atari", "Atari", "WW", "V-Rally 3 — популярная игра для Nintendo Game Boy Advance."),
                ("Wario Land 4", "Шедевр платформеров: побег Варио из пирамиды с таймером Frog Switch", 2001, "Nintendo", "Nintendo", "WW", "Wario Land 4 — популярная игра для Nintendo Game Boy Advance."),
                ("WarioWare: Twisted!", "Микро-игры с гироскопом", 2004, "Nintendo", "Nintendo", "WW", "WarioWare: Twisted! — популярная игра для Nintendo Game Boy Advance."),
                ("Wing Commander: Prophecy", "3D космосимулятор с полигональными кораблями", 2003, "Raylight", "Raylight", "WW", "Wing Commander: Prophecy — популярная игра для Nintendo Game Boy Advance."),
                ("Worms World Party", "Червячки с сетевым режимом", 2002, "Ubisoft", "Ubisoft", "WW", "Worms World Party — популярная игра для Nintendo Game Boy Advance."),
                ("Yggdra Union: We'll Never Fight Alone", "Тактическая карточная RPG принцессы Иггдры от Sting", 2006, "Atlus", "Atlus", "WW", "Yggdra Union: We'll Never Fight Alone — популярная игра для Nintendo Game Boy Advance."),
                ("Yoshi Topsy-Turvy (Yoshi's Universal Gravitation)", "Платформер с гравитационным гироскопом", 2004, "Nintendo", "Nintendo", "WW", "Yoshi Topsy-Turvy (Yoshi's Universal Gravitation) — популярная игра для Nintendo Game Boy Advance."),
                ("Yu-Gi-Oh! The Sacred Cards", "RPG дуэлей карт Юги Муто", 2002, "Konami", "Konami", "WW", "Yu-Gi-Oh! The Sacred Cards — популярная игра для Nintendo Game Boy Advance."),
                ("Yu-Gi-Oh! Reshef of Destruction", "Вторая часть RPG Yu-Gi-Oh", 2004, "Konami", "Konami", "WW", "Yu-Gi-Oh! Reshef of Destruction — популярная игра для Nintendo Game Boy Advance."),
                ("Yu-Gi-Oh! Worldwide Edition: Stairway to the Destined Duel", "Турнирные карточные битвы", 2003, "Konami", "Konami", "WW", "Yu-Gi-Oh! Worldwide Edition: Stairway to the Destined Duel — популярная игра для Nintendo Game Boy Advance."),
                ("Zone of the Enders: The Fist of Mars", "Тактическая RPG боевых роботов орбитальных фреймов Лео Стенбака", 2001, "Konami", "Konami", "WW", "Zone of the Enders: The Fist of Mars — популярная игра для Nintendo Game Boy Advance."),
            };

            foreach (var g in games)
            {
                list.Add(new NintendoCatalogItem
                {
                    Title = g.Title,
                    Genre = g.Genre,
                    Year = g.Year,
                    Developer = g.Dev,
                    Publisher = g.Pub,
                    Region = g.Region,
                    Desc = g.Desc
                });
            }

            return list;
        }
    }
}
