using System;
using System.Collections.Generic;

namespace StormSwitchBox.Services
{
    public static class GbcCatalogData
    {
        public static List<NintendoCatalogItem> GetCatalog()
        {
            var list = new List<NintendoCatalogItem>(257);

            var games = new (string Title, string Genre, int Year, string Dev, string Pub, string Region, string Desc)[]
            {
                ("Pokemon Gold Version", "JRPG", 1999, "Game Freak", "Nintendo", "WW", "Второе поколение: 100 новых покемонов, регионы Джото и Канто, 16 значков и битва с Редом на горе Сильвер."),
                ("Pokemon Silver Version", "JRPG", 1999, "Game Freak", "Nintendo", "WW", "Легендарная птица Лугия, часы реального времени со сменой дня и ночи, дни недели и разведение яиц."),
                ("Pokemon Crystal Version", "JRPG", 2000, "Game Freak", "Nintendo", "WW", "Анимированные спрайты покемонов, выбор девушки-протагониста Крис, Суикун и Башня Битв."),
                ("The Legend of Zelda: Oracle of Ages", "Action-Adventure", 2001, "Capcom (Flagship)", "Nintendo", "WW", "Линк спасает оракула Найру в Лабиринии с путешествиями во времени на Арфе Веков."),
                ("The Legend of Zelda: Oracle of Seasons", "Action-Adventure", 2001, "Capcom (Flagship)", "Nintendo", "WW", "Линк спасает оракула Дин в Холодруме с управлением 4 временами года Жезлом Сезонов."),
                ("The Legend of Zelda: Link's Awakening DX", "Action-Adventure", 1998, "Nintendo EAD", "Nintendo", "WW", "Цветная версия шедевра с новым подземельем цвета (Color Dungeon) и фотосалоном."),
                ("Super Mario Bros. Deluxe", "Платформер", 1999, "Nintendo R&D2", "Nintendo", "WW", "Цветной ремейк SMB1 и Lost Levels с картой мира, поиском красных монет и гонками против призрака Boo."),
                ("Wario Land 3", "Метроидвания / Платформер", 2000, "Nintendo R&D1", "Nintendo", "WW", "Бессмертный Варио исследует волшебную музыкальную шкатулку, находя новые движения и сокровища."),
                ("Metal Gear Solid (Ghost Babel)", "Стелс-экшен", 2000, "Konami (KCEJ)", "Konami", "WW", "Один из величайших стелс-боевиков: Солид Снейк проникает в крепость Галинд на миссию в Африке."),
                ("Shantae", "Метроидвания", 2002, "WayForward", "Capcom", "WW", "Дебют полуджинна Шантэ с танцами живота для превращения в обезьяну, слона, паука и гарпию."),
                ("Dragon Quest Monsters", "JRPG / Ловля монстров", 1998, "TOSE", "Enix", "WW", "Терри из DQ6 исследует порталы и скрещивает сотни монстров вселенной Dragon Quest."),
                ("Dragon Quest Monsters 2: Cobi's Journey", "JRPG", 2001, "TOSE", "Enix", "WW", "Путешествия по ключам-мирам и скрещивание более 300 видов монстров."),
                ("Mario Tennis (GBC)", "Спортивная RPG", 2000, "Camelot", "Nintendo", "WW", "Полноценный сюжетный режим в теннисной академии с прокачкой характеристик персонажа."),
                ("Mario Golf (GBC)", "Спортивная RPG", 1999, "Camelot", "Nintendo", "WW", "Ролевой режим гольфиста с турнирами клуба и переносом персонажа на Nintendo 64."),
                ("Pokemon Trading Card Game", "Коллекционная карточная игра", 1998, "Hudson Soft / Creatures", "Nintendo", "WW", "Сбор колод, дуэли с клубными мастерами и Гранд-Мастерами за Легендарные Карты."),
                ("Pokemon Pinball", "Пинбол со встроенным вибро", 1999, "Jupiter", "Nintendo", "WW", "Картридж со встроенным мотором вибрации Rumble и ловлей покемонов на красном и синем столах."),
                ("Rayman", "Платформер", 2000, "Ubi Soft", "Ubi Soft", "WW", "Красочные приключения Рэймана с полетами на волосах-вертолетах."),
                ("Harvest Moon GBC", "Симулятор фермы", 1998, "Victor Interactive", "Natsume", "WW", "Портативная версия восстановления заброшенного дедушкиного ранчо."),
                ("Harvest Moon 2 GBC", "Симулятор фермы", 1999, "Victor Interactive", "Natsume", "WW", "Расширенная ферма с теплицами, садом и новыми животными."),
                ("Harvest Moon 3 GBC", "Симулятор фермы", 2000, "Victor Interactive", "Natsume", "WW", "Ферма на отдаленном острове с выбором парня или девушки и заведением семьи."),
                ("10 Pin Bowling", "Боулинг", 1999, "Majesco", "Majesco", "WW", "10 Pin Bowling — популярная игра для Nintendo Game Boy Color."),
                ("102 Dalmatians: Puppies to the Rescue", "Платформер", 2000, "Disney", "Disney", "WW", "102 Dalmatians: Puppies to the Rescue — популярная игра для Nintendo Game Boy Color."),
                ("Action Man: Search for Base X", "Экшен", 2001, "THQ", "THQ", "WW", "Action Man: Search for Base X — популярная игра для Nintendo Game Boy Color."),
                ("Adventures of the Smurfs", "Платформер", 2000, "Infogrames", "Infogrames", "WW", "Adventures of the Smurfs — популярная игра для Nintendo Game Boy Color."),
                ("Aliens: Thanatos Encounter", "Экшен / Выживание", 2001, "THQ", "THQ", "WW", "Aliens: Thanatos Encounter — популярная игра для Nintendo Game Boy Color."),
                ("All-Star Baseball 2000", "Спорт", 1999, "Acclaim", "Acclaim", "WW", "All-Star Baseball 2000 — популярная игра для Nintendo Game Boy Color."),
                ("All-Star Baseball 2001", "Спорт", 2000, "Acclaim", "Acclaim", "WW", "All-Star Baseball 2001 — популярная игра для Nintendo Game Boy Color."),
                ("Alone in the Dark: The New Nightmare", "Survival Horror", 2001, "Infogrames", "Infogrames", "WW", "Alone in the Dark: The New Nightmare — популярная игра для Nintendo Game Boy Color."),
                ("Animorphs", "Action-RPG", 2000, "Ubisoft", "Ubisoft", "WW", "Animorphs — популярная игра для Nintendo Game Boy Color."),
                ("Armada: FX Racers", "Гонки", 2000, "Metro3D", "Metro3D", "WW", "Armada: FX Racers — популярная игра для Nintendo Game Boy Color."),
                ("Armorines: Project S.W.A.R.M.", "Шутер", 1999, "Acclaim", "Acclaim", "WW", "Armorines: Project S.W.A.R.M. — популярная игра для Nintendo Game Boy Color."),
                ("Army Men", "Тактический экшен", 1999, "3DO", "3DO", "WW", "Army Men — популярная игра для Nintendo Game Boy Color."),
                ("Army Men 2", "Тактический экшен", 2000, "3DO", "3DO", "WW", "Army Men 2 — популярная игра для Nintendo Game Boy Color."),
                ("Army Men: Air Combat", "Вертолетный экшен", 2000, "3DO", "3DO", "WW", "Army Men: Air Combat — популярная игра для Nintendo Game Boy Color."),
                ("Army Men: Sarge's Heroes 2", "Экшен", 2000, "3DO", "3DO", "WW", "Army Men: Sarge's Heroes 2 — популярная игра для Nintendo Game Boy Color."),
                ("Arthur's Absolutely Fun Day!", "Обучающие мини-игры", 2000, "Mattel", "Mattel", "WW", "Arthur's Absolutely Fun Day! — популярная игра для Nintendo Game Boy Color."),
                ("Asterix: Search for Dogmatix", "Платформер", 2000, "Infogrames", "Infogrames", "WW", "Asterix: Search for Dogmatix — популярная игра для Nintendo Game Boy Color."),
                ("Austin Powers: Welcome to My Underground Lair!", "Мини-игры Остина Пауэрса", 2000, "Rockstar Games", "Rockstar Games", "WW", "Austin Powers: Welcome to My Underground Lair! — популярная игра для Nintendo Game Boy Color."),
                ("Austin Powers: Oh, Behave!", "Мини-игры Остина Пауэрса", 2000, "Rockstar Games", "Rockstar Games", "WW", "Austin Powers: Oh, Behave! — популярная игра для Nintendo Game Boy Color."),
                ("Babe and Friends", "Приключения поросенка Бэйба", 1999, "Crave", "Crave", "WW", "Babe and Friends — популярная игра для Nintendo Game Boy Color."),
                ("Barbie: Fashion Pack Games", "Мода и стиль", 2000, "Mattel", "Mattel", "WW", "Barbie: Fashion Pack Games — популярная игра для Nintendo Game Boy Color."),
                ("Barbie: Magic Genie Adventure", "Приключения Барби", 2000, "Mattel", "Mattel", "WW", "Barbie: Magic Genie Adventure — популярная игра для Nintendo Game Boy Color."),
                ("Barbie: Ocean Discovery", "Подводные исследования", 1999, "Mattel", "Mattel", "WW", "Barbie: Ocean Discovery — популярная игра для Nintendo Game Boy Color."),
                ("Barbie: Pet Rescue", "Спасение животных", 2001, "Mattel", "Mattel", "WW", "Barbie: Pet Rescue — популярная игра для Nintendo Game Boy Color."),
                ("Bass Masters Classic", "Рыбалка", 1999, "THQ", "THQ", "WW", "Bass Masters Classic — популярная игра для Nintendo Game Boy Color."),
                ("Batman Beyond: Return of the Joker", "Beat 'em up", 2000, "Ubisoft", "Ubisoft", "WW", "Batman Beyond: Return of the Joker — популярная игра для Nintendo Game Boy Color."),
                ("Batman: Chaos in Gotham", "Экшен-платформер", 2001, "Ubisoft", "Ubisoft", "WW", "Batman: Chaos in Gotham — популярная игра для Nintendo Game Boy Color."),
                ("BattleTanx", "3D Танковые сражения", 2000, "3DO", "3DO", "WW", "BattleTanx — популярная игра для Nintendo Game Boy Color."),
                ("Bear in the Big Blue House", "Обучающие игры", 2001, "Ubisoft", "Ubisoft", "WW", "Bear in the Big Blue House — популярная игра для Nintendo Game Boy Color."),
                ("Bionic Commando: Elite Forces", "Экшен-платформер", 2000, "Nintendo", "Nintendo", "WW", "Bionic Commando: Elite Forces — популярная игра для Nintendo Game Boy Color."),
                ("Blade", "Экшен охотника на вампиров Блэйда", 2000, "Activision", "Activision", "WW", "Blade — популярная игра для Nintendo Game Boy Color."),
                ("Blaster Master: Enemy Below", "Экшен / Метроидвания", 2000, "Sunsoft", "Sunsoft", "WW", "Blaster Master: Enemy Below — популярная игра для Nintendo Game Boy Color."),
                ("Boarder Zone (Supreme Snowboarding)", "Сноубординг", 2000, "Infogrames", "Infogrames", "WW", "Boarder Zone (Supreme Snowboarding) — популярная игра для Nintendo Game Boy Color."),
                ("Bob the Builder: Fix It Fun!", "Строительные мини-игры", 2001, "THQ", "THQ", "WW", "Bob the Builder: Fix It Fun! — популярная игра для Nintendo Game Boy Color."),
                ("Bomberman Max: Blue Champion", "Аркада", 2000, "Hudson Soft", "Hudson Soft", "WW", "Bomberman Max: Blue Champion — популярная игра для Nintendo Game Boy Color."),
                ("Bomberman Max: Red Challenger", "Аркада", 2000, "Hudson Soft", "Hudson Soft", "WW", "Bomberman Max: Red Challenger — популярная игра для Nintendo Game Boy Color."),
                ("Brave Fencer Musashi", "Action-RPG", 1998, "Square", "Square", "WW", "Brave Fencer Musashi — популярная игра для Nintendo Game Boy Color."),
                ("Buffy the Vampire Slayer", "Экшен Баффи", 2000, "THQ", "THQ", "WW", "Buffy the Vampire Slayer — популярная игра для Nintendo Game Boy Color."),
                ("Bugs Bunny in Crazy Castle 3", "Головоломка", 1999, "Kemco", "Kemco", "WW", "Bugs Bunny in Crazy Castle 3 — популярная игра для Nintendo Game Boy Color."),
                ("Bugs Bunny in Crazy Castle 4", "Головоломка", 2000, "Kemco", "Kemco", "WW", "Bugs Bunny in Crazy Castle 4 — популярная игра для Nintendo Game Boy Color."),
                ("Caterpillar Construction Zone", "Симулятор стройки", 1999, "Mattel", "Mattel", "WW", "Caterpillar Construction Zone — популярная игра для Nintendo Game Boy Color."),
                ("Croc", "Платформер крокодильчика Крока", 2000, "Fox Interactive", "Fox Interactive", "WW", "Croc — популярная игра для Nintendo Game Boy Color."),
                ("Croc 2", "Вторая часть приключений Крока", 2001, "Fox Interactive", "Fox Interactive", "WW", "Croc 2 — популярная игра для Nintendo Game Boy Color."),
                ("Cruis'n Exotica", "Аркадные гонки", 2000, "Midway", "Midway", "WW", "Cruis'n Exotica — популярная игра для Nintendo Game Boy Color."),
                ("Crystalis", "Action-RPG", 2000, "Nintendo", "Nintendo", "WW", "Crystalis — популярная игра для Nintendo Game Boy Color."),
                ("Dave Mirra Freestyle BMX", "Экстремальный BMX", 2000, "Acclaim", "Acclaim", "WW", "Dave Mirra Freestyle BMX — популярная игра для Nintendo Game Boy Color."),
                ("Deja Vu I & II", "Нуарный детективный квест", 1999, "Kemco", "Kemco", "WW", "Deja Vu I & II — популярная игра для Nintendo Game Boy Color."),
                ("Denki Blocks!", "Логическая головоломка с блоками", 2001, "Rage", "Rage", "WW", "Denki Blocks! — популярная игра для Nintendo Game Boy Color."),
                ("Disney's Aladdin", "Платформер Аладдина", 2000, "Ubisoft", "Ubisoft", "WW", "Disney's Aladdin — популярная игра для Nintendo Game Boy Color."),
                ("Disney's Atlantis: The Lost Empire", "Приключения в Атлантиде", 2001, "THQ", "THQ", "WW", "Disney's Atlantis: The Lost Empire — популярная игра для Nintendo Game Boy Color."),
                ("Disney's Dinosaur", "Приключения динозавра Аладара", 2000, "Ubisoft", "Ubisoft", "WW", "Disney's Dinosaur — популярная игра для Nintendo Game Boy Color."),
                ("Disney's Donald Duck: Goin' Quackers", "Платформер Дональда Дака", 2001, "Ubisoft", "Ubisoft", "WW", "Disney's Donald Duck: Goin' Quackers — популярная игра для Nintendo Game Boy Color."),
                ("Disney's Hercules", "Подвиги Геракла", 2001, "THQ", "THQ", "WW", "Disney's Hercules — популярная игра для Nintendo Game Boy Color."),
                ("Disney's Mulan", "Приключения Мулан", 1999, "THQ", "THQ", "WW", "Disney's Mulan — популярная игра для Nintendo Game Boy Color."),
                ("Disney's Tarzan", "Приключения Тарзана", 1999, "Activision", "Activision", "WW", "Disney's Tarzan — популярная игра для Nintendo Game Boy Color."),
                ("Disney's The Emperor's New Groove", "Похождения императора Куско", 2001, "Ubisoft", "Ubisoft", "WW", "Disney's The Emperor's New Groove — популярная игра для Nintendo Game Boy Color."),
                ("Disney's The Jungle Book: Mowgli's Wild Adventure", "Маугли", 2000, "Ubisoft", "Ubisoft", "WW", "Disney's The Jungle Book: Mowgli's Wild Adventure — популярная игра для Nintendo Game Boy Color."),
                ("Disney's The Little Mermaid II: Pinball Frenzy", "Пинбол", 2000, "Disney", "Disney", "WW", "Disney's The Little Mermaid II: Pinball Frenzy — популярная игра для Nintendo Game Boy Color."),
                ("Disney's Winnie the Pooh: Adventures in the 100 Acre Wood", "Винни Пух", 2000, "Disney", "Disney", "WW", "Disney's Winnie the Pooh: Adventures in the 100 Acre Wood — популярная игра для Nintendo Game Boy Color."),
                ("Dragon Ball Z: Legendary Super Warriors", "Пошаговая карточная RPG", 2002, "Banpresto / Infogrames", "Banpresto / Infogrames", "WW", "Dragon Ball Z: Legendary Super Warriors — популярная игра для Nintendo Game Boy Color."),
                ("Dragon's Lair", "Интерактивный мультфильм Дирка", 2000, "Capcom", "Capcom", "WW", "Dragon's Lair — популярная игра для Nintendo Game Boy Color."),
                ("Driver", "Гонки под прикрытием в Майами, Нью-Йорке и Сан-Франциско", 2000, "Infogrames", "Infogrames", "WW", "Driver — популярная игра для Nintendo Game Boy Color."),
                ("Duke Nukem", "Платформер Дюка Нюкема с пушками и шутками", 1999, "GT Interactive", "GT Interactive", "WW", "Duke Nukem — популярная игра для Nintendo Game Boy Color."),
                ("Earthworm Jim: Menace 2 the Galaxy", "Червяк Джим", 1999, "Crave", "Crave", "WW", "Earthworm Jim: Menace 2 the Galaxy — популярная игра для Nintendo Game Boy Color."),
                ("ECW Hardcore Revolution", "Хардкорный рестлинг", 2000, "Acclaim", "Acclaim", "WW", "ECW Hardcore Revolution — популярная игра для Nintendo Game Boy Color."),
                ("Extreme Sports with the Berenstain Bears", "Спорт", 2000, "Sound Source", "Sound Source", "WW", "Extreme Sports with the Berenstain Bears — популярная игра для Nintendo Game Boy Color."),
                ("F-1 World Grand Prix", "Формула-1", 1999, "Video System", "Video System", "WW", "F-1 World Grand Prix — популярная игра для Nintendo Game Boy Color."),
                ("F1 Championship Season 2000", "Формула-1 2000", 2000, "Electronic Arts", "Electronic Arts", "WW", "F1 Championship Season 2000 — популярная игра для Nintendo Game Boy Color."),
                ("FIFA 2000", "Футбол FIFA", 1999, "Electronic Arts", "Electronic Arts", "WW", "FIFA 2000 — популярная игра для Nintendo Game Boy Color."),
                ("Frogger 2", "Аркада", 2000, "Hasbro", "Hasbro", "WW", "Frogger 2 — популярная игра для Nintendo Game Boy Color."),
                ("Galaga: Destination Earth", "Космошутер", 2000, "Hasbro", "Hasbro", "WW", "Galaga: Destination Earth — популярная игра для Nintendo Game Boy Color."),
                ("Game & Watch Gallery 3", "Сборник G&W", 1999, "Nintendo", "Nintendo", "WW", "Game & Watch Gallery 3 — популярная игра для Nintendo Game Boy Color."),
                ("Ghosts 'n Goblins", "Платформер Артура", 2000, "Capcom", "Capcom", "WW", "Ghosts 'n Goblins — популярная игра для Nintendo Game Boy Color."),
                ("Gobs of Games", "Сборник 10 настольных игр", 2000, "3DO", "3DO", "WW", "Gobs of Games — популярная игра для Nintendo Game Boy Color."),
                ("Grand Theft Auto", "Оригинальная GTA с видом сверху и радиостанциями", 1999, "Rockstar Games", "Rockstar Games", "WW", "Grand Theft Auto — популярная игра для Nintendo Game Boy Color."),
                ("Grand Theft Auto 2", "GTA 2 в мегаполисе будущего с бандами Дзайбацу", 2000, "Rockstar Games", "Rockstar Games", "WW", "Grand Theft Auto 2 — популярная игра для Nintendo Game Boy Color."),
                ("Hands of Time", "Action-Adventure", 2001, "Titus", "Titus", "WW", "Hands of Time — популярная игра для Nintendo Game Boy Color."),
                ("Harry Potter and the Chamber of Secrets", "Пошаговая RPG Гарри Поттера в Хогвартсе", 2002, "Electronic Arts", "Electronic Arts", "WW", "Harry Potter and the Chamber of Secrets — популярная игра для Nintendo Game Boy Color."),
                ("Harry Potter and the Sorcerer's Stone", "Пошаговая RPG Гарри Поттера", 2001, "Electronic Arts", "Electronic Arts", "WW", "Harry Potter and the Sorcerer's Stone — популярная игра для Nintendo Game Boy Color."),
                ("Inspector Gadget: Operation Madkactus", "Инспектор Гаджет", 2000, "Ubisoft", "Ubisoft", "WW", "Inspector Gadget: Operation Madkactus — популярная игра для Nintendo Game Boy Color."),
                ("International Superstar Soccer 99", "Футбол ISS Konami", 1999, "Konami", "Konami", "WW", "International Superstar Soccer 99 — популярная игра для Nintendo Game Boy Color."),
                ("International Superstar Soccer 2000", "Футбол ISS 2000", 2000, "Konami", "Konami", "WW", "International Superstar Soccer 2000 — популярная игра для Nintendo Game Boy Color."),
                ("Klax", "Головоломка", 1999, "Midway", "Midway", "WW", "Klax — популярная игра для Nintendo Game Boy Color."),
                ("Klustar", "Головоломка с падающими блоками", 1999, "Infogrames", "Infogrames", "WW", "Klustar — популярная игра для Nintendo Game Boy Color."),
                ("Lego Alpha Team", "Логическая стратегия", 2000, "Lego Media", "Lego Media", "WW", "Lego Alpha Team — популярная игра для Nintendo Game Boy Color."),
                ("Lego Island 2: The Brickster's Revenge", "Приключения на острове Лего", 2001, "Lego Media", "Lego Media", "WW", "Lego Island 2: The Brickster's Revenge — популярная игра для Nintendo Game Boy Color."),
                ("Lego Racers", "Конструктор и гонки на машинках Лего", 2000, "Lego Media", "Lego Media", "WW", "Lego Racers — популярная игра для Nintendo Game Boy Color."),
                ("Lego Stunt Rally", "Трюковые гонки Лего", 2000, "Lego Media", "Lego Media", "WW", "Lego Stunt Rally — популярная игра для Nintendo Game Boy Color."),
                ("Looney Tunes Collector: Alert!", "RPG сбор мультяшек WB", 2000, "Infogrames", "Infogrames", "WW", "Looney Tunes Collector: Alert! — популярная игра для Nintendo Game Boy Color."),
                ("Lufia: The Legend Returns", "JRPG с 4 персонажами и случайными подземельями", 2001, "Natsume", "Natsume", "WW", "Lufia: The Legend Returns — популярная игра для Nintendo Game Boy Color."),
                ("Magical Tetris Challenge", "Тетрис с персонажами Диснея от Capcom", 1999, "Capcom", "Capcom", "WW", "Magical Tetris Challenge — популярная игра для Nintendo Game Boy Color."),
                ("Mario Tennis", "Спортивная RPG", 2000, "Nintendo", "Nintendo", "WW", "Mario Tennis — популярная игра для Nintendo Game Boy Color."),
                ("Mega Man Xtreme", "Экшен-платформер X и Зеро", 2001, "Capcom", "Capcom", "WW", "Mega Man Xtreme — популярная игра для Nintendo Game Boy Color."),
                ("Mega Man Xtreme 2", "Экшен-платформер с боссами X2/X3", 2001, "Capcom", "Capcom", "WW", "Mega Man Xtreme 2 — популярная игра для Nintendo Game Boy Color."),
                ("Men in Black: The Series", "Люди в Черном", 1999, "Crave", "Crave", "WW", "Men in Black: The Series — популярная игра для Nintendo Game Boy Color."),
                ("Men in Black 2: The Series", "Люди в Черном 2", 2000, "Crave", "Crave", "WW", "Men in Black 2: The Series — популярная игра для Nintendo Game Boy Color."),
                ("Micro Machines V3", "Микро-гонки", 2000, "Midway", "Midway", "WW", "Micro Machines V3 — популярная игра для Nintendo Game Boy Color."),
                ("Micro Maniacs", "Микро-гонки мутантов на ногах", 2000, "Codemasters", "Codemasters", "WW", "Micro Maniacs — популярная игра для Nintendo Game Boy Color."),
                ("Midway's Greatest Arcade Hits Vol. 1", "Ретро-сборник аркад (Sinistar, Joust, Defender)", 2000, "Midway", "Midway", "WW", "Midway's Greatest Arcade Hits Vol. 1 — популярная игра для Nintendo Game Boy Color."),
                ("Midway's Greatest Arcade Hits Vol. 2", "Ретро-сборник (Gauntlet, Paperboy, 720, Spy Hunter)", 2001, "Midway", "Midway", "WW", "Midway's Greatest Arcade Hits Vol. 2 — популярная игра для Nintendo Game Boy Color."),
                ("Mission: Impossible", "Шпионский стелс Итана Ханта", 2000, "Infogrames", "Infogrames", "WW", "Mission: Impossible — популярная игра для Nintendo Game Boy Color."),
                ("Monsters, Inc.", "Корпорация Монстров: Салли и Майк", 2001, "THQ", "THQ", "WW", "Monsters, Inc. — популярная игра для Nintendo Game Boy Color."),
                ("Mortal Kombat 4", "Файтинг МК4", 1999, "Midway", "Midway", "WW", "Mortal Kombat 4 — популярная игра для Nintendo Game Boy Color."),
                ("Motocross Maniacs 2", "Мотогонки с трюками", 2000, "Konami", "Konami", "WW", "Motocross Maniacs 2 — популярная игра для Nintendo Game Boy Color."),
                ("Mr. Driller", "Скоростное бурение блоков Сусуму Хори", 2000, "Namco", "Namco", "WW", "Mr. Driller — популярная игра для Nintendo Game Boy Color."),
                ("Ms. Pac-Man: Special Color Edition", "Мисс Пакман", 1999, "Namco", "Namco", "WW", "Ms. Pac-Man: Special Color Edition — популярная игра для Nintendo Game Boy Color."),
                ("NASCAR 2000", "Гонки NASCAR", 2000, "EA Sports", "EA Sports", "WW", "NASCAR 2000 — популярная игра для Nintendo Game Boy Color."),
                ("NBA Hoopz", "Баскетбол 3х3", 2001, "Midway", "Midway", "WW", "NBA Hoopz — популярная игра для Nintendo Game Boy Color."),
                ("NBA in the Zone", "Баскетбол Konami", 1999, "Konami", "Konami", "WW", "NBA in the Zone — популярная игра для Nintendo Game Boy Color."),
                ("NBA Jam 2001", "Баскетбол Acclaim", 2000, "Acclaim", "Acclaim", "WW", "NBA Jam 2001 — популярная игра для Nintendo Game Boy Color."),
                ("Noddy and the Birthday Party", "Детские приключения Нодди", 2000, "BBC", "BBC", "WW", "Noddy and the Birthday Party — популярная игра для Nintendo Game Boy Color."),
                ("Pac-Man: Special Color Edition", "Цветной Пакман", 1999, "Namco", "Namco", "WW", "Pac-Man: Special Color Edition — популярная игра для Nintendo Game Boy Color."),
                ("Paperboy", "Цветной Paperboy", 1999, "Midway", "Midway", "WW", "Paperboy — популярная игра для Nintendo Game Boy Color."),
                ("Perfect Dark", "Шпионский стелс-шутер Джоанны Дарк с поддержкой Game Boy Camera", 2000, "Rare / Nintendo", "Rare / Nintendo", "WW", "Perfect Dark — популярная игра для Nintendo Game Boy Color."),
                ("Pitfall: Beyond the Jungle", "Платформер Гарри Питфолла", 1999, "Crave", "Crave", "WW", "Pitfall: Beyond the Jungle — популярная игра для Nintendo Game Boy Color."),
                ("Pokemon Card GB2: Here Comes Team GR!", "Японский сиквел Pokemon TCG с командой Great Rocket", 2001, "Nintendo", "Nintendo", "WW", "Pokemon Card GB2: Here Comes Team GR! — популярная игра для Nintendo Game Boy Color."),
                ("Pokemon Puzzle Challenge", "Головоломка Panel de Pon в мире покемонов Джото", 2000, "Nintendo", "Nintendo", "WW", "Pokemon Puzzle Challenge — популярная игра для Nintendo Game Boy Color."),
                ("Polaris SnoCross", "Гонки на снегоходах", 2000, "Vatical", "Vatical", "WW", "Polaris SnoCross — популярная игра для Nintendo Game Boy Color."),
                ("Power Rangers: Lightspeed Rescue", "Могучие Рейнджеры", 2000, "THQ", "THQ", "WW", "Power Rangers: Lightspeed Rescue — популярная игра для Nintendo Game Boy Color."),
                ("Power Rangers: Time Force", "Патруль времени Рейнджеров", 2001, "THQ", "THQ", "WW", "Power Rangers: Time Force — популярная игра для Nintendo Game Boy Color."),
                ("Powerpuff Girls: Bad Mojo Jojo", "Суперкрошки против Моджо Джоджо", 2000, "BAM!", "BAM!", "WW", "Powerpuff Girls: Bad Mojo Jojo — популярная игра для Nintendo Game Boy Color."),
                ("Powerpuff Girls: Paint the Townsville Green", "Суперкрошки против банды Гринч", 2000, "BAM!", "BAM!", "WW", "Powerpuff Girls: Paint the Townsville Green — популярная игра для Nintendo Game Boy Color."),
                ("Powerpuff Girls: Battle HIM", "Суперкрошки против ОНО", 2001, "BAM!", "BAM!", "WW", "Powerpuff Girls: Battle HIM — популярная игра для Nintendo Game Boy Color."),
                ("Prince of Persia", "Цветной Принц Персии", 1999, "Redline", "Redline", "WW", "Prince of Persia — популярная игра для Nintendo Game Boy Color."),
                ("Q*bert", "Цветной Кьюберт", 2000, "Majesco", "Majesco", "WW", "Q*bert — популярная игра для Nintendo Game Boy Color."),
                ("Quest: Brian's Journey", "JRPG мага Брайана", 2000, "Sunsoft", "Sunsoft", "WW", "Quest: Brian's Journey — популярная игра для Nintendo Game Boy Color."),
                ("R-Type DX", "Полный цветной сборник R-Type I и II", 1999, "Nintendo", "Nintendo", "WW", "R-Type DX — популярная игра для Nintendo Game Boy Color."),
                ("Rainbow Six", "Тактический спецназ Тома Клэнси", 2000, "Red Storm", "Red Storm", "WW", "Rainbow Six — популярная игра для Nintendo Game Boy Color."),
                ("Rampage World Tour", "Монстры Джордж, Лиззи и Ральф крушат города", 1998, "Midway", "Midway", "WW", "Rampage World Tour — популярная игра для Nintendo Game Boy Color."),
                ("Rampart", "Цветной Rampart", 1999, "Midway", "Midway", "WW", "Rampart — популярная игра для Nintendo Game Boy Color."),
                ("Rayman 2", "Трехмерный платформинг Рэймана", 2000, "Ubisoft", "Ubisoft", "WW", "Rayman 2 — популярная игра для Nintendo Game Boy Color."),
                ("Resident Evil Gaiden", "Survival Horror Леона Кеннеди и Барри Бертона на круизном лайнере", 2001, "Capcom", "Capcom", "WW", "Resident Evil Gaiden — популярная игра для Nintendo Game Boy Color."),
                ("Return of the Ninja", "Ниндзя Цукаге и Кину", 2001, "Natsume", "Natsume", "WW", "Return of the Ninja — популярная игра для Nintendo Game Boy Color."),
                ("Road Champions", "Уличные автогонки", 2000, "Mindscape", "Mindscape", "WW", "Road Champions — популярная игра для Nintendo Game Boy Color."),
                ("Road Rash", "Цветной Road Rash", 2000, "Electronic Arts", "Electronic Arts", "WW", "Road Rash — популярная игра для Nintendo Game Boy Color."),
                ("RoboCop", "Цветной Робокоп", 2001, "Titus", "Titus", "WW", "RoboCop — популярная игра для Nintendo Game Boy Color."),
                ("Rocket Power: Gettin' Air", "Экстремальный спорт Nickelodeon", 2001, "THQ", "THQ", "WW", "Rocket Power: Gettin' Air — популярная игра для Nintendo Game Boy Color."),
                ("San Francisco Rush 2049", "Футуристические 3D гонки со срезками", 2000, "Midway", "Midway", "WW", "San Francisco Rush 2049 — популярная игра для Nintendo Game Boy Color."),
                ("Scooby-Doo! Classic Creep Capers", "Скуби-Ду и Корпорация Тайна", 2001, "THQ", "THQ", "WW", "Scooby-Doo! Classic Creep Capers — популярная игра для Nintendo Game Boy Color."),
                ("Sgt. Rock: On the Frontline", "Военный тактический экшен", 2000, "BAM!", "BAM!", "WW", "Sgt. Rock: On the Frontline — популярная игра для Nintendo Game Boy Color."),
                ("Shadowgate Classic", "Цветной мрачный квест Shadowgate", 1999, "Kemco", "Kemco", "WW", "Shadowgate Classic — популярная игра для Nintendo Game Boy Color."),
                ("Shrek: Fairy Tale Freakdown", "Файтинг сказочных героев Шрека", 2001, "TDK Core", "TDK Core", "WW", "Shrek: Fairy Tale Freakdown — популярная игра для Nintendo Game Boy Color."),
                ("Spider-Man", "Человек-паук против Венома и Доктора Осьминога", 2000, "Activision", "Activision", "WW", "Spider-Man — популярная игра для Nintendo Game Boy Color."),
                ("Spider-Man 2: The Sinister Six", "Битва со Зловещей Шестеркой", 2001, "Activision", "Activision", "WW", "Spider-Man 2: The Sinister Six — популярная игра для Nintendo Game Boy Color."),
                ("Spy vs. Spy", "Цветные шпионские ловушки", 1999, "Kemco", "Kemco", "WW", "Spy vs. Spy — популярная игра для Nintendo Game Boy Color."),
                ("Star Wars Episode I: Racer", "Гонки на подах Энакина Скайуокера на Татуине", 1999, "LucasArts / Nintendo", "LucasArts / Nintendo", "WW", "Star Wars Episode I: Racer — популярная игра для Nintendo Game Boy Color."),
                ("Star Wars Episode I: Obi-Wan's Adventures", "Приключения Оби-Вана Кеноби", 2000, "THQ", "THQ", "WW", "Star Wars Episode I: Obi-Wan's Adventures — популярная игра для Nintendo Game Boy Color."),
                ("Street Fighter Alpha: Warriors' Dreams", "Файтинг Рю, Кен, Акума, Чун-Ли от Crawfish", 2000, "Capcom", "Capcom", "WW", "Street Fighter Alpha: Warriors' Dreams — популярная игра для Nintendo Game Boy Color."),
                ("Super Breakout", "Цветной арканоид", 1999, "Majesco", "Majesco", "WW", "Super Breakout — популярная игра для Nintendo Game Boy Color."),
                ("Survival Kids", "Симулятор выживания на необитаемом острове с крафтом и костром", 1999, "Konami", "Konami", "WW", "Survival Kids — популярная игра для Nintendo Game Boy Color."),
                ("Survival Kids 2: Dasshutsu! Futago Jima!", "Вторая часть выживания на островах-близнецах", 2000, "Konami", "Konami", "WW", "Survival Kids 2: Dasshutsu! Futago Jima! — популярная игра для Nintendo Game Boy Color."),
                ("Tazmanian Devil in Island Chase", "Таз на острове", 2000, "Infogrames", "Infogrames", "WW", "Tazmanian Devil in Island Chase — популярная игра для Nintendo Game Boy Color."),
                ("Tetris DX", "Цветной Тетрис с сохранением рекордов батарейкой", 1998, "Nintendo", "Nintendo", "WW", "Tetris DX — популярная игра для Nintendo Game Boy Color."),
                ("Titus the Fox: To Marrakech and Back", "Лисенок Титус", 2000, "Titus", "Titus", "WW", "Titus the Fox: To Marrakech and Back — популярная игра для Nintendo Game Boy Color."),
                ("Toki Tori", "Логическая головоломка цыпленка Токи Тори", 2001, "Capcom", "Capcom", "WW", "Toki Tori — популярная игра для Nintendo Game Boy Color."),
                ("Tomb Raider", "Лара Крофт в поисках Камня Кошмаров", 2000, "Eidos", "Eidos", "WW", "Tomb Raider — популярная игра для Nintendo Game Boy Color."),
                ("Tomb Raider: Curse of the Sword", "Лара Крофт против культа ведьмы", 2001, "Eidos", "Eidos", "WW", "Tomb Raider: Curse of the Sword — популярная игра для Nintendo Game Boy Color."),
                ("Tony Hawk's Pro Skater", "Скейтбординг Тони Хоука", 2000, "Activision", "Activision", "WW", "Tony Hawk's Pro Skater — популярная игра для Nintendo Game Boy Color."),
                ("Tony Hawk's Pro Skater 2", "Скейтбординг Тони Хоука 2", 2001, "Activision", "Activision", "WW", "Tony Hawk's Pro Skater 2 — популярная игра для Nintendo Game Boy Color."),
                ("Tony Hawk's Pro Skater 3", "Скейтбординг Тони Хоука 3", 2002, "Activision", "Activision", "WW", "Tony Hawk's Pro Skater 3 — популярная игра для Nintendo Game Boy Color."),
                ("Top Gear Pocket", "Гонки Top Gear с вибрацией", 1999, "Kemco", "Kemco", "WW", "Top Gear Pocket — популярная игра для Nintendo Game Boy Color."),
                ("Top Gear Pocket 2", "Вторая часть Top Gear", 2000, "Kemco", "Kemco", "WW", "Top Gear Pocket 2 — популярная игра для Nintendo Game Boy Color."),
                ("Top Gear Rally", "Ралли", 1999, "Kemco", "Kemco", "WW", "Top Gear Rally — популярная игра для Nintendo Game Boy Color."),
                ("Towers: Lord Baniff's Deceit", "3D RPG от первого лица", 2000, "Telegames", "Telegames", "WW", "Towers: Lord Baniff's Deceit — популярная игра для Nintendo Game Boy Color."),
                ("Toy Story 2", "Базз Лайтер и Вуди", 1999, "THQ", "THQ", "WW", "Toy Story 2 — популярная игра для Nintendo Game Boy Color."),
                ("Trick Boarder", "Сноубординг", 1999, "Athena", "Athena", "WW", "Trick Boarder — популярная игра для Nintendo Game Boy Color."),
                ("Turok 2: Seeds of Evil", "Турок против расы динозавров Диносапиенсов", 1998, "Acclaim", "Acclaim", "WW", "Turok 2: Seeds of Evil — популярная игра для Nintendo Game Boy Color."),
                ("Turok 3: Shadow of Oblivion", "Джошуа и Даниэль Файрсид против Обливиона", 2000, "Acclaim", "Acclaim", "WW", "Turok 3: Shadow of Oblivion — популярная игра для Nintendo Game Boy Color."),
                ("Turok: Rage Wars", "Арена-бои Турока", 2000, "Acclaim", "Acclaim", "WW", "Turok: Rage Wars — популярная игра для Nintendo Game Boy Color."),
                ("V-Rally: Championship Edition", "Раллийные гонки", 1999, "Infogrames", "Infogrames", "WW", "V-Rally: Championship Edition — популярная игра для Nintendo Game Boy Color."),
                ("Vigilante 8", "Боевые автогонки с ракетницами и пулеметами", 1999, "Activision", "Activision", "WW", "Vigilante 8 — популярная игра для Nintendo Game Boy Color."),
                ("Wacky Races", "Безумные гонки Дика Дастардли и пса Маттли", 2000, "Infogrames", "Infogrames", "WW", "Wacky Races — популярная игра для Nintendo Game Boy Color."),
                ("Wario Land II (Color)", "Цветной ремейк Wario Land 2", 1998, "Nintendo", "Nintendo", "WW", "Wario Land II (Color) — популярная игра для Nintendo Game Boy Color."),
                ("Warlocked", "Стратегия в реальном времени RTS в стиле Warcraft на GBC", 2000, "Nintendo", "Nintendo", "WW", "Warlocked — популярная игра для Nintendo Game Boy Color."),
                ("Wings of Fury", "Авиасимулятор торпедоносца Тихоокеанского фронта", 1999, "Mindscape", "Mindscape", "WW", "Wings of Fury — популярная игра для Nintendo Game Boy Color."),
                ("Winnie the Pooh: Preschool", "Обучающие игры", 2001, "Disney", "Disney", "WW", "Winnie the Pooh: Preschool — популярная игра для Nintendo Game Boy Color."),
                ("Woody Woodpecker", "Дятел Вуди", 2001, "Universal", "Universal", "WW", "Woody Woodpecker — популярная игра для Nintendo Game Boy Color."),
                ("World Destruction League: Thunder Tanks", "Танковые арена-битвы", 2000, "3DO", "3DO", "WW", "World Destruction League: Thunder Tanks — популярная игра для Nintendo Game Boy Color."),
                ("Worms Armageddon", "Червячки Армагеддон", 2000, "Infogrames", "Infogrames", "WW", "Worms Armageddon — популярная игра для Nintendo Game Boy Color."),
                ("X-Men: Mutant Academy", "Файтинг Людей Икс (Росомаха, Циклоп, Гамбит, Шторм)", 2000, "Activision", "Activision", "WW", "X-Men: Mutant Academy — популярная игра для Nintendo Game Boy Color."),
                ("X-Men: Mutant Wars", "Beat 'em up Людей Икс", 2000, "Activision", "Activision", "WW", "X-Men: Mutant Wars — популярная игра для Nintendo Game Boy Color."),
                ("X-Men: Wolverine's Rage", "Экшен Росомахи", 2001, "Activision", "Activision", "WW", "X-Men: Wolverine's Rage — популярная игра для Nintendo Game Boy Color."),
                ("Yars' Revenge", "Космошутер Atari", 1999, "Telegames", "Telegames", "WW", "Yars' Revenge — популярная игра для Nintendo Game Boy Color."),
                ("Yoda Stories", "Приключения Люка Скайуокера на Дагобе", 1999, "THQ", "THQ", "WW", "Yoda Stories — популярная игра для Nintendo Game Boy Color."),
                ("Yoshi's Challenge", "Головоломка Йоши", 1999, "Nintendo", "Nintendo", "WW", "Yoshi's Challenge — популярная игра для Nintendo Game Boy Color."),
                ("Yu-Gi-Oh! Dark Duel Stories", "Карточная дуэльная игра Юги Муто", 2002, "Konami", "Konami", "WW", "Yu-Gi-Oh! Dark Duel Stories — популярная игра для Nintendo Game Boy Color."),
                ("Zelda: The Minish Cap (Color Demake)", "Приключения Линка", 2001, "Nintendo", "Nintendo", "WW", "Zelda: The Minish Cap (Color Demake) — популярная игра для Nintendo Game Boy Color."),
            };

            foreach (var g in games)
            {
                list.Add(new NintendoCatalogItem
                {
                    Title = g.Title,
                    Genre = g.Genre,
                    Year = g.Year,
                    Developer = g.Dev,
                    Publisher = g.Pub,
                    Region = g.Region,
                    Desc = g.Desc
                });
            }

            return list;
        }
    }
}
