using System;
using System.Collections.Generic;

namespace StormSwitchBox.Services
{
    public static class N64CatalogData
    {
        public static List<NintendoCatalogItem> GetCatalog()
        {
            var list = new List<NintendoCatalogItem>(256);

            var games = new (string Title, string Genre, int Year, string Dev, string Pub, string Region, string Desc)[]
            {
                ("Super Mario 64", "3D Платформер", 1996, "Nintendo EAD", "Nintendo", "WW", "Революция трехмерного пространства: свободная аналоговая камера, 120 звезд замка принцессы Пич."),
                ("The Legend of Zelda: Ocarina of Time", "Action-Adventure", 1998, "Nintendo EAD", "Nintendo", "WW", "Величайшая видеоигра в истории: автолок Z-targeting, окарина времени, взросление Линка на 7 лет."),
                ("The Legend of Zelda: Majora's Mask", "Action-Adventure", 2000, "Nintendo EAD", "Nintendo", "WW", "Мрачный шедевр 3-дневного цикла времени с масками превращений (Деку, Горон, Зора) и падающей Луной."),
                ("GoldenEye 007", "Шутер от первого лица", 1997, "Rare", "Nintendo", "WW", "Родоначальник консольных FPS с реалистичными миссиями Джеймса Бонда и мультиплеером на 4 игроков."),
                ("Perfect Dark", "Шутер от первого лица", 2000, "Rare", "Nintendo", "WW", "Шпионский киберпанк-боевик Джоанны Дарк с кастомизацией ботов и 32 видами футуристического оружия."),
                ("Banjo-Kazooie", "3D Платформер", 1998, "Rare", "Nintendo", "WW", "Медведь Банджо и птица Казуи спасают сестру Тутти из лап ведьмы Грунтильды."),
                ("Banjo-Tooie", "3D Платформер", 2000, "Rare", "Nintendo", "WW", "Грандиозный сиквел с гигантскими соединенными мирами, шутерным режимом от первого лица и разделением героев."),
                ("Conker's Bad Fur Day", "Взрослый 3D Платформер", 2001, "Rare", "Nintendo", "WW", "Белка-пьяница Конкер в сатирическом шедевре с пародиями на Матрицу, Чужого и боссом Great Mighty Poo."),
                ("Super Smash Bros.", "Файтинг-кроссовер", 1999, "HAL Laboratory", "Nintendo", "WW", "Рождение культовой арены Масахиро Сакурая: битва 12 легенд Nintendo за границы экрана."),
                ("Mario Kart 64", "Картинговые гонки", 1996, "Nintendo EAD", "Nintendo", "WW", "4 игрока на одном экране, синий панцирь с шипами, режим Battle Mode и 16 культовых трасс."),
                ("Paper Mario", "JRPG", 2000, "Intelligent Systems", "Nintendo", "WW", "Двумерный бумажный Марио в 3D-мире с напарниками, значками способностей и тайминговыми атаками Action Commands."),
                ("Star Fox 64 (Lylat Wars)", "3D Рельсовый шутер", 1997, "Nintendo EAD", "Nintendo", "WW", "Команда Фокса Макклауда на истребителях Arwing с первой поддержкой мотора Rumble Pak и полной озвучкой."),
                ("F-Zero X", "Сверхзвуковые гонки", 1998, "Nintendo EAD", "Nintendo", "WW", "30 болидов на трассе одновременно при безупречных 60 FPS и рок-саундтреке с генератором случайных трасс."),
                ("Diddy Kong Racing", "Гонки с открытым миром", 1997, "Rare", "Nintendo", "WW", "Сюжетная кампания на картах, самолетах и судах на воздушной подушке против свиньи-мага Визпига."),
                ("Donkey Kong 64", "3D Платформер", 1999, "Rare", "Nintendo", "WW", "5 играбельных конгов (Донки, Дидди, Ланки, Тайни, Чанки) с музыкальными инструментами и фруктометами."),
                ("Mario Party", "Вечеринка / Настольная игра", 1998, "Hudson Soft", "Nintendo", "WW", "Родоначальник жанра вечеринок с кубиками, монетами, звездами и 50 мини-играми."),
                ("Mario Party 2", "Вечеринка / Настольная игра", 1999, "Hudson Soft", "Nintendo", "WW", "Тематические костюмы ковбоев, пиратов и волшебников с покупкой предметов в магазинах предметов."),
                ("Mario Party 3", "Вечеринка / Настольная игра", 2000, "Hudson Soft", "Nintendo", "WW", "Появление Валуиджи и принцессы Дейзи, дуэльный режим Duel Mode и 70 новых мини-игр."),
                ("Pokemon Stadium", "3D Пошаговые сражения", 1999, "Nintendo EAD / HAL", "Nintendo", "WW", "Полные 3D-битвы 151 покемона на телеэкране с переносом через Transfer Pak и мини-играми."),
                ("Pokemon Stadium 2", "3D Пошаговые сражения", 2000, "Nintendo EAD / HAL", "Nintendo", "WW", "251 покемон из Канто и Джото, Академия Эрла, мини-игры и чемпионские кубки."),
                ("Pokemon Snap", "3D Фото-сафари", 1999, "HAL Laboratory", "Nintendo", "WW", "Тодд Снэп фотографирует покемонов в естественной среде обитания на острове Покемонов профессора Оука."),
                ("1080 Snowboarding", "Сноубординг", 1998, "Nintendo EAD", "Nintendo", "WW", "Шедевр экстремального спорта с реалистичной физикой снега, одеждой и трюками."),
                ("Wave Race 64", "Водные гонки на гидроциклах", 1996, "Nintendo EAD", "Nintendo", "WW", "Революционная физика реалистичных трехмерных волн от Сигэру Миямото."),
                ("Ogre Battle 64: Person of Lordly Caliber", "Тактическая RPG", 1999, "Quest", "Atlus / Nintendo", "WW", "Эпическая тактика Магнуса Галланта в Палатине с 6 ветками концовок и моралью."),
                ("Rayman 2: The Great Escape", "3D Платформер", 1999, "Ubisoft", "Ubisoft", "WW", "Рэйман спасает мир Перекрестка Грез от адмирала Остроборода."),
                ("007: The World Is Not Enough", "FPS Джеймса Бонда от Eurocom", 2000, "EA", "EA", "WW", "007: The World Is Not Enough — популярная игра для Nintendo 64 / 64DD."),
                ("Aerofighters Assault", "Авиасимулятор", 1997, "Video System", "Video System", "WW", "Aerofighters Assault — популярная игра для Nintendo 64 / 64DD."),
                ("Aidyn Chronicles: The First Mage", "Масштабная 3D Western-RPG", 2001, "THQ", "THQ", "WW", "Aidyn Chronicles: The First Mage — популярная игра для Nintendo 64 / 64DD."),
                ("All-Star Baseball 99", "Спорт", 1998, "Acclaim", "Acclaim", "WW", "All-Star Baseball 99 — популярная игра для Nintendo 64 / 64DD."),
                ("All-Star Baseball 2000", "Спорт", 1999, "Acclaim", "Acclaim", "WW", "All-Star Baseball 2000 — популярная игра для Nintendo 64 / 64DD."),
                ("All-Star Baseball 2001", "Спорт", 2000, "Acclaim", "Acclaim", "WW", "All-Star Baseball 2001 — популярная игра для Nintendo 64 / 64DD."),
                ("Armorines: Project S.W.A.R.M.", "FPS против насекомоподобных пришельцев", 1999, "Acclaim", "Acclaim", "WW", "Armorines: Project S.W.A.R.M. — популярная игра для Nintendo 64 / 64DD."),
                ("Army Men: Air Combat", "Вертолетный экшен", 2000, "3DO", "3DO", "WW", "Army Men: Air Combat — популярная игра для Nintendo 64 / 64DD."),
                ("Army Men: Sarge's Heroes", "Экшен зеленых пластиковых солдатиков", 1999, "3DO", "3DO", "WW", "Army Men: Sarge's Heroes — популярная игра для Nintendo 64 / 64DD."),
                ("Army Men: Sarge's Heroes 2", "Экшен солдатиков 2", 2000, "3DO", "3DO", "WW", "Army Men: Sarge's Heroes 2 — популярная игра для Nintendo 64 / 64DD."),
                ("Asteroids Hyper 64", "3D ремейк классики Asteroids", 1999, "Crave", "Crave", "WW", "Asteroids Hyper 64 — популярная игра для Nintendo 64 / 64DD."),
                ("Automobili Lamborghini", "Гонки на суперкарах", 1997, "Titus", "Titus", "WW", "Automobili Lamborghini — популярная игра для Nintendo 64 / 64DD."),
                ("Bakuretsu Muteki Bangai-O", "Шедевр 2D меха-экшена от Treasure", 1999, "ESP", "ESP", "WW", "Bakuretsu Muteki Bangai-O — популярная игра для Nintendo 64 / 64DD."),
                ("Bassmasters 2000", "Рыбалка", 1999, "THQ", "THQ", "WW", "Bassmasters 2000 — популярная игра для Nintendo 64 / 64DD."),
                ("Batman Beyond: Return of the Joker", "Beat 'em up Бэтмена будущего", 2000, "Ubisoft", "Ubisoft", "WW", "Batman Beyond: Return of the Joker — популярная игра для Nintendo 64 / 64DD."),
                ("BattleTanx", "Постапокалиптический танковый экшен", 1998, "3DO", "3DO", "WW", "BattleTanx — популярная игра для Nintendo 64 / 64DD."),
                ("BattleTanx: Global Assault", "Танковые сражения в мировых столицах", 1999, "3DO", "3DO", "WW", "BattleTanx: Global Assault — популярная игра для Nintendo 64 / 64DD."),
                ("Beetle Adventure Racing!", "Гонки на фольксвагенах Жук по живописным трассам от EA", 1999, "EA", "EA", "WW", "Beetle Adventure Racing! — популярная игра для Nintendo 64 / 64DD."),
                ("Blast Corps", "Разрушение зданий строительной техникой от Rare", 1997, "Nintendo", "Nintendo", "WW", "Blast Corps — популярная игра для Nintendo 64 / 64DD."),
                ("Blues Brothers 2000", "Платформер Братьев Блюз", 2000, "Titus", "Titus", "WW", "Blues Brothers 2000 — популярная игра для Nintendo 64 / 64DD."),
                ("Body Harvest", "3D Sci-Fi экшен от создателей GTA (DMA Design) с пересадкой на любую технику", 1998, "Midway", "Midway", "WW", "Body Harvest — популярная игра для Nintendo 64 / 64DD."),
                ("Bomberman 64", "3D экшен-головоломка с созданием и бросанием бомб", 1997, "Nintendo", "Nintendo", "WW", "Bomberman 64 — популярная игра для Nintendo 64 / 64DD."),
                ("Bomberman 64: The Second Attack", "Сюжетное продолжение с элементами стихийных бомб", 1999, "Vatical", "Vatical", "WW", "Bomberman 64: The Second Attack — популярная игра для Nintendo 64 / 64DD."),
                ("Bomberman Hero", "3D платформер Бомбермена с полетами на вертолете и плаванием", 1998, "Nintendo", "Nintendo", "WW", "Bomberman Hero — популярная игра для Nintendo 64 / 64DD."),
                ("Buck Bumble", "Кибер-пчела с пулеметами и знаменитым британским гэридж-саундтреком", 1998, "Ubisoft", "Ubisoft", "WW", "Buck Bumble — популярная игра для Nintendo 64 / 64DD."),
                ("Bust-A-Move '99", "Головоломка шариков", 1999, "Acclaim", "Acclaim", "WW", "Bust-A-Move '99 — популярная игра для Nintendo 64 / 64DD."),
                ("Carmageddon 64", "Боевые автогонки", 2000, "Titus", "Titus", "WW", "Carmageddon 64 — популярная игра для Nintendo 64 / 64DD."),
                ("Castlevania 64", "Трехмерные приключения Рейнхардта Шнайдера и Кэрри Фернандес", 1999, "Konami", "Konami", "WW", "Castlevania 64 — популярная игра для Nintendo 64 / 64DD."),
                ("Castlevania: Legacy of Darkness", "Приключения человека-оборотня Корнелла в замке Дракулы", 1999, "Konami", "Konami", "WW", "Castlevania: Legacy of Darkness — популярная игра для Nintendo 64 / 64DD."),
                ("Chameleon Twist", "Платформер хамелеона с захватами длинным языком", 1997, "Sunsoft", "Sunsoft", "WW", "Chameleon Twist — популярная игра для Nintendo 64 / 64DD."),
                ("Chameleon Twist 2", "Вторая часть приключений хамелеона", 1998, "Sunsoft", "Sunsoft", "WW", "Chameleon Twist 2 — популярная игра для Nintendo 64 / 64DD."),
                ("Command & Conquer", "Культовая 3D RTS с полигональной графикой GDI против Nod", 1999, "Nintendo", "Nintendo", "WW", "Command & Conquer — популярная игра для Nintendo 64 / 64DD."),
                ("Cruis'n USA", "Аркадные гонки от побережья до побережья США", 1996, "Nintendo", "Nintendo", "WW", "Cruis'n USA — популярная игра для Nintendo 64 / 64DD."),
                ("Cruis'n World", "Гонки по мировым столицам с трюками и сальто", 1998, "Nintendo", "Nintendo", "WW", "Cruis'n World — популярная игра для Nintendo 64 / 64DD."),
                ("Cruis'n Exotica", "Гонки в космосе, под водой и на Марсе", 2000, "Midway", "Midway", "WW", "Cruis'n Exotica — популярная игра для Nintendo 64 / 64DD."),
                ("Custom Robo", "RPG сражений кастомизируемых боевых роботов", 1999, "Nintendo", "Nintendo", "WW", "Custom Robo — популярная игра для Nintendo 64 / 64DD."),
                ("Custom Robo V2", "Вторая часть кастомизируемых роботов на 4 игроков", 2000, "Nintendo", "Nintendo", "WW", "Custom Robo V2 — популярная игра для Nintendo 64 / 64DD."),
                ("CyberTiger", "Гольф Тайгера Вудса", 2000, "EA Sports", "EA Sports", "WW", "CyberTiger — популярная игра для Nintendo 64 / 64DD."),
                ("Destruction Derby 64", "Гонки на выживание и арены автокатастроф", 1999, "THQ", "THQ", "WW", "Destruction Derby 64 — популярная игра для Nintendo 64 / 64DD."),
                ("Doom 64", "Уникальная эксклюзивная часть Doom с новой мрачной графикой и уровнями", 1997, "Midway", "Midway", "WW", "Doom 64 — популярная игра для Nintendo 64 / 64DD."),
                ("Duke Nukem 64", "3D FPS Дюка Нюкема с кооперативом на 4 игроков", 1997, "GT Interactive", "GT Interactive", "WW", "Duke Nukem 64 — популярная игра для Nintendo 64 / 64DD."),
                ("Duke Nukem: Zero Hour", "Шутер от третьего лица Дюка во времени (Дикий Запад, Викторианский Лондон)", 1999, "GT Interactive", "GT Interactive", "WW", "Duke Nukem: Zero Hour — популярная игра для Nintendo 64 / 64DD."),
                ("Earthworm Jim 3D", "Трехмерный платформер червяка Джима", 1999, "Rockstar Games", "Rockstar Games", "WW", "Earthworm Jim 3D — популярная игра для Nintendo 64 / 64DD."),
                ("ECW Hardcore Revolution", "Хардкорный рестлинг", 2000, "Acclaim", "Acclaim", "WW", "ECW Hardcore Revolution — популярная игра для Nintendo 64 / 64DD."),
                ("Excitebike 64", "Культовые мотокроссовые гонки с трюками и редактором трасс от Left Field", 2000, "Nintendo", "Nintendo", "WW", "Excitebike 64 — популярная игра для Nintendo 64 / 64DD."),
                ("Extreme-G", "Сверхзвуковые футуристические мотогонки с оружием", 1997, "Acclaim", "Acclaim", "WW", "Extreme-G — популярная игра для Nintendo 64 / 64DD."),
                ("Extreme-G 2", "Вторая часть мотогонок с преодолением звукового барьера Mach 1", 1998, "Acclaim", "Acclaim", "WW", "Extreme-G 2 — популярная игра для Nintendo 64 / 64DD."),
                ("F-1 World Grand Prix", "Симулятор Формулы-1 сезона 1997", 1998, "Nintendo", "Nintendo", "WW", "F-1 World Grand Prix — популярная игра для Nintendo 64 / 64DD."),
                ("F1 Pole Position 64", "Гонки Формулы-1", 1997, "Ubisoft", "Ubisoft", "WW", "F1 Pole Position 64 — популярная игра для Nintendo 64 / 64DD."),
                ("FIFA 99", "Футбольный симулятор", 1998, "EA Sports", "EA Sports", "WW", "FIFA 99 — популярная игра для Nintendo 64 / 64DD."),
                ("FIFA: Road to World Cup 98", "Чемпионат Мира по футболу 98 со всеми сборными", 1997, "EA Sports", "EA Sports", "WW", "FIFA: Road to World Cup 98 — популярная игра для Nintendo 64 / 64DD."),
                ("Fighter Destiny 2", "Файтинг по очковой системе", 2000, "SouthPeak", "SouthPeak", "WW", "Fighter Destiny 2 — популярная игра для Nintendo 64 / 64DD."),
                ("Fighters Destiny", "Техничный файтинг с правилом нокдаунов", 1998, "Ocean", "Ocean", "WW", "Fighters Destiny — популярная игра для Nintendo 64 / 64DD."),
                ("Fighting Force 64", "3D Beat 'em up", 1999, "Crave", "Crave", "WW", "Fighting Force 64 — популярная игра для Nintendo 64 / 64DD."),
                ("Forsaken 64", "Шутер с 6 степенями свободы 6DOF от Iguana", 1998, "Acclaim", "Acclaim", "WW", "Forsaken 64 — популярная игра для Nintendo 64 / 64DD."),
                ("Gauntlet Legends", "Кооперативный Hack 'n' Slash на 4 игроков", 1999, "Midway", "Midway", "WW", "Gauntlet Legends — популярная игра для Nintendo 64 / 64DD."),
                ("Glover", "Платформер перчатки Гловера, перекатывающей волшебный шар", 1998, "Hasbro", "Hasbro", "WW", "Glover — популярная игра для Nintendo 64 / 64DD."),
                ("Goemon's Great Adventure", "Кооперативный 2.5D платформер Гоэмона и Эбисумару", 1999, "Konami", "Konami", "WW", "Goemon's Great Adventure — популярная игра для Nintendo 64 / 64DD."),
                ("Harvest Moon 64", "Один из величайших симуляторов фермы с праздниками и заведением семьи", 1999, "Natsume", "Natsume", "WW", "Harvest Moon 64 — популярная игра для Nintendo 64 / 64DD."),
                ("Hexen", "Темное фэнтези от первого лица", 1997, "GT Interactive", "GT Interactive", "WW", "Hexen — популярная игра для Nintendo 64 / 64DD."),
                ("Hot Wheels Turbo Racing", "Трюковые гонки машинок Hot Wheels", 1999, "EA", "EA", "WW", "Hot Wheels Turbo Racing — популярная игра для Nintendo 64 / 64DD."),
                ("Hybrid Heaven", "Научно-фантастический RPG-экшен от Konami с пошаговыми комбо-захватами", 1999, "Konami", "Konami", "WW", "Hybrid Heaven — популярная игра для Nintendo 64 / 64DD."),
                ("Hydro Thunder", "Бешеные гонки на скоростных катерах от Midway", 2000, "Midway", "Midway", "WW", "Hydro Thunder — популярная игра для Nintendo 64 / 64DD."),
                ("Indiana Jones and the Infernal Machine", "Приключения Индианы Джонса в Вавилонской башне от Factor 5", 2000, "LucasArts", "LucasArts", "WW", "Indiana Jones and the Infernal Machine — популярная игра для Nintendo 64 / 64DD."),
                ("International Superstar Soccer 64", "Революционный футбол Konami на 4 игроков", 1997, "Konami", "Konami", "WW", "International Superstar Soccer 64 — популярная игра для Nintendo 64 / 64DD."),
                ("International Superstar Soccer 98", "Футбол ISS 98", 1998, "Konami", "Konami", "WW", "International Superstar Soccer 98 — популярная игра для Nintendo 64 / 64DD."),
                ("International Superstar Soccer 2000", "Футбол с режимом карьеры игрока", 2000, "Konami", "Konami", "WW", "International Superstar Soccer 2000 — популярная игра для Nintendo 64 / 64DD."),
                ("Jet Force Gemini", "Sci-Fi шутер от третьего лица от Rare: Джуно, Вела и собака Люпус против жуков", 1999, "Nintendo", "Nintendo", "WW", "Jet Force Gemini — популярная игра для Nintendo 64 / 64DD."),
                ("Killer Instinct Gold", "Файтинг Rare с 11 персонажами и ультра-комбо", 1996, "Nintendo", "Nintendo", "WW", "Killer Instinct Gold — популярная игра для Nintendo 64 / 64DD."),
                ("Kirby 64: The Crystal Shards", "2.5D платформер Кирби с комбинированием способностей (Огонь+Меч=Огненный меч)", 2000, "Nintendo", "Nintendo", "WW", "Kirby 64: The Crystal Shards — популярная игра для Nintendo 64 / 64DD."),
                ("Knockout Kings 2000", "Бокс от EA Sports", 1999, "EA Sports", "EA Sports", "WW", "Knockout Kings 2000 — популярная игра для Nintendo 64 / 64DD."),
                ("Lego Racers", "Конструктор машинок и гонки Лего", 1999, "Lego Media", "Lego Media", "WW", "Lego Racers — популярная игра для Nintendo 64 / 64DD."),
                ("Madden NFL 2000", "Американский футбол", 1999, "EA Sports", "EA Sports", "WW", "Madden NFL 2000 — популярная игра для Nintendo 64 / 64DD."),
                ("Madden NFL 2001", "Американский футбол 2001", 2000, "EA Sports", "EA Sports", "WW", "Madden NFL 2001 — популярная игра для Nintendo 64 / 64DD."),
                ("Madden NFL 2002", "Финальная часть NFL на N64", 2001, "EA Sports", "EA Sports", "WW", "Madden NFL 2002 — популярная игра для Nintendo 64 / 64DD."),
                ("Magical Tetris Challenge", "Тетрис с персонажами Диснея", 1999, "Capcom", "Capcom", "WW", "Magical Tetris Challenge — популярная игра для Nintendo 64 / 64DD."),
                ("Mario Golf", "Спортивный гольф Марио от Camelot с 14 персонажами", 1999, "Nintendo", "Nintendo", "WW", "Mario Golf — популярная игра для Nintendo 64 / 64DD."),
                ("Mario Tennis", "Спортивный теннис Марио, впервые представивший Валуиджи", 2000, "Nintendo", "Nintendo", "WW", "Mario Tennis — популярная игра для Nintendo 64 / 64DD."),
                ("Mega Man 64 (Mega Man Legends)", "3D Action-Adventure Мегамена Волната на острове Каттельокс", 2001, "Capcom", "Capcom", "WW", "Mega Man 64 (Mega Man Legends) — популярная игра для Nintendo 64 / 64DD."),
                ("Mischief Makers (Yuke Yuke!! Trouble Makers)", "Культовый 2D платформер робота Марины Shake-Shake от Treasure", 1997, "Nintendo", "Nintendo", "WW", "Mischief Makers (Yuke Yuke!! Trouble Makers) — популярная игра для Nintendo 64 / 64DD."),
                ("Mission: Impossible", "Шпионский стелс Итана Ханта", 1998, "Ocean", "Ocean", "WW", "Mission: Impossible — популярная игра для Nintendo 64 / 64DD."),
                ("Monopoly", "3D Монополия", 1999, "Hasbro", "Hasbro", "WW", "Monopoly — популярная игра для Nintendo 64 / 64DD."),
                ("Monster Truck Madness 64", "Гонки на бигфутах с деформацией кузова", 1999, "Rockstar Games", "Rockstar Games", "WW", "Monster Truck Madness 64 — популярная игра для Nintendo 64 / 64DD."),
                ("Mortal Kombat 4", "Трехмерная Смертельная Битва с оружием", 1998, "Midway", "Midway", "WW", "Mortal Kombat 4 — популярная игра для Nintendo 64 / 64DD."),
                ("Mortal Kombat Mythologies: Sub-Zero", "Action-платформер о Саб-Зиро", 1997, "Midway", "Midway", "WW", "Mortal Kombat Mythologies: Sub-Zero — популярная игра для Nintendo 64 / 64DD."),
                ("Mortal Kombat Trilogy", "Сборник всех бойцов и арен MK1-MK3", 1996, "Midway", "Midway", "WW", "Mortal Kombat Trilogy — популярная игра для Nintendo 64 / 64DD."),
                ("Mystical Ninja Starring Goemon", "3D Action-Adventure в стиле Zelda с гигантским роботом Impact", 1997, "Konami", "Konami", "WW", "Mystical Ninja Starring Goemon — популярная игра для Nintendo 64 / 64DD."),
                ("Nagano Winter Olympics '98", "Зимние Олимпийские игры в Нагано 1998 от Konami", 1998, "Konami", "Konami", "WW", "Nagano Winter Olympics '98 — популярная игра для Nintendo 64 / 64DD."),
                ("NASCAR 99", "Гонки NASCAR", 1998, "EA Sports", "EA Sports", "WW", "NASCAR 99 — популярная игра для Nintendo 64 / 64DD."),
                ("NBA Courtside 2", "Баскетбол с Коби Брайантом", 1999, "Nintendo", "Nintendo", "WW", "NBA Courtside 2 — популярная игра для Nintendo 64 / 64DD."),
                ("NBA Hangtime", "Уличный баскетбол 2х2 от Midway", 1997, "Midway", "Midway", "WW", "NBA Hangtime — популярная игра для Nintendo 64 / 64DD."),
                ("NBA Jam 99", "Баскетбол Acclaim", 1998, "Acclaim", "Acclaim", "WW", "NBA Jam 99 — популярная игра для Nintendo 64 / 64DD."),
                ("NBA Jam 2000", "Баскетбол Acclaim 2000", 1999, "Acclaim", "Acclaim", "WW", "NBA Jam 2000 — популярная игра для Nintendo 64 / 64DD."),
                ("NBA Live 2000", "Баскетбол EA с Майклом Джорданом", 1999, "EA Sports", "EA Sports", "WW", "NBA Live 2000 — популярная игра для Nintendo 64 / 64DD."),
                ("NFL Blitz", "Аркадный агрессивный футбол без правил от Midway", 1998, "Midway", "Midway", "WW", "NFL Blitz — популярная игра для Nintendo 64 / 64DD."),
                ("NFL Blitz 2000", "Вторая часть Blitz", 1999, "Midway", "Midway", "WW", "NFL Blitz 2000 — популярная игра для Nintendo 64 / 64DD."),
                ("NFL Blitz 2001", "Третья часть Blitz", 2000, "Midway", "Midway", "WW", "NFL Blitz 2001 — популярная игра для Nintendo 64 / 64DD."),
                ("NHL 99", "Хоккей от EA Sports", 1998, "EA Sports", "EA Sports", "WW", "NHL 99 — популярная игра для Nintendo 64 / 64DD."),
                ("NHL Blades of Steel '99", "Хоккей от Konami", 1999, "Konami", "Konami", "WW", "NHL Blades of Steel '99 — популярная игра для Nintendo 64 / 64DD."),
                ("Nightmare Creatures", "Готический хоррор-слэшер в Лондоне 1834 года", 1998, "Activision", "Activision", "WW", "Nightmare Creatures — популярная игра для Nintendo 64 / 64DD."),
                ("Nuclear Strike 64", "Изометрический вертолетный боевик", 1999, "THQ", "THQ", "WW", "Nuclear Strike 64 — популярная игра для Nintendo 64 / 64DD."),
                ("Off Road Challenge", "Гонки по бездорожью", 1998, "Midway", "Midway", "WW", "Off Road Challenge — популярная игра для Nintendo 64 / 64DD."),
                ("Paperboy 64", "Трехмерная доставка газет", 1999, "Midway", "Midway", "WW", "Paperboy 64 — популярная игра для Nintendo 64 / 64DD."),
                ("Penny Racers (Choro Q 64)", "Гонки игрушечных машинок", 1999, "THQ", "THQ", "WW", "Penny Racers (Choro Q 64) — популярная игра для Nintendo 64 / 64DD."),
                ("Pilotwings 64", "Стартовый 3D авиасимулятор дельтаплана, джетпака и пушки", 1996, "Nintendo", "Nintendo", "WW", "Pilotwings 64 — популярная игра для Nintendo 64 / 64DD."),
                ("Pokemon Puzzle League", "Головоломка по мотивам аниме покемонов со звуками и видео", 2000, "Nintendo", "Nintendo", "WW", "Pokemon Puzzle League — популярная игра для Nintendo 64 / 64DD."),
                ("Quake 64", "3D FPS с динамическим цветным освещением", 1998, "Midway", "Midway", "WW", "Quake 64 — популярная игра для Nintendo 64 / 64DD."),
                ("Quake II", "Эксклюзивная версия Quake 2 с новыми уровнями и поддержкой 4 игроков", 1999, "Activision", "Activision", "WW", "Quake II — популярная игра для Nintendo 64 / 64DD."),
                ("Quest 64 (Holy Magic Century)", "3D JRPG юного мага Брайана", 1998, "THQ", "THQ", "WW", "Quest 64 (Holy Magic Century) — популярная игра для Nintendo 64 / 64DD."),
                ("Rampage 2: Universal Tour", "Монстры крушат планеты", 1999, "Midway", "Midway", "WW", "Rampage 2: Universal Tour — популярная игра для Nintendo 64 / 64DD."),
                ("Rampage World Tour", "Монстры крушат мировые города", 1998, "Midway", "Midway", "WW", "Rampage World Tour — популярная игра для Nintendo 64 / 64DD."),
                ("Re-Volt", "Гонки радиоуправляемых машинок от Acclaim", 1999, "Acclaim", "Acclaim", "WW", "Re-Volt — популярная игра для Nintendo 64 / 64DD."),
                ("Ready 2 Rumble Boxing", "Аркадный комедийный бокс Майкла Баффера", 1999, "Midway", "Midway", "WW", "Ready 2 Rumble Boxing — популярная игра для Nintendo 64 / 64DD."),
                ("Ready 2 Rumble Boxing: Round 2", "Бокс с участием Шакила О'Нила и Майкла Джексона", 2000, "Midway", "Midway", "WW", "Ready 2 Rumble Boxing: Round 2 — популярная игра для Nintendo 64 / 64DD."),
                ("Resident Evil 2", "Технологическое чудо: полная игра на 64 МБ картридже с видео и звуком от Angel Studios", 1999, "Capcom", "Capcom", "WW", "Resident Evil 2 — популярная игра для Nintendo 64 / 64DD."),
                ("Ridge Racer 64", "Скоростной дрифт на 60 FPS от Nintendo Software Technology", 2000, "Nintendo", "Nintendo", "WW", "Ridge Racer 64 — популярная игра для Nintendo 64 / 64DD."),
                ("Road Rash 64", "Мотоциклетные бои с трубами и цепями под рок Sugar Ray", 1999, "THQ", "THQ", "WW", "Road Rash 64 — популярная игра для Nintendo 64 / 64DD."),
                ("Robotron 64", "3D твин-стик шутер", 1998, "Midway", "Midway", "WW", "Robotron 64 — популярная игра для Nintendo 64 / 64DD."),
                ("Rocket: Robot on Wheels", "Первая в истории консольная игра с реалистичным физическим движком от Sucker Punch", 1999, "Ubisoft", "Ubisoft", "WW", "Rocket: Robot on Wheels — популярная игра для Nintendo 64 / 64DD."),
                ("Rush 2: Extreme Racing USA", "Гонки со скрытыми монетами и трюковым парком Stunt Track", 1998, "Midway", "Midway", "WW", "Rush 2: Extreme Racing USA — популярная игра для Nintendo 64 / 64DD."),
                ("San Francisco Rush: Extreme Racing", "Аркадные гонки по трамплинам Сан-Франциско", 1997, "Midway", "Midway", "WW", "San Francisco Rush: Extreme Racing — популярная игра для Nintendo 64 / 64DD."),
                ("San Francisco Rush 2049", "Футуристические гонки с раскрывающимися крыльями и аренами", 2000, "Midway", "Midway", "WW", "San Francisco Rush 2049 — популярная игра для Nintendo 64 / 64DD."),
                ("SCARS", "Боевые гонки на автомобилях в форме диких зверей", 1998, "Ubisoft", "Ubisoft", "WW", "SCARS — популярная игра для Nintendo 64 / 64DD."),
                ("Shadow Man", "Вуду-боевик Майкла ЛеРуа в Царстве Мертвых", 1999, "Acclaim", "Acclaim", "WW", "Shadow Man — популярная игра для Nintendo 64 / 64DD."),
                ("Shadowgate 64: Trials of the Four Towers", "3D квест от первого лица в замке Шадоугейт", 1999, "Kemco", "Kemco", "WW", "Shadowgate 64: Trials of the Four Towers — популярная игра для Nintendo 64 / 64DD."),
                ("Shin Nihon Pro Wrestling: Toukon Road", "Рестлинг NJPW", 1997, "Hudson Soft", "Hudson Soft", "WW", "Shin Nihon Pro Wrestling: Toukon Road — популярная игра для Nintendo 64 / 64DD."),
                ("Sin and Punishment: Successor of the Earth", "Шедевр аркадного рельсового 3D-экшена от Treasure", 2000, "Nintendo", "Nintendo", "WW", "Sin and Punishment: Successor of the Earth — популярная игра для Nintendo 64 / 64DD."),
                ("Snowboard Kids", "Картинговый сноубординг со стрельбой сковородками и бомбами", 1997, "Atlus", "Atlus", "WW", "Snowboard Kids — популярная игра для Nintendo 64 / 64DD."),
                ("Snowboard Kids 2", "Вторая часть снежных гонок с новыми персонажами", 1999, "Atlus", "Atlus", "WW", "Snowboard Kids 2 — популярная игра для Nintendo 64 / 64DD."),
                ("South Park", "3D FPS по мультсериалу Южный Парк со снежками и коровами", 1998, "Acclaim", "Acclaim", "WW", "South Park — популярная игра для Nintendo 64 / 64DD."),
                ("South Park Rally", "Картинговые гонки Южного Парка", 2000, "Acclaim", "Acclaim", "WW", "South Park Rally — популярная игра для Nintendo 64 / 64DD."),
                ("South Park: Chef's Luv Shack", "Телевикторина Шефа", 1999, "Acclaim", "Acclaim", "WW", "South Park: Chef's Luv Shack — популярная игра для Nintendo 64 / 64DD."),
                ("Space Invaders", "3D ремейк космических захватчиков", 1999, "Activision", "Activision", "WW", "Space Invaders — популярная игра для Nintendo 64 / 64DD."),
                ("Space Station Silicon Valley", "Комедийный шедевр DMA Design о чипе Эво, вселяющемся в животных", 1998, "Take-Two", "Take-Two", "WW", "Space Station Silicon Valley — популярная игра для Nintendo 64 / 64DD."),
                ("Spider-Man", "3D экшен Человека-Паука со Стэном Ли от Neversoft", 2000, "Activision", "Activision", "WW", "Spider-Man — популярная игра для Nintendo 64 / 64DD."),
                ("Star Soldier: Vanishing Earth", "Вертикальный космический 3D SHMUP", 1998, "Hudson Soft", "Hudson Soft", "WW", "Star Soldier: Vanishing Earth — популярная игра для Nintendo 64 / 64DD."),
                ("Star Wars: Episode I Racer", "Гонки на подах со скоростью свыше 1000 км/ч от LucasArts", 1999, "Nintendo", "Nintendo", "WW", "Star Wars: Episode I Racer — популярная игра для Nintendo 64 / 64DD."),
                ("Star Wars: Rogue Squadron", "Легендарный космический симулятор X-Wing и Snowspeeder от Factor 5", 1998, "LucasArts", "LucasArts", "WW", "Star Wars: Rogue Squadron — популярная игра для Nintendo 64 / 64DD."),
                ("Star Wars: Shadows of the Empire", "Приключения Дэша Рендара в битве на Хоте и на джетпаке", 1996, "LucasArts / Nintendo", "LucasArts / Nintendo", "WW", "Star Wars: Shadows of the Empire — популярная игра для Nintendo 64 / 64DD."),
                ("Super Bowling", "3D Боулинг", 2000, "UFO", "UFO", "WW", "Super Bowling — популярная игра для Nintendo 64 / 64DD."),
                ("Super Robot Spirits", "3D файтинг гигантских роботов", 1998, "Banpresto", "Banpresto", "WW", "Super Robot Spirits — популярная игра для Nintendo 64 / 64DD."),
                ("Super Robot Taisen 64", "Тактическая RPG роботов с 3D-анимациями", 1999, "Banpresto", "Banpresto", "WW", "Super Robot Taisen 64 — популярная игра для Nintendo 64 / 64DD."),
                ("Tarzan", "3D платформер Тарзана от Disney", 1999, "Activision", "Activision", "WW", "Tarzan — популярная игра для Nintendo 64 / 64DD."),
                ("Tetris 64", "3D Тетрис с датчиком пульса Bio Sensor", 1998, "SETA", "SETA", "WW", "Tetris 64 — популярная игра для Nintendo 64 / 64DD."),
                ("Tetrisphere", "Головоломка со снятием блоков со сферического шара", 1997, "Nintendo", "Nintendo", "WW", "Tetrisphere — популярная игра для Nintendo 64 / 64DD."),
                ("Tom and Jerry in Fists of Furry", "Арена-файтинг Тома и Джерри", 2000, "Ubisoft", "Ubisoft", "WW", "Tom and Jerry in Fists of Furry — популярная игра для Nintendo 64 / 64DD."),
                ("Tonic Trouble", "Платформер уборщика Эда от Мишеля Анселя", 1999, "Ubisoft", "Ubisoft", "WW", "Tonic Trouble — популярная игра для Nintendo 64 / 64DD."),
                ("Tony Hawk's Pro Skater", "Скейтбординг Тони Хоука в 3D", 2000, "Activision", "Activision", "WW", "Tony Hawk's Pro Skater — популярная игра для Nintendo 64 / 64DD."),
                ("Tony Hawk's Pro Skater 2", "Скейтбординг Тони Хоука 2", 2001, "Activision", "Activision", "WW", "Tony Hawk's Pro Skater 2 — популярная игра для Nintendo 64 / 64DD."),
                ("Tony Hawk's Pro Skater 3", "Скейтбординг Тони Хоука 3", 2002, "Activision", "Activision", "WW", "Tony Hawk's Pro Skater 3 — популярная игра для Nintendo 64 / 64DD."),
                ("Top Gear Hyper-Bike", "Сверхскоростные мотогонки", 2000, "Kemco", "Kemco", "WW", "Top Gear Hyper-Bike — популярная игра для Nintendo 64 / 64DD."),
                ("Top Gear Overdrive", "3D автогонки под музыку Primus", 1998, "Kemco", "Kemco", "WW", "Top Gear Overdrive — популярная игра для Nintendo 64 / 64DD."),
                ("Top Gear Rally", "Ралли с динамической генерацией погоды", 1997, "Midway", "Midway", "WW", "Top Gear Rally — популярная игра для Nintendo 64 / 64DD."),
                ("Top Gear Rally 2", "Вторая часть ралли с повреждениями", 1999, "Kemco", "Kemco", "WW", "Top Gear Rally 2 — популярная игра для Nintendo 64 / 64DD."),
                ("Toy Story 2: Buzz Lightyear to the Rescue", "3D платформер Базза Лайтера", 1999, "Activision", "Activision", "WW", "Toy Story 2: Buzz Lightyear to the Rescue — популярная игра для Nintendo 64 / 64DD."),
                ("Turok: Dinosaur Hunter", "Революционный 3D FPS охотника на динозавров с луком и ядерной пушкой", 1997, "Acclaim", "Acclaim", "WW", "Turok: Dinosaur Hunter — популярная игра для Nintendo 64 / 64DD."),
                ("Turok 2: Seeds of Evil", "Грандиозный FPS с церебральным буром Cerebral Bore и Hi-Res режимом", 1998, "Acclaim", "Acclaim", "WW", "Turok 2: Seeds of Evil — популярная игра для Nintendo 64 / 64DD."),
                ("Turok 3: Shadow of Oblivion", "Кинематографичный финал трилогии Турока", 2000, "Acclaim", "Acclaim", "WW", "Turok 3: Shadow of Oblivion — популярная игра для Nintendo 64 / 64DD."),
                ("Turok: Rage Wars", "Арена-шутер для 4 игроков", 1999, "Acclaim", "Acclaim", "WW", "Turok: Rage Wars — популярная игра для Nintendo 64 / 64DD."),
                ("V-Rally Edition 99", "Раллийный чемпионат", 1999, "Infogrames", "Infogrames", "WW", "V-Rally Edition 99 — популярная игра для Nintendo 64 / 64DD."),
                ("Vigilante 8", "Боевые автогонки 70-х годов с лазерами и ракетами", 1999, "Activision", "Activision", "WW", "Vigilante 8 — популярная игра для Nintendo 64 / 64DD."),
                ("Vigilante 8: 2nd Offense", "Вторая часть битв автомобилей во времени", 2000, "Activision", "Activision", "WW", "Vigilante 8: 2nd Offense — популярная игра для Nintendo 64 / 64DD."),
                ("Virtual Chess 64", "3D шахматы с обучающим гроссмейстером", 1998, "Titus", "Titus", "WW", "Virtual Chess 64 — популярная игра для Nintendo 64 / 64DD."),
                ("Virtual Pool 64", "Физически точный симулятор бильярда", 1998, "Crave", "Crave", "WW", "Virtual Pool 64 — популярная игра для Nintendo 64 / 64DD."),
                ("War Gods", "3D файтинг богов от Midway", 1997, "Midway", "Midway", "WW", "War Gods — популярная игра для Nintendo 64 / 64DD."),
                ("Wayne Gretzky's 3D Hockey", "Аркадный 3D хоккей с горящими сетками ворот", 1996, "Midway", "Midway", "WW", "Wayne Gretzky's 3D Hockey — популярная игра для Nintendo 64 / 64DD."),
                ("Wayne Gretzky's 3D Hockey '98", "Вторая часть хоккея Уэйна Гретцки", 1997, "Midway", "Midway", "WW", "Wayne Gretzky's 3D Hockey '98 — популярная игра для Nintendo 64 / 64DD."),
                ("WCW Mayhem", "Рестлинг WCW с выходом за кулисы", 1999, "EA Sports", "EA Sports", "WW", "WCW Mayhem — популярная игра для Nintendo 64 / 64DD."),
                ("WCW Nitro", "Рестлинг WCW", 1999, "THQ", "THQ", "WW", "WCW Nitro — популярная игра для Nintendo 64 / 64DD."),
                ("WCW/nWo Revenge", "Величайший рестлинг на движке AKI: Голдберг, Стинг, Халк Хоган", 1998, "THQ", "THQ", "WW", "WCW/nWo Revenge — популярная игра для Nintendo 64 / 64DD."),
                ("Wetrix", "3D головоломка с удержанием воды дамбами от братьев Пикфорд", 1998, "Ocean", "Ocean", "WW", "Wetrix — популярная игра для Nintendo 64 / 64DD."),
                ("WinBack: Covert Operations", "Родоначальник механики укрытий от третьего лица", 1999, "Koei", "Koei", "WW", "WinBack: Covert Operations — популярная игра для Nintendo 64 / 64DD."),
                ("Wipeout 64", "Футуристические антигравитационные гонки с эксклюзивными трассами от Psygnosis", 1998, "Midway", "Midway", "WW", "Wipeout 64 — популярная игра для Nintendo 64 / 64DD."),
                ("World Cup 98", "Чемпионат Мира по футболу во Франции 98", 1998, "EA Sports", "EA Sports", "WW", "World Cup 98 — популярная игра для Nintendo 64 / 64DD."),
                ("World Driver Championship", "Выдающийся фотореалистичный автосимулятор от Boss Game Studios", 1999, "Midway", "Midway", "WW", "World Driver Championship — популярная игра для Nintendo 64 / 64DD."),
                ("Worms Armageddon", "3D Червячки со всеми видами вооружения", 2000, "Hasbro", "Hasbro", "WW", "Worms Armageddon — популярная игра для Nintendo 64 / 64DD."),
                ("WWF Attitude", "Рестлинг WWF", 1999, "Acclaim", "Acclaim", "WW", "WWF Attitude — популярная игра для Nintendo 64 / 64DD."),
                ("WWF No Mercy", "Абсолютный шедевр симуляторов рестлинга на движке AKI с сюжетным режимом", 2000, "THQ", "THQ", "WW", "WWF No Mercy — популярная игра для Nintendo 64 / 64DD."),
                ("WWF WrestleMania 2000", "Рестлинг WWF на движке AKI с созданием бойца", 1999, "THQ", "THQ", "WW", "WWF WrestleMania 2000 — популярная игра для Nintendo 64 / 64DD."),
                ("Xena: Warrior Princess - The Talisman of Fate", "3D файтинг Зены королевы воинов на 4 игроков", 1999, "Titus", "Titus", "WW", "Xena: Warrior Princess - The Talisman of Fate — популярная игра для Nintendo 64 / 64DD."),
                ("Yoshi's Story", "Пастельный платформер динозавриков Йоши с поеданием 30 фруктов на уровень", 1997, "Nintendo", "Nintendo", "WW", "Yoshi's Story — популярная игра для Nintendo 64 / 64DD."),
            };

            foreach (var g in games)
            {
                list.Add(new NintendoCatalogItem
                {
                    Title = g.Title,
                    Genre = g.Genre,
                    Year = g.Year,
                    Developer = g.Dev,
                    Publisher = g.Pub,
                    Region = g.Region,
                    Desc = g.Desc
                });
            }

            return list;
        }
    }
}
