using System;
using System.Collections.Generic;

namespace StormSwitchBox.Services
{
    public static class NdsCatalogData
    {
        public static List<NintendoCatalogItem> GetCatalog()
        {
            var list = new List<NintendoCatalogItem>(200);

            var games = new (string Title, string Genre, int Year, string Dev, string Pub, string Region, string Desc)[]
            {
                ("Pokemon HeartGold Version", "JRPG", 2009, "Game Freak", "Nintendo", "WW", "Шедевральный ремейк Джото и Канто с 16 значками, шагающими спутниками-покемонами и шагомером Pokewalker."),
                ("Pokemon SoulSilver Version", "JRPG", 2009, "Game Freak", "Nintendo", "WW", "Легендарная Лугия, Водоворотные острова и битвы в сафари-зоне."),
                ("Pokemon Platinum Version", "JRPG", 2008, "Game Freak", "Nintendo", "WW", "Ультимативная версия Синно с Искаженным Миром (Distortion World), Гиратиной и зоной Battle Frontier."),
                ("Pokemon Black Version", "JRPG", 2010, "Game Freak", "Nintendo", "WW", "Пятое поколение в регионе Юнова: Реширам, N и команда Плазма, динамические времена года."),
                ("Pokemon White Version", "JRPG", 2010, "Game Freak", "Nintendo", "WW", "Легендарный Зекром, Белый Лес (White Forest) и исключительно новые покемоны до финала."),
                ("Pokemon Black Version 2", "JRPG", 2012, "Game Freak", "Nintendo", "WW", "Прямой сиквел спустя 2 года: Черный Кюрем, Покевуд и турнир мировых лидеров PWT."),
                ("Pokemon White Version 2", "JRPG", 2012, "Game Freak", "Nintendo", "WW", "Белый Кюрем, дерево испытаний и колоссальный эндгейм-контент."),
                ("Pokemon Diamond Version", "JRPG", 2006, "Game Freak", "Nintendo", "WW", "Четвертое поколение: Диалга, разделение атак на физические/специальные и Wi-Fi сражения."),
                ("Pokemon Pearl Version", "JRPG", 2006, "Game Freak", "Nintendo", "WW", "Палкия, подземные шахты Подземелья Синно и супер-состязания."),
                ("New Super Mario Bros.", "2D Платформер", 2006, "Nintendo EAD", "Nintendo", "WW", "Возрождение 2D-Марио с мега-грибом, синим панцирем коопы и мультиплеером Марио против Луиджи."),
                ("Mario Kart DS", "Картинговые гонки", 2005, "Nintendo EAD", "Nintendo", "WW", "Первый глобальный онлайн Mario Kart по Wi-Fi, режим испытаний Mission Mode и редактор эмблем."),
                ("The Legend of Zelda: Phantom Hourglass", "Action-Adventure", 2007, "Nintendo EAD", "Nintendo", "WW", "Морские приключения Линка со стилусным управлением и Храмом Океанского Короля."),
                ("The Legend of Zelda: Spirit Tracks", "Action-Adventure", 2009, "Nintendo EAD", "Nintendo", "WW", "Линк управляет паровозом и решает головоломки вместе с призраком принцессы Зельды в броне фантома."),
                ("Chrono Trigger DS", "JRPG", 2008, "Square Enix", "Square Enix", "WW", "Идеальное переиздание шедевра с новым переводом, ареной монстров и подземельем Святилище Забытых."),
                ("The World Ends with You (Subarashiki Kono Sekai)", "Action-RPG", 2007, "Jupiter / Square Enix", "Square Enix", "WW", "Нэку Сакураба в Сибуе: битва значками на двух экранах одновременно под современный саундтрек."),
                ("Castlevania: Dawn of Sorrow", "Метроидвания", 2005, "Konami", "Konami", "WW", "Сома Крус в секте Селии с синтезом оружия из душ и начертанием магических печатей стилусом."),
                ("Castlevania: Portrait of Ruin", "Метроидвания", 2006, "Konami", "Konami", "WW", "Джонатан Моррис и волшебница Шарлотта Олин исследуют заколдованные картины замка Дракулы."),
                ("Castlevania: Order of Ecclesia", "Метроидвания", 2008, "Konami", "Konami", "WW", "Шаноа поглощает глифы врагов, сражаясь клинками и магией против Альбуса и Дракулы."),
                ("Mario & Luigi: Bowser's Inside Story", "JRPG / Комедия", 2009, "AlphaDream", "Nintendo", "WW", "Шедевр серии: братья исследуют внутренности гигантского Боузера, а игрок командует самим Боузером."),
                ("Mario & Luigi: Partners in Time", "JRPG / Комедия", 2005, "AlphaDream", "Nintendo", "WW", "Путешествие во времени: взрослые Марио и Луиджи объединяются с малышами Baby Mario и Baby Luigi против пришельцев Шробов."),
                ("Phoenix Wright: Ace Attorney", "Судебный визуальный роман", 2005, "Capcom", "Capcom", "WW", "Адвокат Феникс Райт защищает клиентов криком «OBJECTION!» в микрофон и поиском улик стилусом."),
                ("Phoenix Wright: Ace Attorney - Justice for All", "Судебный роман", 2006, "Capcom", "Capcom", "WW", "Появление прокурора Франциски фон Кармы и волшебного замка души Magatama."),
                ("Phoenix Wright: Ace Attorney - Trials and Tribulations", "Судебный роман", 2007, "Capcom", "Capcom", "WW", "Культовый финал оригинальной трилогии с прокурором Годо и тайнами семьи Фей."),
                ("Apollo Justice: Ace Attorney", "Судебный детектив", 2007, "Capcom", "Capcom", "WW", "Молодой адвокат Аполло Джастис с браслетом поиска тиков лжи свидетелей."),
                ("Professor Layton and the Curious Village", "Головоломка / Детектив", 2007, "Level-5", "Nintendo", "WW", "Профессор Лейтон и Люк разгадывают тайны деревни Мистралери и золотого яблока."),
                ("Professor Layton and the Diabolical Box (Pandora's Box)", "Головоломка", 2007, "Level-5", "Nintendo", "WW", "Поездка на экспрессе Молентри и тайна ящика Пандоры."),
                ("Professor Layton and the Unwound Future (Lost Future)", "Головоломка", 2008, "Level-5", "Nintendo", "WW", "Эмоциональный шедевр о путешествии в будущее Лондона и прощании с прошлым."),
                ("Ghost Trick: Phantom Detective", "Головоломка / Мистика", 2010, "Capcom", "Capcom", "WW", "Шедевр Сю Такуми: призрак Сиссель вселяется в предметы и манипулирует временем за 4 минуты до смерти жертвы."),
                ("Radiant Historia", "JRPG", 2010, "Atlus", "Atlus", "WW", "Шпион Сток перемещается между двумя параллельными временными линиями Белой Хроники."),
                ("Dragon Quest IX: Sentinels of the Starry Skies", "JRPG", 2009, "Level-5", "Square Enix / Nintendo", "WW", "Ангел-хранитель Селестианин с созданием своего отряда, картами сокровищ и миллионами игроков по Tag Mode."),
                ("999: Nine Hours, Nine Persons, Nine Doors", "Визуальная новелла / Побег из комнаты", 2009, "Chunsoft / Aksys", "Chunsoft / Aksys", "WW", "999: Nine Hours, Nine Persons, Nine Doors — популярная игра для Nintendo DS / DSi."),
                ("Advance Wars: Dual Strike", "Пошаговая тактика на двух экранах с двойными силами Super CO", 2005, "Nintendo", "Nintendo", "WW", "Advance Wars: Dual Strike — популярная игра для Nintendo DS / DSi."),
                ("Advance Wars: Days of Ruin (Dark Conflict)", "Мрачная постапокалиптическая тактика Уилла", 2008, "Nintendo", "Nintendo", "WW", "Advance Wars: Days of Ruin (Dark Conflict) — популярная игра для Nintendo DS / DSi."),
                ("Animal Crossing: Wild World", "Симулятор жизни с онлайн-поездками в чужие города по Wi-Fi", 2005, "Nintendo", "Nintendo", "WW", "Animal Crossing: Wild World — популярная игра для Nintendo DS / DSi."),
                ("Bangai-O Spirits", "Меха-шутер с сотнями ракет от Treasure", 2008, "D3 Publisher", "D3 Publisher", "WW", "Bangai-O Spirits — популярная игра для Nintendo DS / DSi."),
                ("Big Brain Academy", "Интеллектуальные тренировки мозга", 2005, "Nintendo", "Nintendo", "WW", "Big Brain Academy — популярная игра для Nintendo DS / DSi."),
                ("Bleach: The Blade of Fate", "Ураганный 2D файтинг на 4 игроков от Treasure", 2006, "Sega", "Sega", "WW", "Bleach: The Blade of Fate — популярная игра для Nintendo DS / DSi."),
                ("Bleach: Dark Souls", "Вторая часть файтинга от Treasure", 2007, "Sega", "Sega", "WW", "Bleach: Dark Souls — популярная игра для Nintendo DS / DSi."),
                ("Brain Age: Train Your Brain in Minutes a Day!", "Тренировка мозга доктора Рюты Кавасимы", 2005, "Nintendo", "Nintendo", "WW", "Brain Age: Train Your Brain in Minutes a Day! — популярная игра для Nintendo DS / DSi."),
                ("Brain Age 2: More Training in Minutes a Day!", "Вторая часть тренировок с судоку и пианино", 2005, "Nintendo", "Nintendo", "WW", "Brain Age 2: More Training in Minutes a Day! — популярная игра для Nintendo DS / DSi."),
                ("Clubhouse Games (42 All-Time Classics)", "Сборник 42 классических настольных и карточных игр", 2006, "Nintendo", "Nintendo", "WW", "Clubhouse Games (42 All-Time Classics) — популярная игра для Nintendo DS / DSi."),
                ("Contra 4", "Хардкорный юбилейный Run and Gun от WayForward на двух экранах", 2007, "Konami", "Konami", "WW", "Contra 4 — популярная игра для Nintendo DS / DSi."),
                ("Cooking Mama", "Кулинарные рецепты стилусом", 2006, "Majesco", "Majesco", "WW", "Cooking Mama — популярная игра для Nintendo DS / DSi."),
                ("Cooking Mama 2: Dinner with Friends", "Кулинарные соревнования с друзьями", 2007, "Majesco", "Majesco", "WW", "Cooking Mama 2: Dinner with Friends — популярная игра для Nintendo DS / DSi."),
                ("Diddy Kong Racing DS", "Ремейк гонок с редактором трасс и микрофоном", 2007, "Nintendo", "Nintendo", "WW", "Diddy Kong Racing DS — популярная игра для Nintendo DS / DSi."),
                ("Disgaea DS", "Тактическая RPG принца Лахарла с прокачкой до 9999 уровня", 2008, "NIS America", "NIS America", "WW", "Disgaea DS — популярная игра для Nintendo DS / DSi."),
                ("Donkey Kong: Jungle Climber", "Платформер лазания Конга с триггерами L/R", 2007, "Nintendo", "Nintendo", "WW", "Donkey Kong: Jungle Climber — популярная игра для Nintendo DS / DSi."),
                ("Dragon Quest IV: Chapters of the Chosen", "Ремейк DQ4 с 5 главами персонажей", 2007, "Square Enix", "Square Enix", "WW", "Dragon Quest IV: Chapters of the Chosen — популярная игра для Nintendo DS / DSi."),
                ("Dragon Quest V: Hand of the Heavenly Bride", "Ремейк DQ5 с появлением невесты Деборы", 2008, "Square Enix", "Square Enix", "WW", "Dragon Quest V: Hand of the Heavenly Bride — популярная игра для Nintendo DS / DSi."),
                ("Dragon Quest VI: Realms of Revelation", "Ремейк DQ6 с профессиями", 2010, "Square Enix", "Square Enix", "WW", "Dragon Quest VI: Realms of Revelation — популярная игра для Nintendo DS / DSi."),
                ("Dragon Quest Monsters: Joker", "3D ловля и скрещивание монстров DQ", 2006, "Square Enix", "Square Enix", "WW", "Dragon Quest Monsters: Joker — популярная игра для Nintendo DS / DSi."),
                ("Dragon Quest Monsters: Joker 2", "Вторая часть с гигантскими монстрами", 2010, "Square Enix", "Square Enix", "WW", "Dragon Quest Monsters: Joker 2 — популярная игра для Nintendo DS / DSi."),
                ("Dragon Quest Heroes: Rocket Slime", "Приключения слизняка Рокета с танковыми дуэлями", 2005, "Square Enix", "Square Enix", "WW", "Dragon Quest Heroes: Rocket Slime — популярная игра для Nintendo DS / DSi."),
                ("Elite Beat Agents", "Культовая ритм-игра агентов поддержки в костюмах", 2006, "Nintendo", "Nintendo", "WW", "Elite Beat Agents — популярная игра для Nintendo DS / DSi."),
                ("Etrian Odyssey", "Хардкорный данжен-кроулер с черчением карты подземелья стилусом", 2007, "Atlus", "Atlus", "WW", "Etrian Odyssey — популярная игра для Nintendo DS / DSi."),
                ("Etrian Odyssey II: Heroes of Lagaard", "Вторая часть черчения карт Иггдрасиля", 2008, "Atlus", "Atlus", "WW", "Etrian Odyssey II: Heroes of Lagaard — популярная игра для Nintendo DS / DSi."),
                ("Etrian Odyssey III: The Drowned City", "Третья часть с морскими плаваниями", 2010, "Atlus", "Atlus", "WW", "Etrian Odyssey III: The Drowned City — популярная игра для Nintendo DS / DSi."),
                ("Final Fantasy III", "Первый в мире 3D-ремейк FF3 с системой профессий", 2006, "Square Enix", "Square Enix", "WW", "Final Fantasy III — популярная игра для Nintendo DS / DSi."),
                ("Final Fantasy IV", "Полный 3D-ремейк FF4 с озвучкой и системой Augments", 2007, "Square Enix", "Square Enix", "WW", "Final Fantasy IV — популярная игра для Nintendo DS / DSi."),
                ("Final Fantasy XII: Revenant Wings", "Стратегическая RTS в реальном времени Ваана и Пенело в небесном Лемуресе", 2007, "Square Enix", "Square Enix", "WW", "Final Fantasy XII: Revenant Wings — популярная игра для Nintendo DS / DSi."),
                ("Final Fantasy Tactics A2: Grimoire of the Rift", "Тактическая RPG Лусо в Ивалисе", 2007, "Square Enix", "Square Enix", "WW", "Final Fantasy Tactics A2: Grimoire of the Rift — популярная игра для Nintendo DS / DSi."),
                ("Final Fantasy: The 4 Heroes of Light", "Классическая JRPG с системой шляп-профессий от авторов Bravely", 2009, "Square Enix", "Square Enix", "WW", "Final Fantasy: The 4 Heroes of Light — популярная игра для Nintendo DS / DSi."),
                ("Fire Emblem: Shadow Dragon", "Ремейк оригинальной Fire Emblem Марса с онлайн-битвами", 2008, "Nintendo", "Nintendo", "WW", "Fire Emblem: Shadow Dragon — популярная игра для Nintendo DS / DSi."),
                ("Fire Emblem: New Mystery of the Emblem", "Ремейк FE3 с созданием своего аватара Криса", 2010, "Nintendo", "Nintendo", "WW", "Fire Emblem: New Mystery of the Emblem — популярная игра для Nintendo DS / DSi."),
                ("Fossil Fighters", "Раскопки окаменелостей динозавров стилусом и битвы вивозавров", 2008, "Nintendo", "Nintendo", "WW", "Fossil Fighters — популярная игра для Nintendo DS / DSi."),
                ("Fossil Fighters: Champions", "Вторая часть раскопок динозавров", 2010, "Nintendo", "Nintendo", "WW", "Fossil Fighters: Champions — популярная игра для Nintendo DS / DSi."),
                ("Freshly-Picked Tingle's Rosy Rupeeland", "RPG алчного эльфа Тингла с торговлей и рупиями", 2006, "Nintendo", "Nintendo", "WW", "Freshly-Picked Tingle's Rosy Rupeeland — популярная игра для Nintendo DS / DSi."),
                ("Grand Theft Auto: Chinatown Wars", "GTA в Либерти-Сити с наркоторговлей, сборкой коктейлей Молотова и взломом авто стилусом", 2009, "Rockstar Games", "Rockstar Games", "WW", "Grand Theft Auto: Chinatown Wars — популярная игра для Nintendo DS / DSi."),
                ("Henry Hatsworth in the Puzzling Adventure", "Платформер джентльмена плюс головоломка со снятием блоков на нижнем экране", 2009, "EA", "EA", "WW", "Henry Hatsworth in the Puzzling Adventure — популярная игра для Nintendo DS / DSi."),
                ("Hotel Dusk: Room 215", "Интерактивный нуарный детектив Кайла Хайда в отеле с поворотом консоли как книги", 2007, "Nintendo", "Nintendo", "WW", "Hotel Dusk: Room 215 — популярная игра для Nintendo DS / DSi."),
                ("Last Window: The Secret of Cape West", "Продолжение расследований Кайла Хайда", 2010, "Nintendo", "Nintendo", "WW", "Last Window: The Secret of Cape West — популярная игра для Nintendo DS / DSi."),
                ("Infinite Space", "Грандиозная Sci-Fi космическая RPG Юрия с кастомизацией флотилий от PlatinumGames", 2009, "Sega", "Sega", "WW", "Infinite Space — популярная игра для Nintendo DS / DSi."),
                ("Jump Ultimate Stars", "Файтинг-кроссовер Shonen Jump (Dragon Ball, Naruto, One Piece, Bleach, Death Note)", 2006, "Nintendo", "Nintendo", "WW", "Jump Ultimate Stars — популярная игра для Nintendo DS / DSi."),
                ("Kingdom Hearts 358/2 Days", "История Роксаса, Акселя и Шион в Организации XIII", 2009, "Square Enix", "Square Enix", "WW", "Kingdom Hearts 358/2 Days — популярная игра для Nintendo DS / DSi."),
                ("Kingdom Hearts Re:coded", "Приключения цифрового Соры в журнале Джимини", 2010, "Square Enix", "Square Enix", "WW", "Kingdom Hearts Re:coded — популярная игра для Nintendo DS / DSi."),
                ("Kirby Super Star Ultra", "Ремейк со всеми режимами, плюс Месть Короля Дидиди и Истинная Арена", 2008, "Nintendo", "Nintendo", "WW", "Kirby Super Star Ultra — популярная игра для Nintendo DS / DSi."),
                ("Kirby: Canvas Curse", "Рисование радужных линий стилусом для катящегося Кирби", 2005, "Nintendo", "Nintendo", "WW", "Kirby: Canvas Curse — популярная игра для Nintendo DS / DSi."),
                ("Kirby: Squeak Squad (Mouse Attack)", "Кирби спасает свой торт от банды мышей-воров Сквиков", 2006, "Nintendo", "Nintendo", "WW", "Kirby: Squeak Squad (Mouse Attack) — популярная игра для Nintendo DS / DSi."),
                ("Kirby: Mass Attack", "Управление армией из 10 маленьких Кирби стилусом", 2011, "Nintendo", "Nintendo", "WW", "Kirby: Mass Attack — популярная игра для Nintendo DS / DSi."),
                ("Knights in the Nightmare", "Уникальный гибрид Bullet Hell шутера и тактической RPG от Sting", 2009, "Atlus", "Atlus", "WW", "Knights in the Nightmare — популярная игра для Nintendo DS / DSi."),
                ("Legendary Starfy, The", "Подводный платформер морской звездочки Старфи", 2008, "Nintendo", "Nintendo", "WW", "Legendary Starfy, The — популярная игра для Nintendo DS / DSi."),
                ("Lock's Quest", "Tower Defense с постройкой крепостных стен от 5TH Cell", 2008, "THQ", "THQ", "WW", "Lock's Quest — популярная игра для Nintendo DS / DSi."),
                ("Luminous Arc", "Тактическая RPG о ведьмах от Imageepoch", 2007, "Atlus", "Atlus", "WW", "Luminous Arc — популярная игра для Nintendo DS / DSi."),
                ("Luminous Arc 2", "Вторая часть тактики ведьм", 2008, "Atlus", "Atlus", "WW", "Luminous Arc 2 — популярная игра для Nintendo DS / DSi."),
                ("Mario & Sonic at the Olympic Games", "Олимпийские игры в Пекине 2008", 2007, "Sega", "Sega", "WW", "Mario & Sonic at the Olympic Games — популярная игра для Nintendo DS / DSi."),
                ("Mario & Sonic at the Olympic Winter Games", "Зимние Олимпийские игры в Ванкувере 2010", 2009, "Sega", "Sega", "WW", "Mario & Sonic at the Olympic Winter Games — популярная игра для Nintendo DS / DSi."),
                ("Mario Party DS", "Уменьшенные в размерах герои в настольной игре с микрофоном", 2007, "Nintendo", "Nintendo", "WW", "Mario Party DS — популярная игра для Nintendo DS / DSi."),
                ("Mario vs. Donkey Kong 2: March of the Minis", "Управление армией заводных Мини-Марио стилусом", 2006, "Nintendo", "Nintendo", "WW", "Mario vs. Donkey Kong 2: March of the Minis — популярная игра для Nintendo DS / DSi."),
                ("Mario vs. Donkey Kong: Mini-Land Mayhem!", "Строительство мостов и батутов в парке аттракционов", 2010, "Nintendo", "Nintendo", "WW", "Mario vs. Donkey Kong: Mini-Land Mayhem! — популярная игра для Nintendo DS / DSi."),
                ("Mega Man Battle Network 5: Double Team DS", "Сборник обеих версий с поддержкой озвучки", 2005, "Capcom", "Capcom", "WW", "Mega Man Battle Network 5: Double Team DS — популярная игра для Nintendo DS / DSi."),
                ("Mega Man Star Force: Dragon / Pegasus / Leo", "Action-RPG Гео Стельяра и пришельца Омега-Ксис", 2006, "Capcom", "Capcom", "WW", "Mega Man Star Force: Dragon / Pegasus / Leo — популярная игра для Nintendo DS / DSi."),
                ("Mega Man Star Force 2: Zerker x Saurian / Zerker x Ninja", "Трансформации племен", 2007, "Capcom", "Capcom", "WW", "Mega Man Star Force 2: Zerker x Saurian / Zerker x Ninja — популярная игра для Nintendo DS / DSi."),
                ("Mega Man Star Force 3: Black Ace / Red Joker", "Финальная битва с шумовыми формами", 2008, "Capcom", "Capcom", "WW", "Mega Man Star Force 3: Black Ace / Red Joker — популярная игра для Nintendo DS / DSi."),
                ("Mega Man Zero/ZX Legacy Collection (ZX / ZX Advent)", "Метроидвании с биометаллами моделей X, Z, F, H, P, L", 2006, "Capcom", "Capcom", "WW", "Mega Man Zero/ZX Legacy Collection (ZX / ZX Advent) — популярная игра для Nintendo DS / DSi."),
                ("Meteos", "Вертикальная головоломка запуска метеоритов от Тэцуи Мидзугути", 2005, "Nintendo", "Nintendo", "WW", "Meteos — популярная игра для Nintendo DS / DSi."),
                ("Metroid Prime Pinball", "Пинбол в мире Metroid со встроенным картриджем Rumble Pak", 2005, "Nintendo", "Nintendo", "WW", "Metroid Prime Pinball — популярная игра для Nintendo DS / DSi."),
                ("Metroid Prime Hunters", "3D FPS с управлением стилусом и онлайном на 7 охотников за головами", 2006, "Nintendo", "Nintendo", "WW", "Metroid Prime Hunters — популярная игра для Nintendo DS / DSi."),
                ("Might & Magic: Clash of Heroes", "Шедевр тактических ролевых головоломок от Capybara Games", 2009, "Ubisoft", "Ubisoft", "WW", "Might & Magic: Clash of Heroes — популярная игра для Nintendo DS / DSi."),
                ("Monster Tale", "Платформер девочки Элли с выращиванием монстра на нижнем экране", 2011, "Majesco", "Majesco", "WW", "Monster Tale — популярная игра для Nintendo DS / DSi."),
                ("Nintendogs: Labrador & Friends / Chihuahua / Dachshund", "Феноменальный симулятор щенков с распознаванием голоса и свистом", 2005, "Nintendo", "Nintendo", "WW", "Nintendogs: Labrador & Friends / Chihuahua / Dachshund — популярная игра для Nintendo DS / DSi."),
                ("Nostalgia", "Стимпанк JRPG с полетами на дирижаблях по альтернативной Земле XIX века", 2009, "Ignition", "Ignition", "WW", "Nostalgia — популярная игра для Nintendo DS / DSi."),
                ("Okamiden", "Приключения маленького волчонка Чибитерасу с рисованием кистью стилусом", 2010, "Capcom", "Capcom", "WW", "Okamiden — популярная игра для Nintendo DS / DSi."),
                ("Osu! Tatakae! Ouendan", "Легендарная японская ритм-игра группы поддержки Оуэндан", 2005, "Nintendo", "Nintendo", "WW", "Osu! Tatakae! Ouendan — популярная игра для Nintendo DS / DSi."),
                ("Moero! Nekketsu Rhythm Damashii: Ouendan 2", "Вторая часть безумных танцев поддержки", 2007, "Nintendo", "Nintendo", "WW", "Moero! Nekketsu Rhythm Damashii: Ouendan 2 — популярная игра для Nintendo DS / DSi."),
                ("Peggle Dual Shot", "Аркадный шариковый хит от PopCap", 2009, "PopCap", "PopCap", "WW", "Peggle Dual Shot — популярная игра для Nintendo DS / DSi."),
                ("Phantasy Star Zero", "Кооперативная онлайн Action-RPG на 4 игроков", 2008, "Sega", "Sega", "WW", "Phantasy Star Zero — популярная игра для Nintendo DS / DSi."),
                ("Picross DS", "Японские кроссворды с сотнями уровней и онлайном", 2007, "Nintendo", "Nintendo", "WW", "Picross DS — популярная игра для Nintendo DS / DSi."),
                ("Picross 3D", "Трехмерные объемные японские кроссворды", 2009, "Nintendo", "Nintendo", "WW", "Picross 3D — популярная игра для Nintendo DS / DSi."),
                ("Plants vs. Zombies", "Культовая Tower Defense растений против зомби", 2011, "PopCap", "PopCap", "WW", "Plants vs. Zombies — популярная игра для Nintendo DS / DSi."),
                ("Pokemon Conquest (Pokemon + Nobunaga's Ambition)", "Тактическая RPG военачальников Японии с покемонами", 2012, "Nintendo", "Nintendo", "WW", "Pokemon Conquest (Pokemon + Nobunaga's Ambition) — популярная игра для Nintendo DS / DSi."),
                ("Pokemon Mystery Dungeon: Explorers of Sky", "Ультимативный сюжетный шедевр команды исследователей покемонов", 2009, "Nintendo", "Nintendo", "WW", "Pokemon Mystery Dungeon: Explorers of Sky — популярная игра для Nintendo DS / DSi."),
                ("Pokemon Mystery Dungeon: Explorers of Time / Darkness", "Исследования подземелий", 2007, "Nintendo", "Nintendo", "WW", "Pokemon Mystery Dungeon: Explorers of Time / Darkness — популярная игра для Nintendo DS / DSi."),
                ("Pokemon Ranger", "Поимка диких покемонов закручиванием кругов стилусом стилизатором Capture Styler", 2006, "Nintendo", "Nintendo", "WW", "Pokemon Ranger — популярная игра для Nintendo DS / DSi."),
                ("Pokemon Ranger: Shadows of Almia", "Вторая часть рейнджеров с академией и новыми напарниками", 2008, "Nintendo", "Nintendo", "WW", "Pokemon Ranger: Shadows of Almia — популярная игра для Nintendo DS / DSi."),
                ("Pokemon Ranger: Guardian Signs", "Рейнджеры призывают легендарных покемонов символами", 2010, "Nintendo", "Nintendo", "WW", "Pokemon Ranger: Guardian Signs — популярная игра для Nintendo DS / DSi."),
                ("Professor Layton and the Last Specter (Spectre's Call)", "Приквел о первой встрече Лейтона и Люка", 2009, "Nintendo", "Nintendo", "WW", "Professor Layton and the Last Specter (Spectre's Call) — популярная игра для Nintendo DS / DSi."),
                ("Puyo Pop Fever", "Головоломка Puyo Puyo", 2005, "Sega", "Sega", "WW", "Puyo Pop Fever — популярная игра для Nintendo DS / DSi."),
                ("Puzzle Quest: Challenge of the Warlords", "Ролевая головоломка «три в ряд»", 2007, "D3 Publisher", "D3 Publisher", "WW", "Puzzle Quest: Challenge of the Warlords — популярная игра для Nintendo DS / DSi."),
                ("Retro Game Challenge", "Приключения в ретро-играх 80-х по шоу GameCenter CX", 2008, "XSEED", "XSEED", "WW", "Retro Game Challenge — популярная игра для Nintendo DS / DSi."),
                ("Rhythm Heaven (Rhythm Paradise)", "Гениальная ритм-игра с щелчками и слайдами стилуса", 2008, "Nintendo", "Nintendo", "WW", "Rhythm Heaven (Rhythm Paradise) — популярная игра для Nintendo DS / DSi."),
                ("Rune Factory: A Fantasy Harvest Moon", "Симулятор фермы с фэнтези-подземельями и мечами", 2006, "Natsume", "Natsume", "WW", "Rune Factory: A Fantasy Harvest Moon — популярная игра для Nintendo DS / DSi."),
                ("Rune Factory 2: A Fantasy Harvest Moon", "Вторая часть со сменой поколений на детей", 2008, "Natsume", "Natsume", "WW", "Rune Factory 2: A Fantasy Harvest Moon — популярная игра для Nintendo DS / DSi."),
                ("Rune Factory 3: A Fantasy Harvest Moon", "Превращение протагониста Майса в золотого пушистого монстра Wooly", 2009, "Natsume", "Natsume", "WW", "Rune Factory 3: A Fantasy Harvest Moon — популярная игра для Nintendo DS / DSi."),
                ("Scribblenauts", "Магический блокнот Максвелла: напиши любое слово — и предмет появится в игре!", 2009, "Warner Bros.", "Warner Bros.", "WW", "Scribblenauts — популярная игра для Nintendo DS / DSi."),
                ("Super Scribblenauts", "Вторая часть со свободным добавлением любых прилагательных (напр., «летающий зомби-бегемот»)", 2010, "Warner Bros.", "Warner Bros.", "WW", "Super Scribblenauts — популярная игра для Nintendo DS / DSi."),
                ("Shin Megami Tensei: Devil Survivor", "Тактическая JRPG выживания в блокированном демонами Токио за 7 дней", 2009, "Atlus", "Atlus", "WW", "Shin Megami Tensei: Devil Survivor — популярная игра для Nintendo DS / DSi."),
                ("Shin Megami Tensei: Devil Survivor 2", "Вторая часть с вторжением Септентрионов и социальными связями Fate", 2011, "Atlus", "Atlus", "WW", "Shin Megami Tensei: Devil Survivor 2 — популярная игра для Nintendo DS / DSi."),
                ("Shin Megami Tensei: Strange Journey", "Исследование аномалии Шварцвельт в Антарктиде в костюмах Demonica", 2009, "Atlus", "Atlus", "WW", "Shin Megami Tensei: Strange Journey — популярная игра для Nintendo DS / DSi."),
                ("Solatorobo: Red the Hunter", "Стимпанк Action-RPG пса-наемника Реда Савари на роботе DAHAK от CyberConnect2", 2010, "Bandai Namco", "Bandai Namco", "WW", "Solatorobo: Red the Hunter — популярная игра для Nintendo DS / DSi."),
                ("Sonic Chronicles: The Dark Brotherhood", "Пошаговая RPG Соника от студии BioWare с управлением стилусом", 2008, "Sega", "Sega", "WW", "Sonic Chronicles: The Dark Brotherhood — популярная игра для Nintendo DS / DSi."),
                ("Sonic Colors DS", "Двумерный скоростной платформер Соника с виспами от Dimps", 2010, "Sega", "Sega", "WW", "Sonic Colors DS — популярная игра для Nintendo DS / DSi."),
                ("Sonic Rush", "Появление кошки Блейз, шкала ускорения Boost и музыка Хидеки Наганумы", 2005, "Sega", "Sega", "WW", "Sonic Rush — популярная игра для Nintendo DS / DSi."),
                ("Sonic Rush Adventure", "Морские плавания на гидроциклах и кораблях между островами", 2007, "Sega", "Sega", "WW", "Sonic Rush Adventure — популярная игра для Nintendo DS / DSi."),
                ("Super Mario 64 DS", "Расширенный ремейк с 150 звездами и 4 героями: Йоши, Марио, Луиджи и Варио", 2004, "Nintendo", "Nintendo", "WW", "Super Mario 64 DS — популярная игра для Nintendo DS / DSi."),
                ("Super Princess Peach", "Принцесса Пич с зонтиком Перри спасает братьев Марио с помощью 4 эмоций (Радость, Гнев, Грусть, Спокойствие)", 2005, "Nintendo", "Nintendo", "WW", "Super Princess Peach — популярная игра для Nintendo DS / DSi."),
                ("Super Robot Taisen OG Saga: Endless Frontier", "Взрослая Action-RPG Хакена Браунинга с комбо-жонглированием от Monolith Soft", 2008, "Atlus", "Atlus", "WW", "Super Robot Taisen OG Saga: Endless Frontier — популярная игра для Nintendo DS / DSi."),
                ("Tetris DS", "Тетрис в оформлении 8-битных хитов Nintendo (Mario, Zelda, Metroid, Donkey Kong)", 2006, "Nintendo", "Nintendo", "WW", "Tetris DS — популярная игра для Nintendo DS / DSi."),
                ("Time Hollow", "Приключения Итана Кая с ручкой Hollow Pen, открывающей порталы в прошлое", 2008, "Konami", "Konami", "WW", "Time Hollow — популярная игра для Nintendo DS / DSi."),
                ("Tony Hawk's American Sk8land", "Сел-шейдинг скейтбординг от Vicarious Visions с онлайном", 2005, "Activision", "Activision", "WW", "Tony Hawk's American Sk8land — популярная игра для Nintendo DS / DSi."),
                ("Touch Detective", "Детективные расследования Маккензи и грибочка Фунги", 2006, "Atlus", "Atlus", "WW", "Touch Detective — популярная игра для Nintendo DS / DSi."),
                ("Trauma Center: Under the Knife", "Хирургический симулятор доктора Дерека Стайлза с целительной рукой стилусом", 2005, "Atlus", "Atlus", "WW", "Trauma Center: Under the Knife — популярная игра для Nintendo DS / DSi."),
                ("Trauma Center: Under the Knife 2", "Вторая часть хирургических операций против вируса GUILT", 2008, "Atlus", "Atlus", "WW", "Trauma Center: Under the Knife 2 — популярная игра для Nintendo DS / DSi."),
                ("Valkyrie Profile: Covenant of the Plume", "Мрачная тактическая RPG Уилфреда с пером Валькирии", 2008, "Square Enix", "Square Enix", "WW", "Valkyrie Profile: Covenant of the Plume — популярная игра для Nintendo DS / DSi."),
                ("Viewtiful Joe: Double Trouble!", "Джо на двух экранах со сменой кадров", 2005, "Capcom", "Capcom", "WW", "Viewtiful Joe: Double Trouble! — популярная игра для Nintendo DS / DSi."),
                ("WarioWare: Touched!", "Безумные микро-игры исключительно под сенсорный экран и микрофон", 2004, "Nintendo", "Nintendo", "WW", "WarioWare: Touched! — популярная игра для Nintendo DS / DSi."),
                ("WarioWare: D.I.Y.", "Создание собственных игр, музыки и комиксов с нуля", 2009, "Nintendo", "Nintendo", "WW", "WarioWare: D.I.Y. — популярная игра для Nintendo DS / DSi."),
                ("Warioland: Shake It! (Promo)", "Варио", 2008, "Nintendo", "Nintendo", "WW", "Warioland: Shake It! (Promo) — популярная игра для Nintendo DS / DSi."),
                ("Yoshi's Island DS", "Остров Йоши с малышами Марио, Донки Конгом, Пич, Варио и Боузером", 2006, "Nintendo", "Nintendo", "WW", "Yoshi's Island DS — популярная игра для Nintendo DS / DSi."),
                ("Yoshi Touch & Go", "Рисование облаков для парящего малыша Марио", 2005, "Nintendo", "Nintendo", "WW", "Yoshi Touch & Go — популярная игра для Nintendo DS / DSi."),
                ("Yu-Gi-Oh! 5D's World Championship 2011: Over the Nexus", "Турнирные карточные дуэли на турбо-дуэлях", 2011, "Konami", "Konami", "WW", "Yu-Gi-Oh! 5D's World Championship 2011: Over the Nexus — популярная игра для Nintendo DS / DSi."),
            };

            foreach (var g in games)
            {
                list.Add(new NintendoCatalogItem
                {
                    Title = g.Title,
                    Genre = g.Genre,
                    Year = g.Year,
                    Developer = g.Dev,
                    Publisher = g.Pub,
                    Region = g.Region,
                    Desc = g.Desc
                });
            }

            return list;
        }
    }
}
