using System;
using System.Collections.Generic;

namespace StormSwitchBox.Services
{
    public static class SnesCatalogData
    {
        public static List<NintendoCatalogItem> GetCatalog()
        {
            var list = new List<NintendoCatalogItem>(249);

            var games = new (string Title, string Genre, int Year, string Dev, string Pub, string Region, string Desc)[]
            {
                ("Super Mario World", "2D Платформер", 1990, "Nintendo EAD", "Nintendo", "WW", "Легендарный шедевр Сигэру Миямото, появление динозаврика Йоши и 96 выходов с уровней Динозавьего острова."),
                ("Super Mario World 2: Yoshi's Island", "2D Платформер", 1995, "Nintendo EAD", "Nintendo", "WW", "Пастельная сказка с чипом Super FX 2, яйцами динозавра Йоши и спасением малыша Марио."),
                ("Super Mario All-Stars", "Сборник ремейков", 1993, "Nintendo EAD", "Nintendo", "WW", "Великолепные 16-битные ремейки всех четырех частей Super Mario Bros. 1, 2, 3 и The Lost Levels."),
                ("Super Mario RPG: Legend of the Seven Stars", "JRPG", 1996, "Square", "Nintendo", "WW", "Грандиозный союз Square и Nintendo: Марио, Джено, Маллоу и Боузер против Смити."),
                ("The Legend of Zelda: A Link to the Past", "Action-Adventure", 1991, "Nintendo EAD", "Nintendo", "WW", "Эталон жанра Action-Adventure с параллельными мирами Света и Тьмы, мечом Master Sword и зеркалом."),
                ("Super Metroid", "Метроидвания", 1994, "Nintendo R&D1 / Intelligent Systems", "Nintendo", "WW", "Один из величайших шедевров видеоигр всех времен: Самус Аран в мрачных глубинах планеты Зебес."),
                ("Donkey Kong Country", "2D Платформер", 1994, "Rare", "Nintendo", "WW", "Технологическая революция предрендеренной 3D-графики от Rare, саундтрек Дэвида Уайза и дуэт Донки и Дидди."),
                ("Donkey Kong Country 2: Diddy's Kong Quest", "2D Платформер", 1995, "Rare", "Nintendo", "WW", "Абсолютная вершина 16-битных платформеров: Дидди и Дикси спасают Донки Конга от капитана К. Руля."),
                ("Donkey Kong Country 3: Dixie Kong's Double Trouble!", "2D Платформер", 1996, "Rare", "Nintendo", "WW", "Приключения Дикси и малыша Кидди в Северном Кремсфере с моторными лодками и ховеркрафтами."),
                ("Chrono Trigger", "JRPG", 1995, "Square", "Square", "WW", "Шедевр «Команды мечты» (Сакагути, Хории, Торияма, Мицуда, Уэмацу) с путешествиями во времени и 13 концовками."),
                ("Final Fantasy VI", "JRPG", 1994, "Square", "Square", "WW", "Эпическая стимпанк-драма с Террой, Локком, Кефкой Палаццо, сценой в Опере и уничтожением мира."),
                ("Final Fantasy IV", "JRPG", 1991, "Square", "Square", "WW", "Темный рыцарь Сесил ищет искупление и становится паладином в битве на Луне с Active Time Battle."),
                ("Final Fantasy V", "JRPG", 1992, "Square", "Square", "JPN", "Глубочайшая система профессий (Job System) и приключения Барца против колдуна Эксдеса."),
                ("EarthBound (Mother 2)", "JRPG", 1994, "Ape / HAL Laboratory", "Nintendo", "WW", "Культовая постмодернистская ролевая сказка Сигэсато Итои с Нессом, битами, НЛО и звукозаписывающим камнем."),
                ("Secret of Mana", "Action-RPG", 1993, "Square", "Square", "WW", "Кооперативное приключение на 3 игроков с кольцевым меню, мечом Маны и дракончиком Фламми."),
                ("Trials of Mana (Seiken Densetsu 3)", "Action-RPG", 1995, "Square", "Square", "JPN", "Шесть уникальных персонажей, система смены классов на светлый/темный и ветвящийся сюжет."),
                ("Mega Man X", "Экшен / Платформер", 1993, "Capcom", "Capcom", "WW", "Революция серии: рывки, карабкание по стенам, капсулы апгрейдов брони Лайта и союзник Зеро."),
                ("Mega Man X2", "Экшен / Платформер", 1994, "Capcom", "Capcom", "WW", "Чип Cx4 для полигональной 3D-графики, мотоциклы и сбор частей тела Зеро."),
                ("Mega Man X3", "Экшен / Платформер", 1995, "Capcom", "Capcom", "WW", "Возможность играть за Зеро с его световым Z-мечом, четыре чипа усилений и золотая броня."),
                ("Mega Man 7", "Экшен / Платформер", 1995, "Capcom", "Capcom", "WW", "16-битный дебют классического Мегамена с соперником Бассом и волком Треблом."),
                ("Castlevania: Dracula X", "Экшен / Платформер", 1995, "Konami", "Konami", "WW", "Рихтер Бельмонт спасает возлюбленную Аннетт из замка Дракулы с суперударами Item Crash."),
                ("Super Castlevania IV", "Экшен / Платформер", 1991, "Konami", "Konami", "WW", "Саймон Бельмонт бьет кнутом во всех 8 направлениях с использованием вращений Mode 7."),
                ("Contra III: The Alien Wars", "Run and Gun", 1992, "Konami", "Konami", "WW", "Ураганный боевик: стрельба из двух пулеметов, ракеты на лету, бомбы и уровни с вращением Mode 7."),
                ("Super Mario Kart", "Гонки", 1992, "Nintendo EAD", "Nintendo", "WW", "Рождение жанра аркадных картинговых гонок с использованием технологии масштабирования Mode 7."),
                ("F-Zero", "Гонки", 1990, "Nintendo EAD", "Nintendo", "WW", "Сверхзвуковые футуристические гонки с Капитаном Фэлконом и болидом Blue Falcon со скоростью свыше 400 км/ч."),
                ("Star Fox", "3D Космосимулятор", 1993, "Nintendo EAD / Argonaut", "Nintendo", "WW", "Первая в мире полностью трехмерная полигональная консольная игра на революционном чипе Super FX."),
                ("Super Punch-Out!!", "Спорт / Бокс", 1994, "Nintendo R&D3", "Nintendo", "WW", "Литтл Мак с супер-нокаутирующими комбо против колоритных мировых боксеров."),
                ("Street Fighter II Turbo", "Файтинг", 1993, "Capcom", "Capcom", "WW", "Эталон соревновательных файтингов с 12 бойцами, зеркальными матчами и турбо-скоростью."),
                ("Super Street Fighter II", "Файтинг", 1994, "Capcom", "Capcom", "WW", "Ками, Ди Джей, Т. Хоук и Фей Лонг присоединяются к мировому турниру."),
                ("Mortal Kombat II", "Файтинг", 1994, "Sculptured Software", "Acclaim", "WW", "Шедевр кровавых фаталити, бруталити, бабалити и дружбы без цензуры."),
                ("Ultimate Mortal Kombat 3", "Файтинг", 1996, "Williams / Sculptured", "Midway", "WW", "Быстрый комбо-геймплей, кнопка бега и ниндзя-киборги Сайракс и Сектор."),
                ("Killer Instinct", "Файтинг", 1995, "Rare", "Nintendo", "WW", "Ультра-комбо на 80+ ударов от Rare на черном картридже с аудиодиском Killer Cuts."),
                ("Secret of Evermore", "Action-RPG", 1995, "Square USA", "Square", "WW", "Мальчик и его собака-трансформер путешествуют по эпохам с алхимической системой магии."),
                ("Lufia II: Rise of the Sinistrals", "JRPG", 1995, "Neverland", "Natsume", "WW", "Максим и Селан спасают мир от Зловещих с подземельями в стиле Zelda и Древней Пещерой на 99 этажей."),
                ("Breath of Fire II", "JRPG", 1994, "Capcom", "Capcom", "WW", "Трансформации в гибридных драконов, строительство собственной деревни Тауншип и шаманизм."),
                ("7th Saga, The", "JRPG", 1993, "Enix", "Enix", "WW", "7th Saga, The — популярная игра для Super Nintendo Entertainment System."),
                ("ActRaiser", "Градостроительный симулятор / Экшен", 1990, "Enix", "Enix", "WW", "ActRaiser — популярная игра для Super Nintendo Entertainment System."),
                ("ActRaiser 2", "Сложный слэшер", 1993, "Enix", "Enix", "WW", "ActRaiser 2 — популярная игра для Super Nintendo Entertainment System."),
                ("Adventures of Batman & Robin, The", "Экшен-платформер", 1994, "Konami", "Konami", "WW", "Adventures of Batman & Robin, The — популярная игра для Super Nintendo Entertainment System."),
                ("Aerobiz Supersonic", "Экономическая стратегия авиалиний", 1994, "Koei", "Koei", "WW", "Aerobiz Supersonic — популярная игра для Super Nintendo Entertainment System."),
                ("Aladdin", "Платформер Аладдина от Синдзи Миками", 1993, "Capcom", "Capcom", "WW", "Aladdin — популярная игра для Super Nintendo Entertainment System."),
                ("Alien 3", "Экшен", 1993, "LJN", "LJN", "WW", "Alien 3 — популярная игра для Super Nintendo Entertainment System."),
                ("Alien vs Predator", "Beat 'em up", 1993, "Activision", "Activision", "WW", "Alien vs Predator — популярная игра для Super Nintendo Entertainment System."),
                ("Axelay", "Инновационный вертикальный и горизонтальный SHMUP", 1992, "Konami", "Konami", "WW", "Axelay — популярная игра для Super Nintendo Entertainment System."),
                ("Bahamut Lagoon", "Тактическая JRPG с выращиванием драконов", 1996, "Square", "Square", "WW", "Bahamut Lagoon — популярная игра для Super Nintendo Entertainment System."),
                ("Batman Returns", "Beat 'em up Бэтмена", 1993, "Konami", "Konami", "WW", "Batman Returns — популярная игра для Super Nintendo Entertainment System."),
                ("Battletoads in Battlemaniacs", "Боевые жабы Раш и Пимпл", 1993, "Tradewest", "Tradewest", "WW", "Battletoads in Battlemaniacs — популярная игра для Super Nintendo Entertainment System."),
                ("Biker Mice from Mars", "Изометрические боевые гонки Мышей-рокеров с Марса", 1994, "Konami", "Konami", "WW", "Biker Mice from Mars — популярная игра для Super Nintendo Entertainment System."),
                ("Blackthorne", "Кинематографичный платформер от Blizzard с дробовиком", 1994, "Interplay", "Interplay", "WW", "Blackthorne — популярная игра для Super Nintendo Entertainment System."),
                ("Boogerman: A Pick and Flick Adventure", "Комедийный платформер Бугермена", 1994, "Interplay", "Interplay", "WW", "Boogerman: A Pick and Flick Adventure — популярная игра для Super Nintendo Entertainment System."),
                ("Bram Stoker's Dracula", "Экшен", 1993, "Sony", "Sony", "WW", "Bram Stoker's Dracula — популярная игра для Super Nintendo Entertainment System."),
                ("Brawl Brothers", "Beat 'em up", 1992, "Jaleco", "Jaleco", "WW", "Brawl Brothers — популярная игра для Super Nintendo Entertainment System."),
                ("Bubsy in Claws Encounters of the Furred Kind", "Платформер рыси Бабси", 1993, "Accolade", "Accolade", "WW", "Bubsy in Claws Encounters of the Furred Kind — популярная игра для Super Nintendo Entertainment System."),
                ("Bust-A-Move", "Головоломка с шариками", 1995, "Taito", "Taito", "WW", "Bust-A-Move — популярная игра для Super Nintendo Entertainment System."),
                ("Captain Commando", "Футуристический Beat 'em up", 1995, "Capcom", "Capcom", "WW", "Captain Commando — популярная игра для Super Nintendo Entertainment System."),
                ("ClayFighter", "Пластилиновый файтинг", 1993, "Interplay", "Interplay", "WW", "ClayFighter — популярная игра для Super Nintendo Entertainment System."),
                ("ClayFighter 2: Judgment Clay", "Пластилиновый файтинг 2", 1995, "Interplay", "Interplay", "WW", "ClayFighter 2: Judgment Clay — популярная игра для Super Nintendo Entertainment System."),
                ("Clock Tower", "Культовый психологический Point-and-Click хоррор о Дженнифер и человеке с ножницами", 1995, "Human Entertainment", "Human Entertainment", "WW", "Clock Tower — популярная игра для Super Nintendo Entertainment System."),
                ("Demon's Crest", "Метроидвания за горгулью Файрбренда с 5 формами стихий", 1994, "Capcom", "Capcom", "WW", "Demon's Crest — популярная игра для Super Nintendo Entertainment System."),
                ("Der Langrisser", "Тактическая JRPG с глубоким разветвлением сюжета на 4 пути", 1995, "NCS", "NCS", "WW", "Der Langrisser — популярная игра для Super Nintendo Entertainment System."),
                ("DoReMi Fantasy: Milon's DokiDoki Adventure", "Красочный платформер Милона", 1996, "Hudson Soft", "Hudson Soft", "WW", "DoReMi Fantasy: Milon's DokiDoki Adventure — популярная игра для Super Nintendo Entertainment System."),
                ("Doom", "Легендарный 3D-шутер Думгая на чипе Super FX 2", 1995, "Williams", "Williams", "WW", "Doom — популярная игра для Super Nintendo Entertainment System."),
                ("Dragon Quest V: Hand of the Heavenly Bride", "Великая JRPG с выбором жены и 3 поколениями семьи", 1992, "Enix", "Enix", "WW", "Dragon Quest V: Hand of the Heavenly Bride — популярная игра для Super Nintendo Entertainment System."),
                ("Dragon Quest VI: Realms of Revelation", "JRPG с мирами Реальности и Снов", 1995, "Enix", "Enix", "WW", "Dragon Quest VI: Realms of Revelation — популярная игра для Super Nintendo Entertainment System."),
                ("Earthworm Jim", "Суперчервяк Джим", 1994, "Playmates", "Playmates", "WW", "Earthworm Jim — популярная игра для Super Nintendo Entertainment System."),
                ("Earthworm Jim 2", "Вторая часть червяка Джима", 1995, "Playmates", "Playmates", "WW", "Earthworm Jim 2 — популярная игра для Super Nintendo Entertainment System."),
                ("E.V.O.: Search for Eden", "Эволюционная Action-RPG от рыбы до млекопитающего", 1992, "Enix", "Enix", "WW", "E.V.O.: Search for Eden — популярная игра для Super Nintendo Entertainment System."),
                ("Feda: The Emblem of Justice", "Тактическая RPG", 1994, "Yanoman", "Yanoman", "WW", "Feda: The Emblem of Justice — популярная игра для Super Nintendo Entertainment System."),
                ("Final Fight", "Классический уличный мордобой Хаггара и Коди", 1990, "Capcom", "Capcom", "WW", "Final Fight — популярная игра для Super Nintendo Entertainment System."),
                ("Final Fight 2", "Мордобой Хаггара, Маки и Карлоса", 1993, "Capcom", "Capcom", "WW", "Final Fight 2 — популярная игра для Super Nintendo Entertainment System."),
                ("Final Fight 3", "Мордобой Хаггара, Гая, Люсии и Дина", 1995, "Capcom", "Capcom", "WW", "Final Fight 3 — популярная игра для Super Nintendo Entertainment System."),
                ("Fire Emblem: Mystery of the Emblem", "Тактическая RPG Марса", 1994, "Nintendo", "Nintendo", "WW", "Fire Emblem: Mystery of the Emblem — популярная игра для Super Nintendo Entertainment System."),
                ("Fire Emblem: Genealogy of the Holy War", "Эпическая тактическая RPG о Сигурде и Селисе на 2 поколения", 1996, "Nintendo", "Nintendo", "WW", "Fire Emblem: Genealogy of the Holy War — популярная игра для Super Nintendo Entertainment System."),
                ("Fire Emblem: Thracia 776", "Хардкорная тактическая RPG принца Лифа", 1999, "Nintendo", "Nintendo", "WW", "Fire Emblem: Thracia 776 — популярная игра для Super Nintendo Entertainment System."),
                ("Flashback: The Quest for Identity", "Кинематографичный платформер Конрада Харта", 1993, "U.S. Gold", "U.S. Gold", "WW", "Flashback: The Quest for Identity — популярная игра для Super Nintendo Entertainment System."),
                ("Front Mission", "Пошаговая тактика гигантских боевых роботов ванзеров", 1995, "Square", "Square", "WW", "Front Mission — популярная игра для Super Nintendo Entertainment System."),
                ("Front Mission: Gun Hazard", "Action-RPG с ванзерами с видом сбоку", 1996, "Square", "Square", "WW", "Front Mission: Gun Hazard — популярная игра для Super Nintendo Entertainment System."),
                ("Ghouls 'n Ghosts (Super Ghouls 'n Ghosts)", "Хардкорный платформер рыцаря Артура с двойным прыжком", 1991, "Capcom", "Capcom", "WW", "Ghouls 'n Ghosts (Super Ghouls 'n Ghosts) — популярная игра для Super Nintendo Entertainment System."),
                ("Goof Troop", "Кооперативная логическая головоломка Гуфи и Макса от Синдзи Миками", 1993, "Capcom", "Capcom", "WW", "Goof Troop — популярная игра для Super Nintendo Entertainment System."),
                ("Gradius III", "Космический SHMUP с кастомизацией оружия", 1990, "Konami", "Konami", "WW", "Gradius III — популярная игра для Super Nintendo Entertainment System."),
                ("Harvest Moon", "Оригинальный шедевр симулятора фермы Ясухиро Вады", 1996, "Natsume", "Natsume", "WW", "Harvest Moon — популярная игра для Super Nintendo Entertainment System."),
                ("Ignition Factor, The", "Симулятор пожарной бригады со спасением людей из горящих зданий", 1994, "Jaleco", "Jaleco", "WW", "Ignition Factor, The — популярная игра для Super Nintendo Entertainment System."),
                ("Illusion of Gaia", "Action-RPG Уилла с превращениями в темного рыцаря Фрида и Шадоу", 1993, "Enix", "Enix", "WW", "Illusion of Gaia — популярная игра для Super Nintendo Entertainment System."),
                ("International Superstar Soccer Deluxe", "Лучший 16-битный футбол Konami с комментатором", 1995, "Konami", "Konami", "WW", "International Superstar Soccer Deluxe — популярная игра для Super Nintendo Entertainment System."),
                ("Joe & Mac: Caveman Ninja", "Первобытные приключения пещерных людей Джо и Мака", 1991, "Data East", "Data East", "WW", "Joe & Mac: Caveman Ninja — популярная игра для Super Nintendo Entertainment System."),
                ("Joe & Mac 2: Lost in the Tropics", "Вторая часть пещерных людей с постройкой хижины", 1994, "Data East", "Data East", "WW", "Joe & Mac 2: Lost in the Tropics — популярная игра для Super Nintendo Entertainment System."),
                ("Jurassic Park", "3D FPS и вид сверху в Парке Юрского периода", 1993, "Ocean", "Ocean", "WW", "Jurassic Park — популярная игра для Super Nintendo Entertainment System."),
                ("Kirby Super Star (Kirby's Fun Pak)", "Сборник 8 полноценных игр Кирби от Масахиро Сакурая", 1996, "Nintendo", "Nintendo", "WW", "Kirby Super Star (Kirby's Fun Pak) — популярная игра для Super Nintendo Entertainment System."),
                ("Kirby's Dream Course", "Изометрический мини-гольф Кирби", 1994, "Nintendo", "Nintendo", "WW", "Kirby's Dream Course — популярная игра для Super Nintendo Entertainment System."),
                ("Kirby's Dream Land 3", "Пастельный шедевр Кирби с 6 друзьями-животными", 1997, "Nintendo", "Nintendo", "WW", "Kirby's Dream Land 3 — популярная игра для Super Nintendo Entertainment System."),
                ("Knights of the Round", "Рыцари круглого стола короля Артура от Capcom", 1994, "Capcom", "Capcom", "WW", "Knights of the Round — популярная игра для Super Nintendo Entertainment System."),
                ("Legend of the Mystical Ninja, The", "Гоэмон и Эбисумару", 1991, "Konami", "Konami", "WW", "Legend of the Mystical Ninja, The — популярная игра для Super Nintendo Entertainment System."),
                ("Lemmings", "Головоломка леммингов", 1992, "Sunsoft", "Sunsoft", "WW", "Lemmings — популярная игра для Super Nintendo Entertainment System."),
                ("Lion King, The", "Король Лев", 1994, "Virgin", "Virgin", "WW", "Lion King, The — популярная игра для Super Nintendo Entertainment System."),
                ("Live A Live", "Уникальная JRPG Такаси Токиты с 7 эпохами (Первобытность, Дикий Запад, Будущее, Ниндзя)", 1994, "Square", "Square", "WW", "Live A Live — популярная игра для Super Nintendo Entertainment System."),
                ("Lode Runner Twin", "Сбор золота вдвоем", 1994, "T&E Soft", "T&E Soft", "WW", "Lode Runner Twin — популярная игра для Super Nintendo Entertainment System."),
                ("Lost Vikings, The", "Головоломка трех викингов Эрика, Балеога и Олафа от Blizzard", 1993, "Interplay", "Interplay", "WW", "Lost Vikings, The — популярная игра для Super Nintendo Entertainment System."),
                ("Lost Vikings 2, The", "Вторая часть трех викингов с бионической рукой", 1997, "Interplay", "Interplay", "WW", "Lost Vikings 2, The — популярная игра для Super Nintendo Entertainment System."),
                ("Lufia & the Fortress of Doom", "JRPG о 4 героях Максиме, Гае, Артее и Селан", 1993, "Taito", "Taito", "WW", "Lufia & the Fortress of Doom — популярная игра для Super Nintendo Entertainment System."),
                ("Magical Pop'n", "Красочный экшен-платформер принцессы волшебницы", 1995, "Pack-In-Video", "Pack-In-Video", "WW", "Magical Pop'n — популярная игра для Super Nintendo Entertainment System."),
                ("Mario Paint", "Творческая студия рисования, анимации и сочинения музыки с мышкой SNES Mouse", 1992, "Nintendo", "Nintendo", "WW", "Mario Paint — популярная игра для Super Nintendo Entertainment System."),
                ("Marvel Super Heroes in War of the Gems", "Экшен Человека-Паука, Росомахи, Железного Человека и Халка за Камни Бесконечности", 1996, "Capcom", "Capcom", "WW", "Marvel Super Heroes in War of the Gems — популярная игра для Super Nintendo Entertainment System."),
                ("Mega Man Soccer", "Футбол с роботами-мастерами", 1994, "Capcom", "Capcom", "WW", "Mega Man Soccer — популярная игра для Super Nintendo Entertainment System."),
                ("Metal Warriors", "Меха-шутер с пересадкой пилота между 6 типами роботов от LucasArts", 1995, "Konami", "Konami", "WW", "Metal Warriors — популярная игра для Super Nintendo Entertainment System."),
                ("Micro Machines", "Гонки микро-машинок", 1993, "Ocean", "Ocean", "WW", "Micro Machines — популярная игра для Super Nintendo Entertainment System."),
                ("Mortal Kombat", "Оригинальная Смертельная Битва", 1993, "Acclaim", "Acclaim", "WW", "Mortal Kombat — популярная игра для Super Nintendo Entertainment System."),
                ("Mortal Kombat 3", "Третья часть МК", 1995, "Williams", "Williams", "WW", "Mortal Kombat 3 — популярная игра для Super Nintendo Entertainment System."),
                ("NBA Jam", "Уличный баскетбол 2х2", 1993, "Acclaim", "Acclaim", "WW", "NBA Jam — популярная игра для Super Nintendo Entertainment System."),
                ("NBA Jam Tournament Edition", "Турнирное издание баскетбола", 1994, "Acclaim", "Acclaim", "WW", "NBA Jam Tournament Edition — популярная игра для Super Nintendo Entertainment System."),
                ("NHL 94", "Величайший спортивный симулятор хоккея 16-битной эпохи", 1993, "EA Sports", "EA Sports", "WW", "NHL 94 — популярная игра для Super Nintendo Entertainment System."),
                ("Ninja Warriors, The", "Beat 'em up ниндзя-киборгов Куноити, Ниндзя и Камаитати от Natsume", 1994, "Taito", "Taito", "WW", "Ninja Warriors, The — популярная игра для Super Nintendo Entertainment System."),
                ("Ogre Battle: The March of the Black Queen", "Глобальная тактическая RPG Ясуми Мацуно с картами Таро", 1993, "Enix", "Enix", "WW", "Ogre Battle: The March of the Black Queen — популярная игра для Super Nintendo Entertainment System."),
                ("Out of This World (Another World)", "Кинематографичный сай-фай шедевр Эрика Шайи", 1992, "Interplay", "Interplay", "WW", "Out of This World (Another World) — популярная игра для Super Nintendo Entertainment System."),
                ("Pac-Attack", "Головоломка Пакмана", 1993, "Namco", "Namco", "WW", "Pac-Attack — популярная игра для Super Nintendo Entertainment System."),
                ("Pac-Man 2: The New Adventures", "Интерактивный мультфильм с рогаткой", 1994, "Namco", "Namco", "WW", "Pac-Man 2: The New Adventures — популярная игра для Super Nintendo Entertainment System."),
                ("Pilotwings", "Авиасимулятор бипланов, парашюта, дельтаплана и реактивного ранца Mode 7", 1990, "Nintendo", "Nintendo", "WW", "Pilotwings — популярная игра для Super Nintendo Entertainment System."),
                ("Pocky & Rocky", "Кооперативный экшен жрицы Покки и енота Рокки от Natsume", 1992, "Natsume", "Natsume", "WW", "Pocky & Rocky — популярная игра для Super Nintendo Entertainment System."),
                ("Pocky & Rocky 2", "Вторая часть приключений Покки и Рокки", 1994, "Natsume", "Natsume", "WW", "Pocky & Rocky 2 — популярная игра для Super Nintendo Entertainment System."),
                ("Populous", "Симулятор бога", 1991, "Acclaim", "Acclaim", "WW", "Populous — популярная игра для Super Nintendo Entertainment System."),
                ("Prince of Persia", "Принц Персии", 1992, "Konami", "Konami", "WW", "Prince of Persia — популярная игра для Super Nintendo Entertainment System."),
                ("Prince of Persia 2: The Shadow and the Flame", "Вторая часть Принца Персии", 1996, "Titus", "Titus", "WW", "Prince of Persia 2: The Shadow and the Flame — популярная игра для Super Nintendo Entertainment System."),
                ("R-Type III: The Third Lightning", "Вершина космических SHMUP на SNES", 1993, "Jaleco", "Jaleco", "WW", "R-Type III: The Third Lightning — популярная игра для Super Nintendo Entertainment System."),
                ("Radical Dreamers", "Визуальная новелла-интерквел Chrono Trigger для Satellaview", 1996, "Square", "Square", "WW", "Radical Dreamers — популярная игра для Super Nintendo Entertainment System."),
                ("Ranma 1/2: Hard Battle", "Файтинг по аниме Ранма 1/2", 1993, "Toho", "Toho", "WW", "Ranma 1/2: Hard Battle — популярная игра для Super Nintendo Entertainment System."),
                ("Rock n' Roll Racing", "Изометрические боевые гонки под рок Black Sabbath и Deep Purple от Blizzard", 1993, "Interplay", "Interplay", "WW", "Rock n' Roll Racing — популярная игра для Super Nintendo Entertainment System."),
                ("Romancing SaGa", "Нелинейная JRPG Акитоси Кавадзу с 8 героями", 1992, "Square", "Square", "WW", "Romancing SaGa — популярная игра для Super Nintendo Entertainment System."),
                ("Romancing SaGa 2", "JRPG с наследованием трона императорской династии сквозь века", 1993, "Square", "Square", "WW", "Romancing SaGa 2 — популярная игра для Super Nintendo Entertainment System."),
                ("Romancing SaGa 3", "Шедевр JRPG с командирским режимом и бизнесом", 1995, "Square", "Square", "WW", "Romancing SaGa 3 — популярная игра для Super Nintendo Entertainment System."),
                ("Rudra no Hihou (Treasure of the Rudras)", "JRPG с созданием собственных заклинаний из слогов", 1996, "Square", "Square", "WW", "Rudra no Hihou (Treasure of the Rudras) — популярная игра для Super Nintendo Entertainment System."),
                ("Run Saber", "Киберпанк-слэшер в стиле Strider", 1993, "Atlus", "Atlus", "WW", "Run Saber — популярная игра для Super Nintendo Entertainment System."),
                ("Sailor Moon: Another Story", "JRPG по аниме Сейлор Мун с 10 сейлор-воительницами", 1995, "Angel", "Angel", "WW", "Sailor Moon: Another Story — популярная игра для Super Nintendo Entertainment System."),
                ("Samurai Shodown", "Файтинг на самурайских мечах", 1993, "Takara", "Takara", "WW", "Samurai Shodown — популярная игра для Super Nintendo Entertainment System."),
                ("Saturday Night Slam Masters", "Рестлинг от Capcom с артом Тэцуо Хары (Fist of the North Star)", 1994, "Capcom", "Capcom", "WW", "Saturday Night Slam Masters — популярная игра для Super Nintendo Entertainment System."),
                ("Secret of the Stars", "JRPG с двумя отрядами героев", 1993, "Tecmo", "Tecmo", "WW", "Secret of the Stars — популярная игра для Super Nintendo Entertainment System."),
                ("Shadowrun", "Киберпанк Action-RPG Джейка Армитиджа в Сиэтле 2050 года", 1993, "Data East", "Data East", "WW", "Shadowrun — популярная игра для Super Nintendo Entertainment System."),
                ("Shin Megami Tensei", "Постапокалиптическая JRPG с призывом демонов и переговорами", 1992, "Atlus", "Atlus", "WW", "Shin Megami Tensei — популярная игра для Super Nintendo Entertainment System."),
                ("Shin Megami Tensei II", "Вторая часть SMT в Токио Миллениум", 1994, "Atlus", "Atlus", "WW", "Shin Megami Tensei II — популярная игра для Super Nintendo Entertainment System."),
                ("SimCity", "Градостроительный симулятор Уилла Райта с доктором Райтом и Боузером", 1991, "Nintendo", "Nintendo", "WW", "SimCity — популярная игра для Super Nintendo Entertainment System."),
                ("SimCity 2000", "Изометрический градостроительный симулятор", 1995, "Maxis", "Maxis", "WW", "SimCity 2000 — популярная игра для Super Nintendo Entertainment System."),
                ("Skyblazer", "Мистический индийский экшен-платформер Скай", 1994, "Sony Imagesoft", "Sony Imagesoft", "WW", "Skyblazer — популярная игра для Super Nintendo Entertainment System."),
                ("Smash Tennis (Super Family Tennis)", "Теннис с 20 кортами от Namco", 1993, "Namco", "Namco", "WW", "Smash Tennis (Super Family Tennis) — популярная игра для Super Nintendo Entertainment System."),
                ("Sonic Blast Man", "Супергеройский Beat 'em up", 1992, "Taito", "Taito", "WW", "Sonic Blast Man — популярная игра для Super Nintendo Entertainment System."),
                ("Sonic Blast Man II", "Вторая часть супергеройского мордобоя", 1994, "Taito", "Taito", "WW", "Sonic Blast Man II — популярная игра для Super Nintendo Entertainment System."),
                ("Soul Blazer", "Action-RPG об освобождении душ живых существ и восстановлении мира", 1992, "Enix", "Enix", "WW", "Soul Blazer — популярная игра для Super Nintendo Entertainment System."),
                ("Space Megaforce (Super Aleste)", "Ультимативный вертикальный SHMUP от Compile", 1992, "Toho", "Toho", "WW", "Space Megaforce (Super Aleste) — популярная игра для Super Nintendo Entertainment System."),
                ("Sparkster", "Опоссум-рыцарь Спаркстер с ракетным ранцем и мечом", 1994, "Konami", "Konami", "WW", "Sparkster — популярная игра для Super Nintendo Entertainment System."),
                ("Star Ocean", "Грандиозная Sci-Fi Action-RPG от tri-Ace с голосовой озвучкой на чипе S-DD1", 1996, "Enix", "Enix", "WW", "Star Ocean — популярная игра для Super Nintendo Entertainment System."),
                ("Street Fighter Alpha 2", "Шедевр 32-битного файтинга, портированный на SNES с чипом S-DD1", 1996, "Capcom", "Capcom", "WW", "Street Fighter Alpha 2 — популярная игра для Super Nintendo Entertainment System."),
                ("Sunset Riders", "Вестерн Run and Gun 4 охотников за головами Стива, Билли, Боба и Кормано", 1993, "Konami", "Konami", "WW", "Sunset Riders — популярная игра для Super Nintendo Entertainment System."),
                ("Super Adventure Island", "Приключения Мастера Хиггинса с саундтреком Юзо Косиро", 1992, "Hudson Soft", "Hudson Soft", "WW", "Super Adventure Island — популярная игра для Super Nintendo Entertainment System."),
                ("Super Adventure Island II", "Action-RPG с картой мира и мечами", 1994, "Hudson Soft", "Hudson Soft", "WW", "Super Adventure Island II — популярная игра для Super Nintendo Entertainment System."),
                ("Super Baseball 2020", "Кибер-бейсбол роботов", 1993, "SNK", "SNK", "WW", "Super Baseball 2020 — популярная игра для Super Nintendo Entertainment System."),
                ("Super Bomberman", "Кооперативный Бомбермен на 4 игроков", 1993, "Hudson Soft", "Hudson Soft", "WW", "Super Bomberman — популярная игра для Super Nintendo Entertainment System."),
                ("Super Bomberman 2", "Вторая часть Бомбермена с сюжетной кампанией", 1994, "Hudson Soft", "Hudson Soft", "WW", "Super Bomberman 2 — популярная игра для Super Nintendo Entertainment System."),
                ("Super Bomberman 3", "Бомбермен на 5 игроков с ездовыми кенгуру Руи", 1995, "Hudson Soft", "Hudson Soft", "WW", "Super Bomberman 3 — популярная игра для Super Nintendo Entertainment System."),
                ("Super Bomberman 4", "Бомбермен с путешествиями во времени", 1996, "Hudson Soft", "Hudson Soft", "WW", "Super Bomberman 4 — популярная игра для Super Nintendo Entertainment System."),
                ("Super Bomberman 5", "Финальная часть саги Bomberman на SNES с 100 уровнями", 1997, "Hudson Soft", "Hudson Soft", "WW", "Super Bomberman 5 — популярная игра для Super Nintendo Entertainment System."),
                ("Super Bonk", "Пещерный мальчик Бонк с трансформациями", 1994, "Hudson Soft", "Hudson Soft", "WW", "Super Bonk — популярная игра для Super Nintendo Entertainment System."),
                ("Super Double Dragon", "Возвращение драконов Билли и Джимми с блоками и захватами", 1992, "Tradewest", "Tradewest", "WW", "Super Double Dragon — популярная игра для Super Nintendo Entertainment System."),
                ("Super Ghouls 'n Ghosts", "Артур в золотой броне", 1991, "Capcom", "Capcom", "WW", "Super Ghouls 'n Ghosts — популярная игра для Super Nintendo Entertainment System."),
                ("Super Mario Kart", "Картинговые гонки", 1992, "Nintendo", "Nintendo", "WW", "Super Mario Kart — популярная игра для Super Nintendo Entertainment System."),
                ("Super Ninja Boy", "Кунг-фу RPG", 1991, "Culture Brain", "Culture Brain", "WW", "Super Ninja Boy — популярная игра для Super Nintendo Entertainment System."),
                ("Super Nova (Darius Force)", "Космический SHMUP", 1993, "Taito", "Taito", "WW", "Super Nova (Darius Force) — популярная игра для Super Nintendo Entertainment System."),
                ("Super Off Road", "Гонки на внедорожниках", 1993, "Tradewest", "Tradewest", "WW", "Super Off Road — популярная игра для Super Nintendo Entertainment System."),
                ("Super R-Type", "Космический SHMUP", 1991, "Irem", "Irem", "WW", "Super R-Type — популярная игра для Super Nintendo Entertainment System."),
                ("Super Smash T.V.", "Гладиаторское телешоу с двумя стиками", 1992, "Acclaim", "Acclaim", "WW", "Super Smash T.V. — популярная игра для Super Nintendo Entertainment System."),
                ("Super Star Wars", "Экшен Люка Скайуокера на Татуине с гонками на спидере", 1992, "LucasArts / JVC", "LucasArts / JVC", "WW", "Super Star Wars — популярная игра для Super Nintendo Entertainment System."),
                ("Super Star Wars: The Empire Strikes Back", "Битва на планете Хот на сноу-спидерах и тренировки у Йоды", 1993, "LucasArts / JVC", "LucasArts / JVC", "WW", "Super Star Wars: The Empire Strikes Back — популярная игра для Super Nintendo Entertainment System."),
                ("Super Star Wars: Return of the Jedi", "Битва на Эндоре и дуэль с Императором Палпатином", 1994, "LucasArts / JVC", "LucasArts / JVC", "WW", "Super Star Wars: Return of the Jedi — популярная игра для Super Nintendo Entertainment System."),
                ("Super Turrican", "Шедевр Run and Gun с лазерным кнутом Криса Хюльсбека", 1993, "Seika", "Seika", "WW", "Super Turrican — популярная игра для Super Nintendo Entertainment System."),
                ("Super Turrican 2", "Вторая часть с крюком-кошкой и поездками на багги", 1995, "Ocean", "Ocean", "WW", "Super Turrican 2 — популярная игра для Super Nintendo Entertainment System."),
                ("Tactics Ogre: Let Us Cling Together", "Абсолютный шедевр изометрических тактических RPG Ясуми Мацуно", 1995, "Quest", "Quest", "WW", "Tactics Ogre: Let Us Cling Together — популярная игра для Super Nintendo Entertainment System."),
                ("Tales of Phantasia", "Родоначальник серии Tales от Wolf Team с первой в истории полнотекстовой песней на SNES", 1995, "Namco", "Namco", "WW", "Tales of Phantasia — популярная игра для Super Nintendo Entertainment System."),
                ("Teenage Mutant Ninja Turtles IV: Turtles in Time", "Величайший аркадный Beat 'em up Черепашек-ниндзя сквозь века", 1992, "Konami", "Konami", "WW", "Teenage Mutant Ninja Turtles IV: Turtles in Time — популярная игра для Super Nintendo Entertainment System."),
                ("Teenage Mutant Ninja Turtles: Tournament Fighters", "Турнирный файтинг Черепашек-ниндзя от Konami", 1993, "Konami", "Konami", "WW", "Teenage Mutant Ninja Turtles: Tournament Fighters — популярная игра для Super Nintendo Entertainment System."),
                ("Terranigma", "Монументальная Action-RPG о возрождении континентов, растений, животных и цивилизации Земли", 1995, "Enix", "Enix", "WW", "Terranigma — популярная игра для Super Nintendo Entertainment System."),
                ("Tetris & Dr. Mario", "Сборник Тетриса и Доктора Марио со смешанным режимом", 1994, "Nintendo", "Nintendo", "WW", "Tetris & Dr. Mario — популярная игра для Super Nintendo Entertainment System."),
                ("Tetris 2", "Цветной Тетрис с бомбами", 1994, "Nintendo", "Nintendo", "WW", "Tetris 2 — популярная игра для Super Nintendo Entertainment System."),
                ("Tetris Attack (Panel de Pon)", "Легендарная соревновательная головоломка с Йоши", 1996, "Nintendo", "Nintendo", "WW", "Tetris Attack (Panel de Pon) — популярная игра для Super Nintendo Entertainment System."),
                ("Top Gear", "Культовые аркадные автогонки со сплит-скрином и саундтреком Барри Лейтча", 1992, "Kemco", "Kemco", "WW", "Top Gear — популярная игра для Super Nintendo Entertainment System."),
                ("Top Gear 2", "Гонки с апгрейдом двигателя, нитро, брони и коробки передач", 1993, "Kemco", "Kemco", "WW", "Top Gear 2 — популярная игра для Super Nintendo Entertainment System."),
                ("Top Gear 3000", "Футуристические космические гонки на чипе DSP-4 с телепортами и ядерным ускорением", 1995, "Kemco", "Kemco", "WW", "Top Gear 3000 — популярная игра для Super Nintendo Entertainment System."),
                ("True Lies", "Шпионский боевик со Шварценеггером", 1994, "LJN", "LJN", "WW", "True Lies — популярная игра для Super Nintendo Entertainment System."),
                ("Turok: Dinosaur Hunter (SNES Demo)", "Экшен", 1996, "Acclaim", "Acclaim", "WW", "Turok: Dinosaur Hunter (SNES Demo) — популярная игра для Super Nintendo Entertainment System."),
                ("U.N. Squadron (Area 88)", "Культовый боевой авиасимулятор от Capcom с покупкой оружия", 1991, "Capcom", "Capcom", "WW", "U.N. Squadron (Area 88) — популярная игра для Super Nintendo Entertainment System."),
                ("Uncharted Waters: New Horizons", "Морские приключения эпохи Великих географических открытий", 1994, "Koei", "Koei", "WW", "Uncharted Waters: New Horizons — популярная игра для Super Nintendo Entertainment System."),
                ("Wario's Woods", "Головоломка Тоада с бомбами", 1994, "Nintendo", "Nintendo", "WW", "Wario's Woods — популярная игра для Super Nintendo Entertainment System."),
                ("Weaponlord", "Хардкорный варварский файтинг с парированием оружия", 1995, "Namco", "Namco", "WW", "Weaponlord — популярная игра для Super Nintendo Entertainment System."),
                ("Wild Guns", "Стимпанк-вестерн тир Клинта и Энни от Natsume", 1994, "Natsume", "Natsume", "WW", "Wild Guns — популярная игра для Super Nintendo Entertainment System."),
                ("Wing Commander", "3D Космосимулятор полковника Блэра против килрахи", 1992, "Mindscape", "Mindscape", "WW", "Wing Commander — популярная игра для Super Nintendo Entertainment System."),
                ("Wing Commander: The Secret Missions", "Секретные миссии Wing Commander", 1993, "Mindscape", "Mindscape", "WW", "Wing Commander: The Secret Missions — популярная игра для Super Nintendo Entertainment System."),
                ("Wolverine: Adamantium Rage", "Экшен Росомахи с регенерацией здоровья", 1994, "LJN", "LJN", "WW", "Wolverine: Adamantium Rage — популярная игра для Super Nintendo Entertainment System."),
                ("Wrecking Crew '98", "Головоломка Марио с кувалдой", 1998, "Nintendo", "Nintendo", "WW", "Wrecking Crew '98 — популярная игра для Super Nintendo Entertainment System."),
                ("WWF Royal Rumble", "Королевская битва рестлинга на 6 бойцов", 1993, "LJN", "LJN", "WW", "WWF Royal Rumble — популярная игра для Super Nintendo Entertainment System."),
                ("X-Men: Mutant Apocalypse", "Экшен Людей Икс (Циклоп, Росомаха, Псайлок, Гамбит, Зверь) от Capcom", 1994, "Capcom", "Capcom", "WW", "X-Men: Mutant Apocalypse — популярная игра для Super Nintendo Entertainment System."),
                ("Yoshi's Cookie", "Головоломка Йоши", 1993, "Nintendo", "Nintendo", "WW", "Yoshi's Cookie — популярная игра для Super Nintendo Entertainment System."),
                ("Yoshi's Safari", "3D-шутер верхом на Йоши для световой пушки Super Scope", 1993, "Nintendo", "Nintendo", "WW", "Yoshi's Safari — популярная игра для Super Nintendo Entertainment System."),
                ("Zero The Kamikaze Squirrel", "Платформер белки-ниндзя Зеро", 1994, "Sunsoft", "Sunsoft", "WW", "Zero The Kamikaze Squirrel — популярная игра для Super Nintendo Entertainment System."),
                ("Zombies Ate My Neighbors", "Культовый комедийный кооперативный хоррор Зика и Джулии с водными пистолетами от LucasArts", 1993, "Konami", "Konami", "WW", "Zombies Ate My Neighbors — популярная игра для Super Nintendo Entertainment System."),
            };

            foreach (var g in games)
            {
                list.Add(new NintendoCatalogItem
                {
                    Title = g.Title,
                    Genre = g.Genre,
                    Year = g.Year,
                    Developer = g.Dev,
                    Publisher = g.Pub,
                    Region = g.Region,
                    Desc = g.Desc
                });
            }

            return list;
        }
    }
}
