using System;
using System.Collections.Generic;

namespace StormSwitchBox.Services
{
    public static class ThreeDsCatalogData
    {
        public static List<NintendoCatalogItem> GetCatalog()
        {
            var list = new List<NintendoCatalogItem>(208);

            var games = new (string Title, string Genre, int Year, string Dev, string Pub, string Region, string Desc)[]
            {
                ("The Legend of Zelda: A Link Between Worlds", "Action-Adventure", 2013, "Nintendo EAD", "Nintendo", "WW", "Прямой сиквел A Link to the Past: превращение Линка в настенный рисунок и нелинейная аренда предметов у Равио."),
                ("The Legend of Zelda: Ocarina of Time 3D", "Action-Adventure", 2011, "Grezzo / Nintendo", "Nintendo", "WW", "Великолепный ремейк шедевра при 30 FPS с автоприцеливанием гироскопом и зеркальным режимом Master Quest."),
                ("The Legend of Zelda: Majora's Mask 3D", "Action-Adventure", 2015, "Grezzo / Nintendo", "Nintendo", "WW", "Ремейк культового темного цикла 3 дней с обновленным блокнотом бомберов и рыбалкой."),
                ("Pokemon X Version", "JRPG", 2013, "Game Freak", "Nintendo", "WW", "Шестое поколение в регионе Калос (Франция): полная 3D-графика, Мега-Эволюции и волшебный тип Fairy."),
                ("Pokemon Y Version", "JRPG", 2013, "Game Freak", "Nintendo", "WW", "Легендарный Ивельтал, кастомизация внешности тренера и онлайн-система PSS."),
                ("Pokemon Sun Version", "JRPG", 2016, "Game Freak", "Nintendo", "WW", "Седьмое поколение на тропических островах Алола: испытания вместо гимов, региональные формы и Z-атаки."),
                ("Pokemon Moon Version", "JRPG", 2016, "Game Freak", "Nintendo", "WW", "Легендарная Лунала, ультра-чудовища (Ultra Beasts) и смещение времени суток на 12 часов."),
                ("Pokemon Ultra Sun Version", "JRPG", 2017, "Game Freak", "Nintendo", "WW", "Расширенная версия: Некрозма, путешествия по червоточинам Ультра-Пространства и команда Team Rainbow Rocket."),
                ("Pokemon Ultra Moon Version", "JRPG", 2017, "Game Freak", "Nintendo", "WW", "Ультимативное издание поколения Алолы со всеми прошлыми легендарными покемонами."),
                ("Pokemon Omega Ruby", "JRPG", 2014, "Game Freak", "Nintendo", "WW", "Грандиозный 3D-ремейк Хоэнна: Первобытный Граудон, полет на Латиосе над картой мира и Эпизод Дельта с Деоксисом."),
                ("Pokemon Alpha Sapphire", "JRPG", 2014, "Game Freak", "Nintendo", "WW", "Первобытный Кайогр, морские глубины и Мега-Рэйкваза."),
                ("Super Mario 3D Land", "3D Платформер", 2011, "Nintendo EAD Tokyo", "Nintendo", "WW", "Идеальное сочетание 2D-платформинга и объема автостереоскопического 3D с костюмом Тануки."),
                ("Mario Kart 7", "Картинговые гонки", 2011, "Nintendo EAD / Retro Studios", "Nintendo", "WW", "Впервые в серии: дельтапланы для полетов, винты для подводного плавания и сборка картов из деталей."),
                ("Fire Emblem Awakening", "Тактическая RPG", 2012, "Intelligent Systems", "Nintendo", "WW", "Возрождение франшизы: Хром, Робин, парные связки Pair Up, свадьбы и дети из будущего."),
                ("Fire Emblem Fates: Birthright / Conquest / Revelation", "Тактическая RPG", 2015, "Intelligent Systems", "Nintendo", "WW", "Драматический выбор между семьей по крови Хосидо и приемной семьей Нор."),
                ("Fire Emblem Echoes: Shadows of Valentia", "Тактическая RPG", 2017, "Intelligent Systems", "Nintendo", "WW", "Ремейк Gaiden с Альмом и Селикой, исследовательской камерой от третьего лица в подземельях и полной озвучкой."),
                ("Super Smash Bros. for Nintendo 3DS", "Файтинг-кроссовер", 2014, "Bandai Namco / Sora", "Nintendo", "WW", "Первый портативный Smash Bros при 60 FPS: 58 бойцов (Мегамен, Пакман, Рю, Клауд) и режим Smash Run."),
                ("Monster Hunter 4 Ultimate", "Action-RPG / Охота на монстров", 2015, "Capcom", "Capcom", "WW", "Абсолютная вершина портативной охоты: вертикальный геймплей, оседлание монстров, Glaive и Charge Blade."),
                ("Monster Hunter Generations", "Action-RPG", 2015, "Capcom", "Capcom", "WW", "Четыре стиля охоты Hunting Styles, супер-приемы Hunter Arts и игра за котиков Палико в режиме Prowler."),
                ("Luigi's Mansion: Dark Moon", "Приключенческий экшен", 2013, "Next Level Games", "Nintendo", "WW", "Луиджи исследует 5 особняков в Долине Призраков с пылесосом Poltergust 5000 и ультрафиолетовым фонарем."),
                ("Kid Icarus: Uprising", "Экшен / Шутер от третьего лица", 2012, "Project Sora", "Nintendo", "WW", "Шедевр Масахиро Сакурая: полеты Пита на крыльях богини Палютены, наземные бои и сотни видов оружия."),
                ("Bravely Default", "JRPG", 2012, "Silicon Studio / Square Enix", "Nintendo", "WW", "Революция пошаговых боев с механикой накопления и займа ходов Brave и Default, 24 профессиями."),
                ("Bravely Second: End Layer", "JRPG", 2015, "Silicon Studio / Square Enix", "Nintendo", "WW", "Продолжение саги Луксемдарка с рыцарем Ю Зенолсией и новыми безумными классами (Экзорцист, Кот-маг)."),
                ("Animal Crossing: New Leaf", "Симулятор жизни", 2012, "Nintendo EAD", "Nintendo", "WW", "Игрок становится мэром города: общественные проекты, законы города, остров Тортимера и клубы."),
                ("Metroid: Samus Returns", "Метроидвания", 2017, "MercurySteam / Nintendo", "Nintendo", "WW", "Шедевральное 2.5D переосмысление Metroid II: парирование рукопашным ударом Melee Counter и способности Aeion."),
                ("Ace Attorney: Dual Destinies", "Судебный роман Феникса, Аполло и Афины Сайкс", 2013, "Capcom", "Capcom", "WW", "Ace Attorney: Dual Destinies — популярная игра для Nintendo 3DS / 2DS."),
                ("Ace Attorney: Spirit of Justice", "Суд в мистическом королевстве Кураин с сеансами спиритизма", 2016, "Capcom", "Capcom", "WW", "Ace Attorney: Spirit of Justice — популярная игра для Nintendo 3DS / 2DS."),
                ("Captain Toad: Treasure Tracker", "Головоломки Капитана Тоада в трехмерных диорамах", 2018, "Nintendo", "Nintendo", "WW", "Captain Toad: Treasure Tracker — популярная игра для Nintendo 3DS / 2DS."),
                ("Castlevania: Lords of Shadow - Mirror of Fate", "Метроидвания Тревора, Саймона и Алукарда от MercurySteam", 2013, "Konami", "Konami", "WW", "Castlevania: Lords of Shadow - Mirror of Fate — популярная игра для Nintendo 3DS / 2DS."),
                ("Cave Story 3D", "Трехмерный ремейк легендарной инди-метроидвании Дайсукэ Амайи", 2011, "NIS America", "NIS America", "WW", "Cave Story 3D — популярная игра для Nintendo 3DS / 2DS."),
                ("Corpse Party", "Психологический хоррор в проклятой начальной школе Тендзин", 2016, "XSEED", "XSEED", "WW", "Corpse Party — популярная игра для Nintendo 3DS / 2DS."),
                ("Dead or Alive Dimensions", "3D файтинг со всеми главами саги DOA", 2011, "Koei Tecmo", "Koei Tecmo", "WW", "Dead or Alive Dimensions — популярная игра для Nintendo 3DS / 2DS."),
                ("Donkey Kong Country Returns 3D", "Платформер Донки Конга с 8 новыми уровнями", 2013, "Nintendo", "Nintendo", "WW", "Donkey Kong Country Returns 3D — популярная игра для Nintendo 3DS / 2DS."),
                ("Dragon Ball Fusions", "Action-RPG с безумными слияниями любых персонажей DB", 2016, "Bandai Namco", "Bandai Namco", "WW", "Dragon Ball Fusions — популярная игра для Nintendo 3DS / 2DS."),
                ("Dragon Quest VII: Fragments of the Forgotten Past", "Монументальный 3D-ремейк DQ7 с восстановлением островов мира", 2016, "Square Enix / Nintendo", "Square Enix / Nintendo", "WW", "Dragon Quest VII: Fragments of the Forgotten Past — популярная игра для Nintendo 3DS / 2DS."),
                ("Dragon Quest VIII: Journey of the Cursed King", "Шедевр 3D JRPG с двумя новыми персонажами Ред и Мори", 2017, "Square Enix / Nintendo", "Square Enix / Nintendo", "WW", "Dragon Quest VIII: Journey of the Cursed King — популярная игра для Nintendo 3DS / 2DS."),
                ("Etrian Odyssey IV: Legends of the Titan", "Данжен-кроулер с дирижаблем над континентом", 2012, "Atlus", "Atlus", "WW", "Etrian Odyssey IV: Legends of the Titan — популярная игра для Nintendo 3DS / 2DS."),
                ("Etrian Odyssey V: Beyond the Myth", "Пятая часть исследования древа Иггдрасиль", 2016, "Atlus", "Atlus", "WW", "Etrian Odyssey V: Beyond the Myth — популярная игра для Nintendo 3DS / 2DS."),
                ("Etrian Odyssey Nexus", "Финальный масштабный кроссовер со всеми классами серии", 2018, "Atlus", "Atlus", "WW", "Etrian Odyssey Nexus — популярная игра для Nintendo 3DS / 2DS."),
                ("Etrian Odyssey Untold: The Millennium Girl", "Сюжетный ремейк первой части с анимациями Madhouse", 2013, "Atlus", "Atlus", "WW", "Etrian Odyssey Untold: The Millennium Girl — популярная игра для Nintendo 3DS / 2DS."),
                ("Etrian Odyssey Untold 2: The Fafnir Knight", "Сюжетный ремейк второй части с рыцарем Фафнира", 2015, "Atlus", "Atlus", "WW", "Etrian Odyssey Untold 2: The Fafnir Knight — популярная игра для Nintendo 3DS / 2DS."),
                ("Ever Oasis", "Action-RPG в пустыне с постройкой оазиса от Коити Исии (создателя Mana)", 2017, "Nintendo", "Nintendo", "WW", "Ever Oasis — популярная игра для Nintendo 3DS / 2DS."),
                ("Fantasy Life", "Симулятор жизни и RPG с 12 профессиями (Паладин, Кузнец, Маг, Повар, Алхимик) от Level-5", 2012, "Nintendo", "Nintendo", "WW", "Fantasy Life — популярная игра для Nintendo 3DS / 2DS."),
                ("Harvest Moon 3D: A New Beginning", "Симулятор фермы с полной кастомизацией города", 2012, "Natsume", "Natsume", "WW", "Harvest Moon 3D: A New Beginning — популярная игра для Nintendo 3DS / 2DS."),
                ("Inazuma Eleven GO: Light / Shadow", "Футбольная JRPG с призывом духов Keshin", 2011, "Level-5", "Level-5", "WW", "Inazuma Eleven GO: Light / Shadow — популярная игра для Nintendo 3DS / 2DS."),
                ("Kirby: Triple Deluxe", "2.5D платформер с гиперновой силой Hypernova и перемещением между планами", 2014, "Nintendo", "Nintendo", "WW", "Kirby: Triple Deluxe — популярная игра для Nintendo 3DS / 2DS."),
                ("Kirby: Planet Robobot", "Шедевр Кирби с управлением боевым мехом Robobot Armor с копированием способностей", 2016, "Nintendo", "Nintendo", "WW", "Kirby: Planet Robobot — популярная игра для Nintendo 3DS / 2DS."),
                ("Kirby's Extra Epic Yarn", "Тканевый мир Кирби с новыми шляпами и мини-играми Метанайта и Дидиди", 2019, "Nintendo", "Nintendo", "WW", "Kirby's Extra Epic Yarn — популярная игра для Nintendo 3DS / 2DS."),
                ("Layton's Mystery Journey: Katrielle and the Millionaires' Conspiracy", "Расследования дочери Лейтона Катриэль", 2017, "Level-5", "Level-5", "WW", "Layton's Mystery Journey: Katrielle and the Millionaires' Conspiracy — популярная игра для Nintendo 3DS / 2DS."),
                ("Lego City Undercover: The Chase Begins", "Приквел о становлении копа Чейза Маккейна в открытом Лего-городе", 2013, "Nintendo", "Nintendo", "WW", "Lego City Undercover: The Chase Begins — популярная игра для Nintendo 3DS / 2DS."),
                ("Luigi's Mansion", "3D-ремейк оригинального хита с GameCube с поддержкой кооператива", 2018, "Nintendo", "Nintendo", "WW", "Luigi's Mansion — популярная игра для Nintendo 3DS / 2DS."),
                ("Mario & Luigi: Dream Team", "Братья исследуют сны Луиджи с сотнями его проекций Luiginoids", 2013, "Nintendo", "Nintendo", "WW", "Mario & Luigi: Dream Team — популярная игра для Nintendo 3DS / 2DS."),
                ("Mario & Luigi: Paper Jam", "Кроссовер классических Марио и Луиджи с Бумажным Марио", 2015, "Nintendo", "Nintendo", "WW", "Mario & Luigi: Paper Jam — популярная игра для Nintendo 3DS / 2DS."),
                ("Mario & Luigi: Superstar Saga + Bowser's Minions", "Ремейк первой части с тактической кампанией за приспешников Боузера", 2017, "Nintendo", "Nintendo", "WW", "Mario & Luigi: Superstar Saga + Bowser's Minions — популярная игра для Nintendo 3DS / 2DS."),
                ("Mario & Luigi: Bowser's Inside Story + Bowser Jr.'s Journey", "Ремейк шедевра с историей Боузера Младшего", 2018, "Nintendo", "Nintendo", "WW", "Mario & Luigi: Bowser's Inside Story + Bowser Jr.'s Journey — популярная игра для Nintendo 3DS / 2DS."),
                ("Mario Golf: World Tour", "Гольф Марио от Camelot с онлайн-турнирами", 2014, "Nintendo", "Nintendo", "WW", "Mario Golf: World Tour — популярная игра для Nintendo 3DS / 2DS."),
                ("Mario Party: Island Tour", "Вечеринка с 7 уникальными игровыми досками", 2013, "Nintendo", "Nintendo", "WW", "Mario Party: Island Tour — популярная игра для Nintendo 3DS / 2DS."),
                ("Mario Sports Superstars", "5 видов спорта (Футбол, Бейсбол, Теннис, Гольф, Скачки)", 2017, "Nintendo", "Nintendo", "WW", "Mario Sports Superstars — популярная игра для Nintendo 3DS / 2DS."),
                ("Mario Tennis Open", "Теннис Марио с онлайн-матчами", 2012, "Nintendo", "Nintendo", "WW", "Mario Tennis Open — популярная игра для Nintendo 3DS / 2DS."),
                ("Metal Gear Solid: Snake Eater 3D", "Стелс-шедевр Нейкед Снейка в джунглях с автоприцелом гироскопа и фотокамуфляжем", 2012, "Konami", "Konami", "WW", "Metal Gear Solid: Snake Eater 3D — популярная игра для Nintendo 3DS / 2DS."),
                ("Miitopia", "Комедийная ролевая игра, где все роли (герои, злодеи, король) исполняют Mii-персонажи", 2016, "Nintendo", "Nintendo", "WW", "Miitopia — популярная игра для Nintendo 3DS / 2DS."),
                ("Monster Hunter Stories", "Сюжетная JRPG с ездой на монстрах (Оталках) и высиживанием яиц", 2016, "Capcom", "Capcom", "WW", "Monster Hunter Stories — популярная игра для Nintendo 3DS / 2DS."),
                ("New Super Mario Bros. 2", "Золотой платформер с целью собрать 1 000 000 золотых монет", 2012, "Nintendo", "Nintendo", "WW", "New Super Mario Bros. 2 — популярная игра для Nintendo 3DS / 2DS."),
                ("Persona Q: Shadow of the Labyrinth", "Кроссовер Persona 3 и Persona 4 в стиле данжен-кроулера", 2014, "Atlus", "Atlus", "WW", "Persona Q: Shadow of the Labyrinth — популярная игра для Nintendo 3DS / 2DS."),
                ("Persona Q2: New Cinema Labyrinth", "Кроссовер Persona 3, 4 и Persona 5 в мирах кинофильмов", 2018, "Atlus", "Atlus", "WW", "Persona Q2: New Cinema Labyrinth — популярная игра для Nintendo 3DS / 2DS."),
                ("Poochy & Yoshi's Woolly World", "Шерстяной мир Йоши с собачкой Пучи и редактором узоров", 2017, "Nintendo", "Nintendo", "WW", "Poochy & Yoshi's Woolly World — популярная игра для Nintendo 3DS / 2DS."),
                ("Professor Layton and the Miracle Mask", "Лейтон расследует тайну Маски Чудес в Монте-д'Ор", 2011, "Nintendo", "Nintendo", "WW", "Professor Layton and the Miracle Mask — популярная игра для Nintendo 3DS / 2DS."),
                ("Professor Layton and the Azran Legacy", "Финал саги о древней цивилизации Азран", 2013, "Nintendo", "Nintendo", "WW", "Professor Layton and the Azran Legacy — популярная игра для Nintendo 3DS / 2DS."),
                ("Professor Layton vs. Phoenix Wright: Ace Attorney", "Грандиозный кроссовер расследований Лейтона и судов Феникса в Лабиринтия", 2012, "Capcom / Level-5", "Capcom / Level-5", "WW", "Professor Layton vs. Phoenix Wright: Ace Attorney — популярная игра для Nintendo 3DS / 2DS."),
                ("Project X Zone", "Тактический кроссовер персонажей Capcom, Sega и Bandai Namco", 2012, "Bandai Namco", "Bandai Namco", "WW", "Project X Zone — популярная игра для Nintendo 3DS / 2DS."),
                ("Project X Zone 2", "Вторая часть кроссовера с появлением персонажей Nintendo (Ксеноблейд, Fire Emblem)", 2015, "Bandai Namco", "Bandai Namco", "WW", "Project X Zone 2 — популярная игра для Nintendo 3DS / 2DS."),
                ("Radiant Historia: Perfect Chronology", "Ультимативный ремейк путешествий во времени с третьей временной линией", 2017, "Atlus", "Atlus", "WW", "Radiant Historia: Perfect Chronology — популярная игра для Nintendo 3DS / 2DS."),
                ("Resident Evil: Revelations", "Графический шедевр Survival Horror Джилл Валентайн на океанском лайнере Queen Zenobia", 2012, "Capcom", "Capcom", "WW", "Resident Evil: Revelations — популярная игра для Nintendo 3DS / 2DS."),
                ("Resident Evil: The Mercenaries 3D", "Аркадный экшен уничтожения волн мутантов на время", 2011, "Capcom", "Capcom", "WW", "Resident Evil: The Mercenaries 3D — популярная игра для Nintendo 3DS / 2DS."),
                ("Rhythm Heaven Megamix (Rhythm Paradise Megamix)", "Ультимативный сборник более 100 ритм-игр всей серии", 2015, "Nintendo", "Nintendo", "WW", "Rhythm Heaven Megamix (Rhythm Paradise Megamix) — популярная игра для Nintendo 3DS / 2DS."),
                ("Rune Factory 4", "Симулятор фермы принца/принцессы Леста с драконом Вентусвилл", 2012, "XSEED", "XSEED", "WW", "Rune Factory 4 — популярная игра для Nintendo 3DS / 2DS."),
                ("Shin Megami Tensei IV", "Грандиозная постапокалиптическая JRPG самурая Флинна в Восточном Микадо и Токио", 2013, "Atlus", "Atlus", "WW", "Shin Megami Tensei IV — популярная игра для Nintendo 3DS / 2DS."),
                ("Shin Megami Tensei IV: Apocalypse", "Сюжетное продолжение от лица Нанаси и бога Дагды", 2016, "Atlus", "Atlus", "WW", "Shin Megami Tensei IV: Apocalypse — популярная игра для Nintendo 3DS / 2DS."),
                ("Shin Megami Tensei: Devil Summoner - Soul Hackers", "Киберпанк JRPG хакеров Spookies в виртуальном городе Амами", 2012, "Atlus", "Atlus", "WW", "Shin Megami Tensei: Devil Summoner - Soul Hackers — популярная игра для Nintendo 3DS / 2DS."),
                ("Shin Megami Tensei: Devil Survivor Overclocked", "Расширенный ремейк тактической RPG с 8-м днем выживания", 2011, "Atlus", "Atlus", "WW", "Shin Megami Tensei: Devil Survivor Overclocked — популярная игра для Nintendo 3DS / 2DS."),
                ("Shin Megami Tensei: Devil Survivor 2 Record Breaker", "Ремейк со второй полноценной сюжетной кампанией Триангулюм", 2015, "Atlus", "Atlus", "WW", "Shin Megami Tensei: Devil Survivor 2 Record Breaker — популярная игра для Nintendo 3DS / 2DS."),
                ("Shin Megami Tensei: Strange Journey Redux", "Расширенный ремейк экспедиции в Шварцвельт с новой героиней Алекс", 2017, "Atlus", "Atlus", "WW", "Shin Megami Tensei: Strange Journey Redux — популярная игра для Nintendo 3DS / 2DS."),
                ("Shovel Knight", "Ретро-платформер Лопатного Рыцаря со всеми кампаниями (Plague, Specter, King)", 2014, "Yacht Club", "Yacht Club", "WW", "Shovel Knight — популярная игра для Nintendo 3DS / 2DS."),
                ("Sonic Generations 3D", "Платформер классического и современного Соника с эксклюзивными уровнями от Dimps", 2011, "Sega", "Sega", "WW", "Sonic Generations 3D — популярная игра для Nintendo 3DS / 2DS."),
                ("Sonic Lost World 3D", "Платформер Соника на сферических уровнях", 2013, "Sega", "Sega", "WW", "Sonic Lost World 3D — популярная игра для Nintendo 3DS / 2DS."),
                ("Star Fox 64 3D", "Ремейк Arwing в 3D с управлением гироскопом", 2011, "Nintendo", "Nintendo", "WW", "Star Fox 64 3D — популярная игра для Nintendo 3DS / 2DS."),
                ("Stella Glow", "Тактическая JRPG альто-рыцарей и 5 поющих ведьм от Imageepoch", 2015, "Atlus", "Atlus", "WW", "Stella Glow — популярная игра для Nintendo 3DS / 2DS."),
                ("Story of Seasons (Bokujou Monogatari)", "Симулятор фермы с международной торговлей", 2014, "XSEED", "XSEED", "WW", "Story of Seasons (Bokujou Monogatari) — популярная игра для Nintendo 3DS / 2DS."),
                ("Story of Seasons: Trio of Towns", "Ферма в трех разных культурах (Западная, Гавайская, Восточная)", 2016, "XSEED", "XSEED", "WW", "Story of Seasons: Trio of Towns — популярная игра для Nintendo 3DS / 2DS."),
                ("Super Mario Maker for Nintendo 3DS", "Конструктор уровней Марио с обменом через StreetPass и 100 испытаниями", 2016, "Nintendo", "Nintendo", "WW", "Super Mario Maker for Nintendo 3DS — популярная игра для Nintendo 3DS / 2DS."),
                ("Tales of the Abyss", "Портативное издание 3D JRPG Люка фон Фабре", 2011, "Bandai Namco", "Bandai Namco", "WW", "Tales of the Abyss — популярная игра для Nintendo 3DS / 2DS."),
                ("Theatrhythm Final Fantasy: Curtain Call", "Ритм-игра с более чем 220 музыкальными темами всей саги Final Fantasy", 2014, "Square Enix", "Square Enix", "WW", "Theatrhythm Final Fantasy: Curtain Call — популярная игра для Nintendo 3DS / 2DS."),
                ("Theatrhythm Dragon Quest", "Ритм-игра по бессмертной музыке Коити Сугиямы", 2015, "Square Enix", "Square Enix", "WW", "Theatrhythm Dragon Quest — популярная игра для Nintendo 3DS / 2DS."),
                ("Tom Clancy's Ghost Recon: Shadow Wars", "Пошаговая тактика спецназа от Джулиана Голлопа (создателя X-COM)", 2011, "Ubisoft", "Ubisoft", "WW", "Tom Clancy's Ghost Recon: Shadow Wars — популярная игра для Nintendo 3DS / 2DS."),
                ("WarioWare Gold", "Самый большой сборник микро-игр с полной озвучкой и всеми стилями управления", 2018, "Nintendo", "Nintendo", "WW", "WarioWare Gold — популярная игра для Nintendo 3DS / 2DS."),
                ("Xenoblade Chronicles 3D", "Масштабная Sci-Fi JRPG Шулка на теле титана Биониса для New Nintendo 3DS", 2015, "Nintendo", "Nintendo", "WW", "Xenoblade Chronicles 3D — популярная игра для Nintendo 3DS / 2DS."),
                ("Yo-kai Watch", "Ловля японских духов ёкаев Нэйтаном с помощью волшебных часов от Level-5", 2013, "Nintendo", "Nintendo", "WW", "Yo-kai Watch — популярная игра для Nintendo 3DS / 2DS."),
                ("Yo-kai Watch 2: Bony Spirits / Fleshy Souls / Psychic Specters", "Путешествие в прошлое на 60 лет назад на поезде", 2014, "Nintendo", "Nintendo", "WW", "Yo-kai Watch 2: Bony Spirits / Fleshy Souls / Psychic Specters — популярная игра для Nintendo 3DS / 2DS."),
                ("Yo-kai Watch 3", "Американские приключения в городе Сент-Пинатсбург с сеткой боевого поля 3х3", 2016, "Nintendo", "Nintendo", "WW", "Yo-kai Watch 3 — популярная игра для Nintendo 3DS / 2DS."),
                ("Yo-kai Watch Blasters: Red Cat Corps / White Dog Squad", "Кооперативный экшен охотников на ёкаев", 2015, "Nintendo", "Nintendo", "WW", "Yo-kai Watch Blasters: Red Cat Corps / White Dog Squad — популярная игра для Nintendo 3DS / 2DS."),
                ("Yoshi's New Island", "Остров Йоши с гигантскими яйцами Mega Eggdozers", 2014, "Nintendo", "Nintendo", "WW", "Yoshi's New Island — популярная игра для Nintendo 3DS / 2DS."),
                ("Pokemon X", "JRPG", 2013, "Game Freak", "Nintendo", "WW", "Шестое поколение в регионе Калос: трехмерная графика, Мега-эволюции и феи."),
                ("Pokemon Y", "JRPG", 2013, "Game Freak", "Nintendo", "WW", "Легендарный Ивельтал и поке-глажение Pokemon-Amie."),
                ("Pokemon Sun", "JRPG", 2016, "Game Freak", "Nintendo", "WW", "Седьмое поколение на тропических островах Алола с Z-атаками и региональными формами."),
                ("Pokemon Moon", "JRPG", 2016, "Game Freak", "Nintendo", "WW", "Легендарная Лунала и испытания островов без традиционных гимов."),
                ("Pokemon Ultra Sun", "JRPG", 2017, "Game Freak", "Nintendo", "WW", "Некрозма, полеты через ультра-червоточины и Команда Радужная Ракета."),
                ("Pokemon Ultra Moon", "JRPG", 2017, "Game Freak", "Nintendo", "WW", "Ультра-мегалополис и новые Ультра-чудовища."),
                ("Luigi's Mansion: Dark Moon (2)", "Action-Adventure", 2013, "Next Level Games", "Nintendo", "WW", "Луиджи с Poltergust 5000 и ультрафиолетовым фонарем исследует 5 особняков."),
            };

            foreach (var g in games)
            {
                list.Add(new NintendoCatalogItem
                {
                    Title = g.Title,
                    Genre = g.Genre,
                    Year = g.Year,
                    Developer = g.Dev,
                    Publisher = g.Pub,
                    Region = g.Region,
                    Desc = g.Desc
                });
            }

            return list;
        }
    }
}
