using System;
using System.Collections.Generic;

namespace StormSwitchBox.Services
{
    public static class WiiCatalogData
    {
        public static List<NintendoCatalogItem> GetCatalog()
        {
            var list = new List<NintendoCatalogItem>(215);

            var games = new (string Title, string Genre, int Year, string Dev, string Pub, string Region, string Desc)[]
            {
                ("Super Mario Galaxy", "3D Платформер", 2007, "Nintendo EAD Tokyo", "Nintendo", "WW", "Шедевр всех времен: сферическая гравитация маленьких планет, оркестровый саундтрек и Розалина."),
                ("Super Mario Galaxy 2", "3D Платформер", 2010, "Nintendo EAD Tokyo", "Nintendo", "WW", "Вершина 3D-платформинга: Йоши с трансформациями, бур Spin Drill, космический корабль Звездный Лик."),
                ("The Legend of Zelda: Skyward Sword", "Action-Adventure", 2011, "Nintendo EAD", "Nintendo", "WW", "Хронологическое начало саги Зельды: фехтование 1:1 с Wii MotionPlus, полет на Небокрылах и кузница Master Sword."),
                ("The Legend of Zelda: Twilight Princess", "Action-Adventure", 2006, "Nintendo EAD", "Nintendo", "WW", "Линк-волк и Мидна в Сумеречном Царстве с управлением луком и мечом прицелом Wiimote."),
                ("Super Smash Bros. Brawl", "Файтинг-кроссовер", 2008, "Ad hoc / Nintendo", "Nintendo", "WW", "Полноценная кинематографичная кампания Subspace Emissary, появление Соника и Солида Снейка."),
                ("Mario Kart Wii", "Картинговые гонки", 2008, "Nintendo EAD", "Nintendo", "WW", "Глобальный суперхит (37+ млн копий): появление мотоциклов с трюками, руль Wii Wheel и 12 гонщиков в онлайне."),
                ("Xenoblade Chronicles", "Sci-Fi JRPG", 2010, "Monolith Soft", "Nintendo", "WW", "Грандиозный открытый мир на телах титанов Биониса и Мехониса, меч Монадо с видениями будущего Шулка."),
                ("Metroid Prime Trilogy", "Сборник шутеров от первого лица", 2009, "Retro Studios", "Nintendo", "WW", "Все три части великой трилогии Metroid Prime с безупречным прицеливанием пультом Wii Remote."),
                ("Metroid Prime 3: Corruption", "Шутер от первого лица", 2007, "Retro Studios", "Nintendo", "WW", "Самус Аран сражается с фазоновой заразой и Темной Самус в режиме гипер-состояния Hypermode."),
                ("Donkey Kong Country Returns", "2D Платформер", 2010, "Retro Studios", "Nintendo", "WW", "Возрождение легендарной серии: безумная динамика, вагонетки, ракетные бочки и племя Тики."),
                ("Wii Sports", "Спортивный симулятор движений", 2006, "Nintendo EAD", "Nintendo", "WW", "Самая продаваемая одиночная игра в истории (82+ млн копий): Теннис, Боулинг, Бейсбол, Гольф, Бокс."),
                ("Wii Sports Resort", "Спортивный симулятор", 2009, "Nintendo EAD", "Nintendo", "WW", "Остров Уху с 12 видами спорта на сверхточном датчике Wii MotionPlus (Мечи, Стрельба из лука, Вейкбординг, Самолет)."),
                ("New Super Mario Bros. Wii", "Кооперативный платформер", 2009, "Nintendo EAD", "Nintendo", "WW", "Впервые в серии: безумное одновременное прохождение вчетвером за Марио, Луиджи и двух Тоадов."),
                ("Monster Hunter Tri", "Action-RPG", 2009, "Capcom", "Capcom", "WW", "Подводная охота, появление левиафана Лагиакруса и онлайн-город Лок Лак."),
                ("Resident Evil 4: Wii Edition", "Survival Horror / Экшен", 2007, "Capcom", "Capcom", "WW", "Лучшая версия RE4 благодаря идеальному и молниеносному лазерному прицеливанию контроллером Wiimote."),
                ("The Last Story", "Action-RPG", 2011, "Mistwalker", "Nintendo", "WW", "Шедевр Хиронобу Сакагути: наемник Заэл на острове Лазулис с механикой концентрации внимания врагов Gathering."),
                ("Pandora's Tower", "Action-RPG", 2011, "Ganbarion", "Nintendo", "WW", "Эрон штурмует 13 башен с цепью Oraclos Chain, чтобы спасти возлюбленную Елену от превращения в чудовище."),
                ("Super Paper Mario", "Платформер / RPG", 2007, "Intelligent Systems", "Nintendo", "WW", "Марио переключает перспективу из 2D в 3D на лету в глубокой истории графа Блека и Типпи."),
                ("Punch-Out!!", "Спорт / Бокс", 2009, "Next Level Games", "Nintendo", "WW", "Великолепный аркадный бокс Литтл Мака с Balance Board и колоритными противниками в сочной анимации."),
                ("No More Heroes", "Стилизованный слэшер", 2007, "Grasshopper / Suda51", "Ubisoft", "WW", "Трэвис Тачдаун с лазерной катаной пробивается на первое место в рейтинге Ассоциации Киллеров UAA."),
                ("No More Heroes 2: Desperate Struggle", "Слэшер", 2010, "Grasshopper / Suda51", "Ubisoft", "WW", "Двойные световые катаны, 8-битные ретро-подработки и кровавая месть за друга."),
                ("Sin & Punishment: Star Successor", "Аркадный 3D SHMUP", 2009, "Treasure", "Nintendo", "WW", "Абсолютный шедевр скоростной стрельбы от Treasure с Исой и Кати при 60 FPS."),
                ("Okami", "Action-Adventure", 2008, "Ready at Dawn / Capcom", "Capcom", "WW", "Богиня-волчица Аматерасу рисует небесной кистью Celestial Brush прямо в воздухе движением руки."),
                ("Rayman Origins", "2D Платформер", 2011, "Ubisoft Montpellier", "Ubisoft", "WW", "Безумно красивый кооперативный платформер Мишеля Анселя на 4 игроков на движке UbiArt Framework."),
                ("Kirby's Return to Dream Land (Kirby's Adventure Wii)", "2D Платформер", 2011, "HAL Laboratory", "Nintendo", "WW", "Кооператив на 4 игроков (Кирби, Метанайт, Дидиди, Бандана Ваддл Ди) с ультра-мечами Super Abilities."),
                ("A Boy and His Blob", "Пазл-платформер мальчика и капли-трансформера от WayForward", 2009, "Majesco", "Majesco", "WW", "A Boy and His Blob — популярная игра для Nintendo Wii."),
                ("Animal Crossing: City Folk (Let's Go to the City)", "Симулятор жизни с поездками на автобусе в большой город", 2008, "Nintendo", "Nintendo", "WW", "Animal Crossing: City Folk (Let's Go to the City) — популярная игра для Nintendo Wii."),
                ("Battalion Wars 2 (BWii)", "Тактический экшен на суше, в воздухе и на море от Kuju", 2007, "Nintendo", "Nintendo", "WW", "Battalion Wars 2 (BWii) — популярная игра для Nintendo Wii."),
                ("Boom Blox", "Физическая головоломка разрушения башен от Стивена Спилберга и EA", 2008, "EA", "EA", "WW", "Boom Blox — популярная игра для Nintendo Wii."),
                ("Boom Blox Bash Party", "Вторая часть головоломки Спилберга с 400 уровнями", 2009, "EA", "EA", "WW", "Boom Blox Bash Party — популярная игра для Nintendo Wii."),
                ("Call of Duty: World at War", "Военный FPS на тихоокеанском фронте с прицелом Wiimote", 2008, "Activision", "Activision", "WW", "Call of Duty: World at War — популярная игра для Nintendo Wii."),
                ("Call of Duty: Black Ops", "Спецоперации холодной войны Мэйсона на Wii", 2010, "Activision", "Activision", "WW", "Call of Duty: Black Ops — популярная игра для Nintendo Wii."),
                ("Call of Duty: Modern Warfare: Reflex Edition", "Адаптация Modern Warfare 1 с онлайном", 2009, "Activision", "Activision", "WW", "Call of Duty: Modern Warfare: Reflex Edition — популярная игра для Nintendo Wii."),
                ("Castlevania Judgment", "3D файтинг бойцов Castlevania с дизайном Такэси Обаты (Death Note)", 2008, "Konami", "Konami", "WW", "Castlevania Judgment — популярная игра для Nintendo Wii."),
                ("Dead Space: Extraction", "Кинематографичный рельсовый хоррор-шутер от первого лица на корабле USG Ишимура", 2009, "EA", "EA", "WW", "Dead Space: Extraction — популярная игра для Nintendo Wii."),
                ("de Blob", "Раскрашивание монохромного города Чунг-Сити шариком краски Блобом", 2008, "THQ", "THQ", "WW", "de Blob — популярная игра для Nintendo Wii."),
                ("de Blob 2", "Вторая часть раскрашивания города красками", 2011, "THQ", "THQ", "WW", "de Blob 2 — популярная игра для Nintendo Wii."),
                ("Disaster: Day of Crisis", "Кинематографичный экшен выживания в эпицентре 10 природных катастроф от Monolith Soft", 2008, "Nintendo", "Nintendo", "WW", "Disaster: Day of Crisis — популярная игра для Nintendo Wii."),
                ("Disney Epic Mickey", "Микки Маус с волшебной кистью с краской и растворителем в Пустоши от Уоррена Спектора", 2010, "Disney", "Disney", "WW", "Disney Epic Mickey — популярная игра для Nintendo Wii."),
                ("Disney Epic Mickey 2: The Power of Two", "Кооперативные приключения Микки Мауса и кролика Освальда", 2012, "Disney", "Disney", "WW", "Disney Epic Mickey 2: The Power of Two — популярная игра для Nintendo Wii."),
                ("Dragon Quest Swords: The Masked Queen and the Tower of Mirrors", "Экшен от первого лица с фехтованием мечом Wiimote", 2007, "Square Enix", "Square Enix", "WW", "Dragon Quest Swords: The Masked Queen and the Tower of Mirrors — популярная игра для Nintendo Wii."),
                ("Elebits (Eledees)", "Поиск электрических существ Элебитов с грави-лучом в стиле Half-Life", 2006, "Konami", "Konami", "WW", "Elebits (Eledees) — популярная игра для Nintendo Wii."),
                ("Excite Truck", "Гонки на бигфутах с терраформированием ландшафта на лету", 2006, "Nintendo", "Nintendo", "WW", "Excite Truck — популярная игра для Nintendo Wii."),
                ("Excitebots: Trick Racing", "Гонки на роботах-животных с безумными мини-играми (дартс, сэндвичи, пироги)", 2009, "Nintendo", "Nintendo", "WW", "Excitebots: Trick Racing — популярная игра для Nintendo Wii."),
                ("Final Fantasy Crystal Chronicles: The Crystal Bearers", "Action-Adventure Лейлы с телекинезом и гравитацией", 2009, "Square Enix", "Square Enix", "WW", "Final Fantasy Crystal Chronicles: The Crystal Bearers — популярная игра для Nintendo Wii."),
                ("Fire Emblem: Radiant Dawn", "Эпическая 4-частная тактическая RPG: Микая, бригада Рассвета и возвращение Айка", 2007, "Nintendo", "Nintendo", "WW", "Fire Emblem: Radiant Dawn — популярная игра для Nintendo Wii."),
                ("Fortune Street (Boom Street)", "Экономическая настольная игра с персонажами Mario и Dragon Quest", 2011, "Nintendo / Square Enix", "Nintendo / Square Enix", "WW", "Fortune Street (Boom Street) — популярная игра для Nintendo Wii."),
                ("Fragile Dreams: Farewell Ruins of the Moon", "Атмосферный постапокалиптический квест Сето с фонариком по заброшенному Токио", 2009, "XSEED", "XSEED", "WW", "Fragile Dreams: Farewell Ruins of the Moon — популярная игра для Nintendo Wii."),
                ("Ghost Squad", "Аркадный армейский световой тир от Sega", 2007, "Sega", "Sega", "WW", "Ghost Squad — популярная игра для Nintendo Wii."),
                ("GoldenEye 007 (Remake)", "Современное переосмысление с Дэниелом Крейгом от Eurocom", 2010, "Activision", "Activision", "WW", "GoldenEye 007 (Remake) — популярная игра для Nintendo Wii."),
                ("Guilty Gear XX Accent Core Plus", "2D файтинг", 2008, "Aksys", "Aksys", "WW", "Guilty Gear XX Accent Core Plus — популярная игра для Nintendo Wii."),
                ("House of the Dead: Overkill, The", "Грайндхаус-хоррор тир спецагента Вашингтона и агента G", 2009, "Sega", "Sega", "WW", "House of the Dead: Overkill, The — популярная игра для Nintendo Wii."),
                ("House of the Dead 2 & 3 Return, The", "Сборник аркадных тиров Sega", 2008, "Sega", "Sega", "WW", "House of the Dead 2 & 3 Return, The — популярная игра для Nintendo Wii."),
                ("Just Dance", "Старт танцевального феномена Ubisoft с повторением движений", 2009, "Ubisoft", "Ubisoft", "WW", "Just Dance — популярная игра для Nintendo Wii."),
                ("Just Dance 2", "Суперхит вечеринок с командными танцами", 2010, "Ubisoft", "Ubisoft", "WW", "Just Dance 2 — популярная игра для Nintendo Wii."),
                ("Just Dance 3", "Танцевальный хит", 2011, "Ubisoft", "Ubisoft", "WW", "Just Dance 3 — популярная игра для Nintendo Wii."),
                ("Just Dance 4", "Танцевальный хит", 2012, "Ubisoft", "Ubisoft", "WW", "Just Dance 4 — популярная игра для Nintendo Wii."),
                ("Just Dance 2020", "Финальная игра, выпущенная на Nintendo Wii спустя 14 лет после запуска консоли!", 2019, "Ubisoft", "Ubisoft", "WW", "Just Dance 2020 — популярная игра для Nintendo Wii."),
                ("Kirby's Epic Yarn", "Невероятно уютный шерстяной мир Кирби и принца Флаффа от Good-Feel", 2010, "Nintendo", "Nintendo", "WW", "Kirby's Epic Yarn — популярная игра для Nintendo Wii."),
                ("Klonoa", "Красивый 2.5D ремейк первой части Клоноа Door to Phantomile", 2008, "Bandai Namco", "Bandai Namco", "WW", "Klonoa — популярная игра для Nintendo Wii."),
                ("Kororinpa: Marble Mania", "Прокатывание шарика по трехмерным лабиринтам наклоном пульта Wiimote", 2006, "Hudson Soft", "Hudson Soft", "WW", "Kororinpa: Marble Mania — популярная игра для Nintendo Wii."),
                ("Lego Star Wars: The Complete Saga", "Все 6 эпизодов Звездных Войн в Лего", 2007, "LucasArts", "LucasArts", "WW", "Lego Star Wars: The Complete Saga — популярная игра для Nintendo Wii."),
                ("Lost In Shadow (A Shadow's Tale)", "Поэтичный платформер тени мальчика, бегущей по теням башни от Hudson Soft", 2010, "Hudson Soft", "Hudson Soft", "WW", "Lost In Shadow (A Shadow's Tale) — популярная игра для Nintendo Wii."),
                ("MadWorld", "Черно-бело-красный ультра-жестокий слэшер Джека с бензопилой в реалити-шоу DeathWatch от PlatinumGames", 2009, "Sega", "Sega", "WW", "MadWorld — популярная игра для Nintendo Wii."),
                ("Mario & Sonic at the Olympic Games", "Олимпийские игры 2008", 2007, "Sega", "Sega", "WW", "Mario & Sonic at the Olympic Games — популярная игра для Nintendo Wii."),
                ("Mario & Sonic at the Olympic Winter Games", "Зимние игры 2010 с Balance Board", 2009, "Sega", "Sega", "WW", "Mario & Sonic at the Olympic Winter Games — популярная игра для Nintendo Wii."),
                ("Mario & Sonic at the London 2012 Olympic Games", "Олимпийские игры в Лондоне 2012", 2011, "Sega", "Sega", "WW", "Mario & Sonic at the London 2012 Olympic Games — популярная игра для Nintendo Wii."),
                ("Mario Party 8", "Первая вечеринка на Wii с управлением движениями", 2007, "Nintendo", "Nintendo", "WW", "Mario Party 8 — популярная игра для Nintendo Wii."),
                ("Mario Party 9", "Вечеринка с совместной поездкой всех 4 игроков на одном вездеходе", 2012, "Nintendo", "Nintendo", "WW", "Mario Party 9 — популярная игра для Nintendo Wii."),
                ("Mario Sports Mix", "Хоккей, Баскетбол, Вышибалы и Волейбол с персонажами Mario и Final Fantasy (Черный Маг, Мугл)", 2010, "Nintendo / Square Enix", "Nintendo / Square Enix", "WW", "Mario Sports Mix — популярная игра для Nintendo Wii."),
                ("Mario Strikers Charged", "Ураганный кибер-футбол с электрической оградой, суперударами Mega Strikes и онлайном", 2007, "Nintendo", "Nintendo", "WW", "Mario Strikers Charged — популярная игра для Nintendo Wii."),
                ("Mario Super Sluggers", "Бейсбол Марио с движением руки как битой от Bandai Namco", 2008, "Nintendo", "Nintendo", "WW", "Mario Super Sluggers — популярная игра для Nintendo Wii."),
                ("Medal of Honor: Heroes 2", "32-пользовательский онлайн FPS", 2007, "EA", "EA", "WW", "Medal of Honor: Heroes 2 — популярная игра для Nintendo Wii."),
                ("Muramasa: The Demon Blade", "Живописный японский слэшер Момохимэ и Кисукэ с 108 мечами от Vanillaware", 2009, "Ignition", "Ignition", "WW", "Muramasa: The Demon Blade — популярная игра для Nintendo Wii."),
                ("Need for Speed: Nitro", "Стилизованные уличные гонки с кастомизацией граффити", 2009, "EA", "EA", "WW", "Need for Speed: Nitro — популярная игра для Nintendo Wii."),
                ("Nights: Journey of Dreams", "Полеты в мире снов Найта от Sonic Team", 2007, "Sega", "Sega", "WW", "Nights: Journey of Dreams — популярная игра для Nintendo Wii."),
                ("Pokepark Wii: Pikachu's Adventure", "3D приключения Пикачу в парке развлечений покемонов", 2009, "Nintendo", "Nintendo", "WW", "Pokepark Wii: Pikachu's Adventure — популярная игра для Nintendo Wii."),
                ("Pokepark 2: Wonders Beyond", "Пикачу, Ошавотт, Снайви и Тепиг спасают парк Желаний", 2011, "Nintendo", "Nintendo", "WW", "Pokepark 2: Wonders Beyond — популярная игра для Nintendo Wii."),
                ("Prince of Persia: The Forgotten Sands", "Эксклюзивная версия с созданием колец магии и парением", 2010, "Ubisoft", "Ubisoft", "WW", "Prince of Persia: The Forgotten Sands — популярная игра для Nintendo Wii."),
                ("Rabbids Go Home", "Комедийное приключение кролегов, собирающих гигантскую кучу хлама на Луну", 2009, "Ubisoft", "Ubisoft", "WW", "Rabbids Go Home — популярная игра для Nintendo Wii."),
                ("Rayman Raving Rabbids", "Безумные мини-игры с вантузами и бешеными кролегами", 2006, "Ubisoft", "Ubisoft", "WW", "Rayman Raving Rabbids — популярная игра для Nintendo Wii."),
                ("Red Steel", "Стартовый боевик якудза с перестрелками и дуэлями на катанах", 2006, "Ubisoft", "Ubisoft", "WW", "Red Steel — популярная игра для Nintendo Wii."),
                ("Red Steel 2", "Стильный вестерн-самурайский боевик в пустыне с точнейшим фехтованием Wii MotionPlus", 2010, "Ubisoft", "Ubisoft", "WW", "Red Steel 2 — популярная игра для Nintendo Wii."),
                ("Resident Evil: The Umbrella Chronicles", "Рельсовый хоррор-шутер с историей падения корпорации Амбрелла", 2007, "Capcom", "Capcom", "WW", "Resident Evil: The Umbrella Chronicles — популярная игра для Nintendo Wii."),
                ("Resident Evil: The Darkside Chronicles", "Рельсовый хоррор по событиям RE2 и Code Veronica", 2009, "Capcom", "Capcom", "WW", "Resident Evil: The Darkside Chronicles — популярная игра для Nintendo Wii."),
                ("Rhythm Heaven Fever (Beat the Beat: Rhythm Paradise)", "Шедевральная ритм-игра с барабанами, реслинг-интервью и кольцами", 2011, "Nintendo", "Nintendo", "WW", "Rhythm Heaven Fever (Beat the Beat: Rhythm Paradise) — популярная игра для Nintendo Wii."),
                ("Rune Factory: Frontier", "Симулятор фермы с китовым островом в небесах", 2008, "XSEED", "XSEED", "WW", "Rune Factory: Frontier — популярная игра для Nintendo Wii."),
                ("Rune Factory: Tides of Destiny (Oceans)", "Морские путешествия верхом на гигантском големе Йомире", 2011, "Natsume", "Natsume", "WW", "Rune Factory: Tides of Destiny (Oceans) — популярная игра для Nintendo Wii."),
                ("Silent Hill: Shattered Memories", "Психологический хоррор-переосмысление Гарри Мейсона без оружия с фонариком и телефоном", 2009, "Konami", "Konami", "WW", "Silent Hill: Shattered Memories — популярная игра для Nintendo Wii."),
                ("Sonic and the Secret Rings", "Скоростные приключения Соника в мире Тысячи и Одной Ночи с управлением наклонами", 2007, "Sega", "Sega", "WW", "Sonic and the Secret Rings — популярная игра для Nintendo Wii."),
                ("Sonic and the Black Knight", "Соник с говорящим мечом Калибурном в легендах о короле Артуре", 2009, "Sega", "Sega", "WW", "Sonic and the Black Knight — популярная игра для Nintendo Wii."),
                ("Sonic Colors", "Триумфальный скоростной платформер Соника в космическом парке Эггмана с силами Виспов", 2010, "Sega", "Sega", "WW", "Sonic Colors — популярная игра для Nintendo Wii."),
                ("Sonic Riders: Zero Gravity", "Гонки на гравитационных ховербордах", 2008, "Sega", "Sega", "WW", "Sonic Riders: Zero Gravity — популярная игра для Nintendo Wii."),
                ("Sonic Unleashed", "Дневные сверхзвуковые уровни ежа Соника и ночные драки оборотня-Werehog", 2008, "Sega", "Sega", "WW", "Sonic Unleashed — популярная игра для Nintendo Wii."),
                ("Super Monkey Ball: Banana Blitz", "Обезьянки в шарах с управлением движениями и 50 мини-играми", 2006, "Sega", "Sega", "WW", "Super Monkey Ball: Banana Blitz — популярная игра для Nintendo Wii."),
                ("Tatsunoko vs. Capcom: Ultimate All-Stars", "Великолепный кроссовер 2D файтинга бойцов Capcom и аниме-героев Tatsunoko", 2008, "Capcom", "Capcom", "WW", "Tatsunoko vs. Capcom: Ultimate All-Stars — популярная игра для Nintendo Wii."),
                ("Tenchu: Shadow Assassins", "Стелс-ниндзя Рикимару и Аяме от Acquire", 2008, "Ubisoft", "Ubisoft", "WW", "Tenchu: Shadow Assassins — популярная игра для Nintendo Wii."),
                ("Trauma Center: Second Opinion", "Хирургические операции ремейк с новыми миссиями", 2006, "Atlus", "Atlus", "WW", "Trauma Center: Second Opinion — популярная игра для Nintendo Wii."),
                ("Trauma Center: New Blood", "Кооперативные операции двух хирургов Маркуса и Валери", 2007, "Atlus", "Atlus", "WW", "Trauma Center: New Blood — популярная игра для Nintendo Wii."),
                ("Trauma Team", "Масштабный медицинский симулятор: Хирург, Диагност, Парамедик, Ортопед, Эндоскопист, Судмедэксперт", 2010, "Atlus", "Atlus", "WW", "Trauma Team — популярная игра для Nintendo Wii."),
                ("Wario Land: Shake It! (The Shake Dimension)", "Шедевр рисованной покадровой анимации от Production I.G и тряской сундуков", 2008, "Nintendo", "Nintendo", "WW", "Wario Land: Shake It! (The Shake Dimension) — популярная игра для Nintendo Wii."),
                ("WarioWare: Smooth Moves", "Безумные стойки с пультом («Слон», «Официант», «Самурай») на скорость", 2006, "Nintendo", "Nintendo", "WW", "WarioWare: Smooth Moves — популярная игра для Nintendo Wii."),
                ("Wii Fit", "Фитнес-тренировки, йога и аэробика с напольной доской Wii Balance Board", 2007, "Nintendo", "Nintendo", "WW", "Wii Fit — популярная игра для Nintendo Wii."),
                ("Wii Fit Plus", "Расширенная версия с тренировкой скейтбординга, полосой препятствий и подсчетом калорий", 2009, "Nintendo", "Nintendo", "WW", "Wii Fit Plus — популярная игра для Nintendo Wii."),
                ("Wii Party", "Вечеринка для всей семьи с использованием гостиной комнаты House Party", 2010, "Nintendo", "Nintendo", "WW", "Wii Party — популярная игра для Nintendo Wii."),
                ("Wii Play", "Сборник 9 мини-игр с легендарным режимом Танчики Tanks!", 2006, "Nintendo", "Nintendo", "WW", "Wii Play — популярная игра для Nintendo Wii."),
                ("Wii Play: Motion", "12 мини-игр для сверхточного датчика MotionPlus", 2011, "Nintendo", "Nintendo", "WW", "Wii Play: Motion — популярная игра для Nintendo Wii."),
                ("WWE SmackDown vs. Raw 2008", "Рестлинг", 2007, "THQ", "THQ", "WW", "WWE SmackDown vs. Raw 2008 — популярная игра для Nintendo Wii."),
                ("Zack & Wiki: Quest for Barbaros' Treasure", "Гениальный Point-and-Click квест юного пирата Зака и обезьянки от Capcom", 2007, "Capcom", "Capcom", "WW", "Zack & Wiki: Quest for Barbaros' Treasure — популярная игра для Nintendo Wii."),
                ("The Legend of Zelda: Twilight Princess (Wii)", "Action-Adventure", 2006, "Nintendo EAD", "Nintendo", "WW", "Управление мечом и луком взмахами контроллера Wii Remote."),
                ("Metroid: Other M", "Action-слэшер", 2010, "Team Ninja / Nintendo", "Nintendo", "WW", "История Самус Аран и Адама Малковича от Team Ninja с кинематографичными добиваниями."),
                ("Sin and Punishment: Star Successor", "3D Рельсовый шутер", 2009, "Treasure", "Nintendo", "WW", "Ультимативный безостановочный боевик от Treasure с идеальным управлением Wii Remote."),
                ("Punch-Out!! (Wii)", "Аркадный бокс", 2009, "Next Level Games", "Nintendo", "WW", "Литтл Мак и тренер Док Луис против колоритных мировых боксеров с поддержкой Balance Board."),
                ("Kirby's Return to Dream Land", "2D Платформер", 2011, "HAL Laboratory", "Nintendo", "WW", "Кооператив на 4 игроков с супер-способностями Ultra Sword и починкой корабля Лора Старкаттер."),
                ("Rhythm Heaven Fever (Beat the Beat)", "Ритм-игра", 2011, "Nintendo / TNX", "Nintendo", "WW", "Безумно стильная и смешная ритм-игра под авторством продюсера Цунку (Tsunku)."),
            };

            foreach (var g in games)
            {
                list.Add(new NintendoCatalogItem
                {
                    Title = g.Title,
                    Genre = g.Genre,
                    Year = g.Year,
                    Developer = g.Dev,
                    Publisher = g.Pub,
                    Region = g.Region,
                    Desc = g.Desc
                });
            }

            return list;
        }
    }
}
