using System;
using System.Collections.Generic;

namespace StormSwitchBox.Services
{
    public class LocalizationService
    {
        public static LocalizationService Instance { get; } = new LocalizationService();

        public event Action? LanguageChanged;

        private string _currentLanguage = "ru";

        public string CurrentLanguage
        {
            get => _currentLanguage;
            set
            {
                if (_currentLanguage != value)
                {
                    _currentLanguage = value switch
                    {
                        "en" => "en",
                        "de" => "de",
                        "zh" => "zh",
                        "ja" => "ja",
                        _ => "ru"
                    };
                    LanguageChanged?.Invoke();
                }
            }
        }

        public string this[string key] => GetString(key);

        public string GetString(string key)
        {
            if (string.IsNullOrEmpty(key)) return "";

            if (_strings.TryGetValue(_currentLanguage, out var dict) && dict.TryGetValue(key, out var val))
            {
                return val;
            }

            // Fallback to Russian
            if (_strings.TryGetValue("ru", out var ruDict) && ruDict.TryGetValue(key, out var ruVal))
            {
                return ruVal;
            }

            return key;
        }

        public static readonly (string Code, string Name)[] SupportedLanguages = new[]
        {
            ("ru", "Русский"),
            ("en", "English"),
            ("de", "Deutsch"),
            ("zh", "中文"),
            ("ja", "日本語")
        };

        private readonly Dictionary<string, Dictionary<string, string>> _strings = new(StringComparer.OrdinalIgnoreCase)
        {
            ["ru"] = new Dictionary<string, string>
            {
                // App & Tray
                ["App_Title"] = "STORM SWITCH BOX",
                ["Tray_Title"] = "STORM SWITCH BOX",
                ["Tray_Restore"] = "Развернуть",
                ["Tray_Exit"] = "Выход",

                // Navigation
                ["Nav_Update"] = "Обновление",
                ["Nav_Unpack"] = "Распаковка",
                ["Nav_Pack"] = "Упаковка",
                ["Nav_Convert"] = "Конвертация",
                ["Nav_Multi"] = "Мульти-контент",
                ["Nav_Verify"] = "Проверка",
                ["Nav_Instruction"] = "Инструкция",
                ["Nav_GameLibrary"] = "Библиотека игр",
                ["Nav_Catalog"] = "Информация",
                ["Nav_History"] = "История",
                ["Nav_Settings"] = "Параметры",

                // Tasks Common
                ["Tasks_AddFiles"] = "Добавить файлы",
                ["Tasks_AddFolder"] = "Добавить папку",
                ["Tasks_ClearList"] = "Очистить список",
                ["Tasks_StartAll"] = "Запустить все",
                ["Tasks_StopAll"] = "Остановить все",
                ["Tasks_TargetFormat"] = "Целевой формат:",
                ["Tasks_Col_Game"] = "Игра / Задача",
                ["Tasks_Col_Format"] = "Формат",
                ["Tasks_Col_Files"] = "Файлы",
                ["Tasks_Col_Size"] = "Размер",
                ["Tasks_Col_Status"] = "Статус",
                ["Tasks_Col_Progress"] = "Прогресс",
                ["Tasks_Col_Actions"] = "Действия",
                ["Tasks_EmptyHint"] = "Список задач пуст. Добавьте файлы кнопками выше или перетащите их в окно программы.",
                ["Tasks_DropHint"] = "Перетащите файлы или папки сюда для автоматического добавления",
                ["Tasks_Status_Pending"] = "Ожидание",
                ["Tasks_Status_Processing"] = "Обработка...",
                ["Tasks_Status_Success"] = "Завершено",
                ["Tasks_Status_Error"] = "Ошибка",
                ["Tasks_Status_Cancelled"] = "Отменено",
                ["Tasks_Menu_EditMetadata"] = "Редактировать метаданные и иконку",
                ["Tasks_Menu_OpenFolder"] = "Открыть папку с файлом",
                ["Tasks_Menu_Delete"] = "Удалить задачу",
                ["Tasks_Menu_ChangeFormat"] = "Сменить формат",

                // Settings Tabs
                ["Settings_Title"] = "Параметры",
                ["Settings_Tab_General"] = "Общие",
                ["Settings_Tab_Switch"] = "Nintendo Switch",
                ["Settings_Tab_3ds"] = "Nintendo 3DS",

                // Settings General
                ["Settings_General_Language_Header"] = "Язык интерфейса",
                ["Settings_General_Language_Title"] = "Язык интерфейса",
                ["Settings_General_Language_Desc"] = "Выберите основной язык приложения (применяется мгновенно)",
                ["Settings_General_Appearance_Header"] = "Оформление и звуковые уведомления",
                ["Settings_General_Sound_Title"] = "Звуковые уведомления",
                ["Settings_General_Sound_Desc"] = "Воспроизводить звуковой сигнал по окончании выполнения очереди задач",
                ["Settings_General_Theme_Title"] = "Тема оформления интерфейса",
                ["Settings_General_Theme_Desc"] = "Выбор общей стилистической темы оформления приложения",
                ["Settings_General_Accent_Title"] = "Цветовой акцент интерфейса",
                ["Settings_General_Accent_Desc"] = "Выбор главного акцентного цвета элементов приложения",
                ["Settings_General_Files_Header"] = "Пути и организация файлов",
                ["Settings_General_Complex_Title"] = "Комплексное выходное имя файла по папкам",
                ["Settings_General_Complex_Desc"] = "Создает удобные вложенные папки формата [Название Игры]/[Формат] с TitleID и версией в названии",
                ["Settings_General_DeleteSource_Title"] = "Удалять исходные файлы после успешной обработки",
                ["Settings_General_DeleteSource_Desc"] = "Автоматически удаляет оригинальный входной файл после успешной конвертации или сборки",
                ["Settings_General_Perf_Header"] = "Производительность и сжатие",
                ["Settings_General_Compression_Title"] = "Уровень сжатия Zstandard (NSZ / XCZ)",
                ["Settings_General_Compression_Desc"] = "Выбор уровня сжатия алгоритма Zstd (от Быстрого 3 до Ультра 22)",
                ["Settings_General_Tasks_Title"] = "Максимум одновременных задач",
                ["Settings_General_Tasks_Desc"] = "Количество задач, выполняемых одновременно в фоновой очереди (от 1 до 5)",
                ["Settings_General_Threads_Title"] = "Многопоточность (Используемые ядра)",
                ["Settings_General_Threads_Desc"] = "Максимальное количество ядер ЦП, выделяемых для ZstdSharp-сжатия",
                ["Settings_General_About_Header"] = "О программе",
                ["Settings_General_About_Desc"] = "Специализированный комбайн для обработки, сжатия и конвертации игр Nintendo Switch и Nintendo 3DS. Нативная интеграция высокопроизводительных алгоритмов для максимальной производительности.",
                ["Settings_General_CheckUpdates"] = "Проверить обновления",
                ["Settings_General_OpenLogs"] = "Открыть папку с логами",

                // Settings Switch
                ["Settings_Switch_Keys_Header"] = "Криптографические ключи Nintendo Switch",
                ["Settings_Switch_Keys_Title"] = "Файл криптографических ключей (prod.keys / keys.txt)",
                ["Settings_Switch_Keys_Desc"] = "Загружать ключи для расшифровки. Можно перетащить файл прямо сюда",
                ["Settings_Switch_Keys_Loaded"] = "Файл выбран",
                ["Settings_Switch_Keys_Pick"] = "📂 Выбрать файл",
                ["Settings_Switch_Algorithms_Header"] = "Алгоритмы сборки и очистки Switch",
                ["Settings_Switch_KeyGen_Title"] = "Понижение версии ключей (KeyGen)",
                ["Settings_Switch_KeyGen_Desc"] = "Маскирует требования к прошивке (0-30), позволяя запускать новые игры на старых FW",
                ["Settings_Switch_Rsv_Title"] = "Понижение системных требований (RSV Cap Downgrade)",
                ["Settings_Switch_Rsv_Desc"] = "Ограничивает проверку версии системного ПО консоли в метаданных CNMT",
                ["Settings_Switch_Titlerights_Title"] = "Удалить Titlerights (Ticketless NSP)",
                ["Settings_Switch_Titlerights_Desc"] = "Конвертирует ticket-зависимые NSP в стандартный крипто-формат без тикетов (--C_clean_ND)",
                ["Settings_Switch_Delta_Title"] = "Удалять Delta NCA из обновлений",
                ["Settings_Switch_Delta_Desc"] = "Удаляет избыточные дельта-патчи из Update-файлов для экономии до 30% места (-ND true)",
                ["Settings_Switch_Fat32_Title"] = "Разделять файлы для FAT32 (> 4 GB)",
                ["Settings_Switch_Fat32_Desc"] = "Автоматически разбивает готовые файлы > 4 ГБ на чанки (.xc0/.xc1 или .00/.01) для FAT32 SD-карт",
                ["Settings_Switch_ForceMulti_Title"] = "Пересборка файлов в Мульти-контенте",
                ["Settings_Switch_ForceMulti_Desc"] = "Полная пересборка контейнеров PFS0 через NSC_Builder для устранения ошибок в эмуляторах",
                ["Settings_Switch_LangTrim_Title"] = "Удалять неиспользуемые языки из RomFS",
                ["Settings_Switch_LangTrim_Desc"] = "Работает при конвертации NSP/NSZ → XCI/XCZ и при HardPatch (пересборка Base+Update)",
                ["Settings_Switch_LangTrim_Sub"] = "Выберите языки, которые нужно ОСТАВИТЬ при вырезании:",
                ["Settings_Switch_WatchFolder_Header"] = "«Умная» папка Nintendo Switch",
                ["Settings_Switch_WatchFolder_Title"] = "Папка автоматического наблюдения Switch",
                ["Settings_Switch_WatchFolder_Desc"] = "Автоматически обнаруживает файлы Switch (.nsp, .nsz, .xci, .xcz, архивы .zip, .rar, .7z) и отправляет в задачи",
                ["Settings_Switch_WatchFolder_Badge"] = "⚡ Switch авто-обработка:",
                ["Settings_Switch_WatchFolder_Pick"] = "Выбрать папку...",
                ["Settings_Switch_WatchFolder_Start"] = "▶ Запустить отслеживание",
                ["Settings_Switch_WatchFolder_Stop"] = "⏹ Остановить отслеживание",
                ["Settings_Switch_WatchFolder_Active"] = "● Отслеживание активно",
                ["Settings_Switch_WatchFolder_Stopped"] = "○ Отслеживание остановлено",
                ["Settings_Switch_OutFolder_Title"] = "Выходная папка Switch по умолчанию",
                ["Settings_Switch_OutFolder_Desc"] = "Папка для сохранения обработанных файлов Switch (.nsp / .nsz / .xci / .xcz). Можно перетащить папку сюда",
                ["Settings_Switch_OutFolder_Placeholder"] = "Не указана (сохранять в папку с исходным файлом)",
                ["Settings_Switch_OutFolder_Browse"] = "Обзор...",

                // Settings 3DS
                ["Settings_3ds_Keys_Header"] = "Криптографические ключи Nintendo 3DS",
                ["Settings_3ds_Keys_Title"] = "Файл ключей 3DS (aes_keys.txt / boot9.bin / encTitleKeys.bin)",
                ["Settings_3ds_Keys_Desc"] = "Используется для дешифровки NCCH, CIA и RomFS при сборке и конвертации. Можно перетащить файл сюда",
                ["Settings_3ds_Keys_Loaded"] = "Ключи подключены",
                ["Settings_3ds_Keys_Pick"] = "📂 Выбрать файл",
                ["Settings_3ds_Algorithms_Header"] = "Алгоритмы сборки и форматы Nintendo 3DS",
                ["Settings_3ds_Format_Title"] = "Выходной формат 3DS по умолчанию",
                ["Settings_3ds_Format_Desc"] = "Формат по умолчанию для конвертации и сборки (.3ds / .cci для эмуляторов Citra/Lime3DS, .cia для установки)",
                ["Settings_3ds_HardPatch_Title"] = "3DS HardPatch (Вшивание обновлений и модов)",
                ["Settings_3ds_HardPatch_Desc"] = "Автоматически распаковывает RomFS/ExeFS, накладывает файлы обновления и модов/переводов и пересобирает единый образ",
                ["Settings_3ds_WatchFolder_Header"] = "«Умная» папка Nintendo 3DS",
                ["Settings_3ds_WatchFolder_Title"] = "Папка автоматического наблюдения 3DS",
                ["Settings_3ds_WatchFolder_Desc"] = "Автоматически обнаруживает файлы 3DS (.3ds, .cci, .cia, .cxi, архивы .zip, .rar, .7z) и отправляет в задачи",
                ["Settings_3ds_WatchFolder_Badge"] = "⚡ 3DS авто-обработка:",
                ["Settings_3ds_WatchFolder_Pick"] = "Выбрать папку...",
                ["Settings_3ds_WatchFolder_Start"] = "▶ Запустить отслеживание",
                ["Settings_3ds_WatchFolder_Stop"] = "⏹ Остановить отслеживание",
                ["Settings_3ds_WatchFolder_Active"] = "● Отслеживание активно",
                ["Settings_3ds_WatchFolder_Stopped"] = "○ Отслеживание остановлено",
                ["Settings_3ds_OutFolder_Title"] = "Выходная папка 3DS по умолчанию",
                ["Settings_3ds_OutFolder_Desc"] = "Папка для сохранения обработанных файлов 3DS (.3ds / .cia / .cxi). Можно перетащить папку сюда",
                ["Settings_3ds_OutFolder_Placeholder"] = "Не указана (сохранять в папку с исходным файлом)",
                ["Settings_3ds_OutFolder_Browse"] = "Обзор...",

                // Catalog Page
                ["Catalog_ScanFolders"] = "Папки сканирования",
                ["Catalog_ScanFolders_Title"] = "Папки для сканирования",
                ["Catalog_AddFolder"] = "Добавить",
                ["Catalog_RemoveFolder"] = "Удалить",
                ["Catalog_ScanAll"] = "Сканировать все",
                ["Catalog_Filter_All"] = "Все игры",
                ["Catalog_Filter_Switch"] = "🎮 Nintendo Switch",
                ["Catalog_Filter_3ds"] = "🕹️ Nintendo 3DS",
                ["Catalog_Search_Placeholder"] = "Поиск по названию или Title ID...",
                ["Catalog_UpdateDb"] = "Обновление данных TitleDB",
                ["Catalog_Details_Genre"] = "Жанр:",
                ["Catalog_Details_ReleaseDate"] = "Дата выхода:",
                ["Catalog_Details_Publisher"] = "Издатель:",
                ["Catalog_Details_Size"] = "Размер:",
                ["Catalog_Details_Description"] = "Описание",
                ["Catalog_Details_Screenshots"] = "Скриншоты и изображения",

                // History Page
                ["History_Title"] = "История обработки",
                ["History_Clear"] = "Очистить историю",
                ["History_Export"] = "Экспорт в CSV",
                ["History_Empty"] = "История обработки пуста.",

                // Common State & Controls
                ["Common_On"] = "Вкл.",
                ["Common_Off"] = "Откл.",
                ["Common_All"] = "Все",
                ["Common_Yes"] = "Да",
                ["Common_No"] = "Нет",

                // Languages for RomFS Trim
                ["Lang_Russian"] = "Русский",
                ["Lang_English"] = "Английский",
                ["Lang_Japanese"] = "Японский",
                ["Lang_Spanish"] = "Испанский",
                ["Lang_French"] = "Французский",
                ["Lang_German"] = "Немецкий",
                ["Lang_Italian"] = "Итальянский",
                ["Lang_Dutch"] = "Нидерландский",
                ["Lang_Portuguese"] = "Португальский",
                ["Lang_Korean"] = "Корейский",
                ["Lang_Chinese_Simplified"] = "Китайский (упр.)",
                ["Lang_Chinese_Traditional"] = "Китайский (трад.)",

                // Game Library Page
                ["Library_Title"] = "Библиотека игр",
                ["Library_Search_Placeholder"] = "Поиск по названию, студии или ID...",
                ["Library_AllSystems"] = "Все системы",
                ["Library_AllGenres"] = "Все жанры",
                ["Library_AllDevs"] = "Все разработчики",
                ["Library_AllPubs"] = "Все издатели",
                ["Library_Sort_Title"] = "По названию",
                ["Library_Sort_ReleaseDate"] = "По дате выхода",
                ["Library_Sort_System"] = "По системе",
                ["Library_Reset"] = "Сброс",
                ["Library_TotalGames"] = "Игр: {0}",
                ["Library_Page_Of"] = "Страница {0} из {1}",
                ["Library_Page_Items"] = "Показано {0}–{1} из {2}",
                ["Library_PerPage"] = "На странице:",
                ["Library_SaveCover"] = "💾 Сохранить обложку",
                ["Library_CopyDetails"] = "📋 Копировать",
                ["Library_SearchWeb"] = "🔍 Найти в сети",
                ["Library_PrevPage"] = "◀ Назад",
                ["Library_NextPage"] = "Вперёд ▶",
                ["Library_FirstPage"] = "⏮ В начало",
                ["Library_LastPage"] = "В конец ⏭",
                ["Library_All"] = "Все",

                // Dialogs & Metadata Editor
                ["Editor_Title"] = "Редактирование метаданных и иконки",
                ["Editor_TitleRu"] = "Название игры (Русский):",
                ["Editor_TitleEn"] = "Название игры (English):",
                ["Editor_Publisher"] = "Издатель:",
                ["Editor_ChangeIcon"] = "Заменить иконку (PNG/JPG)",
                ["Editor_ResetIcon"] = "Сбросить иконку",
                ["Editor_Save"] = "Сохранить",
                ["Editor_Cancel"] = "Отмена",
                ["Common_OK"] = "OK",
                ["Common_Close"] = "Закрыть"
            },

            ["en"] = new Dictionary<string, string>
            {
                // App & Tray
                ["App_Title"] = "STORM SWITCH BOX",
                ["Tray_Title"] = "STORM SWITCH BOX",
                ["Tray_Restore"] = "Restore",
                ["Tray_Exit"] = "Exit",

                // Navigation
                ["Nav_Update"] = "Update",
                ["Nav_Unpack"] = "Unpack",
                ["Nav_Pack"] = "Pack",
                ["Nav_Convert"] = "Convert",
                ["Nav_Multi"] = "Multi-content",
                ["Nav_Verify"] = "Verify",
                ["Nav_Instruction"] = "Guide",
                ["Nav_GameLibrary"] = "Game Library",
                ["Nav_Catalog"] = "Catalog",
                ["Nav_History"] = "History",
                ["Nav_Settings"] = "Settings",

                // Tasks Common
                ["Tasks_AddFiles"] = "Add Files",
                ["Tasks_AddFolder"] = "Add Folder",
                ["Tasks_ClearList"] = "Clear List",
                ["Tasks_StartAll"] = "Start All",
                ["Tasks_StopAll"] = "Stop All",
                ["Tasks_TargetFormat"] = "Target format:",
                ["Tasks_Col_Game"] = "Game / Task",
                ["Tasks_Col_Format"] = "Format",
                ["Tasks_Col_Files"] = "Files",
                ["Tasks_Col_Size"] = "Size",
                ["Tasks_Col_Status"] = "Status",
                ["Tasks_Col_Progress"] = "Progress",
                ["Tasks_Col_Actions"] = "Actions",
                ["Tasks_EmptyHint"] = "Task list is empty. Add files using the buttons above or drag them into the window.",
                ["Tasks_DropHint"] = "Drag and drop files or folders here to add tasks automatically",
                ["Tasks_Status_Pending"] = "Pending",
                ["Tasks_Status_Processing"] = "Processing...",
                ["Tasks_Status_Success"] = "Completed",
                ["Tasks_Status_Error"] = "Error",
                ["Tasks_Status_Cancelled"] = "Cancelled",
                ["Tasks_Menu_EditMetadata"] = "Edit Metadata & Icon",
                ["Tasks_Menu_OpenFolder"] = "Open Output Folder",
                ["Tasks_Menu_Delete"] = "Delete Task",
                ["Tasks_Menu_ChangeFormat"] = "Change Format",

                // Settings Tabs
                ["Settings_Title"] = "Settings",
                ["Settings_Tab_General"] = "General",
                ["Settings_Tab_Switch"] = "Nintendo Switch",
                ["Settings_Tab_3ds"] = "Nintendo 3DS",

                // Settings General
                ["Settings_General_Language_Header"] = "Interface Language",
                ["Settings_General_Language_Title"] = "Interface Language",
                ["Settings_General_Language_Desc"] = "Choose the main application language (applied immediately)",
                ["Settings_General_Appearance_Header"] = "Appearance & Sound Notifications",
                ["Settings_General_Sound_Title"] = "Sound Notifications",
                ["Settings_General_Sound_Desc"] = "Play audio cue upon task queue completion",
                ["Settings_General_Theme_Title"] = "Interface Theme",
                ["Settings_General_Theme_Desc"] = "Select visual style and color scheme for the application",
                ["Settings_General_Accent_Title"] = "Interface Accent Color",
                ["Settings_General_Accent_Desc"] = "Choose primary accent color for UI elements",
                ["Settings_General_Files_Header"] = "Paths & File Organization",
                ["Settings_General_Complex_Title"] = "Organize output into structured subfolders",
                ["Settings_General_Complex_Desc"] = "Creates folders in [Game Name]/[Format] format with TitleID and version",
                ["Settings_General_DeleteSource_Title"] = "Delete source files after successful processing",
                ["Settings_General_DeleteSource_Desc"] = "Automatically deletes input files after 100% error-free completion",
                ["Settings_General_Perf_Header"] = "Performance & Compression",
                ["Settings_General_Compression_Title"] = "Zstandard Compression Level (NSZ / XCZ)",
                ["Settings_General_Compression_Desc"] = "Select Zstd compression level (from Fast 3 to Ultra 22)",
                ["Settings_General_Tasks_Title"] = "Maximum Concurrent Tasks",
                ["Settings_General_Tasks_Desc"] = "Number of tasks processed in parallel (1 to 5)",
                ["Settings_General_Threads_Title"] = "Multithreading (CPU Cores)",
                ["Settings_General_Threads_Desc"] = "Max CPU cores allocated for Zstd compression",
                ["Settings_General_About_Header"] = "About",
                ["Settings_General_About_Desc"] = "Specialized suite for processing, compressing, and converting Nintendo Switch and Nintendo 3DS games. Native high-performance algorithms.",
                ["Settings_General_CheckUpdates"] = "Check for Updates",
                ["Settings_General_OpenLogs"] = "Open Logs Folder",

                // Settings Switch
                ["Settings_Switch_Keys_Header"] = "Nintendo Switch Cryptographic Keys",
                ["Settings_Switch_Keys_Title"] = "Keys File (prod.keys / keys.txt)",
                ["Settings_Switch_Keys_Desc"] = "Load keys for decryption. You can drag and drop file directly here",
                ["Settings_Switch_Keys_Loaded"] = "File selected",
                ["Settings_Switch_Keys_Pick"] = "📂 Browse...",
                ["Settings_Switch_Algorithms_Header"] = "Switch Build & Cleanup Algorithms",
                ["Settings_Switch_KeyGen_Title"] = "Key Generation Downgrade (KeyGen)",
                ["Settings_Switch_KeyGen_Desc"] = "Masks firmware requirements (0-30) to run new games on older FW",
                ["Settings_Switch_Rsv_Title"] = "RSV Cap Downgrade",
                ["Settings_Switch_Rsv_Desc"] = "Caps required system software version checks in CNMT metadata",
                ["Settings_Switch_Titlerights_Title"] = "Remove Titlerights (Ticketless NSP)",
                ["Settings_Switch_Titlerights_Desc"] = "Converts ticket-dependent NSPs to standard ticketless format (--C_clean_ND)",
                ["Settings_Switch_Delta_Title"] = "Remove Delta NCAs from Updates",
                ["Settings_Switch_Delta_Desc"] = "Removes redundant delta patches from updates to save up to 30% disk space (-ND true)",
                ["Settings_Switch_Fat32_Title"] = "Split Files for FAT32 (> 4 GB)",
                ["Settings_Switch_Fat32_Desc"] = "Automatically splits files > 4 GB into chunks (.xc0/.xc1 or .00/.01) for FAT32 SD cards",
                ["Settings_Switch_ForceMulti_Title"] = "Rebuild Multi-content Containers",
                ["Settings_Switch_ForceMulti_Desc"] = "Full rebuild of PFS0 containers via NSC_Builder to prevent emulator crashes",
                ["Settings_Switch_LangTrim_Title"] = "Trim Unused Languages from RomFS",
                ["Settings_Switch_LangTrim_Desc"] = "Applies during NSP/NSZ → XCI/XCZ conversion and HardPatch (Base+Update)",
                ["Settings_Switch_LangTrim_Sub"] = "Select languages to KEEP when trimming:",
                ["Settings_Switch_WatchFolder_Header"] = "Nintendo Switch Smart Watch Folder",
                ["Settings_Switch_WatchFolder_Title"] = "Switch Automatic Watch Folder",
                ["Settings_Switch_WatchFolder_Desc"] = "Automatically detects Switch files (.nsp, .nsz, .xci, .xcz, .zip, .rar, .7z) and queues tasks",
                ["Settings_Switch_WatchFolder_Badge"] = "⚡ Switch auto-processing:",
                ["Settings_Switch_WatchFolder_Pick"] = "Choose Folder...",
                ["Settings_Switch_WatchFolder_Start"] = "▶ Start Monitoring",
                ["Settings_Switch_WatchFolder_Stop"] = "⏹ Stop Monitoring",
                ["Settings_Switch_WatchFolder_Active"] = "● Monitoring active",
                ["Settings_Switch_WatchFolder_Stopped"] = "○ Monitoring stopped",
                ["Settings_Switch_OutFolder_Title"] = "Default Switch Output Folder",
                ["Settings_Switch_OutFolder_Desc"] = "Folder for processed Switch files (.nsp / .nsz / .xci / .xcz). Drag folder here",
                ["Settings_Switch_OutFolder_Placeholder"] = "Not set (save to source file folder)",
                ["Settings_Switch_OutFolder_Browse"] = "Browse...",

                // Settings 3DS
                ["Settings_3ds_Keys_Header"] = "Nintendo 3DS Cryptographic Keys",
                ["Settings_3ds_Keys_Title"] = "3DS Keys File (aes_keys.txt / boot9.bin / encTitleKeys.bin)",
                ["Settings_3ds_Keys_Desc"] = "Used for NCCH, CIA, and RomFS decryption during builds and conversions. Drag file here",
                ["Settings_3ds_Keys_Loaded"] = "Keys connected",
                ["Settings_3ds_Keys_Pick"] = "📂 Browse...",
                ["Settings_3ds_Algorithms_Header"] = "Nintendo 3DS Build & Format Algorithms",
                ["Settings_3ds_Format_Title"] = "Default 3DS Output Format",
                ["Settings_3ds_Format_Desc"] = "Default output format for conversion and builds (.3ds/.cci for emulators, .cia for installation)",
                ["Settings_3ds_HardPatch_Title"] = "3DS HardPatch (Merge Updates & Mods)",
                ["Settings_3ds_HardPatch_Desc"] = "Unpacks RomFS/ExeFS, integrates update and mod/translation files, and rebuilds unified ROM",
                ["Settings_3ds_WatchFolder_Header"] = "Nintendo 3DS Smart Watch Folder",
                ["Settings_3ds_WatchFolder_Title"] = "3DS Automatic Watch Folder",
                ["Settings_3ds_WatchFolder_Desc"] = "Automatically detects 3DS files (.3ds, .cci, .cia, .cxi, .zip, .rar, .7z) and queues tasks",
                ["Settings_3ds_WatchFolder_Badge"] = "⚡ 3DS auto-processing:",
                ["Settings_3ds_WatchFolder_Pick"] = "Choose Folder...",
                ["Settings_3ds_WatchFolder_Start"] = "▶ Start Monitoring",
                ["Settings_3ds_WatchFolder_Stop"] = "⏹ Stop Monitoring",
                ["Settings_3ds_WatchFolder_Active"] = "● Monitoring active",
                ["Settings_3ds_WatchFolder_Stopped"] = "○ Monitoring stopped",
                ["Settings_3ds_OutFolder_Title"] = "Default 3DS Output Folder",
                ["Settings_3ds_OutFolder_Desc"] = "Folder for processed 3DS files (.3ds / .cia / .cxi). Drag folder here",
                ["Settings_3ds_OutFolder_Placeholder"] = "Not set (save to source file folder)",
                ["Settings_3ds_OutFolder_Browse"] = "Browse...",

                // Catalog Page
                ["Catalog_ScanFolders"] = "Scan Folders",
                ["Catalog_ScanFolders_Title"] = "Folders for Scanning",
                ["Catalog_AddFolder"] = "Add",
                ["Catalog_RemoveFolder"] = "Remove",
                ["Catalog_ScanAll"] = "Scan All",
                ["Catalog_Filter_All"] = "All Games",
                ["Catalog_Filter_Switch"] = "🎮 Nintendo Switch",
                ["Catalog_Filter_3ds"] = "🕹️ Nintendo 3DS",
                ["Catalog_Search_Placeholder"] = "Search by title or Title ID...",
                ["Catalog_UpdateDb"] = "Update TitleDB Database",
                ["Catalog_Details_Genre"] = "Genre:",
                ["Catalog_Details_ReleaseDate"] = "Release Date:",
                ["Catalog_Details_Publisher"] = "Publisher:",
                ["Catalog_Details_Size"] = "Size:",
                ["Catalog_Details_Description"] = "Description",
                ["Catalog_Details_Screenshots"] = "Screenshots & Media",

                // Common State & Controls
                ["Common_On"] = "On",
                ["Common_Off"] = "Off",
                ["Common_All"] = "All",
                ["Common_Yes"] = "Yes",
                ["Common_No"] = "No",

                // Languages for RomFS Trim
                ["Lang_Russian"] = "Russian",
                ["Lang_English"] = "English",
                ["Lang_Japanese"] = "Japanese",
                ["Lang_Spanish"] = "Spanish",
                ["Lang_French"] = "French",
                ["Lang_German"] = "German",
                ["Lang_Italian"] = "Italian",
                ["Lang_Dutch"] = "Dutch",
                ["Lang_Portuguese"] = "Portuguese",
                ["Lang_Korean"] = "Korean",
                ["Lang_Chinese_Simplified"] = "Chinese (Simplified)",
                ["Lang_Chinese_Traditional"] = "Chinese (Traditional)",

                // Game Library Page
                ["Library_Title"] = "Game Library",
                ["Library_Search_Placeholder"] = "Search by title, developer or ID...",
                ["Library_AllSystems"] = "All Systems",
                ["Library_AllGenres"] = "All Genres",
                ["Library_AllDevs"] = "All Developers",
                ["Library_AllPubs"] = "All Publishers",
                ["Library_Sort_Title"] = "By Title",
                ["Library_Sort_ReleaseDate"] = "By Release Date",
                ["Library_Sort_System"] = "By System",
                ["Library_Reset"] = "Reset",
                ["Library_TotalGames"] = "Games: {0}",
                ["Library_Page_Of"] = "Page {0} of {1}",
                ["Library_Page_Items"] = "Showing {0}–{1} of {2}",
                ["Library_PerPage"] = "Per page:",
                ["Library_SaveCover"] = "💾 Save Cover",
                ["Library_CopyDetails"] = "📋 Copy",
                ["Library_SearchWeb"] = "🔍 Search Web",
                ["Library_PrevPage"] = "◀ Previous",
                ["Library_NextPage"] = "Next ▶",
                ["Library_FirstPage"] = "⏮ First",
                ["Library_LastPage"] = "Last ⏭",
                ["Library_All"] = "All",

                // Dialogs & Metadata Editor
                ["Editor_Title"] = "Edit Metadata & Icon",
                ["Editor_TitleRu"] = "Game Title (Russian):",
                ["Editor_TitleEn"] = "Game Title (English):",
                ["Editor_Publisher"] = "Publisher:",
                ["Editor_ChangeIcon"] = "Replace Icon (PNG/JPG)",
                ["Editor_ResetIcon"] = "Reset Icon",
                ["Editor_Save"] = "Save",
                ["Editor_Cancel"] = "Cancel",
                ["Common_OK"] = "OK",
                ["Common_Close"] = "Close"
            },

            ["de"] = new Dictionary<string, string>
            {
                // App & Tray
                ["App_Title"] = "STORM SWITCH BOX",
                ["Tray_Title"] = "STORM SWITCH BOX",
                ["Tray_Restore"] = "Wiederherstellen",
                ["Tray_Exit"] = "Beenden",

                // Navigation
                ["Nav_Update"] = "Aktualisierung",
                ["Nav_Unpack"] = "Entpacken",
                ["Nav_Pack"] = "Packen",
                ["Nav_Convert"] = "Konvertieren",
                ["Nav_Multi"] = "Multi-Inhalt",
                ["Nav_Verify"] = "Überprüfen",
                ["Nav_Instruction"] = "Anleitung",
                ["Nav_GameLibrary"] = "Spielebibliothek",
                ["Nav_Catalog"] = "Katalog",
                ["Nav_History"] = "Verlauf",
                ["Nav_Settings"] = "Einstellungen",

                // Tasks Common
                ["Tasks_AddFiles"] = "Dateien hinzufügen",
                ["Tasks_AddFolder"] = "Ordner hinzufügen",
                ["Tasks_ClearList"] = "Liste leeren",
                ["Tasks_StartAll"] = "Alle starten",
                ["Tasks_StopAll"] = "Alle stoppen",
                ["Tasks_TargetFormat"] = "Zielformat:",
                ["Tasks_Col_Game"] = "Spiel / Aufgabe",
                ["Tasks_Col_Format"] = "Format",
                ["Tasks_Col_Files"] = "Dateien",
                ["Tasks_Col_Size"] = "Größe",
                ["Tasks_Col_Status"] = "Status",
                ["Tasks_Col_Progress"] = "Fortschritt",
                ["Tasks_Col_Actions"] = "Aktionen",
                ["Tasks_EmptyHint"] = "Aufgabenliste ist leer. Fügen Sie Dateien hinzu oder ziehen Sie sie in das Fenster.",
                ["Tasks_DropHint"] = "Dateien oder Ordner hierher ziehen, um Aufgaben automatisch hinzuzufügen",
                ["Tasks_Status_Pending"] = "Wartend",
                ["Tasks_Status_Processing"] = "In Bearbeitung...",
                ["Tasks_Status_Success"] = "Abgeschlossen",
                ["Tasks_Status_Error"] = "Fehler",
                ["Tasks_Status_Cancelled"] = "Abgebrochen",
                ["Tasks_Menu_EditMetadata"] = "Metadaten & Symbol bearbeiten",
                ["Tasks_Menu_OpenFolder"] = "Ausgabeordner öffnen",
                ["Tasks_Menu_Delete"] = "Aufgabe löschen",
                ["Tasks_Menu_ChangeFormat"] = "Format ändern",

                // Settings Tabs
                ["Settings_Title"] = "Einstellungen",
                ["Settings_Tab_General"] = "Allgemein",
                ["Settings_Tab_Switch"] = "Nintendo Switch",
                ["Settings_Tab_3ds"] = "Nintendo 3DS",

                // Settings General
                ["Settings_General_Language_Header"] = "Sprache der Benutzeroberfläche",
                ["Settings_General_Language_Title"] = "Sprache",
                ["Settings_General_Language_Desc"] = "Wählen Sie die Hauptsprache der Anwendung (wird sofort angewendet)",
                ["Settings_General_Appearance_Header"] = "Erscheinungsbild & Tonbenachrichtigungen",
                ["Settings_General_Sound_Title"] = "Tonbenachrichtigungen",
                ["Settings_General_Sound_Desc"] = "Signalton nach Abschluss der Aufgabenwarteschlange abspielen",
                ["Settings_General_Theme_Title"] = "Oberflächendesign",
                ["Settings_General_Theme_Desc"] = "Wählen Sie das visuelle Gesamtdesign der Anwendung",
                ["Settings_General_Accent_Title"] = "Akzentfarbe der Benutzeroberfläche",
                ["Settings_General_Accent_Desc"] = "Hauptakzentfarbe für Elemente wählen",
                ["Settings_General_Files_Header"] = "Pfade & Dateiorganisation",
                ["Settings_General_Complex_Title"] = "Ausgabe in strukturierte Unterordner sortieren",
                ["Settings_General_Complex_Desc"] = "Erstellt Unterordner im Format [Spieltitel]/[Format] mit TitleID und Version",
                ["Settings_General_DeleteSource_Title"] = "Quelldateien nach erfolgreicher Verarbeitung löschen",
                ["Settings_General_DeleteSource_Desc"] = "Löscht Eingabedateien nach 100% fehlerfreier Verarbeitung automatisch",
                ["Settings_General_Perf_Header"] = "Leistung & Komprimierung",
                ["Settings_General_Compression_Title"] = "Zstandard-Komprimierungsstufe (NSZ / XCZ)",
                ["Settings_General_Compression_Desc"] = "Zstd-Komprimierungsstufe wählen (von Schnell 3 bis Ultra 22)",
                ["Settings_General_Tasks_Title"] = "Maximale gleichzeitige Aufgaben",
                ["Settings_General_Tasks_Desc"] = "Anzahl parallel ausgeführter Aufgaben (1 bis 5)",
                ["Settings_General_Threads_Title"] = "Multithreading (CPU-Kerne)",
                ["Settings_General_Threads_Desc"] = "Maximale CPU-Kerne für Zstd-Kompression",
                ["Settings_General_About_Header"] = "Über das Programm",
                ["Settings_General_About_Desc"] = "Spezialisiertes Toolkit für Nintendo Switch- und Nintendo 3DS-Spiele. Native Algorithmen für Höchstleistung.",
                ["Settings_General_CheckUpdates"] = "Nach Updates suchen",
                ["Settings_General_OpenLogs"] = "Protokollordner öffnen",

                // Settings Switch
                ["Settings_Switch_Keys_Header"] = "Nintendo Switch Kryptoschlüssel",
                ["Settings_Switch_Keys_Title"] = "Schlüsseldatei (prod.keys / keys.txt)",
                ["Settings_Switch_Keys_Desc"] = "Schlüssel zur Entschlüsselung laden. Datei hierher ziehen",
                ["Settings_Switch_Keys_Loaded"] = "Datei ausgewählt",
                ["Settings_Switch_Keys_Pick"] = "📂 Datei wählen",
                ["Settings_Switch_Algorithms_Header"] = "Switch Erstellungs- & Bereinigungsalgorithmen",
                ["Settings_Switch_KeyGen_Title"] = "Schlüsselversions-Downgrade (KeyGen)",
                ["Settings_Switch_KeyGen_Desc"] = "Maskiert Firmware-Anforderungen (0-30) für ältere FW",
                ["Settings_Switch_Rsv_Title"] = "Systemanforderungs-Downgrade (RSV Cap)",
                ["Settings_Switch_Rsv_Desc"] = "Begrenzt erforderliche Systemversionsprüfungen in CNMT",
                ["Settings_Switch_Titlerights_Title"] = "Titlerights entfernen (Ticketless NSP)",
                ["Settings_Switch_Titlerights_Desc"] = "Konvertiert ticketabhängige NSPs in ticketloses Standardformat (--C_clean_ND)",
                ["Settings_Switch_Delta_Title"] = "Delta-NCAs aus Updates entfernen",
                ["Settings_Switch_Delta_Desc"] = "Entfernt redundante Delta-Patches aus Updates für bis zu 30% Platzersparnis (-ND true)",
                ["Settings_Switch_Fat32_Title"] = "Dateien für FAT32 aufteilen (> 4 GB)",
                ["Settings_Switch_Fat32_Desc"] = "Teilt Dateien > 4 GB automatisch für FAT32-SD-Karten auf",
                ["Settings_Switch_ForceMulti_Title"] = "PFS0 in Multi-Inhalt neu erstellen",
                ["Settings_Switch_ForceMulti_Desc"] = "Vollständige Neuerstellung der PFS0-Container zur Vermeidung von Emulatorfehlern",
                ["Settings_Switch_LangTrim_Title"] = "Ungenutzte Sprachen aus RomFS entfernen",
                ["Settings_Switch_LangTrim_Desc"] = "Funktioniert bei NSP/NSZ → XCI/XCZ Konvertierung und HardPatch",
                ["Settings_Switch_LangTrim_Sub"] = "Wählen Sie Sprachen, die BEIBEHALTEN werden sollen:",
                ["Settings_Switch_WatchFolder_Header"] = "Intelligenter Überwachungsordner (Switch)",
                ["Settings_Switch_WatchFolder_Title"] = "Automatischer Überwachungsordner Switch",
                ["Settings_Switch_WatchFolder_Desc"] = "Erkennt Switch-Dateien (.nsp, .nsz, .xci, .xcz, .zip, .rar, .7z) automatisch",
                ["Settings_Switch_WatchFolder_Badge"] = "⚡ Switch Automatische Verarbeitung:",
                ["Settings_Switch_WatchFolder_Pick"] = "Ordner wählen...",
                ["Settings_Switch_WatchFolder_Start"] = "▶ Überwachung starten",
                ["Settings_Switch_WatchFolder_Stop"] = "⏹ Überwachung stoppen",
                ["Settings_Switch_WatchFolder_Active"] = "● Überwachung aktiv",
                ["Settings_Switch_WatchFolder_Stopped"] = "○ Überwachung gestoppt",
                ["Settings_Switch_OutFolder_Title"] = "Standardmäßiger Switch-Ausgabeordner",
                ["Settings_Switch_OutFolder_Desc"] = "Ordner für verarbeitete Switch-Dateien (.nsp / .nsz / .xci / .xcz). Ordner hierher ziehen",
                ["Settings_Switch_OutFolder_Placeholder"] = "Nicht festgelegt (im Quellordner speichern)",
                ["Settings_Switch_OutFolder_Browse"] = "Durchsuchen...",

                // Settings 3DS
                ["Settings_3ds_Keys_Header"] = "Nintendo 3DS Kryptoschlüssel",
                ["Settings_3ds_Keys_Title"] = "3DS Schlüsseldatei (aes_keys.txt / boot9.bin / encTitleKeys.bin)",
                ["Settings_3ds_Keys_Desc"] = "Wird zur NCCH-, CIA- und RomFS-Entschlüsselung verwendet. Datei hierher ziehen",
                ["Settings_3ds_Keys_Loaded"] = "Schlüssel geladen",
                ["Settings_3ds_Keys_Pick"] = "📂 Datei wählen",
                ["Settings_3ds_Algorithms_Header"] = "Nintendo 3DS Erstellungs- & Formatalgorithmen",
                ["Settings_3ds_Format_Title"] = "Standardmäßiges 3DS-Ausgabeformat",
                ["Settings_3ds_Format_Desc"] = "Standardformat für Konvertierung (.3ds/.cci für Emulatoren, .cia zur Installation)",
                ["Settings_3ds_HardPatch_Title"] = "3DS HardPatch (Updates & Mods einbinden)",
                ["Settings_3ds_HardPatch_Desc"] = "Entpackt RomFS/ExeFS, wendet Updates und Mod-Dateien an und baut das Image neu",
                ["Settings_3ds_WatchFolder_Header"] = "Intelligenter Überwachungsordner (3DS)",
                ["Settings_3ds_WatchFolder_Title"] = "Automatischer Überwachungsordner 3DS",
                ["Settings_3ds_WatchFolder_Desc"] = "Erkennt 3DS-Dateien (.3ds, .cci, .cia, .cxi, .zip, .rar, .7z) automatisch",
                ["Settings_3ds_WatchFolder_Badge"] = "⚡ 3DS Automatische Verarbeitung:",
                ["Settings_3ds_WatchFolder_Pick"] = "Ordner wählen...",
                ["Settings_3ds_WatchFolder_Start"] = "▶ Überwachung starten",
                ["Settings_3ds_WatchFolder_Stop"] = "⏹ Überwachung stoppen",
                ["Settings_3ds_WatchFolder_Active"] = "● Überwachung aktiv",
                ["Settings_3ds_WatchFolder_Stopped"] = "○ Überwachung gestoppt",
                ["Settings_3ds_OutFolder_Title"] = "Standardmäßiger 3DS-Ausgabeordner",
                ["Settings_3ds_OutFolder_Desc"] = "Ordner für verarbeitete 3DS-Dateien (.3ds / .cia / .cxi). Ordner hierher ziehen",
                ["Settings_3ds_OutFolder_Placeholder"] = "Nicht festgelegt (im Quellordner speichern)",
                ["Settings_3ds_OutFolder_Browse"] = "Durchsuchen...",

                // Catalog Page
                ["Catalog_ScanFolders"] = "Suchordner",
                ["Catalog_ScanFolders_Title"] = "Ordner zum Scannen",
                ["Catalog_AddFolder"] = "Hinzufügen",
                ["Catalog_RemoveFolder"] = "Entfernen",
                ["Catalog_ScanAll"] = "Alle scannen",
                ["Catalog_Filter_All"] = "Alle Spiele",
                ["Catalog_Filter_Switch"] = "🎮 Nintendo Switch",
                ["Catalog_Filter_3ds"] = "🕹️ Nintendo 3DS",
                ["Catalog_Search_Placeholder"] = "Nach Titel oder Title-ID suchen...",
                ["Catalog_UpdateDb"] = "TitleDB-Datenbank aktualisieren",
                ["Catalog_Details_Genre"] = "Genre:",
                ["Catalog_Details_ReleaseDate"] = "Erscheinungsdatum:",
                ["Catalog_Details_Publisher"] = "Herausgeber:",
                ["Catalog_Details_Size"] = "Größe:",
                ["Catalog_Details_Description"] = "Beschreibung",
                ["Catalog_Details_Screenshots"] = "Screenshots & Medien",

                // History Page
                ["History_Title"] = "Verlauf der Verarbeitung",
                ["History_Clear"] = "Verlauf leeren",
                // Common State & Controls
                ["Common_On"] = "Ein",
                ["Common_Off"] = "Aus",
                ["Common_All"] = "Alle",
                ["Common_Yes"] = "Ja",
                ["Common_No"] = "Nein",

                // Languages for RomFS Trim
                ["Lang_Russian"] = "Russisch",
                ["Lang_English"] = "Englisch",
                ["Lang_Japanese"] = "Japanisch",
                ["Lang_Spanish"] = "Spanisch",
                ["Lang_French"] = "Französisch",
                ["Lang_German"] = "Deutsch",
                ["Lang_Italian"] = "Italienisch",
                ["Lang_Dutch"] = "Niederländisch",
                ["Lang_Portuguese"] = "Portugiesisch",
                ["Lang_Korean"] = "Koreanisch",
                ["Lang_Chinese_Simplified"] = "Chinesisch (Vereinfacht)",
                ["Lang_Chinese_Traditional"] = "Chinesisch (Traditionell)",

                // Game Library Page
                ["Library_Title"] = "Spielebibliothek",
                ["Library_Search_Placeholder"] = "Nach Titel, Entwickler oder ID suchen...",
                ["Library_AllSystems"] = "Alle Systeme",
                ["Library_AllGenres"] = "Alle Genres",
                ["Library_AllDevs"] = "Alle Entwickler",
                ["Library_AllPubs"] = "Alle Publisher",
                ["Library_Sort_Title"] = "Nach Titel",
                ["Library_Sort_ReleaseDate"] = "Nach Datum",
                ["Library_Sort_System"] = "Nach System",
                ["Library_Reset"] = "Zurücksetzen",
                ["Library_TotalGames"] = "Spiele: {0}",
                ["Library_Page_Of"] = "Seite {0} von {1}",
                ["Library_Page_Items"] = "{0}–{1} von {2} angezeigt",
                ["Library_PerPage"] = "Pro Seite:",
                ["Library_SaveCover"] = "💾 Cover speichern",
                ["Library_CopyDetails"] = "📋 Kopieren",
                ["Library_SearchWeb"] = "🔍 Im Web suchen",
                ["Library_PrevPage"] = "◀ Zurück",
                ["Library_NextPage"] = "Weiter ▶",
                ["Library_FirstPage"] = "⏮ Erste",
                ["Library_LastPage"] = "Letzte ⏭",
                ["Library_All"] = "Alle",

                // Dialogs & Metadata Editor
                ["Editor_Title"] = "Metadaten & Symbol bearbeiten",
                ["Editor_TitleRu"] = "Spieltitel (Russisch):",
                ["Editor_TitleEn"] = "Spieltitel (Englisch):",
                ["Editor_Publisher"] = "Herausgeber:",
                ["Editor_ChangeIcon"] = "Symbol ersetzen (PNG/JPG)",
                ["Editor_ResetIcon"] = "Symbol zurücksetzen",
                ["Editor_Save"] = "Speichern",
                ["Editor_Cancel"] = "Abbrechen",
                ["Common_OK"] = "OK",
                ["Common_Close"] = "Schließen"
            },

            ["zh"] = new Dictionary<string, string>
            {
                // App & Tray
                ["App_Title"] = "STORM SWITCH BOX",
                ["Tray_Title"] = "STORM SWITCH BOX",
                ["Tray_Restore"] = "还原",
                ["Tray_Exit"] = "退出",

                // Navigation
                ["Nav_Update"] = "更新",
                ["Nav_Unpack"] = "解包",
                ["Nav_Pack"] = "打包",
                ["Nav_Convert"] = "转换",
                ["Nav_Multi"] = "多内容合集",
                ["Nav_Verify"] = "校验",
                ["Nav_Instruction"] = "使用说明",
                ["Nav_GameLibrary"] = "任天堂游戏库",
                ["Nav_Catalog"] = "游戏库",
                ["Nav_History"] = "历史记录",
                ["Nav_Settings"] = "设置",

                // Tasks Common
                ["Tasks_AddFiles"] = "添加文件",
                ["Tasks_AddFolder"] = "添加文件夹",
                ["Tasks_ClearList"] = "清空列表",
                ["Tasks_StartAll"] = "全部开始",
                ["Tasks_StopAll"] = "全部停止",
                ["Tasks_TargetFormat"] = "目标格式：",
                ["Tasks_Col_Game"] = "游戏 / 任务",
                ["Tasks_Col_Format"] = "格式",
                ["Tasks_Col_Files"] = "文件",
                ["Tasks_Col_Size"] = "大小",
                ["Tasks_Col_Status"] = "状态",
                ["Tasks_Col_Progress"] = "进度",
                ["Tasks_Col_Actions"] = "操作",
                ["Tasks_EmptyHint"] = "任务列表为空。请使用上方按钮添加文件或直接拖放至窗口中。",
                ["Tasks_DropHint"] = "将文件或文件夹拖放至此处自动添加任务",
                ["Tasks_Status_Pending"] = "等待中",
                ["Tasks_Status_Processing"] = "处理中...",
                ["Tasks_Status_Success"] = "已完成",
                ["Tasks_Status_Error"] = "错误",
                ["Tasks_Status_Cancelled"] = "已取消",
                ["Tasks_Menu_EditMetadata"] = "编辑元数据和图标",
                ["Tasks_Menu_OpenFolder"] = "打开输出文件夹",
                ["Tasks_Menu_Delete"] = "删除任务",
                ["Tasks_Menu_ChangeFormat"] = "更改格式",

                // Settings Tabs
                ["Settings_Title"] = "设置",
                ["Settings_Tab_General"] = "常规",
                ["Settings_Tab_Switch"] = "Nintendo Switch",
                ["Settings_Tab_3ds"] = "Nintendo 3DS",

                // Settings General
                ["Settings_General_Language_Header"] = "界面语言",
                ["Settings_General_Language_Title"] = "界面语言",
                ["Settings_General_Language_Desc"] = "选择应用程序主要显示语言（即时生效）",
                ["Settings_General_Appearance_Header"] = "外观与声音通知",
                ["Settings_General_Sound_Title"] = "声音通知",
                ["Settings_General_Sound_Desc"] = "任务队列处理完成时播放提示音",
                ["Settings_General_Theme_Title"] = "界面主题风格",
                ["Settings_General_Theme_Desc"] = "选择应用程序的整体界面配色方案",
                ["Settings_General_Accent_Title"] = "界面强调色",
                ["Settings_General_Accent_Desc"] = "选择界面主要交互元素的高亮强调颜色",
                ["Settings_General_Files_Header"] = "路径与文件整理",
                ["Settings_General_Complex_Title"] = "按文件夹整理输出文件",
                ["Settings_General_Complex_Desc"] = "自动创建 [游戏名称]/[格式] 结构的子文件夹，并附带TitleID和版本号",
                ["Settings_General_DeleteSource_Title"] = "处理成功后删除源文件",
                ["Settings_General_DeleteSource_Desc"] = "在转换或构建100%无误完成后自动删除原始输入文件",
                ["Settings_General_Perf_Header"] = "性能与压缩",
                ["Settings_General_Compression_Title"] = "Zstandard 压缩级别 (NSZ / XCZ)",
                ["Settings_General_Compression_Desc"] = "选择Zstd压缩算法级别（从 快速3 到 极致22）",
                ["Settings_General_Tasks_Title"] = "最大同时任务数",
                ["Settings_General_Tasks_Desc"] = "后台并发处理的任务数量（1 到 5）",
                ["Settings_General_Threads_Title"] = "多线程设置（CPU核心数）",
                ["Settings_General_Threads_Desc"] = "分配给Zstd压缩算法的最大CPU核心数",
                ["Settings_General_About_Header"] = "关于软件",
                ["Settings_General_About_Desc"] = "专为 Nintendo Switch 与 Nintendo 3DS 打造的高性能处理、压缩与转换工具箱。原生算法集成，带来极致性能体验。",
                ["Settings_General_CheckUpdates"] = "检查更新",
                ["Settings_General_OpenLogs"] = "打开日志文件夹",

                // Settings Switch
                ["Settings_Switch_Keys_Header"] = "Nintendo Switch 密钥",
                ["Settings_Switch_Keys_Title"] = "密钥文件 (prod.keys / keys.txt)",
                ["Settings_Switch_Keys_Desc"] = "用于解密ROM。可以直接将密钥文件拖放到此处",
                ["Settings_Switch_Keys_Loaded"] = "密钥已加载",
                ["Settings_Switch_Keys_Pick"] = "📂 选择文件",
                ["Settings_Switch_Algorithms_Header"] = "Switch 构建与清理算法",
                ["Settings_Switch_KeyGen_Title"] = "降低密钥生成版本 (KeyGen)",
                ["Settings_Switch_KeyGen_Desc"] = "伪装固件要求（0-30），允许在低版本系统上运行新游戏",
                ["Settings_Switch_Rsv_Title"] = "降低系统版本要求 (RSV Cap Downgrade)",
                ["Settings_Switch_Rsv_Desc"] = "限制CNMT元数据中声明的最低系统版本要求",
                ["Settings_Switch_Titlerights_Title"] = "移除 Titlerights (无票据 NSP)",
                ["Settings_Switch_Titlerights_Desc"] = "将依赖票据的NSP转换为通用的无票据加密格式 (--C_clean_ND)",
                ["Settings_Switch_Delta_Title"] = "从更新中移除 Delta NCA",
                ["Settings_Switch_Delta_Desc"] = "移除更新补丁中多余的增量数据，最高节省30%存储空间 (-ND true)",
                ["Settings_Switch_Fat32_Title"] = "为 FAT32 分割文件 (> 4 GB)",
                ["Settings_Switch_Fat32_Desc"] = "自动将大于4GB的文件拆分为分卷，兼容FAT32格式内存卡",
                ["Settings_Switch_ForceMulti_Title"] = "多内容合集强制重建",
                ["Settings_Switch_ForceMulti_Desc"] = "完整重建PFS0容器，彻底解决在模拟器中的兼容性问题",
                ["Settings_Switch_LangTrim_Title"] = "从 RomFS 中精简未使用的语言",
                ["Settings_Switch_LangTrim_Desc"] = "在 NSP/NSZ → XCI/XCZ 转换或 HardPatch 重建时生效",
                ["Settings_Switch_LangTrim_Sub"] = "请勾选精简时需要保留的语言：",
                ["Settings_Switch_WatchFolder_Header"] = "Nintendo Switch 智能监控文件夹",
                ["Settings_Switch_WatchFolder_Title"] = "Switch 自动监控文件夹",
                ["Settings_Switch_WatchFolder_Desc"] = "自动检测 Switch 游戏文件 (.nsp, .nsz, .xci, .xcz, .zip, .rar, .7z) 并加入任务",
                ["Settings_Switch_WatchFolder_Badge"] = "⚡ Switch 自动处理：",
                ["Settings_Switch_WatchFolder_Pick"] = "选择文件夹...",
                ["Settings_Switch_WatchFolder_Start"] = "▶ 启动监控",
                ["Settings_Switch_WatchFolder_Stop"] = "⏹ 停止监控",
                ["Settings_Switch_WatchFolder_Active"] = "● 监控运行中",
                ["Settings_Switch_WatchFolder_Stopped"] = "○ 监控已停止",
                ["Settings_Switch_OutFolder_Title"] = "Switch 默认输出文件夹",
                ["Settings_Switch_OutFolder_Desc"] = "保存处理后的Switch文件（.nsp / .nsz / .xci / .xcz）。支持拖放文件夹",
                ["Settings_Switch_OutFolder_Placeholder"] = "未指定（默认保存至源文件所在目录）",
                ["Settings_Switch_OutFolder_Browse"] = "浏览...",

                // Settings 3DS
                ["Settings_3ds_Keys_Header"] = "Nintendo 3DS 密钥",
                ["Settings_3ds_Keys_Title"] = "3DS 密钥文件 (aes_keys.txt / boot9.bin / encTitleKeys.bin)",
                ["Settings_3ds_Keys_Desc"] = "在构建和转换时用于解密NCCH、CIA和RomFS。可直接拖放文件",
                ["Settings_3ds_Keys_Loaded"] = "密钥已连接",
                ["Settings_3ds_Keys_Pick"] = "📂 选择文件",
                ["Settings_3ds_Algorithms_Header"] = "Nintendo 3DS 构建与格式算法",
                ["Settings_3ds_Format_Title"] = "3DS 默认输出格式",
                ["Settings_3ds_Format_Desc"] = "默认转换与构建格式（.3ds/.cci 用于模拟器，.cia 用于主机安装）",
                ["Settings_3ds_HardPatch_Title"] = "3DS HardPatch (整合更新与模组)",
                ["Settings_3ds_HardPatch_Desc"] = "自动解包RomFS/ExeFS，合并更新补丁与汉化/模组并重新打包为完整ROM",
                ["Settings_3ds_WatchFolder_Header"] = "Nintendo 3DS 智能监控文件夹",
                ["Settings_3ds_WatchFolder_Title"] = "3DS 自动监控文件夹",
                ["Settings_3ds_WatchFolder_Desc"] = "自动检测 3DS 游戏文件 (.3ds, .cci, .cia, .cxi, .zip, .rar, .7z) 并加入任务",
                ["Settings_3ds_WatchFolder_Badge"] = "⚡ 3DS 自动处理：",
                ["Settings_3ds_WatchFolder_Pick"] = "选择文件夹...",
                ["Settings_3ds_WatchFolder_Start"] = "▶ 启动监控",
                ["Settings_3ds_WatchFolder_Stop"] = "⏹ 停止监控",
                ["Settings_3ds_WatchFolder_Active"] = "● 监控运行中",
                ["Settings_3ds_WatchFolder_Stopped"] = "○ 监控已停止",
                ["Settings_3ds_OutFolder_Title"] = "3DS 默认输出文件夹",
                ["Settings_3ds_OutFolder_Desc"] = "保存处理后的3DS文件（.3ds / .cia / .cxi）。支持拖放文件夹",
                ["Settings_3ds_OutFolder_Placeholder"] = "未指定（默认保存至源文件所在目录）",
                ["Settings_3ds_OutFolder_Browse"] = "浏览...",

                // Catalog Page
                ["Catalog_ScanFolders"] = "扫描文件夹",
                ["Catalog_ScanFolders_Title"] = "扫描目录列表",
                ["Catalog_AddFolder"] = "添加",
                ["Catalog_RemoveFolder"] = "移除",
                ["Catalog_ScanAll"] = "全部扫描",
                ["Catalog_Filter_All"] = "全部游戏",
                ["Catalog_Filter_Switch"] = "🎮 Nintendo Switch",
                ["Catalog_Filter_3ds"] = "🕹️ Nintendo 3DS",
                ["Catalog_Search_Placeholder"] = "按游戏名称或 Title ID 搜索...",
                ["Catalog_UpdateDb"] = "更新 TitleDB 数据库",
                ["Catalog_Details_Genre"] = "游戏类型：",
                ["Catalog_Details_ReleaseDate"] = "发售日期：",
                ["Catalog_Details_Publisher"] = "发行商：",
                ["Catalog_Details_Size"] = "文件大小：",
                ["Catalog_Details_Description"] = "游戏简介",
                ["Catalog_Details_Screenshots"] = "游戏截图与媒体",

                // Common State & Controls
                ["Common_On"] = "开启",
                ["Common_Off"] = "关闭",
                ["Common_All"] = "全部",
                ["Common_Yes"] = "是",
                ["Common_No"] = "否",

                // Languages for RomFS Trim
                ["Lang_Russian"] = "俄语",
                ["Lang_English"] = "英语",
                ["Lang_Japanese"] = "日语",
                ["Lang_Spanish"] = "西班牙语",
                ["Lang_French"] = "法语",
                ["Lang_German"] = "德语",
                ["Lang_Italian"] = "意大利语",
                ["Lang_Dutch"] = "荷兰语",
                ["Lang_Portuguese"] = "葡萄牙语",
                ["Lang_Korean"] = "韩语",
                ["Lang_Chinese_Simplified"] = "简体中文",
                ["Lang_Chinese_Traditional"] = "繁体中文",

                // Game Library Page
                ["Library_Title"] = "任天堂游戏库",
                ["Library_Search_Placeholder"] = "输入名称、工作室或ID搜索...",
                ["Library_AllSystems"] = "所有系统",
                ["Library_AllGenres"] = "所有类型",
                ["Library_AllDevs"] = "所有开发商",
                ["Library_AllPubs"] = "所有发行商",
                ["Library_Sort_Title"] = "按名称",
                ["Library_Sort_ReleaseDate"] = "按发售日",
                ["Library_Sort_System"] = "按系统",
                ["Library_Reset"] = "重置",
                ["Library_TotalGames"] = "游戏数量：{0}",
                ["Library_Page_Of"] = "第 {0} 页，共 {1} 页",
                ["Library_Page_Items"] = "显示 {0}–{1} / 共 {2}",
                ["Library_PerPage"] = "每页显示：",
                ["Library_SaveCover"] = "💾 保存封面",
                ["Library_CopyDetails"] = "📋 复制信息",
                ["Library_SearchWeb"] = "🔍 网页搜索",
                ["Library_PrevPage"] = "◀ 上一页",
                ["Library_NextPage"] = "下一页 ▶",
                ["Library_FirstPage"] = "⏮ 首页",
                ["Library_LastPage"] = "末页 ⏭",
                ["Library_All"] = "全部",

                // Dialogs & Metadata Editor
                ["Editor_Title"] = "编辑元数据和图标",
                ["Editor_TitleRu"] = "游戏名称 (俄文)：",
                ["Editor_TitleEn"] = "游戏名称 (英文)：",
                ["Editor_Publisher"] = "发行商：",
                ["Editor_ChangeIcon"] = "替换图标 (PNG/JPG)",
                ["Editor_ResetIcon"] = "恢复默认图标",
                ["Editor_Save"] = "保存",
                ["Editor_Cancel"] = "取消",
                ["Common_OK"] = "确定",
                ["Common_Close"] = "关闭"
            },

            ["ja"] = new Dictionary<string, string>
            {
                // App & Tray
                ["App_Title"] = "STORM SWITCH BOX",
                ["Tray_Title"] = "STORM SWITCH BOX",
                ["Tray_Restore"] = "元に戻す",
                ["Tray_Exit"] = "終了",

                // Navigation
                ["Nav_Update"] = "アップデート",
                ["Nav_Unpack"] = "展開",
                ["Nav_Pack"] = "パック",
                ["Nav_Convert"] = "変換",
                ["Nav_Multi"] = "マルチコンテンツ",
                ["Nav_Verify"] = "検証",
                ["Nav_Instruction"] = "ガイド",
                ["Nav_GameLibrary"] = "ゲームライブラリ",
                ["Nav_Catalog"] = "カタログ",
                ["Nav_History"] = "履歴",
                ["Nav_Settings"] = "設定",

                // Tasks Common
                ["Tasks_AddFiles"] = "ファイルを追加",
                ["Tasks_AddFolder"] = "フォルダを追加",
                ["Tasks_ClearList"] = "リストをクリア",
                ["Tasks_StartAll"] = "すべて開始",
                ["Tasks_StopAll"] = "すべて停止",
                ["Tasks_TargetFormat"] = "ターゲット形式：",
                ["Tasks_Col_Game"] = "ゲーム / タスク",
                ["Tasks_Col_Format"] = "形式",
                ["Tasks_Col_Files"] = "ファイル",
                ["Tasks_Col_Size"] = "サイズ",
                ["Tasks_Col_Status"] = "ステータス",
                ["Tasks_Col_Progress"] = "進捗",
                ["Tasks_Col_Actions"] = "操作",
                ["Tasks_EmptyHint"] = "タスクリストは空です。上のボタンからファイルを追加するか、ウィンドウにドラッグしてください。",
                ["Tasks_DropHint"] = "ここにファイルやフォルダをドラッグ＆ドロップしてタスクを追加",
                ["Tasks_Status_Pending"] = "待機中",
                ["Tasks_Status_Processing"] = "処理中...",
                ["Tasks_Status_Success"] = "完了",
                ["Tasks_Status_Error"] = "エラー",
                ["Tasks_Status_Cancelled"] = "キャンセル済み",
                ["Tasks_Menu_EditMetadata"] = "メタデータとアイコンを編集",
                ["Tasks_Menu_OpenFolder"] = "出力先フォルダを開く",
                ["Tasks_Menu_Delete"] = "タスクを削除",
                ["Tasks_Menu_ChangeFormat"] = "形式を変更",

                // Settings Tabs
                ["Settings_Title"] = "設定",
                ["Settings_Tab_General"] = "一般",
                ["Settings_Tab_Switch"] = "Nintendo Switch",
                ["Settings_Tab_3ds"] = "Nintendo 3DS",

                // Settings General
                ["Settings_General_Language_Header"] = "インターフェース言語",
                ["Settings_General_Language_Title"] = "表示言語",
                ["Settings_General_Language_Desc"] = "アプリケーションの表示言語を選択します（即座に適用）",
                ["Settings_General_Appearance_Header"] = "外観とサウンド通知",
                ["Settings_General_Sound_Title"] = "サウンド通知",
                ["Settings_General_Sound_Desc"] = "タスクキュー完了時にサウンド通知を再生",
                ["Settings_General_Theme_Title"] = "UIテーマ",
                ["Settings_General_Theme_Desc"] = "アプリケーションのビジュアルテーマを選択",
                ["Settings_General_Accent_Title"] = "アクセントカラー",
                ["Settings_General_Accent_Desc"] = "UI要素のメインアクセントカラーを選択",
                ["Settings_General_Files_Header"] = "パスとファイル整理",
                ["Settings_General_Complex_Title"] = "フォルダ別に整理して出力",
                ["Settings_General_Complex_Desc"] = "TitleIDとバージョンを含む[ゲーム名]/[形式]形式のサブフォルダを作成",
                ["Settings_General_DeleteSource_Title"] = "処理成功後に元のファイルを削除",
                ["Settings_General_DeleteSource_Desc"] = "タスクが正常に完了した後、元の入力ファイルを自動的に削除",
                ["Settings_General_Perf_Header"] = "パフォーマンスと圧縮",
                ["Settings_General_Compression_Title"] = "Zstandard 圧縮レベル (NSZ / XCZ)",
                ["Settings_General_Compression_Desc"] = "Zstd圧縮レベルを選択（高速3からウルトラ22まで）",
                ["Settings_General_Tasks_Title"] = "最大同時実行タスク数",
                ["Settings_General_Tasks_Desc"] = "バックグラウンドで並行処理するタスク数（1〜5）",
                ["Settings_General_Threads_Title"] = "マルチスレッド（使用CPUコア数）",
                ["Settings_General_Threads_Desc"] = "Zstd圧縮に割り当てる最大CPUコア数",
                ["Settings_General_About_Header"] = "バージョン情報",
                ["Settings_General_About_Desc"] = "Nintendo SwitchおよびNintendo 3DSゲームの処理・圧縮・変換用高機能ツールキット。最高速度を実現するネイティブ実装。",
                ["Settings_General_CheckUpdates"] = "アップデートを確認",
                ["Settings_General_OpenLogs"] = "ログフォルダを開く",

                // Settings Switch
                ["Settings_Switch_Keys_Header"] = "Nintendo Switch 暗号化キー",
                ["Settings_Switch_Keys_Title"] = "キーファイル (prod.keys / keys.txt)",
                ["Settings_Switch_Keys_Desc"] = "復号に必要なキーを読み込みます。ここにファイルをドラッグ可能",
                ["Settings_Switch_Keys_Loaded"] = "キー読み込み済み",
                ["Settings_Switch_Keys_Pick"] = "📂 ファイルを選択",
                ["Settings_Switch_Algorithms_Header"] = "Switch ビルド＆クリーンアップアルゴリズム",
                ["Settings_Switch_KeyGen_Title"] = "キー世代ダウングレード (KeyGen)",
                ["Settings_Switch_KeyGen_Desc"] = "FW要件を偽装し(0-30)、古いFWで新しいゲームを起動可能にします",
                ["Settings_Switch_Rsv_Title"] = "システム要件ダウングレード (RSV Cap)",
                ["Settings_Switch_Rsv_Desc"] = "CNMTメタデータ内の必須システムバージョンチェックを制限",
                ["Settings_Switch_Titlerights_Title"] = "Titlerights削除 (Ticketless NSP)",
                ["Settings_Switch_Titlerights_Desc"] = "チケット依存のNSPを標準的なチケットレス形式に変換 (--C_clean_ND)",
                ["Settings_Switch_Delta_Title"] = "アップデートからDelta NCAを削除",
                ["Settings_Switch_Delta_Desc"] = "不要な差分データを削除して最大30%容量を節約 (-ND true)",
                ["Settings_Switch_Fat32_Title"] = "FAT32用にファイルを分割 (> 4 GB)",
                ["Settings_Switch_Fat32_Desc"] = "4GBを超えるファイルをFAT32 SDカード用に自動分割",
                ["Settings_Switch_ForceMulti_Title"] = "マルチコンテンツでPFS0を再構築",
                ["Settings_Switch_ForceMulti_Desc"] = "エミュレータでのエラーを防ぐためPFS0コンテナを完全再構築",
                ["Settings_Switch_LangTrim_Title"] = "RomFSから不要な言語を削除",
                ["Settings_Switch_LangTrim_Desc"] = "NSP/NSZ → XCI/XCZ 変換時およびHardPatch時に適用",
                ["Settings_Switch_LangTrim_Sub"] = "削除時に保持する言語を選択してください：",
                ["Settings_Switch_WatchFolder_Header"] = "Nintendo Switch スマート監視フォルダ",
                ["Settings_Switch_WatchFolder_Title"] = "Switch 自動監視フォルダ",
                ["Settings_Switch_WatchFolder_Desc"] = "Switchゲームファイル（.nsp, .nsz, .xci, .xcz, .zip, .rar, .7z）を自動検出してタスク追加",
                ["Settings_Switch_WatchFolder_Badge"] = "⚡ Switch 自動処理：",
                ["Settings_Switch_WatchFolder_Pick"] = "フォルダを選択...",
                ["Settings_Switch_WatchFolder_Start"] = "▶ 監視を開始",
                ["Settings_Switch_WatchFolder_Stop"] = "⏹ 監視を停止",
                ["Settings_Switch_WatchFolder_Active"] = "● 監視中",
                ["Settings_Switch_WatchFolder_Stopped"] = "○ 停止中",
                ["Settings_Switch_OutFolder_Title"] = "Switch デフォルト出力フォルダ",
                ["Settings_Switch_OutFolder_Desc"] = "処理済みSwitchファイル（.nsp / .nsz / .xci / .xcz）の保存先。フォルダをドラッグ可能",
                ["Settings_Switch_OutFolder_Placeholder"] = "未設定（元のファイルと同じフォルダに保存）",
                ["Settings_Switch_OutFolder_Browse"] = "参照...",

                // Settings 3DS
                ["Settings_3ds_Keys_Header"] = "Nintendo 3DS 暗号化キー",
                ["Settings_3ds_Keys_Title"] = "3DS キーファイル (aes_keys.txt / boot9.bin / encTitleKeys.bin)",
                ["Settings_3ds_Keys_Desc"] = "ビルドおよび変換時のNCCH、CIA、RomFSの復号に使用。ファイルをドラッグ可能",
                ["Settings_3ds_Keys_Loaded"] = "キー接続済み",
                ["Settings_3ds_Keys_Pick"] = "📂 ファイルを選択",
                ["Settings_3ds_Algorithms_Header"] = "Nintendo 3DS ビルド＆形式アルゴリズム",
                ["Settings_3ds_Format_Title"] = "3DS デフォルト出力形式",
                ["Settings_3ds_Format_Desc"] = "変換およびビルドのデフォルト形式（Citra/Lime3DS用.3ds/.cci、本体インストール用.cia）",
                ["Settings_3ds_HardPatch_Title"] = "3DS HardPatch (更新とModを統合)",
                ["Settings_3ds_HardPatch_Desc"] = "RomFS/ExeFSを展開し、更新やMod/翻訳を適用して単一イメージに再構築",
                ["Settings_3ds_WatchFolder_Header"] = "Nintendo 3DS スマート監視フォルダ",
                ["Settings_3ds_WatchFolder_Title"] = "3DS 自動監視フォルダ",
                ["Settings_3ds_WatchFolder_Desc"] = "3DSゲームファイル（.3ds, .cci, .cia, .cxi, .zip, .rar, .7z）を自動検出してタスク追加",
                ["Settings_3ds_WatchFolder_Badge"] = "⚡ 3DS 自動処理：",
                ["Settings_3ds_WatchFolder_Pick"] = "フォルダを選択...",
                ["Settings_3ds_WatchFolder_Start"] = "▶ 監視を開始",
                ["Settings_3ds_WatchFolder_Stop"] = "⏹ 監視を停止",
                ["Settings_3ds_WatchFolder_Active"] = "● 監視中",
                ["Settings_3ds_WatchFolder_Stopped"] = "○ 停止中",
                ["Settings_3ds_OutFolder_Title"] = "3DS デフォルト出力フォルダ",
                ["Settings_3ds_OutFolder_Desc"] = "処理済み3DSファイル（.3ds / .cia / .cxi）の保存先。フォルダをドラッグ可能",
                ["Settings_3ds_OutFolder_Placeholder"] = "未設定（元のファイルと同じフォルダに保存）",
                ["Settings_3ds_OutFolder_Browse"] = "参照...",

                // Catalog Page
                ["Catalog_ScanFolders"] = "スキャンフォルダ",
                ["Catalog_ScanFolders_Title"] = "スキャン対象フォルダ",
                ["Catalog_AddFolder"] = "追加",
                ["Catalog_RemoveFolder"] = "削除",
                ["Catalog_ScanAll"] = "すべてスキャン",
                ["Catalog_Filter_All"] = "すべてのゲーム",
                ["Catalog_Filter_Switch"] = "🎮 Nintendo Switch",
                ["Catalog_Filter_3ds"] = "🕹️ Nintendo 3DS",
                ["Catalog_Search_Placeholder"] = "タイトルまたはTitle IDで検索...",
                ["Catalog_UpdateDb"] = "TitleDB データベースを更新",
                ["Catalog_Details_Genre"] = "ジャンル：",
                ["Catalog_Details_ReleaseDate"] = "発売日：",
                ["Catalog_Details_Publisher"] = "メーカー：",
                ["Catalog_Details_Size"] = "サイズ：",
                ["Catalog_Details_Description"] = "概要",
                ["Catalog_Details_Screenshots"] = "スクリーンショット＆メディア",

                // Common State & Controls
                ["Common_On"] = "オン",
                ["Common_Off"] = "オフ",
                ["Common_All"] = "すべて",
                ["Common_Yes"] = "はい",
                ["Common_No"] = "いいえ",

                // Languages for RomFS Trim
                ["Lang_Russian"] = "ロシア語",
                ["Lang_English"] = "英語",
                ["Lang_Japanese"] = "日本語",
                ["Lang_Spanish"] = "スペイン語",
                ["Lang_French"] = "フランス語",
                ["Lang_German"] = "ドイツ語",
                ["Lang_Italian"] = "イタリア語",
                ["Lang_Dutch"] = "オランダ語",
                ["Lang_Portuguese"] = "ポルトガル語",
                ["Lang_Korean"] = "韓国語",
                ["Lang_Chinese_Simplified"] = "中国語（簡体字）",
                ["Lang_Chinese_Traditional"] = "中国語（繁体字）",

                // Game Library Page
                ["Library_Title"] = "ゲームライブラリ",
                ["Library_Search_Placeholder"] = "タイトル、メーカー、IDで検索...",
                ["Library_AllSystems"] = "すべてのシステム",
                ["Library_AllGenres"] = "すべてのジャンル",
                ["Library_AllDevs"] = "すべての開発元",
                ["Library_AllPubs"] = "すべてのメーカー",
                ["Library_Sort_Title"] = "タイトル順",
                ["Library_Sort_ReleaseDate"] = "発売日順",
                ["Library_Sort_System"] = "システム順",
                ["Library_Reset"] = "リセット",
                ["Library_TotalGames"] = "ゲーム総数：{0}",
                ["Library_Page_Of"] = "{0} / {1} ページ",
                ["Library_Page_Items"] = "{0}–{1} / 全{2}件を表示",
                ["Library_PerPage"] = "表示件数：",
                ["Library_SaveCover"] = "💾 カバーを保存",
                ["Library_CopyDetails"] = "📋 情報をコピー",
                ["Library_SearchWeb"] = "🔍 Webで検索",
                ["Library_PrevPage"] = "◀ 前へ",
                ["Library_NextPage"] = "次へ ▶",
                ["Library_FirstPage"] = "⏮ 最初",
                ["Library_LastPage"] = "最後 ⏭",
                ["Library_All"] = "すべて",

                // Dialogs & Metadata Editor
                ["Editor_Title"] = "メタデータとアイコンを編集",
                ["Editor_TitleRu"] = "ゲーム名 (ロシア語)：",
                ["Editor_TitleEn"] = "ゲーム名 (英語)：",
                ["Editor_Publisher"] = "メーカー：",
                ["Editor_ChangeIcon"] = "アイコンを変更 (PNG/JPG)",
                ["Editor_ResetIcon"] = "アイコンをリセット",
                ["Editor_Save"] = "保存",
                ["Editor_Cancel"] = "キャンセル",
                ["Common_OK"] = "OK",
                ["Common_Close"] = "閉じる"
            }
        };
    }
}
