<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>..\..\storm_switch_box.ico</ApplicationIcon>
    <Version>4.7.4</Version>
    <AssemblyVersion>4.7.4.0</AssemblyVersion>
    <FileVersion>4.7.4.0</FileVersion>
    <AssemblyTitle>STORM SWITCH BOX 4.7.4</AssemblyTitle>
    <Product>STORM SWITCH BOX 4.7.4</Product>
    <Title>STORM SWITCH BOX 4.7.4</Title>
    <Description>STORM SWITCH BOX 4.7.4</Description>
    <Company>STORM TEAM</Company>
    <Authors>STORM TEAM</Authors>
    <PublisherName>STORM TEAM</PublisherName>
    <Copyright>Copyright © 2026 STORM TEAM</Copyright>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\Output\STORM_SWITCH_BOX_4.7.4_win-x64.zip" Link="Payload\Payload.zip" />
    <EmbeddedResource Include="..\STORM_Certificate.cer" Link="Payload\STORM_Certificate.cer" />
    <EmbeddedResource Include="..\..\storm_switch_box.ico" Link="Payload\storm_switch_box.ico" />
    <EmbeddedResource Include="header_badge.png" Link="Payload\header_badge.png" />
  </ItemGroup>

</Project>
